import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_ANNAPURNA_CIRCUIT: TrekPageContent = {
  coverImageUrl: img("photo-1464822759023-fed622ff2c3b", 2000),
  coverTitle: "Annapurna Circuit Trek - 16 Days",
  coverSubtitle:
    "Marsyangdi Valley to Thorong La (5,416 m), Muktinath, and the Kali Gandaki gorge — Nepal’s classic high-altitude circuit with Ice Lake and Tatopani hot springs.",
  heroMainImageUrl: img("photo-1464822759023-fed622ff2c3b", 2000),
  heroSideImage1Url: img("photo-1585409677983-0f6c41ca9c3b", 900),
  heroSideImage2Url: img("photo-1483728642387-6c3bdd6c93e5", 900),
  breadcrumbLabel: "Annapurna Region · Circuit",
  title: "Annapurna Circuit Trek - 16 Days",
  regionLabel: "Annapurna Region",
  rating: 5,
  reviewCount: 48,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 1000,
  compareAtPrice: 1100,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "9% OFF",
  shortTripBadge: "Classic Trek",
  durationLabel: "16 Days",
  difficultyLabel: "Challenging",
  groupSizeLabel: "1+",
  bookingNote:
    "Private and small-group departures available. Package includes permits, licensed guide, porter, teahouse meals on trek days, and road transfers as per itinerary. Prior multi-day trekking experience strongly recommended.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 1100, visible: true },
    { id: "gd2", paxLabel: "2-3 pax", price: 1000, visible: true },
    { id: "gd3", paxLabel: "4-6 pax", price: 975, visible: true },
    { id: "gd4", paxLabel: "7-10 pax", price: 950, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "16 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Challenging", visible: true },
    { id: "f3", label: "Max Altitude", value: "5,416 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Annapurna", visible: true },
    { id: "f6", label: "Group Size", value: "1+", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Culture", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The Annapurna Circuit is one of Nepal’s legendary long treks — a high-altitude journey through the western Himalayas that climbs from lush Marsyangdi valleys and rhododendron forests to the alpine zone and over Thorong La (5,416 m).\n\nStarting with a scenic drive from Kathmandu to Bhulbhule via Besisahar, the trail threads traditional villages (Jagat, Danakyu, Chame, Upper Pisang) toward Manang for acclimatization and an Ice Lake hike. Above the tree line you continue via Ledar to Thorong Phedi, then cross the pass to sacred Muktinath before descending the Kali Gandaki gorge — among the world’s deepest — to Tatopani hot springs and Pokhara.\n\nExpect immense landscape diversity, Hindu–Buddhist cultural harmony, and big mountain views of Annapurna, Dhaulagiri, Nilgiri, Gangapurna, Machhapuchhre, and more. Summit Seek runs this 16-day package with licensed guides, fair porter support, clear group pricing, and room to customize (Tilicho, Poon Hill, ABC, or Upper Mustang extensions on request).",
  overviewImageUrl: img("photo-1544735716-392fe2489ffa"),
  highlightsHeading: "Highlights",
  highlights: [
    "Classic western Himalayan adventure on the Annapurna Circuit",
    "Lush forests, misty valleys, and alpine terrain above 5,400 m",
    "Cross famous Thorong La Pass (5,416 m)",
    "Acclimatization hike to Ice Lake above Manang",
    "Blessings at Muktinath Temple and eternal flame",
    "Kali Gandaki gorge drive toward Tatopani hot springs",
    "Teahouse hospitality and Hindu–Buddhist mountain culture",
    "Views of Annapurna, Dhaulagiri, Nilgiri, Gangapurna & Machhapuchhre",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport pickup and drop-off as per itinerary",
    "Licensed English-speaking mountain guide with salary, food, lodging & insurance",
    "Porter support to carry trek luggage (typically shared 2:1)",
    "ACAP & TIMS permits arranged",
    "Teahouse lodging and full-board meals during the trek",
    "Kathmandu & Pokhara hotel nights as listed (BB basis)",
    "Road transfers Kathmandu–Bhulbhule and Muktinath–Pokhara–Kathmandu as per itinerary",
    "First-aid support, trek briefing, and completion certificate",
  ],
  whyHeading: "Why choose Annapurna Circuit?",
  whyPoints: [
    "A fuller challenge than classic ABC or short Poon Hill — long days and a true high pass",
    "Unmatched landscape range from subtropical forest to barren high desert",
    "Cultural depth across Gurung, Manangi, Thakali, and pilgrimage communities",
    "Signature Thorong La crossing plus Ice Lake and Tatopani recovery soak",
    "Easy to extend toward Tilicho Lake, ABC, Poon Hill, or Upper Mustang",
  ],
  beginnersHeading: "Who is this trek for?",
  beginnersBody:
    "Annapurna Circuit is for trekkers with prior multi-day mountain experience who are physically and mentally fit. It is one of Nepal’s longer classic routes, with steep terrain, cold alpine weather, and a demanding 8–9 hour pass day over Thorong La (5,416 m).\n\nTrain 4–6 weeks beforehand with long walks, hill hiking, cardio, and knee/core strength work. Travel insurance covering helicopter evacuation from high altitude is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train 4–6 weeks with long hikes, stairs, jogging, cycling, or swimming",
    "Build knee and core strength for long descents after Thorong La",
    "Break in waterproof boots; practice with a loaded daypack",
    "Pack serious warm layers for Manang, Thorong Phedi, and the pass",
    "Buy insurance covering high-altitude trekking and helicopter evacuation",
    "Choose spring or autumn for the most reliable weather and views",
  ],
  itineraryHeading: "16-day itinerary",
  itineraryIntro:
    "Walking and drive times are estimates and vary with road conditions, weather, and pace. Lodge stops may change with availability. Your Summit Seek guide can adjust the plan for safety — especially around Thorong La.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,400 m",
      meals: "—",
      accommodation: "Hotel in Kathmandu",
      description:
        "Arrive at Tribhuvan International Airport. Private transfer to your hotel and trip welcome. Free evening to rest or explore Thamel. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Kathmandu sightseeing & trek preparation",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Guided morning sightseeing of major Kathmandu heritage sites (as arranged). Afternoon trek briefing, gear check, and permit preparation. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Drive Kathmandu – Bhulbhule via Besisahar",
      maxAltitude: "≈ 840 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Long scenic drive (about 8–10 hours) via Besisahar into the Marsyangdi foothills to Bhulbhule, the trek start. Overnight in Bhulbhule.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Bhulbhule – Jagat",
      maxAltitude: "≈ 1,300 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Begin walking into the Marsyangdi valley through villages, terraces, and forest trails. Overnight in Jagat.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Jagat – Danakyu",
      maxAltitude: "≈ 2,300 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Continue upstream with waterfall views, suspension bridges, and changing vegetation as altitude rises. Overnight in Danakyu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Danakyu – Chame",
      maxAltitude: "≈ 2,670 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Trek toward Chame, district headquarters of Manang, with growing Annapurna views and apple-country atmosphere. Overnight in Chame.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Chame – Upper Pisang",
      maxAltitude: "≈ 3,300 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Walk past dramatic cliffs including Paungda Danda rock face into Upper Pisang with open mountain panoramas. Overnight in Upper Pisang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Upper Pisang – Manang via Geru",
      maxAltitude: "≈ 3,540 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Take the scenic high trail via Geru for outstanding Annapurna and Gangapurna views into Manang village. Overnight in Manang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Manang acclimatization – hike to Ice Lake",
      maxAltitude: "≈ 4,600 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Acclimatization day with a hike toward Ice Lake for alpine views and safer altitude adaptation. Overnight again in Manang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Manang – Ledar",
      maxAltitude: "≈ 4,200 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Leave Manang above the tree line via yak pastures toward Ledar with increasingly rugged alpine scenery. Overnight in Ledar.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Ledar – Thorong Phedi",
      maxAltitude: "≈ 4,450 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Short but high day to Thorong Phedi, the last lodge before the pass. Rest early for the big day ahead. Overnight in Thorong Phedi.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Thorong Phedi – Thorong La – Muktinath",
      maxAltitude: "5,416 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Very early start to cross Thorong La (5,416 m) — about 8–9 hours including a steep descent to Muktinath (3,760 m). Visit the temple and eternal flame. Overnight in Muktinath.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Drive Muktinath – Tatopani",
      maxAltitude: "≈ 1,190 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Local sharing bus/jeep via the Kali Gandaki gorge toward Tatopani. Soak in natural hot springs. Overnight in Tatopani.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Drive Tatopani – Pokhara",
      maxAltitude: "≈ 820 m",
      meals: "Breakfast",
      accommodation: "Hotel in Pokhara",
      description:
        "Scenic road transfer to lakeside Pokhara. Free afternoon to relax by Phewa Lake. Overnight in Pokhara.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d15",
      dayLabel: "Day 15",
      title: "Drive Pokhara – Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Tourist bus (or private vehicle on request) back to Kathmandu. Free evening for shopping or a farewell dinner. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d16",
      dayLabel: "Day 16",
      title: "Final departure",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "— (departure day)",
      description:
        "Private transfer to Tribhuvan International Airport for your departure flight. End of the Annapurna Circuit journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Circuit departures run on private and joining bases. March–May and September–November usually bring the clearest mountain views. Winter is colder on Thorong La; monsoon means more rain and unstable trails on lower sections.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Prior trekking experience strongly recommended",
    "Thorong La crossing depends on weather and group fitness",
    "Extensions: Tilicho Lake, Poon Hill, ABC, or Upper Mustang on request",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Single room supplement",
      description: "Private rooms where available in hotels and teahouses.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Tilicho Lake extension",
      description: "Add days from Manang to visit Tilicho Lake before rejoining the circuit.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Private vehicle upgrades",
      description: "Upgrade sharing buses to private jeeps on key road sections.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport pickup and drop-off in Kathmandu as per itinerary",
    "Hotel accommodation in Kathmandu and Pokhara (BB basis) as listed",
    "Teahouse / lodge accommodation during the trek",
    "Full-board meals (breakfast, lunch, dinner) during the trek",
    "Licensed mountain guide (salary, food, lodging, insurance)",
    "Porter to carry trek luggage (typically shared; solo supplement may apply)",
    "ACAP and TIMS permits",
    "Road transfers as per itinerary (Kathmandu–Bhulbhule; Muktinath–Tatopani–Pokhara–Kathmandu)",
    "First-aid kit and trek briefing",
    "Trek completion certificate and government taxes as applicable",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Lunch and dinner in Kathmandu and Pokhara (unless stated)",
    "Travel insurance (mandatory — high-altitude evacuation)",
    "Nepal entry visa fee",
    "International airfare",
    "Tips for guide, porter, and drivers",
    "Drinks, hot showers, charging, and Wi-Fi on the trail",
    "Personal shopping, laundry, and personal trekking equipment",
    "Costs from roadblocks, weather, or delays beyond our control",
    "Any items not listed in the includes section",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "High Himalayan ridges on the Circuit",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1585409677983-0f6c41ca9c3b"),
      caption: "Annapurna massif mountain light",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1483728642387-6c3bdd6c93e5"),
      caption: "Alpine trail atmosphere",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Valley approaches toward Manang",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May and September–November usually offer the clearest views and most reliable Thorong La conditions. Winter is colder and snowier on the pass; monsoon brings rain and muddy lower trails.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & AMS",
      body: "Maximum altitude is Thorong La at 5,416 m. Use the Manang rest day and Ice Lake hike, drink plenty of water, avoid alcohol, and descend if symptoms worsen. Follow your guide’s pacing on pass day.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Challenging. Long walking days, steep terrain, and a demanding high-pass crossing. Prior multi-day trekking experience is strongly recommended — not an ideal first Himalayan trek.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Lodges & meals",
      body: "Teahouses on the trail; hotels in Kathmandu and Pokhara. Expect dal bhat, noodles, soups, and simple breakfasts. Hot showers and Wi-Fi usually cost extra higher up.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack for cold alpine nights and a long pass day. Porters typically carry your main bag; you hike with a daypack for water, layers, documents, and snacks.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers & thermals",
        "Fleece mid-layer",
        "Down / insulated jacket",
        "Windbreaker / waterproof shell",
        "Trekking shirts and pants (multiple pairs)",
        "Warm hat, sun cap, gloves, scarf / buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Camp shoes",
        "Cotton and wool trekking socks",
        "Trekking poles (strongly recommended)",
        "Daypack + duffel for porter",
        "Water bottle / filter",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "SPF sunscreen, lip balm, sunglasses",
        "Personal medications, blister care, antiseptic",
        "Electrolyte powder / ORS",
        "Headlamp + spare batteries / power bank",
        "Insect repellent",
        "Toiletries, wet wipes, sanitizer",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport, visa, and copies",
        "Travel insurance details",
        "Passport-size photos if needed for permits",
        "Cash for personal trail expenses",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Route briefing and permit arrangement in Kathmandu",
    "First-aid support with your guiding team",
    "Advice on Tilicho, ABC, Poon Hill, or Mustang extensions",
    "Help arranging private vehicle upgrades on road days",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Annapurna Circuit trek?",
      answer:
        "A classic 16-day Annapurna-region journey from the Marsyangdi valley over Thorong La (5,416 m) to Muktinath, then down the Kali Gandaki corridor to Tatopani and Pokhara.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Challenging. Long days, high altitude, and a tough pass crossing. Best for trekkers with previous multi-day hiking experience and strong fitness.",
      visible: true,
    },
    {
      id: "q3",
      question: "What is the maximum altitude?",
      answer:
        "Thorong La Pass at 5,416 m. An Ice Lake acclimatization hike above Manang also reaches high alpine elevations.",
      visible: true,
    },
    {
      id: "q4",
      question: "How much does the Annapurna Circuit cost?",
      answer:
        "This Summit Seek listing starts at US$1,000 for 2–3 pax (US$1,100 solo), with group rates of US$975 (4–6) and US$950 (7–10) as shown on the page.",
      visible: true,
    },
    {
      id: "q5",
      question: "When is the best time to go?",
      answer:
        "Spring (March–May) and autumn (September–November) usually offer the best weather and mountain views for Thorong La.",
      visible: true,
    },
    {
      id: "q6",
      question: "Is travel insurance necessary?",
      answer:
        "Yes. Cover high-altitude trekking and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q7",
      question: "Can I add Tilicho Lake or ABC?",
      answer:
        "Yes. Tilicho Lake, Annapurna Base Camp, Poon Hill, or Upper Mustang can be combined on request — ask us to customize your itinerary.",
      visible: true,
    },
    {
      id: "q8",
      question: "Where does the trek start and end?",
      answer:
        "The package starts and ends in Kathmandu. Trekking begins at Bhulbhule after the drive via Besisahar and finishes via Tatopani and Pokhara before returning to Kathmandu.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Annapurna Circuit?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Annapurna Circuit Trek 16 Days | Summit Seek",
  metaDescription:
    "Book the 16-day Annapurna Circuit with Summit Seek — Thorong La (5,416 m), Ice Lake, Muktinath, Tatopani, permits, guide, porter & group discounts from US$950.",
};
