import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_ANNAPURNA_CIRCUIT_TREK: TrekPageContent = {
  coverImageUrl: img("photo-1454496522488-7a8e488e8606", 2000),
  coverTitle: "Annapurna Circuit Trek - 15 Days",
  coverSubtitle:
    "Classic teahouse circuit around the Annapurna massif — Manang acclimatization, Thorong La (5,416 m), Muktinath, Kali Gandaki gorge, Tatopani hot springs, and sunrise from Poon Hill.",
  heroMainImageUrl: img("photo-1454496522488-7a8e488e8606", 2000),
  heroSideImage1Url: img("photo-1464822759023-fed622ff2c3b", 900),
  heroSideImage2Url: img("photo-1585409677983-0f6c41ca9c3b", 900),
  breadcrumbLabel: "Packages · Annapurna Region",
  title: "Annapurna Circuit Trek - 15 Days",
  regionLabel: "Annapurna Region",
  rating: 5,
  reviewCount: 15,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 1005,
  compareAtPrice: 1550,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "35% OFF",
  shortTripBadge: "Best Seller",
  durationLabel: "15 Days",
  difficultyLabel: "Strenuous",
  groupSizeLabel: "1–12",
  bookingNote:
    "Private and small-group departures. Package includes Kathmandu & Pokhara hotel nights (BB as listed), ACAP & TIMS permits, licensed guide and porter, full-board trek meals, teahouse lodges, and road transfers as per itinerary. Prior high-mountain trekking experience recommended.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 1250, visible: true },
    { id: "gd2", paxLabel: "2-5 pax", price: 1005, visible: true },
    { id: "gd3", paxLabel: "6+ pax", price: 1000, visible: true },
    { id: "gd4", paxLabel: "10+ pax", price: 975, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "15 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Strenuous", visible: true },
    { id: "f3", label: "Max Altitude", value: "5,416 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Annapurna", visible: true },
    { id: "f6", label: "Group Size", value: "1–12", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Walking", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "Annapurna Circuit Trek – 15 Days is a teahouse trek around the Annapurna massif in central Nepal, reaching 5,416 m at Thorong La Pass — one of the highest trekking passes on Earth.\n\nStarting and ending in Kathmandu, this itinerary combines the Manang highlands, the Thorong La crossing, sacred Muktinath, the Kali Gandaki Valley, Tatopani hot springs, and a spectacular sunrise finish from Poon Hill above Ghorepani.\n\nYou begin in lush lowlands and rhododendron forests, acclimatize in Manang with side hikes to Braga Monastery or Ice Lake (4,500 m), cross the pass to Muktinath, descend the world’s deepest gorge, soak in Tatopani, and climb to Poon Hill for golden Himalayan panoramas. Summit Seek includes permits, guide, porter, trek meals and lodges, hotels as listed, and clear group pricing.",
  overviewImageUrl: img("photo-1464822759023-fed622ff2c3b"),
  highlightsHeading: "Highlights",
  highlights: [
    "Cross iconic Thorong La Pass (5,416 m)",
    "Trek inside Annapurna Conservation Area — forests to alpine meadows",
    "Acclimatization day in Manang — Braga Monastery or Ice Lake hikes",
    "Blessings at Muktinath Temple — sacred to Hindus and Buddhists",
    "Scenic drive through the Kali Gandaki Gorge",
    "Natural hot springs at Tatopani",
    "Sunrise from Poon Hill (3,210 m) — Annapurna & Dhaulagiri views",
    "Gurung, Magar, and Thakali village culture along the trail",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport pickup and drop-off in Kathmandu as per itinerary",
    "3 nights Kathmandu + 1 night Pokhara hotel (BB) as listed",
    "Licensed English-speaking guide with salary, food, lodging & insurance",
    "Porter support — typically 1 porter per 2 trekkers (~20–22 kg)",
    "ACAP & TIMS permits arranged",
    "Teahouse lodging and full-board meals during the trek",
    "Road transfers Kathmandu–Dharapani, Muktinath–Tatopani, Pokhara–Kathmandu",
    "First-aid kit, trek map, seasonal fruit on trek, and completion certificate",
  ],
  whyHeading: "Why choose the Annapurna Circuit?",
  whyPoints: [
    "One of Nepal’s greatest long treks — diverse landscapes every day",
    "Thorong La is a true high-Himalayan achievement without technical climbing",
    "Cultural depth from lowland Brahmin villages to Tibetan-influenced Manang",
    "Includes Tatopani recovery soak and Poon Hill sunrise finale",
    "Side trips to Tilicho Lake or Nar Phu available on request",
  ],
  beginnersHeading: "Who is this trek for?",
  beginnersBody:
    "Annapurna Circuit is graded Strenuous — you need strong physical fitness plus experience in high-mountain trekking. The Thorong La day is long (9–10 hours) and demanding at altitude.\n\nTrain 4–6 weeks with long hikes, cardio, and knee/core strength. Travel insurance covering helicopter evacuation from high altitude is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train 4–6 weeks with long walks, hill hiking, and cardio",
    "Build knee and core strength for long descents after Thorong La",
    "Break in waterproof boots; practice with a loaded daypack",
    "Pack serious warm layers for Manang, Thorong Phedi, and pass day",
    "Buy insurance covering high-altitude trekking and helicopter evacuation",
    "Choose spring or autumn for the most reliable weather and views",
  ],
  itineraryHeading: "15-day itinerary",
  itineraryIntro:
    "Walking and drive times are estimates (~116 km on foot from Dharapani to Ulleri). Lodge stops may change with availability. Your Summit Seek guide can adjust the plan for safety — especially around Thorong La.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,345 m",
      meals: "—",
      accommodation: "Hotel in Kathmandu",
      description:
        "Arrive at Tribhuvan International Airport. Private transfer to your hotel. Rest, unpack, or explore nearby streets. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Kathmandu cultural tour & trek preparation",
      maxAltitude: "1,345 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "After breakfast, explore Boudhanath, Swayambhunath (Monkey Temple), Pashupatinath, and Durbar Square. Afternoon trek briefing, gear check, and meet your trekking crew. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Drive Kathmandu to Dharapani",
      maxAltitude: "1,860 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Long scenic drive (~9–10 hours, ~180 km) via Besisahar to Dharapani — the trek start point. Green hills, rivers, and terraces along the Marsyangdi valley. Overnight in Dharapani.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Trek Dharapani to Chame",
      maxAltitude: "2,670 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Begin the Himalayan trek through rural villages and subtropical forest (~18 km, 6–7 hrs). Pass Timang and Koto along the Marshyangdi River to Chame, district headquarters of Manang. Overnight in Chame.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Trek Chame to Pisang",
      maxAltitude: "3,200 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Walk through apple orchards past Paungda Danda rock face, prayer wheels, and pine forest (~15 km, 6–7 hrs). Growing Annapurna views. Overnight in Pisang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Trek Pisang to Manang via Ghyaru",
      maxAltitude: "3,540 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Take the scenic upper trail via Ghyaru and Ngawal through Mani walls and Tibetan Buddhist influence (~19 km, 6–7 hrs). Pass Braga village into Manang. Overnight in Manang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Acclimatization day in Manang",
      maxAltitude: "4,500 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Rest day for altitude adaptation. Side hike to Braga Monastery, Gangapurna Lake, or Ice Lake (4,500 m). Return to Manang — coffee shops, museum, and mountain atmosphere. Overnight in Manang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Trek Manang to Yak Kharka",
      maxAltitude: "4,050 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Leave Manang above the tree line through Gunsang and alpine meadows with yaks grazing (~9 km, 4–5 hrs). Fir and juniper forest guide you to Yak Kharka. Overnight in Yak Kharka.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Trek Yak Kharka to Thorong Phedi / High Camp",
      maxAltitude: "4,450 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Steady climb via Ledar and Deurali Tea House beside Jarang Khola (~9 km, 4–5 hrs). Base for tomorrow’s pass — push to High Camp if time allows. Early sleep tonight. Overnight in Thorong Phedi or High Camp.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Thorong Phedi to Muktinath via Thorong La",
      maxAltitude: "5,416 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Very early start for the pass day (~17 km, 9–10 hrs). Ascend to Thorong La (5,416 m) with prayer flags and sweeping Himalayan views, then descend to sacred Muktinath (3,800 m). Overnight in Muktinath.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Drive Muktinath to Tatopani",
      maxAltitude: "1,190 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Visit Muktinath Temple for blessings, then jeep/bus through the Kali Gandaki Gorge (~45 km, 4–5 hrs) — terraced fields and snowy peaks. Soak in Tatopani’s natural hot springs. Overnight in Tatopani.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Trek Tatopani to Ghorepani",
      maxAltitude: "2,860 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Steep ascent through villages, terraced fields, and rhododendron forest via Phalate and Chitre (~17 km, 7–8 hrs). Charming Ghorepani village for the night. Overnight in Ghorepani.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Poon Hill sunrise — trek to Ulleri — drive to Pokhara",
      maxAltitude: "3,210 m",
      meals: "Breakfast, Lunch",
      accommodation: "Hotel in Pokhara",
      description:
        "Pre-dawn hike to Poon Hill (3,210 m) for sunrise over Dhaulagiri, Annapurna, Machhapuchhre, and more. Descend through rhododendron and oak forest to Ulleri, then drive to Pokhara (~12 km trek, 4–5 hrs total). Overnight in Pokhara.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Drive Pokhara to Kathmandu",
      maxAltitude: "1,345 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Tourist bus or private vehicle (~210 km, 7–8 hrs) back to Kathmandu via hills and rivers. Free evening — optional farewell dinner with the team. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d15",
      dayLabel: "Day 15",
      title: "Final departure",
      maxAltitude: "1,345 m",
      meals: "Breakfast",
      accommodation: "— (departure day)",
      description:
        "Private transfer to Tribhuvan International Airport for your departure flight. End of the Annapurna Circuit journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Fixed and private departures available spring and autumn. March–May and September–November usually bring the clearest mountain views for Thorong La. Winter is colder on the pass; monsoon means rain on lower sections.",
  availabilityNotes: [
    "Private and small-group joining departures (1–12 pax)",
    "Prior high-mountain trekking experience recommended",
    "Thorong La crossing depends on weather and group fitness",
    "Extensions: Tilicho Lake, Nar Phu, ABC, or Upper Mustang on request",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Private jeep upgrade (Day 3)",
      description: "Kathmandu to Dharapani by private jeep instead of local bus.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Pokhara–Kathmandu flight (Day 14)",
      description: "Skip the long bus ride with a domestic flight to Kathmandu.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Tilicho Lake extension",
      description: "Add days from Manang to visit Tilicho Lake before rejoining the circuit.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a4",
      title: "Single room supplement",
      description: "Private rooms where available in hotels and teahouses.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport pickup and drop-off in Kathmandu as per itinerary",
    "3 nights hotel in Kathmandu + 1 night in Pokhara (BB basis)",
    "9 nights teahouse / guest house accommodation on the trek",
    "Licensed mountain guide (salary, food, lodging, insurance)",
    "Porter to carry trek luggage (typically 1 per 2 trekkers)",
    "ACAP and TIMS permits",
    "Meals as per itinerary (~14 breakfasts, 11 lunches, 11 dinners on trek)",
    "Road transfers: Kathmandu–Dharapani, Muktinath–Tatopani, Pokhara–Kathmandu",
    "Kathmandu heritage sightseeing tour (Day 2) as listed",
    "Trek map, seasonal fruit on trek, first-aid kit, and completion certificate",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Nepal entry visa fee",
    "Travel insurance (mandatory — high-altitude evacuation)",
    "Lunch and dinner in Kathmandu and Pokhara (unless stated)",
    "Kathmandu sightseeing entrance fees (~NPR 2,600 per person)",
    "International airfare to and from Nepal",
    "Tips for guide, porter, and drivers",
    "Drinks, hot showers, charging, Wi-Fi, and laundry on the trail",
    "Personal shopping and personal trekking equipment",
    "Costs from roadblocks, weather, or delays beyond our control",
    "Anything not listed in the includes section",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1454496522488-7a8e488e8606"),
      caption: "Annapurna range panoramas on the Circuit",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "High Himalayan ridges toward Thorong La",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1585409677983-0f6c41ca9c3b"),
      caption: "Annapurna massif mountain light",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Marsyangdi valley approaches",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May and September–November usually offer the clearest views and most reliable Thorong La conditions. Morning departures on pass day are essential.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & AMS",
      body: "Maximum altitude is Thorong La at 5,416 m. Use the Manang rest day and Ice Lake hike, drink plenty of water, and descend if symptoms worsen.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty & distance",
      body: "Strenuous — ~116 km on foot from Dharapani to Ulleri with steep climbs, rocky paths, and a demanding pass day. Prior high-mountain trekking experience recommended.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Lodges & meals",
      body: "Teahouses on the trail; hotels in Kathmandu and Pokhara. Expect dal bhat, noodles, and hearty mountain breakfasts. Hot showers and Wi-Fi usually cost extra higher up.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack for cold alpine nights and a long pass day. Porters typically carry your main bag; you hike with a daypack.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers & thermals",
        "Fleece mid-layer and down jacket",
        "Windbreaker / waterproof shell",
        "Trekking shirts and pants (multiple pairs)",
        "Warm hat, sun cap, gloves, scarf / buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Camp shoes",
        "Trekking poles (strongly recommended)",
        "Daypack + duffel for porter",
        "Water bottle / filter",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "SPF sunscreen, lip balm, sunglasses",
        "Headlamp + spare batteries (Poon Hill pre-dawn)",
        "Personal medications and blister care",
        "Electrolyte powder / ORS",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport, visa, and copies",
        "Travel insurance details",
        "Cash for personal trail expenses",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Route briefing and permit arrangement in Kathmandu",
    "First-aid support with your guiding team",
    "Sleeping bag and down jacket rental if needed",
    "Advice on Tilicho, Nar Phu, ABC, or Mustang extensions",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Annapurna Circuit Trek?",
      answer:
        "A 15-day teahouse trek around the Annapurna massif from Kathmandu — through Manang, over Thorong La (5,416 m), Muktinath, Kali Gandaki, Tatopani, and finishing with Poon Hill sunrise.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Strenuous. You need strong fitness and prior high-mountain trekking experience. The Thorong La day is 9–10 hours at altitude.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This listing starts at US$1,005 for 2–5 pax (US$1,250 solo; US$1,000 for 6+; US$975 for 10+). Compare-at US$1,550.",
      visible: true,
    },
    {
      id: "q4",
      question: "What is the maximum altitude?",
      answer:
        "Thorong La Pass at 5,416 m. The Manang acclimatization hike to Ice Lake reaches about 4,500 m.",
      visible: true,
    },
    {
      id: "q5",
      question: "Does this include Poon Hill?",
      answer:
        "Yes — Day 13 includes a pre-dawn hike to Poon Hill for sunrise before descending to Ulleri and driving to Pokhara.",
      visible: true,
    },
    {
      id: "q6",
      question: "When is the best time to go?",
      answer:
        "Spring (March–May) and autumn (September–November) usually offer the best weather and mountain views for Thorong La.",
      visible: true,
    },
    {
      id: "q7",
      question: "Is travel insurance necessary?",
      answer:
        "Yes. Cover high-altitude trekking and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q8",
      question: "Can I customize the itinerary?",
      answer:
        "Yes — Tilicho Lake, Nar Phu, private jeep upgrades, or Pokhara–Kathmandu flights can be added on request.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Annapurna Circuit?",
  ctaBody: `Tell us your preferred dates and group size (1–12) — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Annapurna Circuit Trek 15 Days | Summit Seek",
  metaDescription:
    "Book 15-day Annapurna Circuit trek — Thorong La, Muktinath, Tatopani hot springs, Poon Hill sunrise & group rates from US$1,000.",
};
