import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_ANNAPURNA_LUXURY_LODGE: TrekPageContent = {
  coverImageUrl: img("photo-1519904981063-b0cf448d479e", 2000),
  coverTitle: "Annapurna Luxury Lodge Trek - 10 Days",
  coverSubtitle:
    "Comfortable mid-hill Annapurna walks with luxury lodge nights — Dhampus, Landruk, and Ghandruk Gurung villages, Machhapuchhre views, plus Kathmandu and Pokhara.",
  heroMainImageUrl: img("photo-1519904981063-b0cf448d479e", 2000),
  heroSideImage1Url: img("photo-1506905925346-21bda4d32df4", 900),
  heroSideImage2Url: img("photo-1464822759023-fed622ff2c3b", 900),
  breadcrumbLabel: "Annapurna Region · Luxury Lodge",
  title: "Annapurna Luxury Lodge Trek - 10 Days",
  regionLabel: "Annapurna Region",
  rating: 5,
  reviewCount: 2,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 3290,
  compareAtPrice: 3590,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "8% OFF",
  shortTripBadge: "Luxury Lodges",
  durationLabel: "10 Days",
  difficultyLabel: "Moderate",
  groupSizeLabel: "2+",
  bookingNote:
    "Private luxury lodge departures. Package includes Kathmandu and Pokhara deluxe hotel nights (BB as listed), KTM–Pokhara flights, ACAP & TIMS, licensed guide and porter, full-board meals on trek days, and twin-sharing luxury mountain lodges with attached bathrooms where available. Ideal soft adventure below 2,200 m with Annapurna panoramas.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 3590, visible: true },
    { id: "gd2", paxLabel: "2-3 pax", price: 3290, visible: true },
    { id: "gd3", paxLabel: "4-6 pax", price: 3090, visible: true },
    { id: "gd4", paxLabel: "7+ pax", price: 2890, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "10 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Moderate", visible: true },
    { id: "f3", label: "Max Altitude", value: "2,210 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Annapurna / Pokhara", visible: true },
    { id: "f6", label: "Group Size", value: "2 onwards", visible: true },
    { id: "f7", label: "Style", value: "Luxury lodge trek", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–Jun & Sep–Dec",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "Annapurna Luxury Lodge Trek – 10 Days is a scenic mid-hill holiday through rhododendron, magnolia, oak, and pine forests facing the Annapurna massif — with overnight stops in cozy high-standard lodges rather than basic teahouses.\n\nFrom Kathmandu you fly to lakeside Pokhara, drive to Phedi, and trek into Dhampus for mountain-facing rooms and Gurung village life. Continue via Potana and Pitam Deurali (~2,050 m+) to Landruk, then climb to Ghandruk (1,940 m) — one of the largest Gurung settlements — for a full cultural exploration day before descending to Nayapul and returning to Pokhara and Kathmandu.\n\nExpect panoramas of Annapurna South, Hiunchuli, Machhapuchhre (Fishtail), Dhaulagiri, and Manaslu ranges, plus warm hospitality and attached-bathroom comfort. Summit Seek includes deluxe city hotels, domestic flights, permits, guide, porter, luxury lodge nights, and clear group pricing.",
  overviewImageUrl: img("photo-1506905925346-21bda4d32df4"),
  highlightsHeading: "Highlights",
  highlights: [
    "Luxury mountain lodges with private bathrooms and peak-facing rooms",
    "Dhampus ridge panoramas of Annapurna, Dhaulagiri & Machhapuchhre",
    "Gurung culture in Landruk and Ghandruk villages",
    "Rhododendron forests and terraced mid-hill landscapes",
    "Moderate walking mostly below 2,200 m — great first Nepal trek",
    "Kathmandu heritage sightseeing and Pokhara lakeside nights",
    "Scenic Kathmandu–Pokhara flights both ways",
    "Avoid overcrowded basic teahouses on popular foothill trails",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport transfers by private vehicle as listed",
    "Deluxe Kathmandu hotel nights (BB) and Pokhara nights (BB) as listed",
    "Welcome dinner in Kathmandu as listed",
    "Kathmandu–Pokhara–Kathmandu flights",
    "ACAP and TIMS permits",
    "Licensed English-speaking guide; porter (2:1) as listed",
    "Twin-sharing luxury lodge lodging and three meals a day on trek",
    "First-aid kit; emergency evacuation coordination (insurance pays)",
  ],
  whyHeading: "Why choose luxury lodge Annapurna?",
  whyPoints: [
    "Same foothill scenery with quieter, exclusive lodge nights",
    "Attached bathrooms and better dining than standard teahouses",
    "Ideal for first-time trekkers and comfort-focused travelers",
    "Strong Gurung cultural immersion at Ghandruk",
    "Short, moderate days — no extreme altitude",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "Yes — one of the best luxury introductions to Nepal trekking. Graded Moderate with daily walks of about 4–5 hours on ups and downs, but maximum altitude stays around 2,210 m so AMS risk is low compared with EBC or ABC.\n\nModerate fitness is enough. Travel insurance covering trek medical and evacuation is still recommended.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train with regular walks, hills, and light cardio for 4–6 weeks",
    "Break in hiking boots before departure",
    "Pack layers for cool ridge evenings and warmer valley days",
    "Book early in peak season — luxury lodges fill quickly",
    "Obtain comprehensive travel insurance",
    "Confirm any dietary needs for lodge kitchens when booking",
  ],
  itineraryHeading: "10-day itinerary",
  itineraryIntro:
    "Based on the classic Dhampus–Landruk–Ghandruk luxury lodge circuit with Kathmandu and Pokhara bookends. Lodge names may vary by availability while keeping comfort standards.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,350 m",
      meals: "Welcome dinner as listed",
      accommodation: "Deluxe hotel in Kathmandu",
      description:
        "Airport meet-and-greet and hotel transfer. Trek briefing and welcome dinner with cultural program as listed. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Kathmandu sightseeing",
      maxAltitude: "1,350 m",
      meals: "Breakfast",
      accommodation: "Deluxe hotel in Kathmandu",
      description:
        "Guided tour of key heritage sites such as Durbar Square, Swayambhunath, Boudhanath, Pashupatinath (view from east bank for non-Hindus), and Patan Durbar Square. Entrance fees extra unless added. Overnight Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Fly Kathmandu – Pokhara",
      maxAltitude: "860 m",
      meals: "Breakfast",
      accommodation: "Deluxe hotel in Pokhara",
      description:
        "Morning flight (~30 min) to Pokhara with Himalayan panoramas. Transfer to lakeside hotel; free time by Phewa Lake with Annapurna views. Overnight Pokhara.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Drive Phedi – trek to Dhampus",
      maxAltitude: "1,530 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Luxury lodge in Dhampus",
      description:
        "Drive (~1 hour) to Phedi trailhead, then climb stone steps through forest and terraces to Dhampus (~4 hours). Lodge rooms face Annapurna–Dhaulagiri–Machhapuchhre views. Overnight luxury lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Trek Dhampus – Landruk",
      maxAltitude: "2,050 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Luxury lodge in Landruk",
      description:
        "Via Potana and Pitam Deurali ridge (~2,050 m+) with Annapurna panoramas, then descend through forest to Landruk (~5 hours) with views of Annapurna South and Hiunchuli. Overnight luxury lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Trek Landruk – Ghandruk",
      maxAltitude: "1,940 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Luxury lodge in Ghandruk",
      description:
        "Descend toward the Modi Khola, then climb stone steps into large Gurung village Ghandruk (~5 hours). Afternoon free for museum and village walks with Annapurna views. Overnight luxury lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Ghandruk cultural exploration",
      maxAltitude: "1,940 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Luxury lodge in Ghandruk",
      description:
        "Full day in Ghandruk to explore Gurung farm life, culture, and viewpoints — gateway village for many Annapurna trails. Overnight luxury lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Trek Ghandruk – Nayapul – drive Pokhara",
      maxAltitude: "1,940 m",
      meals: "Breakfast, Lunch; dinner in Pokhara as arranged",
      accommodation: "Deluxe hotel in Pokhara",
      description:
        "Descend via Kimche and farm terraces to Birethanti / Nayapul (~4 hours walking), then drive (~2 hours) back to Pokhara. Overnight lakeside hotel.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Fly Pokhara – Kathmandu",
      maxAltitude: "1,350 m",
      meals: "Breakfast",
      accommodation: "Deluxe hotel in Kathmandu",
      description:
        "Morning flight to Kathmandu (~30 min). Hotel transfer and free afternoon for shopping or rest. Overnight Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Departure from Kathmandu",
      maxAltitude: "1,350 m",
      meals: "Breakfast",
      accommodation: "—",
      description:
        "Airport transfer for your international flight. End of the Annapurna Luxury Lodge journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best in March–May (rhododendron bloom) and September–November (clear skies). Private luxury groups welcome year-round; monsoon trails can be slippery and leechy.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Luxury lodges sell out in peak season — book early",
    "Fixed and private group options",
    "Kathmandu and Pokhara hotel categories upgradeable on request",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Pokhara sightseeing / Peace Pagoda",
      description: "Half-day lakeside and viewpoint tour with private vehicle.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Heritage entrance fees package",
      description: "Pre-pay Kathmandu/Pokhara monument tickets with the guide.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Single-room upgrade",
      description: "Private room in city hotels and lodges where available.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport pickups and drops by private vehicle as listed",
    "Welcome dinner in Kathmandu as listed",
    "Deluxe twin/double hotel nights on BB in Kathmandu (as listed)",
    "Deluxe twin/double hotel nights on BB in Pokhara (as listed)",
    "Kathmandu–Pokhara–Kathmandu flights",
    "ACAP and TIMS permits",
    "Licensed English-speaking guide and porter (2:1) as listed",
    "Twin-sharing luxury lodge lodging and three meals a day on trek",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Nepal visa fees and international airfare",
    "Lunch and dinner in Kathmandu and Pokhara (except welcome dinner as listed)",
    "Monument entrance fees on city sightseeing (unless added)",
    "Travel insurance including emergency evacuation (mandatory cover recommended)",
    "Personal expenses: laundry, charging, drinks, tips",
    "Extra nights from early arrival, late departure, or delays",
    "Anything not listed under inclusions",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1519904981063-b0cf448d479e"),
      caption: "Annapurna foothill ridges and lodge country",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Mountain light over mid-hill villages",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Forest trails toward Ghandruk and Landruk",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1483728642387-6c3bdd6c93e5"),
      caption: "Pokhara lakes and Annapurna reflections",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May for flowers and warm days; September–November for clearest mountain views. Avoid heavy monsoon if possible.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & difficulty",
      body: "Highest points around ~2,050–2,210 m (Deurali / ridge). Graded Moderate — ups and downs, but far gentler altitude than ABC or EBC.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Permits",
      body: "Annapurna Conservation Area Permit (ACAP) and TIMS. Summit Seek arranges these with your guide.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Routes",
      body: "Kathmandu → Pokhara → Phedi → Dhampus → Landruk → Ghandruk → Nayapul → Pokhara → Kathmandu.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Porters carry main bags; keep water, layers, and camera in a daypack. Luxury lodges provide comfortable beds — a sleeping bag is usually optional.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Light fleece or mid-layer",
        "Waterproof shell",
        "Warm layer for cool evenings",
        "Sun hat and buff",
        "Modest village-appropriate clothes",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear",
      items: [
        "Broken-in hiking boots or sturdy trail shoes",
        "Trekking poles (helpful on stone steps)",
        "Camp shoes / sandals",
        "Good socks",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Daypack & personal",
      items: [
        "Daypack with rain cover",
        "Reusable water bottle",
        "Sunglasses and sunscreen",
        "Personal medications and blister care",
        "Headlamp",
        "Power bank",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Nepal visa as applicable",
        "Travel insurance documents",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Luxury lodge pre-booking and city hotel coordination",
    "ACAP / TIMS processing and licensed guide / porter",
    "Domestic flight ticketing as listed",
    "Emergency evacuation coordination (insurance pays)",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Annapurna Luxury Lodge Trek?",
      answer:
        "A 10-day moderate foothill trek combining Kathmandu and Pokhara with luxury lodge nights in Dhampus, Landruk, and Ghandruk — Annapurna views without extreme altitude.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Moderately challenging with daily ups and downs of several hours, but maximum altitude stays around 2,210 m — suitable for fit beginners seeking comfort.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This listing starts at US$3,290 for 2–3 pax (US$3,590 for 1; US$3,090 for 4–6; US$2,890 for 7+). Market luxury-lodge packages elsewhere often start near US$1,599–2,500 depending on inclusions.",
      visible: true,
    },
    {
      id: "q4",
      question: "What is the maximum altitude?",
      answer:
        "About 2,210 m on ridge sections (Deurali area). Ghandruk sits around 1,940 m — much lower than Annapurna Base Camp.",
      visible: true,
    },
    {
      id: "q5",
      question: "Are bathrooms attached?",
      answer:
        "Luxury lodges typically offer attached western bathrooms and hot showers (availability can vary with weather and season).",
      visible: true,
    },
    {
      id: "q6",
      question: "What permits are required?",
      answer:
        "ACAP and TIMS. Summit Seek arranges these for your group.",
      visible: true,
    },
    {
      id: "q7",
      question: "When is the best time to go?",
      answer:
        "March–May and September–November. Spring brings rhododendrons; autumn usually has the clearest mountain views.",
      visible: true,
    },
    {
      id: "q8",
      question: "Can solo travelers join?",
      answer:
        "Yes — private departures are available for solo travelers and families. Group discounts apply as group size grows.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Annapurna luxury lodges?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm lodge availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Annapurna Luxury Lodge Trek 10 Days | Summit Seek",
  metaDescription:
    "Book 10-day Annapurna Luxury Lodge Trek — Dhampus, Landruk, Ghandruk, deluxe hotels, flights, permits, guide & group rates from US$2,890.",
};
