import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_ANNAPURNA_BASE_CAMP: TrekPageContent = {
  coverImageUrl: img("photo-1585409677983-0f6c41ca9c3b", 2000),
  coverTitle: "Annapurna Base Camp Trek - 11 Days",
  coverSubtitle:
    "Stand inside the glacial amphitheatre beneath Annapurna I — Poon Hill sunrise, Gurung villages, Machhapuchhre Base Camp, and Jhinu hot springs.",
  heroMainImageUrl: img("photo-1585409677983-0f6c41ca9c3b", 2000),
  heroSideImage1Url: img("photo-1483728642387-6c3bdd6c93e5", 900),
  heroSideImage2Url: img("photo-1464822759023-fed622ff2c3b", 900),
  breadcrumbLabel: "Annapurna Region · Base Camp",
  title: "Annapurna Base Camp Trek - 11 Days",
  regionLabel: "Annapurna Region",
  rating: 5,
  reviewCount: 48,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 720,
  compareAtPrice: 899,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "20% OFF",
  shortTripBadge: "Classic Trek",
  durationLabel: "11 Days",
  difficultyLabel: "Moderate",
  groupSizeLabel: "2+",
  bookingNote:
    "Private and small-group departures available year-round. Tourist bus Kathmandu ↔ Pokhara included; flights or private jeep available as add-ons.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 850, visible: true },
    { id: "gd2", paxLabel: "2-5 pax", price: 720, visible: true },
    { id: "gd3", paxLabel: "6-9 pax", price: 690, visible: true },
    { id: "gd4", paxLabel: "10-17 pax", price: 650, visible: true },
    { id: "gd5", paxLabel: "18-25 pax", price: 600, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "11 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Moderate", visible: true },
    { id: "f3", label: "Max Altitude", value: "4,130 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Annapurna", visible: true },
    { id: "f6", label: "Group Size", value: "2+", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Culture", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Feb–Jun & Sep–Dec",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The 11-day Annapurna Base Camp trek takes you deep into Nepal’s Annapurna region to stand inside a glacial basin beneath Annapurna I (8,091 m), surrounded by Machhapuchhre, Dhaulagiri, and Hiunchuli. From glacier valleys and terraced fields, you pass stone-built Gurung and Magar villages, hike to Poon Hill for sunrise over the Annapurna range, then enter alpine terrain before relaxing at the hot springs of Jhinu Danda.\n\nYour journey begins with a peaceful morning in Pokhara (820 m), then a drive toward Nayapul and Tikhedhunga and the climb to Ulleri and Ghorepani through rhododendron forest. Beyond Chhomrong — gateway to the Annapurna Sanctuary — the trail grows quieter through Sinuwa, Bamboo, Himalaya, and Deurali, then via Machhapuchhre Base Camp to Annapurna Base Camp at 4,130 m.\n\nSummit Seek guides every day with licensed leaders, fair porter support, clear pricing, and flexible private departures so you can focus on the mountains.",
  overviewImageUrl: img("photo-1544735716-392fe2489ffa"),
  highlightsHeading: "Highlights",
  highlights: [
    "Annapurna Base Camp (4,130 m) — a natural amphitheatre of towering peaks",
    "Poon Hill sunrise over Dhaulagiri, Annapurna I, and Nilgiri",
    "Machhapuchhre Base Camp (3,700 m) — close views of the sacred Fishtail",
    "360° Himalayan panorama at ABC: Annapurna South, Hiunchuli, Gangapurna & more",
    "Ghandruk & Chhomrong — traditional Gurung culture and stone villages",
    "Jhinu Danda natural hot springs after the descent",
    "Rhododendron forests, terraced fields, and alpine glacier terrain",
    "Scenic lakeside Pokhara as your trek hub",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Licensed English-speaking guide with salary, food, lodging & insurance included",
    "Porter support (typically 2 guests : 1 porter) with fair pay and insurance",
    "Kathmandu ↔ Pokhara tourist bus and private Pokhara ↔ trailhead transfers",
    "ACAP permit arranged; TIMS / local fees as required",
    "Teahouse lodging and full-board meals on trek days as listed",
    "First-aid kit & oximeter on trail; emergency evacuation coordination via your insurance",
    "Online pre-trek briefing after booking and daily evening plan with your guide",
  ],
  whyHeading: "Why choose Annapurna Base Camp?",
  whyPoints: [
    "Stand inside a Himalayan amphitheatre without technical climbing skills",
    "Combine culture, forests, sunrise viewpoints, and high alpine scenery in one trip",
    "Moderate difficulty — rewarding for fit beginners with good preparation",
    "Classic teahouse network with warm meals after each trek day",
    "Memorable finish at riverside hot springs before returning to Pokhara",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "Yes — with solid fitness. ABC is moderate: expect long walking days, stone steps, and a max altitude of 4,130 m. Prior multi-day hiking helps, but many first-time Himalayan trekkers succeed with preparation.\n\nBuild cardio and stair/hill walks before you fly, stay hydrated, and tell your guide early if you feel unwell. If you have medical conditions, check with your doctor before booking. Travel insurance covering helicopter evacuation is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Walk 45–60 minutes several times a week; add hills or stairs in the month before departure",
    "Break in waterproof hiking boots on practice walks",
    "Pack layers for warm valleys and cold nights near MBC/ABC, plus rain shell and sun protection",
    "Buy travel insurance covering trekking to 4,500 m+ and helicopter evacuation",
    "Arrive in Kathmandu at least one day before Day 1 (ideally by 3 p.m.) for briefing and packing",
    "Read our packing checklist and confirm dietary needs with Summit Seek",
  ],
  itineraryHeading: "11-day itinerary",
  itineraryIntro:
    "Walking and drive times are estimates and vary with pace, road, and weather. Lodges may change with availability. Your guide can adjust the plan for safety or comfort. Tourist bus Kathmandu–Pokhara is included; flights or private jeep are optional add-ons.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Kathmandu – Pokhara (drive)",
      maxAltitude: "1,350 m → 820 m",
      meals: "Breakfast (hotel)",
      accommodation: "Hotel in Pokhara",
      description:
        "Early morning tourist bus (approx. 6–7 hours / 205 km) along the Prithvi Highway beside the Trishuli and Marsyangdi rivers. Arrive in lakeside Pokhara by afternoon — views of Annapurna, Dhaulagiri, and Machhapuchhre. Settle into your hotel, optional Phewa Lake stroll, and evening trek briefing with your Summit Seek guide.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Pokhara – Tikhedhunga – Ulleri",
      maxAltitude: "1,960 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Private drive via Nayapul and Birethanti to Tikhedhunga (about 2 hours). After lunch, trek across the Bhurungdi Khola and climb stone staircases through forest to Ulleri, a traditional Magar village with views of Annapurna South and Hiunchuli (about 2–4 hours walking).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Ulleri – Ghorepani",
      maxAltitude: "2,860 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Trek through Banthanti and Nangethanti into rhododendron, pine, and oak forest toward Ghorepani (about 3–4 hours). Enjoy Pun Magar hospitality and panoramic Annapurna–Dhaulagiri views before an early night ahead of Poon Hill sunrise.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Poon Hill sunrise – Tadapani",
      maxAltitude: "3,210 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Pre-dawn hike to Poon Hill (3,210 m) for sunrise over Annapurna, Dhaulagiri, Nilgiri, and Machhapuchhre. Return to Ghorepani for breakfast, then continue via Deurali and Banthanti through rhododendron forest to Tadapani (about 4–6 hours total walking).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Tadapani – Chhomrong",
      maxAltitude: "2,165 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Descend through Chuile and Gurjung forests, cross Kimrong Khola, then climb into Chhomrong — gateway to the Annapurna Sanctuary, with Gurung stone houses and sanctuary views (about 5 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Chhomrong – Himalaya",
      maxAltitude: "2,890 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Longer sanctuary day: descend to Chhomrong Khola, climb to Sinuwa and Khuldigar, through bamboo forest to Bamboo for lunch, then upstream along the Modi Khola to Himalaya village in a cooler gorge (about 6–7 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Himalaya – ABC via Machhapuchhre Base Camp",
      maxAltitude: "4,130 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Trek via Hinku Cave, Weeping Wall, and Deurali to Machhapuchhre Base Camp (3,700 m) for lunch, then into the Annapurna Sanctuary amphitheatre to Annapurna Base Camp (4,130 m). 360° views of Annapurna I, South, Hiunchuli, Gangapurna, and more (about 5 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "ABC – Bamboo",
      maxAltitude: "4,130 m → 2,350 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Sunrise at ABC, then descend via MBC, Deurali, and Himalaya (lunch) through the Modi Khola valley to Bamboo among dense bamboo forest (about 6 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Bamboo – Jhinu Danda (hot springs)",
      maxAltitude: "1,780 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Shorter walk via Sinuwa and Chhomrong to Jhinu Danda (about 3–4 hours). Soak in natural riverside hot springs and recover after high days in the sanctuary.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Jhinu Danda – Pokhara (drive)",
      maxAltitude: "820 m",
      meals: "Breakfast, Lunch",
      accommodation: "Hotel in Pokhara",
      description:
        "Private vehicle on mountain roads via Nayapul back to Pokhara (about 2–3 hours). Free afternoon by Phewa Lake — cafés, lakeside walk, or rest. Overnight hotel in Pokhara.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Pokhara – Kathmandu (drive)",
      maxAltitude: "1,350 m",
      meals: "Breakfast",
      accommodation: "— (return to Kathmandu)",
      description:
        "Tourist bus back to Kathmandu along the Trishuli valley (about 6–7 hours). Arrive by afternoon — end of your Annapurna Base Camp journey with Summit Seek. Optional hotel nights in Kathmandu available on request.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "ABC departures run on private and small-group bases across the best seasons. Spring and autumn usually bring the clearest mountain views; winter is quieter and colder near ABC; monsoon is greener but wetter on lower trails.",
  availabilityNotes: [
    "Private departures with flexible start dates",
    "Small-group joining available with advance booking",
    "Fully customizable for couples, families, and larger groups",
    "Confirmed booking after deposit and online trip briefing",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Kathmandu ↔ Pokhara flight",
      description: "Faster mountain-view flights instead of the tourist bus (subject to weather).",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Private Kathmandu ↔ Pokhara jeep",
      description: "Private road transfer for more comfort and flexible stops.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Extra Kathmandu / Pokhara hotel nights",
      description: "Add rest days before or after the trek — we can book hotels to your budget.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Kathmandu ↔ Pokhara tourist bus (as per itinerary)",
    "Private vehicle Pokhara ↔ Tikhedhunga and Jhinu Danda ↔ Pokhara",
    "2 nights hotel in Pokhara with breakfast (twin / double)",
    "Teahouse / lodge accommodation during the trek (twin sharing)",
    "Full-board meals on trek days as listed (one main course per meal) + seasonal fruit",
    "Licensed English-speaking trekking guide (salary, food, lodging, insurance)",
    "Porter support (typically 2:1) with insurance and fair wages",
    "Annapurna Conservation Area Permit (ACAP) & applicable local taxes",
    "Basic first-aid kit and oximeter with the guiding team",
    "Pre-trek briefing and farewell gathering in Pokhara",
    "Sleeping bag / down jacket rental options on many packages (return after trek)",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "International flights and Nepal visa fees",
    "Hotel stays and meals in Kathmandu (before / after trek)",
    "Extra nights in Kathmandu or Pokhara due to early arrival or delays",
    "Travel insurance (mandatory — must cover helicopter evacuation)",
    "Tips for guide, porter, and driver",
    "Personal expenses (hot showers, Wi-Fi, charging, snacks, drinks, laundry)",
    "Extra food beyond the included main meal per sitting",
    "Costs from delays beyond our control (weather, strikes, roadblocks, illness)",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1585409677983-0f6c41ca9c3b"),
      caption: "Annapurna massif and sanctuary approaches",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1483728642387-6c3bdd6c93e5"),
      caption: "Sunrise ridgelines near Poon Hill",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "High Himalayan panorama",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Forest and village trails toward the sanctuary",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "February–June and September–December are popular windows. March–May and September–November usually offer the clearest views. Pack layers — mornings at Ghorepani and nights at ABC can be cold.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & climate",
      body: "Max altitude is 4,130 m at ABC. Expect mild days in lower villages and cold alpine nights near MBC/ABC. Monsoon (Jun–Aug) is lush but wetter; winter can bring frost and occasional snow higher up.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Culture along the route",
      body: "Gurung and Magar communities welcome travelers through villages like Ghorepani, Ghandruk approaches, and Chhomrong. Dress modestly, ask before photographing people, and enjoy local dal bhat hospitality.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Lodges & facilities",
      body: "Teahouses offer twin or shared rooms with blankets. Attached bathrooms appear on some lower nights; higher lodges are simpler. Hot showers and charging often cost a small fee. Carry toilet paper, sanitizer, and a quick-dry towel.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack light — porter limit is typically about 9 kg per trekker in a shared duffel. Carry a daypack for water, layers, documents, and valuables. Many bulky items can be rented in Kathmandu or Pokhara.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece or mid-layer",
        "Down / insulated jacket",
        "Waterproof shell",
        "Trekking pants + evening pants",
        "Warm hat, sun hat, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in hiking boots",
        "Camp shoes / sandals",
        "3–4 pairs trekking socks",
        "25–35L daypack",
        "Duffel for porter (within weight limit)",
        "Trekking poles (recommended)",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "Personal medications & blister care",
        "Sunscreen SPF 50+ & lip balm",
        "Sunglasses",
        "Water bottle / bladder + purification",
        "Hand sanitizer & wet wipes",
        "Headlamp + spare batteries",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance details",
        "Passport photos for permits if requested",
        "Cash (NPR) for personal trail expenses (~US$15–20/day)",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Duffel bag for porter use on many packages (return after trek)",
    "Route briefing and packing guidance before departure",
    "Sleeping bag / down jacket rental options on request",
    "Help arranging Kathmandu hotels and flight upgrades",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "How hard is the Annapurna Base Camp trek?",
      answer:
        "It is generally moderate. Expect several hours of walking daily with stone steps, forest trails, and a high point of 4,130 m. Fit beginners with preparation succeed; it is less extreme than Everest Base Camp for many trekkers but still demanding.",
      visible: true,
    },
    {
      id: "q2",
      question: "How long does the ABC trek take?",
      answer:
        "This Summit Seek package is 11 days Kathmandu to Kathmandu, including Pokhara transfers, Poon Hill, the sanctuary approach to ABC, Jhinu hot springs, and the return.",
      visible: true,
    },
    {
      id: "q3",
      question: "What is the highest altitude?",
      answer:
        "Annapurna Base Camp at approximately 4,130 m. Machhapuchhre Base Camp is about 3,700 m on the same day.",
      visible: true,
    },
    {
      id: "q4",
      question: "Where does the trek start and end?",
      answer:
        "The package starts and ends in Kathmandu. Trekking begins after the drive from Pokhara toward Tikhedhunga/Ulleri and finishes with a drive from Jhinu Danda back to Pokhara, then bus to Kathmandu.",
      visible: true,
    },
    {
      id: "q5",
      question: "Are permits included?",
      answer:
        "Yes. The Annapurna Conservation Area Permit (ACAP) and applicable local taxes for this itinerary are included. Carry your passport and permits at checkpoints.",
      visible: true,
    },
    {
      id: "q6",
      question: "Do I need travel insurance?",
      answer:
        "Yes. Your policy should cover trekking at altitude and helicopter evacuation. Summit Seek does not sell insurance — we can help you confirm altitude limits before you buy.",
      visible: true,
    },
    {
      id: "q7",
      question: "How much does the trek cost?",
      answer:
        "Listed from US$720 per person for small groups (2–5), with progressive discounts for larger groups. Solo pricing and exact quotes depend on dates and add-ons — enquire for a clear package.",
      visible: true,
    },
    {
      id: "q8",
      question: "Is transport included?",
      answer:
        "Kathmandu ↔ Pokhara tourist bus and private transfers between Pokhara and the trailheads are included. Domestic flights or private jeeps for the highway segment are optional add-ons.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Annapurna Base Camp?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Annapurna Base Camp Trek 11 Days | Summit Seek",
  metaDescription:
    "Book the 11-day Annapurna Base Camp trek with Summit Seek — Poon Hill sunrise, ABC amphitheatre, hot springs, guide, porter, permits & group discounts from Kathmandu.",
};
