import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_ANNAPURNA_BASE_CAMP_TREK: TrekPageContent = {
  coverImageUrl: img("photo-1585409677983-0f6c41ca9c3b", 2000),
  coverTitle: "Annapurna Base Camp Trek - 15 Days",
  coverSubtitle:
    "Complete ABC package — Kathmandu sightseeing, Pokhara, Poon Hill sunrise, Annapurna Sanctuary (4,130 m), and Jhinu Danda hot springs.",
  heroMainImageUrl: img("photo-1585409677983-0f6c41ca9c3b", 2000),
  heroSideImage1Url: img("photo-1483728642387-6c3bdd6c93e5", 900),
  heroSideImage2Url: img("photo-1464822759023-fed622ff2c3b", 900),
  breadcrumbLabel: "Packages · Annapurna Region",
  title: "Annapurna Base Camp Trek - 15 Days",
  regionLabel: "Annapurna Region",
  rating: 5,
  reviewCount: 5,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 955,
  compareAtPrice: 1540,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "38% OFF",
  shortTripBadge: "Best Seller",
  durationLabel: "15 Days",
  difficultyLabel: "Moderate",
  groupSizeLabel: "2+",
  bookingNote:
    "Complete package includes 3 nights Kathmandu hotel (BB), 2 nights Pokhara hotel (BB), guided Kathmandu sightseeing, tourist bus KTM–Pokhara–KTM, private transfers to trailhead, ACAP & TIMS permits, licensed guide, porter (2:1), and full-board trek meals. Flights or private jeep available as add-ons.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 1200, visible: true },
    { id: "gd2", paxLabel: "2-4 pax", price: 955, visible: true },
    { id: "gd3", paxLabel: "5-8 pax", price: 900, visible: true },
    { id: "gd4", paxLabel: "9+ pax", price: 875, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "15 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Moderate", visible: true },
    { id: "f3", label: "Max Altitude", value: "4,130 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Annapurna", visible: true },
    { id: "f6", label: "Group Size", value: "2+", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Culture", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Feb–Jun & Sep–Dec",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "Annapurna Base Camp Trek – 15 Days is one of the world’s most exciting teahouse treks — a complete package from Kathmandu through Pokhara into the Annapurna Sanctuary beneath Annapurna I (8,091 m).\n\nOver 15 days you’ll see thirteen peaks above 8,000 m and many above 7,000 m, walk picturesque villages and rhododendron forests, climb to Poon Hill (3,210 m) for sunrise over Dhaulagiri and Annapurna, then follow the Modi Khola through Machhapuchhre Base Camp to Annapurna Base Camp (4,130 m) — a natural amphitheatre guarded by mountains on all sides.\n\nThe return route includes Jhinu Danda’s natural hot springs and scenic Pothana before driving back to Pokhara and Kathmandu. Summit Seek includes hotels, sightseeing, permits, guide, porter, meals, and clear group pricing.",
  overviewImageUrl: img("photo-1544735716-392fe2489ffa"),
  highlightsHeading: "Highlights",
  highlights: [
    "Stand at Annapurna Base Camp (4,130 m) inside the Sanctuary amphitheatre",
    "Poon Hill sunrise — Dhaulagiri, Annapurna I, and Machhapuchhre panoramas",
    "Machhapuchhre Base Camp (3,700 m) on the Annapurna South Glacier",
    "Views of Annapurna I (8,091 m), Hiunchuli, Gangapurna & more",
    "Ghandruk, Chhomrong & Gurung village culture",
    "Natural hot springs at Jhinu Danda",
    "Guided Kathmandu heritage sightseeing included",
    "Lakeside Pokhara gateway with Himalayan views",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport pickup and drop-off by private vehicle",
    "3 nights hotel in Kathmandu + 2 nights in Pokhara (BB basis)",
    "Guided Kathmandu sightseeing tour with private vehicle",
    "Licensed English-speaking guide with salary, food, lodging & insurance",
    "Porter support (typically 2 guests : 1 porter) with fair pay and insurance",
    "Tourist bus Kathmandu–Pokhara–Kathmandu; private Pokhara–Nayapul–Phedi transfers",
    "ACAP & TIMS permits; full-board meals on trek days",
    "Fresh fruit on trek, oximeter checks, first-aid kit, and trek map",
  ],
  whyHeading: "Why choose this 15-day ABC package?",
  whyPoints: [
    "Full-service package — hotels, sightseeing, and transfers included",
    "Combines Poon Hill, ABC Sanctuary, and hot springs in one journey",
    "Moderate grade — rewarding for fit beginners with preparation",
    "Classic teahouse network with warm meals after each trek day",
    "Flexible private departures with customizable itinerary on request",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "Yes — with solid fitness. Graded Moderate with a max altitude of 4,130 m. Expect long walking days, stone steps (especially Ulleri), and cold nights at ABC.\n\nBuild cardio and hill walks before you fly. Travel insurance covering helicopter evacuation to 4,500 m+ is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Walk 45–60 minutes several times a week; add hills or stairs before departure",
    "Break in waterproof hiking boots on practice walks",
    "Pack layers for warm valleys and cold nights at MBC/ABC",
    "Buy travel insurance covering trekking and helicopter evacuation",
    "Arrive Kathmandu at least one day before Day 1 for briefing",
    "Confirm dietary needs (vegetarian/vegan available) with Summit Seek",
  ],
  itineraryHeading: "15-day itinerary",
  itineraryIntro:
    "Walking and drive times are estimates and vary with pace, road, and weather. Lodges may change with availability. Tourist bus KTM–Pokhara included; flights or private jeep are optional add-ons.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,350 m",
      meals: "—",
      accommodation: "Hotel in Kathmandu",
      description:
        "Airport pickup and transfer to your hotel. Trek briefing and welcome overview. Free evening to explore Thamel or rest. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Kathmandu sightseeing tour",
      maxAltitude: "1,350 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Guided sightseeing (~6–7 hrs) to Pashupatinath, Boudhanath, Swayambhunath, and Kathmandu Durbar Square with private vehicle. Evening trek preparation. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Drive Kathmandu to Pokhara",
      maxAltitude: "820 m",
      meals: "Breakfast",
      accommodation: "Hotel in Pokhara",
      description:
        "Scenic tourist bus along Prithvi Highway (~6–7 hrs) with western Himalayan views. Arrive lakeside Pokhara — optional Phewa Lake boating in the evening. Overnight in Pokhara.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Drive Nayapul — trek to Hile",
      maxAltitude: "1,430 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Private drive to Nayapul (~1.5 hrs), then trek along the Modi Khola bank to Hile (~3 hrs). Village views and first mountain atmosphere. Overnight in Hile.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Trek to Ghorepani",
      maxAltitude: "2,840 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Trek via Tikhedhunga and Ulleri stone steps through oak and rhododendron forest past Banthanti to Ghorepani (~6–7 hrs). Magar culture at Ulleri. Overnight in Ghorepani.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Poon Hill sunrise — trek to Tadapani",
      maxAltitude: "3,210 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Pre-dawn hike to Poon Hill (3,210 m) for sunrise over Annapurna and Dhaulagiri. Return to Ghorepani for breakfast, then trek via Deurali through pine and rhododendron to Tadapani (~6 hrs). Overnight in Tadapani.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Trek to Sinuwa",
      maxAltitude: "2,340 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Descend through rhododendron forest to Gurung villages, continue via Chhomrong after lunch to Sinuwa (~6–7 hrs). Gateway country toward the Sanctuary. Overnight in Sinuwa.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Trek to Himalaya Hotel",
      maxAltitude: "2,900 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Drop to Chhomrong Khola, climb through Khuldighar and forest, steep descent to Dovan, then upstream to Himalaya Hotel (~5–6 hrs). Modi Khola gorge scenery. Overnight in Himalaya Hotel.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Trek to Annapurna Base Camp",
      maxAltitude: "4,130 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Trek via Machhapuchhre Base Camp (3,700 m) for lunch, then enter the Annapurna Sanctuary to ABC (4,130 m) (~5–6 hrs). 360° Himalayan panorama and sunset views. Overnight at ABC.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Trek to Bamboo",
      maxAltitude: "2,345 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Descend ~1,700 m along the Modi Khola back to Bamboo (~6 hrs). Farewell views of the Sanctuary peaks. Overnight in Bamboo.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Trek to Jhinu Danda",
      maxAltitude: "1,760 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Climb via Kuldi Ghar, Sinuwa, and Chhomrong stone steps, then descend to Jhinu Danda (~6–7 hrs). Optional natural hot springs 20 minutes from the village. Overnight in Jhinu Danda.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Trek to Pothana",
      maxAltitude: "1,990 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Scenic trek through traditional villages with mountain and hill views (~6 hrs). Optional village exploration and sunset. Overnight in Pothana.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Trek to Phedi — drive to Pokhara",
      maxAltitude: "1,100 m",
      meals: "Breakfast, Lunch",
      accommodation: "Hotel in Pokhara",
      description:
        "Hike down to Phedi (~2 hrs), private drive to lakeside Pokhara. Leave snow peaks behind and celebrate with your team. Overnight in Pokhara.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Drive Pokhara to Kathmandu",
      maxAltitude: "1,350 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Tourist bus back to Kathmandu (~6–7 hrs) along the Prithvi Highway. Free evening for shopping or farewell dinner. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d15",
      dayLabel: "Day 15",
      title: "Final departure",
      maxAltitude: "1,350 m",
      meals: "Breakfast",
      accommodation: "— (departure day)",
      description:
        "Private airport transfer for your international departure. End of the Annapurna Base Camp journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "ABC departures run year-round on private and joining bases. Spring (Feb–Jun) and autumn (Sep–Dec) offer the clearest views. Monsoon brings rain; winter is colder at ABC but quieter.",
  availabilityNotes: [
    "Private and guaranteed group joining dates available",
    "Complete package with hotels and sightseeing as listed",
    "Kathmandu–Pokhara flight upgrade available on request",
    "Itinerary customizable — contact Summit Seek",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Kathmandu–Pokhara flights",
      description: "Skip the bus with return flights between Kathmandu and Pokhara.",
      priceLabel: "From US$260 return",
      visible: true,
    },
    {
      id: "a2",
      title: "Private jeep transfers",
      description: "Upgrade tourist bus or trailhead transfers to private vehicle.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Single room supplement",
      description: "Private rooms where available in hotels and teahouses.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a4",
      title: "Gear rental",
      description: "Sleeping bag, down jacket, and trekking poles if needed.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport pickup and drop-off by private vehicle",
    "3 nights hotel in Kathmandu + 2 nights in Pokhara (BB basis)",
    "Guided Kathmandu sightseeing with private vehicle",
    "Tourist bus Kathmandu–Pokhara–Kathmandu",
    "Private transport Pokhara–Nayapul and Phedi–Pokhara",
    "Licensed guide and porter (2:1) with salary, food, lodging & insurance",
    "ACAP & TIMS permits",
    "Teahouse lodging and full-board meals during the trek",
    "Fresh fruit on trek, oximeter checks, first-aid kit, and government taxes",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Nepal entry visa fee (~US$30 for 15 days on arrival)",
    "Travel insurance (mandatory — helicopter evacuation)",
    "International airfare",
    "Lunch and dinner in Kathmandu and Pokhara (unless stated)",
    "Kathmandu sightseeing entrance fees (~US$30 per person)",
    "Drinks, hot showers, charging, Wi-Fi, and laundry on the trail",
    "Tips for guide, porter, and drivers",
    "Gear rental unless arranged",
    "Anything not listed in the includes section",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1585409677983-0f6c41ca9c3b"),
      caption: "Annapurna massif mountain light",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1483728642387-6c3bdd6c93e5"),
      caption: "Sanctuary approaches through alpine terrain",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "High Himalayan ridges on the ABC trail",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Rhododendron forest near Ghorepani",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "February–June and September–December usually offer the clearest ABC views. Spring rhododendron blooms; autumn brings crisp skies.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & AMS",
      body: "Maximum altitude is Annapurna Base Camp at 4,130 m. Pace steadily, hydrate, and report symptoms early. Oximeter checks included on trek days.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Moderate. Long walking days and Ulleri stone steps are the main challenges. Suitable for fit beginners with good preparation.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Lodges & meals",
      body: "Twin-share teahouses on trek; hotels in Kathmandu and Pokhara. Dal bhat, noodles, and hearty breakfasts. Hot showers usually cost extra.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack for warm valleys and cold ABC nights. Porter carries your main bag; hike with a daypack for water, layers, and snacks.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers & thermals",
        "Fleece mid-layer and down jacket",
        "Waterproof shell and trekking pants",
        "Warm hat, sun cap, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Trekking poles (recommended for Ulleri steps)",
        "Daypack + duffel for porter",
        "Water bottle or purification tablets",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "SPF sunscreen, lip balm, sunglasses",
        "Headlamp for Poon Hill pre-dawn start",
        "Personal medications and blister care",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport, visa, and copies",
        "Travel insurance certificate",
        "Cash for personal trail expenses",
        "Summit Seek booking confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Luggage storage in Kathmandu for items not needed on trek",
    "Sleeping bag and down jacket rental if needed",
    "Pre-trek briefing and daily plan with your guide",
    "Emergency helicopter coordination via your insurance",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Annapurna Base Camp Trek?",
      answer:
        "A 15-day complete package from Kathmandu through Pokhara, Poon Hill, and the Annapurna Sanctuary to ABC (4,130 m), returning via Jhinu hot springs.",
      visible: true,
    },
    {
      id: "q2",
      question: "How much does the 15-day package cost?",
      answer:
        "This listing starts at US$955 for 2–4 pax (US$1,200 solo; US$900 for 5–8; US$875 for 9+). Compare-at US$1,540.",
      visible: true,
    },
    {
      id: "q3",
      question: "What is included in this package?",
      answer:
        "Hotels in Kathmandu and Pokhara, Kathmandu sightseeing, tourist bus, trailhead transfers, permits, guide, porter, and full-board trek meals as listed.",
      visible: true,
    },
    {
      id: "q4",
      question: "What is the maximum altitude?",
      answer:
        "Annapurna Base Camp at 4,130 m. Poon Hill viewpoint reaches 3,210 m on Day 6.",
      visible: true,
    },
    {
      id: "q5",
      question: "Is this suitable for beginners?",
      answer:
        "Yes for fit beginners. Graded Moderate — prepare with cardio and hill walking before departure.",
      visible: true,
    },
    {
      id: "q6",
      question: "When is the best time?",
      answer:
        "Spring (February–June) and autumn (September–December) offer the clearest mountain views.",
      visible: true,
    },
    {
      id: "q7",
      question: "Are permits included?",
      answer:
        "Yes — ACAP and TIMS permits are arranged by Summit Seek as part of this package.",
      visible: true,
    },
    {
      id: "q8",
      question: "Can I customize the itinerary?",
      answer:
        "Yes — shorter or longer ABC routes, flight upgrades, or side trips can be arranged on request.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Annapurna Base Camp?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Annapurna Base Camp Trek 15 Days | Summit Seek",
  metaDescription:
    "Book 15-day Annapurna Base Camp trek — Poon Hill, ABC Sanctuary, Jhinu hot springs, hotels & group rates from US$875.",
};
