import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_ARUN_VALLEY: TrekPageContent = {
  coverImageUrl: img("photo-1483728642387-6c3bdd6c93e5", 2000),
  coverTitle: "Arun Valley Trek - 12 Days",
  coverSubtitle:
    "Quiet eastern Nepal trail from Tumlingtar through Rai & Sherpa villages to Salpa Pass (3,350 m) — Makalu and Kanchenjunga views, then down toward Lukla.",
  heroMainImageUrl: img("photo-1483728642387-6c3bdd6c93e5", 2000),
  heroSideImage1Url: img("photo-1464822759023-fed622ff2c3b", 900),
  heroSideImage2Url: img("photo-1506905925346-21bda4d32df4", 900),
  breadcrumbLabel: "Makalu Region · Arun Valley",
  title: "Arun Valley Trek - 12 Days",
  regionLabel: "Makalu Region",
  rating: 5,
  reviewCount: 6,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 1190,
  compareAtPrice: 1490,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "20% OFF",
  shortTripBadge: "Moderate",
  durationLabel: "12 Days",
  difficultyLabel: "Moderate",
  groupSizeLabel: "1–20",
  bookingNote:
    "Private and small-group departures. Package includes Kathmandu hotels (as listed), Kathmandu–Tumlingtar and Lukla–Kathmandu flights, licensed guide, trek meals, teahouse lodging, TIMS and permits as required. Porter support available as arranged. Ideal for fit trekkers seeking a quieter alternative to Everest/Annapurna classics.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "2 pax", price: 1350, visible: true },
    { id: "gd2", paxLabel: "3-5 pax", price: 1190, visible: true },
    { id: "gd3", paxLabel: "6-10 pax", price: 1090, visible: true },
    { id: "gd4", paxLabel: "11-15 pax", price: 990, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "12 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Moderate", visible: true },
    { id: "f3", label: "Max Altitude", value: "3,350 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Arun Valley / East Nepal", visible: true },
    { id: "f6", label: "Group Size", value: "1–20", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Culture", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The Arun Valley Trek is one of Nepal’s most captivating and least-explored routes — a cultural and scenic journey from eastern lowlands to alpine heights, far quieter than Everest or Annapurna.\n\nThis 12-day itinerary flies Kathmandu–Tumlingtar, then walks via Khandbari, Bhotebas, Salpa Phedi, and Guranse to cross Salpa Pass (3,350 m) with panoramas toward Makalu and Kanchenjunga. You descend through Dudhkund and Gudel, continue via Pangum and Paiya, and finish at Lukla for the return flight to Kathmandu.\n\nExpect Rai and Sherpa villages, terraced farmland, rhododendron forest, waterfalls, and peaceful trails with gradual acclimatization. Days typically run 5–7 hours — moderate for fit walkers with some trek experience. Summit Seek includes domestic flights as listed, guide, meals, teahouses, permits, and clear group pricing.",
  overviewImageUrl: img("photo-1464822759023-fed622ff2c3b"),
  highlightsHeading: "Highlights",
  highlights: [
    "Remote Arun Valley — one of Nepal’s least-visited trek corridors",
    "Cross Salpa Pass (3,350 m) with Himalayan panoramas",
    "Views toward Makalu, Kanchenjunga, and surrounding ridges",
    "Rai and Sherpa village culture and hospitality",
    "Subtropical valleys to alpine meadows in one journey",
    "Quieter trails than Everest Base Camp routes",
    "Scenic Tumlingtar arrival and Lukla departure flights",
    "Rhododendron forests, terraces, waterfalls, and wildlife habitat",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport transfers in Kathmandu as listed",
    "Kathmandu hotel nights as listed",
    "Kathmandu–Tumlingtar and Lukla–Kathmandu flights",
    "Teahouse / lodge lodging throughout the trek as listed",
    "Breakfast, lunch, and dinner on trek days",
    "Experienced licensed local guide",
    "TIMS and necessary permits",
    "First-aid support with the guide; ground transport as listed",
  ],
  whyHeading: "Why choose Arun Valley?",
  whyPoints: [
    "Gentler max altitude than Makalu Base Camp or Kanchenjunga",
    "Strong culture focus with authentic village stays",
    "Off-the-beaten-path solitude without extreme remoteness",
    "Scenic link from Arun country toward the Lukla / Everest gateway",
    "Ideal moderate adventure for 12 days",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "Suitable for fit beginners with some walking experience and for moderately experienced trekkers. Expect 5–7 hour days with steep sections around Salpa Pass, but the high point is only 3,350 m.\n\nComfort with simple teahouses and remote trails helps. Travel insurance covering trekking and evacuation is strongly recommended.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train with aerobic exercise and practice hikes with a daypack",
    "Strengthen legs and core for ups and downs",
    "Break in waterproof hiking boots",
    "Pack layers for warm valleys and cool pass weather",
    "Carry water purification and a basic first-aid kit",
    "Arrive Kathmandu a day early for briefing and permits",
  ],
  itineraryHeading: "12-day itinerary",
  itineraryIntro:
    "Flight and walking times are estimates and vary with weather — Tumlingtar and Lukla flights often delay. Lodge stops may change with availability. Your Summit Seek guide can adjust pacing for comfort and safety.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Lunch, Dinner",
      accommodation: "Hotel in Kathmandu",
      description:
        "Airport meet-and-greet and hotel transfer. Rest, light exploration, and evening trek briefing with gear/permit check. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Fly Tumlingtar – trek to Khandbari",
      maxAltitude: "1,040 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Khandbari",
      description:
        "Scenic flight to Tumlingtar (~518 m), then gentle walk through lowland villages and farmland to Khandbari (~4–5 hours / ~12 km). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Trek Khandbari – Bhotebas",
      maxAltitude: "1,740 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Bhotebas",
      description:
        "Steady ascent through Rai villages, terraces, and forest (~5–6 hours / ~14 km). Overnight in Bhotebas.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Trek Bhotebas – Salpa Phedi",
      maxAltitude: "1,680 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Salpa Phedi",
      description:
        "Undulating trail through villages and ridgelines (~5–6 hours / ~13 km). Overnight at Salpa Phedi.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Trek Salpa Phedi – Guranse",
      maxAltitude: "2,600 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Guranse",
      description:
        "Longer climb through rhododendron and oak forest (~6–7 hours / ~15 km) to Guranse, gateway to higher ground. Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Cross Salpa Pass – descend to Dudhkund",
      maxAltitude: "3,350 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Dudhkund",
      description:
        "Highlight day: ascend Salpa Pass (3,350 m) for Makalu / Kanchenjunga panoramas, then descend to Dudhkund (~6–7 hours / ~14 km). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Trek Dudhkund – Gudel",
      maxAltitude: "1,800 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Gudel",
      description:
        "Long descent through forest, terraces, and Rai villages to Gudel (~5–6 hours / ~13 km). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Trek Gudel – Pangum",
      maxAltitude: "2,850 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Pangum",
      description:
        "Ups and downs through forest and remote settlements (~6–7 hours / ~14 km). Overnight in Pangum.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Trek Pangum – Paiya",
      maxAltitude: "2,730 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Paiya",
      description:
        "Continue toward trails linking the Everest side (~5–6 hours / ~12 km). Overnight in Paiya.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Trek Paiya – Lukla",
      maxAltitude: "2,840 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge in Lukla",
      description:
        "Final walking day to Lukla (~5–6 hours / ~12 km). Celebrate trek completion. Overnight in Lukla.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Fly Lukla – Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Morning scenic flight to Kathmandu (weather permitting). Free afternoon to rest or explore. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Departure from Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "—",
      description:
        "Airport transfer for your international departure. End of the Arun Valley journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best in March–May (rhododendron bloom) and September–November (clear skies). Private groups of 1–20 are welcome. Build buffer days for Tumlingtar and Lukla flights.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Licensed guide included; porter available on request",
    "TIMS and permits as required",
    "Tumlingtar and Lukla flights are weather-dependent — allow buffers",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Extra Kathmandu nights",
      description: "Buffer nights for flight delays or early arrivals.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Porter support",
      description: "Typically one porter between two trekkers for main bags.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Village cultural visit / cooking class",
      description: "Deeper Rai / Sherpa cultural experiences on request.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport transfers in Kathmandu as listed",
    "Kathmandu hotel nights as listed",
    "Kathmandu–Tumlingtar and Lukla–Kathmandu domestic flights",
    "Teahouse / lodge lodging during the trek as listed",
    "Breakfast, lunch, and dinner on trek days",
    "Experienced licensed trekking guide",
    "TIMS and necessary permits",
    "Ground transport as listed; first-aid kit with the guide",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "International airfare",
    "Nepal entry visa fees",
    "Travel insurance (mandatory — evacuation coverage recommended)",
    "Lunch and dinner in Kathmandu (except as listed)",
    "Personal expenses, snacks, laundry, souvenirs",
    "Beverages beyond meals as listed",
    "Tips for guide and porters",
    "Optional porter hire and emergency helicopter costs",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1483728642387-6c3bdd6c93e5"),
      caption: "Terraced hills and eastern valley light",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Alpine approaches toward Salpa Pass",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Remote ridgelines in east Nepal",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Wilderness trails toward the Arun corridor",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May for rhododendron bloom and mild temperatures; September–November for clear skies and dry trails. Monsoon is generally avoided.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude",
      body: "Highest point is Salpa Pass at 3,350 m. Gradual ascent and hydration help reduce AMS risk. Tell your guide early if you feel unwell.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Moderate. Daily walks of 5–7 hours with steep sections around the pass — doable for fit walkers with preparation.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Culture & lodging",
      body: "Simple teahouses and community lodges. Expect dal bhat, noodles, and local vegetables. Hot showers and charging may cost extra in villages.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack for warm lower valleys and cool pass weather. Keep water, layers, documents, and camera in a daypack; main bags can go with a porter if hired.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece mid-layer",
        "Light insulated jacket",
        "Waterproof shell",
        "Trekking pants",
        "Warm hat, sun hat, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Camp shoes",
        "Trekking poles (helpful on descents)",
        "25–35L daypack",
        "Sleeping bag liner or bag as preferred",
        "Headlamp + spare batteries",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "SPF sunscreen & lip balm",
        "UV sunglasses",
        "Personal medications & blister care",
        "Water bottle + purification",
        "Hand sanitizer & toilet paper",
        "Trail snacks",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance details",
        "Cash for personal trail extras",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Permit processing and licensed guiding team",
    "Flight booking coordination for Tumlingtar and Lukla",
    "First-aid kit with the guide",
    "Advice on porter hire and cultural add-ons",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Arun Valley trek?",
      answer:
        "A 12-day moderate trek in eastern Nepal from Tumlingtar through Rai/Sherpa villages to Salpa Pass (3,350 m), finishing toward Lukla.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Moderate. Expect 5–7 hour days with a challenging pass day. Fit beginners with preparation can manage; prior trek experience helps.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This listing starts at US$1,190 for 3–5 pax (US$1,350 for 2; US$1,090 for 6–10; US$990 for 11–15).",
      visible: true,
    },
    {
      id: "q4",
      question: "What is the maximum altitude?",
      answer: "Salpa Pass at 3,350 m — lower than Makalu Base Camp or Everest treks.",
      visible: true,
    },
    {
      id: "q5",
      question: "When is the best time to go?",
      answer:
        "March–May and September–November usually offer the best weather and views.",
      visible: true,
    },
    {
      id: "q6",
      question: "Do I need a guide?",
      answer:
        "A licensed guide is strongly recommended for navigation, safety, and cultural insight on this remote route. Summit Seek includes guiding.",
      visible: true,
    },
    {
      id: "q7",
      question: "Is travel insurance necessary?",
      answer:
        "Yes — covering trekking and emergency evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q8",
      question: "How does this differ from Makalu Base Camp?",
      answer:
        "Arun Valley is shorter and lower (max 3,350 m) with stronger village culture focus. Makalu Base Camp / Barun routes go much higher into the national park wilderness.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Arun Valley?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Arun Valley Trek 12 Days | Summit Seek",
  metaDescription:
    "Book the 12-day Arun Valley trek with Summit Seek — Salpa Pass 3,350 m, Rai & Sherpa culture, flights, guide, meals & group discounts from US$990.",
};
