import type { BestSellingPackagesContent } from "@/types/best-selling-packages";

export const DEFAULT_BEST_SELLING: BestSellingPackagesContent = {
  heading: "Best Selling Packages for 2026",
  viewAllLabel: "View All Packages",
  viewAllHref: "/packages",
  visible: true,
  packages: [
    {
      id: "bs-1",
      title: "Everest Base Camp Trek",
      price: 1300,
      compareAtPrice: 1550,
      reviewCount: 22,
      rating: 5,
      durationDays: 15,
      href: "/packages/everest-base-camp-trek",
      imageUrl:
        "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=900&q=80",
      showOnHome: true,
      visible: true,
    },
    {
      id: "bs-2",
      title: "Everest Base Camp Helicopter Tour",
      price: 1400,
      compareAtPrice: 1500,
      reviewCount: 3,
      rating: 5,
      durationDays: 1,
      href: "/packages/everest-base-camp-helicopter-tour",
      imageUrl:
        "https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&w=900&q=80",
      showOnHome: true,
      visible: true,
    },
    {
      id: "bs-3",
      title: "Annapurna Circuit Trek",
      price: 1005,
      compareAtPrice: 1550,
      reviewCount: 15,
      rating: 5,
      durationDays: 15,
      href: "/packages/annapurna-circuit-trek",
      imageUrl:
        "https://images.unsplash.com/photo-1454496522488-7a8e488e8606?auto=format&fit=crop&w=900&q=80",
      showOnHome: true,
      visible: true,
    },
    {
      id: "bs-4",
      title: "Langtang Valley Trek",
      price: 790,
      compareAtPrice: 1275,
      reviewCount: 7,
      rating: 5,
      durationDays: 9,
      href: "/packages/langtang-valley-trek",
      imageUrl:
        "https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?auto=format&fit=crop&w=900&q=80",
      showOnHome: true,
      visible: true,
    },
    {
      id: "bs-5",
      title: "Manaslu Circuit Trek",
      price: 950,
      compareAtPrice: 1520,
      reviewCount: 6,
      rating: 5,
      durationDays: 14,
      href: "/packages/manaslu-circuit-trek",
      imageUrl:
        "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=900&q=80",
      showOnHome: true,
      visible: true,
    },
    {
      id: "bs-6",
      title: "Annapurna Base Camp Trek",
      price: 955,
      compareAtPrice: 1540,
      reviewCount: 5,
      rating: 5,
      durationDays: 15,
      href: "/packages/annapurna-base-camp-trek",
      imageUrl:
        "https://images.unsplash.com/photo-1585409677983-0f6c41ca9c3b?auto=format&fit=crop&w=900&q=80",
      showOnHome: true,
      visible: true,
    },
  ],
};
