import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_EVEREST_BASE_CAMP: TrekPageContent = {
  coverImageUrl: img("photo-1544735716-392fe2489ffa", 2000),
  coverTitle: "Everest Base Camp Trek - 14 Days",
  coverSubtitle:
    "Lukla flight, Sherpa villages, Namche & Dingboche acclimatization, Everest Base Camp, and sunrise from Kala Patthar — the classic Khumbu journey.",
  heroMainImageUrl: img("photo-1544735716-392fe2489ffa", 2000),
  heroSideImage1Url: img("photo-1486870591958-9b9d0d1dda99", 900),
  heroSideImage2Url: img("photo-1464822759023-fed622ff2c3b", 900),
  breadcrumbLabel: "Everest Region · Base Camp",
  title: "Everest Base Camp Trek - 14 Days",
  regionLabel: "Everest Region",
  rating: 5,
  reviewCount: 112,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 1399,
  compareAtPrice: 1599,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "12% OFF",
  shortTripBadge: "Classic Trek",
  durationLabel: "14 Days",
  difficultyLabel: "Moderate",
  groupSizeLabel: "1+",
  bookingNote:
    "Private and fixed-departure options available. Package includes Kathmandu–Lukla flights (or Manthali routing in peak season), permits, guide & porter, and trek meals. Arrive 1–2 days early for buffer flights.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 1399, visible: true },
    { id: "gd2", paxLabel: "2-6 pax", price: 1299, visible: true },
    { id: "gd3", paxLabel: "7-14 pax", price: 1250, visible: true },
    { id: "gd4", paxLabel: "15-20 pax", price: 1199, visible: true },
    { id: "gd5", paxLabel: "21-30 pax", price: 1150, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "14 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Moderate", visible: true },
    { id: "f3", label: "Max Altitude", value: "5,545 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Everest / Khumbu", visible: true },
    { id: "f6", label: "Group Size", value: "1+", visible: true },
    { id: "f7", label: "Trek Distance", value: "~130 km round trip", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–Jun & Sep–Dec",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The Everest Base Camp trek — 14 days is one of Nepal’s most iconic journeys, offering immersion in Sherpa culture and the thrill of standing at the base of the world’s highest mountain. From arrival in Kathmandu to departure, the itinerary balances adventure and acclimatization with stops at Namche Bazaar and Dingboche.\n\nA scenic flight to Lukla opens the Khumbu trail through Phakding, Namche, Tengboche Monastery, Dingboche, Lobuche, and Gorak Shep. You reach Everest Base Camp (5,364 m) beside the Khumbu Glacier and Icefall, then climb Kala Patthar (5,545 m) for the classic sunrise panorama of Everest, Lhotse, and Nuptse.\n\nSummit Seek leads with licensed guides, fair porter support, clear pricing that includes Lukla flights and permits, and flexible private departures so you can focus on the mountains.",
  overviewImageUrl: img("photo-1506905925346-21bda4d32df4"),
  highlightsHeading: "Highlights",
  highlights: [
    "Thrilling Kathmandu (or Manthali) flight into Lukla — gateway to Everest",
    "Stand at Everest Base Camp (5,364 m) beneath the Khumbu Icefall",
    "Sunrise from Kala Patthar (5,545 m) — best views of Mt. Everest",
    "Acclimatization hikes: Everest View Hotel & Nangkartshang Peak",
    "Sherpa culture, prayer flags, mani walls, and Tengboche Monastery",
    "Walk through Sagarmatha National Park — UNESCO World Heritage Site",
    "Namche Bazaar — vibrant hub of the Khumbu with cafés and markets",
    "Views of Everest, Lhotse, Nuptse, Ama Dablam, Pumori, and more",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport pickups/drop-offs by private vehicle (international & domestic)",
    "Kathmandu ↔ Lukla flights included (Manthali routing in peak season as required)",
    "Sagarmatha National Park & Khumbu Pasang Lhamu permits arranged",
    "Licensed English-speaking guide with salary, food, lodging & insurance",
    "Porter support (typically 2 guests : 1 porter) with fair pay and insurance",
    "2 nights 3-star hotel in Kathmandu with breakfast + welcome/farewell dinners",
    "Teahouse lodging and three meals a day on the trek as listed",
    "First-aid kit & oximeter checks; emergency evacuation coordination via your insurance",
  ],
  whyHeading: "Why choose Everest Base Camp?",
  whyPoints: [
    "Reach the base of the world’s highest mountain on a well-supported classic route",
    "Proper acclimatization days reduce altitude risk and deepen the experience",
    "Unforgettable mountain panoramas plus living Sherpa culture and monasteries",
    "Moderate-to-challenging but achievable for fit first-time high-altitude trekkers",
    "Spring and autumn bring clear skies — ideal photography and trail conditions",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "Many first-time Himalayan trekkers complete EBC each year with preparation. Expect 5–8 hours of walking on many days and a high point of 5,545 m at Kala Patthar. You do not need technical climbing skills, but good cardio fitness and broken-in boots matter.\n\nTrain 6–8 weeks ahead with hills, stairs, and long walks. Stay hydrated, follow “climb high, sleep low” on acclimatization days, and tell your guide early if you feel unwell. Travel insurance covering helicopter evacuation is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Build endurance with hiking, jogging, cycling, or stair climbs 6–8 weeks before departure",
    "Break in waterproof ankle-support hiking boots on practice walks",
    "Pack warm layers for cold nights near Gorak Shep / EBC, rain shell, and strong sun protection",
    "Buy travel insurance covering trekking to 6,000 m and helicopter evacuation",
    "Arrive in Kathmandu 1–2 days before Day 1 to allow Lukla flight buffer",
    "Lukla baggage is typically ~15 kg total — pack light; rent bulky gear in Kathmandu if needed",
  ],
  itineraryHeading: "14-day itinerary",
  itineraryIntro:
    "Walking and flight times are estimates and vary with weather and pace. Lodge stops may change with availability. In peak season, Lukla flights often operate via Manthali (Ramechhap). Your Summit Seek guide can adjust the plan for safety. Buffer days in Kathmandu are strongly recommended.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrival in Kathmandu & trip briefing",
      maxAltitude: "1,350 m",
      meals: "Welcome dinner",
      accommodation: "3-star hotel in Kathmandu",
      description:
        "Airport meet-and-greet at Tribhuvan International Airport and private transfer to your hotel (about 20–25 minutes). Rest, then meet your trek leader for a gear check and itinerary briefing. Welcome dinner with the group. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Fly to Lukla – trek to Phakding",
      maxAltitude: "2,860 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Scenic flight to Lukla (about 35–45 minutes; peak season may route via Manthali). Meet porters and trek along the Dudh Koshi via Cheplung and Ghat to Phakding (about 3–4 hours / ~8 km). Overnight in Phakding. Optional Kathmandu–Lukla helicopter add-on available on request.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Phakding – Namche Bazaar",
      maxAltitude: "3,440 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Trek through pine forest and Benkar valley, enter Sagarmatha National Park at Monjo, cross suspension bridges near Jorsale, then climb steeply into Namche Bazaar — the main Sherpa hub of the Khumbu (about 6–7 hours / ~11 km).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Namche acclimatization – Everest View Hotel",
      maxAltitude: "3,880 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Rest and acclimatize in Namche. Hike to Everest View Hotel (~3,880 m) for first clear views of Everest, Lhotse, Nuptse, and Ama Dablam (about 3–4 hours). Optional visit toward Khumjung / Hillary School. Overnight again in Namche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Namche – Tengboche",
      maxAltitude: "3,860 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Pleasant trail to Phunki then climb to Tengboche, home to the region’s largest monastery with Ama Dablam and Everest views (about 5–6 hours / ~11 km). Explore the monastery and overnight in Tengboche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Tengboche – Dingboche",
      maxAltitude: "4,410 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Descend through birch and rhododendron forest to Debuche, cross the Imja Khola toward Pangboche, then climb the Imja Valley into Dingboche with potato and barley fields and Ama Dablam views (about 5–6 hours / ~11 km).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Dingboche acclimatization – Nangkartshang Peak",
      maxAltitude: "≈ 5,100 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Second acclimatization day. Hike toward Nangkartshang Peak (~5,083–5,100 m) for panoramic views of Ama Dablam, Makalu, Lhotse, and Island Peak (about 4–5 hours). Overnight in Dingboche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Dingboche – Lobuche",
      maxAltitude: "4,950 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Trail with views of Taboche and Cholatse via Duglha onto the Khumbu Glacier moraine and climbers’ memorials, then into Lobuche (about 5–6 hours / ~8–9 km). Overnight in Lobuche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Lobuche – Gorak Shep – Everest Base Camp",
      maxAltitude: "5,364 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Rocky path along the Khumbu moraine to Gorak Shep, then continue to Everest Base Camp (5,364 m) beside the Khumbu Glacier and Icefall. Photos and celebration, then return to overnight at Gorak Shep (about 5–7 hours total).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Kala Patthar sunrise – Pheriche",
      maxAltitude: "5,545 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Pre-dawn climb to Kala Patthar (5,545 m) for the best sunrise views of Mt. Everest and surrounding giants. Breakfast at Gorak Shep, then descend to Pheriche (about 5 hours / ~13 km).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Pheriche – Namche Bazaar",
      maxAltitude: "3,440 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Long descent through rhododendron and juniper, crossing the Dudh Koshi and forest trails toward Namche with views of Ama Dablam, Thamserku, and Nuptse (about 6 hours / ~14 km). Overnight in Namche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Namche – Lukla",
      maxAltitude: "2,860 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Final mountain walking day along the Dudh Koshi with multiple suspension bridges through villages and monasteries back to Lukla (about 6 hours / ~21 km). Celebrate with your team. Overnight in Lukla.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Fly Lukla – Kathmandu",
      maxAltitude: "1,350 m",
      meals: "Breakfast, Farewell dinner",
      accommodation: "3-star hotel in Kathmandu",
      description:
        "Early flight Lukla to Kathmandu (or Lukla–Manthali then road transfer in peak season). Transfer to hotel, free time, and farewell dinner. Overnight in Kathmandu. Optional Lukla–Kathmandu helicopter add-on on request.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Departure from Kathmandu",
      maxAltitude: "1,350 m",
      meals: "Breakfast",
      accommodation: "— (departure day)",
      description:
        "Private transfer to Tribhuvan International Airport for your departure flight. End of the Everest Base Camp journey with Summit Seek — carry home the memories of Khumbu and Kala Patthar.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "EBC departures run on private and joining-group bases. Spring (Mar–May) and autumn (Sep–Nov) offer the clearest mountain views. Winter is quieter and colder; monsoon is greener with more cloud and possible Lukla delays.",
  availabilityNotes: [
    "Private and fixed-departure options with flexible start dates",
    "Arrive Kathmandu 1–2 days early for Lukla flight buffer",
    "Peak-season Lukla flights often operate via Manthali (Ramechhap)",
    "Confirmed booking after deposit and pre-trek briefing",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Kathmandu ↔ Lukla helicopter",
      description: "Avoid Manthali road transfers or flight delays — sharing heli options on request.",
      priceLabel: "From US$500 / person",
      visible: true,
    },
    {
      id: "a2",
      title: "Extra private porter",
      description: "Dedicated porter for solo travelers or extra luggage (within ethical load limits).",
      priceLabel: "From US$220",
      visible: true,
    },
    {
      id: "a3",
      title: "Lodge / hotel upgrades",
      description: "Comfort lodges on the trail or 4–5 star Kathmandu nights available as upgrades.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport pickups and drop-offs by private vehicle",
    "Welcome and farewell dinners in Kathmandu",
    "2 nights twin/double 3-star hotel in Kathmandu with breakfast",
    "Kathmandu ↔ Lukla flights with airport taxes (Manthali bus both ways in peak season as required)",
    "Sagarmatha National Park entry & Khumbu Pasang Lhamu / TIMS permits as applicable",
    "Licensed English-speaking trekking guide (salary, food, lodging, insurance, transport)",
    "Porter support (typically 2:1) with insurance, salary, food, lodging & equipment",
    "Twin/double teahouse accommodation during the trek",
    "Three meals a day (breakfast, lunch, dinner) and tea/coffee while trekking",
    "First-aid kit and oximeter checks; emergency evacuation arrangement (paid by your insurance)",
    "Sleeping bag / down jacket / duffel for porter use on many packages (return after trek)",
    "Government and local taxes as per itinerary",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Nepal visa fees and international airfare",
    "Lunch and dinner in Kathmandu (except welcome/farewell as listed)",
    "Travel insurance covering helicopter evacuation (mandatory)",
    "Extra hotel nights / meals due to early arrival, late departure, or early return from the trail",
    "Personal expenses (laundry, phone, bar bills, bottled water, snacks, extra porter)",
    "Wi-Fi, device charging, and hot showers on the trail",
    "Tips for guides, porters, and drivers",
    "Costs from flight delays, strikes, weather, or events beyond our control",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Everest region ridges and Himalayan light",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "High Khumbu mountain panorama",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Glacier approaches toward base camp",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Alpine trail atmosphere in the Himalaya",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May and September–November usually bring the clearest skies and most reliable trail conditions. Winter is possible with colder nights; monsoon can mean cloud, rain, and more Lukla delays.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & climate",
      body: "Max altitude is 5,545 m at Kala Patthar; EBC is about 5,364 m. Nights near Gorak Shep can drop well below freezing. Pace yourself on acclimatization days and drink plenty of water.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Permits",
      body: "You need the Khumbu Pasang Lhamu Rural Municipality permit and Sagarmatha National Park entry. Summit Seek arranges these for the package so checkpoints at Monjo and along the route go smoothly.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Lodges & facilities",
      body: "Teahouses offer twin rooms with blankets. Higher lodges are simpler and colder. Hot showers, Wi-Fi, and charging often cost extra. Carry sanitizer, toilet paper, and a headlamp.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack light for Lukla weight limits. Porters typically share luggage between two trekkers. Carry a daypack for water, layers, documents, and valuables. Rent bulky items in Kathmandu if needed.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece or mid-layer",
        "Down / insulated jacket",
        "Waterproof shell",
        "Trekking pants + warm evening layer",
        "Warm hat, sun hat, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Camp shoes / sandals",
        "3–4 pairs trekking socks",
        "25–35L daypack",
        "Duffel for porter (within weight limit)",
        "Trekking poles (strongly recommended)",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "Personal medications & blister care",
        "Sunscreen SPF 50+ & lip balm",
        "UV sunglasses",
        "Water bottle / bladder + purification",
        "Hand sanitizer & wet wipes",
        "Headlamp + spare batteries",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance details (evacuation coverage)",
        "Passport photos if requested for permits",
        "Cash (NPR / USD) for personal trail expenses",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Duffel bag for porter use on many packages (return after trek)",
    "Sleeping bag / down jacket rental options on request",
    "City and trail route maps / briefing in Kathmandu",
    "Help arranging hotel upgrades and helicopter options",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "How difficult is the Everest Base Camp trek?",
      answer:
        "It is moderate to challenging due to altitude and consecutive walking days, not technical climbing. Fit beginners with preparation and a steady pace regularly succeed.",
      visible: true,
    },
    {
      id: "q2",
      question: "What is the highest altitude on this trip?",
      answer:
        "Kala Patthar at approximately 5,545 m is the high point. Everest Base Camp itself is about 5,364 m.",
      visible: true,
    },
    {
      id: "q3",
      question: "Are Lukla flights included?",
      answer:
        "Yes. Kathmandu–Lukla–Kathmandu flights are included in the package price. In peak months, airlines often fly via Manthali (Ramechhap) with a shared bus — that road transfer is included when required.",
      visible: true,
    },
    {
      id: "q4",
      question: "When is the best time to go?",
      answer:
        "Spring (March–May) and autumn (September–November) offer the most reliable views and trail conditions. Winter is quieter and colder; monsoon is wetter with more flight uncertainty.",
      visible: true,
    },
    {
      id: "q5",
      question: "Do I need travel insurance?",
      answer:
        "Yes. Cover trekking at high altitude and helicopter evacuation. Summit Seek does not sell insurance — we can help you confirm altitude limits before you buy.",
      visible: true,
    },
    {
      id: "q6",
      question: "How much does the trek cost?",
      answer:
        "Listed from US$1,399 per person for 1 pax, with group discounts down to US$1,150 for larger groups. Exact quotes depend on dates and add-ons.",
      visible: true,
    },
    {
      id: "q7",
      question: "Can beginners do EBC?",
      answer:
        "Yes, with good fitness, broken-in boots, and respect for acclimatization. Tell us your experience when you enquire so we can advise on pace and preparation.",
      visible: true,
    },
    {
      id: "q8",
      question: "Are permits included?",
      answer:
        "Yes. Sagarmatha National Park entry and Khumbu local permits required for this itinerary are arranged in the package.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Everest Base Camp?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Everest Base Camp Trek 14 Days | Summit Seek",
  metaDescription:
    "Book the 14-day Everest Base Camp trek with Summit Seek — Lukla flights, Namche & Dingboche acclimatization, EBC, Kala Patthar sunrise, permits, guide & group discounts.",
};
