import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_EVEREST_HELI_VIEW: TrekPageContent = {
  coverImageUrl: img("photo-1609137144813-7d9921338f24", 2000),
  coverTitle: "Everest View Trek With Helicopter Tour - 4 Days",
  coverSubtitle:
    "Short Khumbu trek to Namche plus helicopter overfly of Everest Base Camp and Kala Patthar landing (as regulations allow) — Everest views without the full EBC walk.",
  heroMainImageUrl: img("photo-1609137144813-7d9921338f24", 2000),
  heroSideImage1Url: img("photo-1464822759023-fed622ff2c3b", 900),
  heroSideImage2Url: img("photo-1486870591958-9b9d0d1dda99", 900),
  breadcrumbLabel: "Everest Region · Luxury & Heli",
  title: "Everest View Trek With Helicopter Tour - 4 Days",
  regionLabel: "Everest Region",
  rating: 5,
  reviewCount: 9,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 2899,
  compareAtPrice: 2999,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "3% OFF",
  shortTripBadge: "Trek + Heli Landing",
  durationLabel: "4 Days",
  difficultyLabel: "Easy",
  groupSizeLabel: "2+",
  bookingNote:
    "Private and small-group departures. Package includes Kathmandu–Lukla flights (via Manthali if season requires), teahouse lodging and meals on trek days, licensed guide and porter, park/local permits, and Namche–EBC overfly–Kala Patthar–Lukla helicopter as listed. CAAN rules: Kala Patthar landing typically requires 1–2 passengers; shared larger groups may overfly only — confirm landing preference when booking.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 2899, visible: true },
    { id: "gd2", paxLabel: "2 pax", price: 1999, visible: true },
    { id: "gd3", paxLabel: "3-4 pax", price: 1960, visible: true },
    { id: "gd4", paxLabel: "5-9 pax", price: 1899, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "4 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Easy", visible: true },
    { id: "f3", label: "Max Altitude", value: "5,545 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Khumbu / Everest", visible: true },
    { id: "f6", label: "Group Size", value: "2 onwards", visible: true },
    {
      id: "f7",
      label: "Activities",
      value: "Trek & Helicopter",
      visible: true,
    },
    {
      id: "f8",
      label: "Best Season",
      value: "Sep–May (best Mar–May & Sep–Nov)",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "Everest View Trek with Helicopter Tour is built for travelers who want Khumbu trails and Everest panoramas without a full Everest Base Camp trek. In four days you fly to Lukla, trek to Phakding and Namche Bazaar through Sagarmatha National Park, then take a helicopter overfly of Everest Base Camp (~5,364 m) with a stop near Kala Patthar (~5,545 m) when landing rules allow, before returning to Lukla and Kathmandu.\n\nFrom the trail and the air you see Everest, Lhotse, Nuptse, Ama Dablam, Pumori, Cho Oyu, and the Khumbu Glacier / Icefall. Namche offers Sherpa culture, markets, and optional views toward Everest View Hotel country. Spring (Mar–May) and autumn (Sep–Nov) give the most reliable flying and walking weather.\n\nSummit Seek includes Lukla flights as listed, permits, guide, porter, trek meals and lodges, and the helicopter sector as listed — with clear notes on CAAN landing limits (typically 1–2 passengers for Kala Patthar touchdown; larger shared flights may overfly only).",
  overviewImageUrl: img("photo-1464822759023-fed622ff2c3b"),
  highlightsHeading: "Highlights",
  highlights: [
    "Helicopter overfly of Everest Base Camp with Kala Patthar stop (as rules allow)",
    "Views of Everest, Lhotse, Nuptse, Ama Dablam, Pumori & Cho Oyu",
    "Short trek into Namche Bazaar — Sherpa hub of the Khumbu",
    "Sagarmatha National Park UNESCO trails and suspension bridges",
    "Scenic Lukla flights bookending the journey",
    "Beginner-friendly walking days vs classic 12–14 day EBC",
    "Optional Everest View Hotel / Syangboche add-ons on request",
    "Ideal for limited-time travelers seeking Everest drama",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport transfers by private vehicle as listed",
    "Kathmandu–Lukla–Kathmandu flights (via Manthali if season requires)",
    "Namche–EBC overfly–Kala Patthar–Lukla helicopter as listed",
    "Sagarmatha National Park and Khumbu local permits",
    "Licensed English-speaking guide; porter (2:1) as listed",
    "Twin-sharing lodge lodging and three meals a day on trek",
    "First-aid kit, oximeter checks, emergency heli coordination (insurance pays)",
    "All applicable taxes as listed",
  ],
  whyHeading: "Why choose trek + heli?",
  whyPoints: [
    "See Everest heights without 10+ walking days to Base Camp",
    "Combine real Sherpa-trail culture with aerial mountain drama",
    "Landing at/near Kala Patthar (when permitted) beats a fly-over-only day trip",
    "Short, beginner-friendly walking to Namche",
    "Clear group pricing that reflects shared vs private heli economics",
  ],
  beginnersHeading: "Is this trip good for beginners?",
  beginnersBody:
    "Yes for fit travelers who can walk 3–6 hours on mountain trails for two days. Difficulty is Easy relative to classic EBC, but you still gain altitude quickly to Namche (~3,440 m) and fly to ~5,500 m on heli day — AMS awareness matters.\n\nTravel insurance covering helicopter evacuation and high altitude is mandatory. Confirm whether you need a guaranteed Kala Patthar landing (1–2 pax private/shared) when you book.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Arrive Kathmandu 1–2 days early for Lukla flight buffers",
    "Train with hills/stairs for Namche ascent day",
    "Pack layers for cold heli-landing stops above 5,000 m",
    "Buy insurance covering heli evacuation and altitude",
    "Carry passport + copies for park and flight checks",
    "Discuss private vs shared helicopter landing preference in advance",
  ],
  itineraryHeading: "4-day itinerary",
  itineraryIntro:
    "Based on the classic Lukla–Phakding–Namche trek plus Day-3 helicopter. Peak-season Lukla flights often operate via Manthali (Ramechhap). Helicopter landing at Kala Patthar follows CAAN passenger limits — your guide confirms the day’s plan.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Fly Lukla – trek to Phakding",
      maxAltitude: "2,860 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Phakding",
      description:
        "Hotel pickup for domestic flight to Lukla (~35 min; or Manthali + flight in peak season). Meet crew, then trek along the Dudh Koshi through pine forest and suspension bridges to Phakding (~3–4 hours / ~8–9 km). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Trek Phakding – Namche Bazaar",
      maxAltitude: "3,440 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Namche",
      description:
        "Via Monjo checkpoint into Sagarmatha National Park, lunch near Jorsale, cross the Hillary Bridge, and climb steeply into Namche Bazaar (~5–6 hours / ~10–12 km). Explore the Sherpa hub. Overnight teahouse. Optional add-ons: Everest View Hotel or Khumjung loop on request.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Helicopter: Namche – EBC overfly – Kala Patthar – Lukla",
      maxAltitude: "5,545 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Lukla",
      description:
        "Transfer to helipad. Fly toward Everest Base Camp (~5,364 m) for aerial views of the Khumbu Icefall and peaks, then land near Kala Patthar (~5,545 m) for ~10–15 minutes when passenger limits allow (typically 1–2 for landing; larger shared flights may overfly only). Optional breakfast stop at Everest View Hotel as arranged. Fly to Lukla and overnight.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Fly Lukla – Kathmandu",
      maxAltitude: "1,350 m",
      meals: "Breakfast",
      accommodation: "—",
      description:
        "Morning flight Lukla–Kathmandu (or Lukla–Manthali + drive in peak season). Hotel transfer. Optional Lukla–Kathmandu direct heli upgrade on request. End of the 4-day Everest view trek with helicopter tour.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Private departures most days September–May. Best flying and views in March–May and September–November. Keep 1–2 buffer days in Kathmandu for Lukla weather delays.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Fixed and private group options",
    "Confirm Kala Patthar landing vs overfly when booking",
    "Lukla flights are weather-dependent — allow buffers",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Everest View Hotel breakfast stop",
      description: "Syangboche / Everest View Hotel meal with mountain panorama.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Private Kala Patthar landing heli",
      description: "1–2 passenger configuration for guaranteed landing attempt.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Lukla–Kathmandu helicopter",
      description: "Skip Manthali road transfer in peak season (extra per person sharing).",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport pickups/drops by private vehicle as listed",
    "Kathmandu–Lukla–Kathmandu flights (shared bus to Manthali if required)",
    "Helicopter: Namche–EBC overfly–Kala Patthar–Lukla as listed",
    "Sagarmatha National Park and Khumbu local permits",
    "Licensed English-speaking guide; porter (2 guests : 1 porter)",
    "Twin-sharing lodge lodging on trek",
    "Three meals a day plus tea/coffee on trek days",
    "First-aid kit, oximeter checks, applicable taxes",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Nepal visa fees and international airfare",
    "Kathmandu hotel nights and city meals (unless listed)",
    "Travel insurance including helicopter evacuation (mandatory)",
    "Personal expenses: laundry, charging, hot showers, bottled water, drinks",
    "Tips for guide, porter, and drivers",
    "Extra nights or costs from flight delays / weather beyond our control",
    "Private jeep to Manthali (optional upgrade)",
    "Anything not listed under inclusions",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1609137144813-7d9921338f24"),
      caption: "Helicopter approaches above the Khumbu",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Alpine trails toward Namche and Everest views",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "Glacier light near Lobuche and Kala Patthar country",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1519681393784-d120267933ba"),
      caption: "High Himalayan ridges on a clear flying day",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "September–May overall; March–May and September–November offer the best combination of clear skies for heli and pleasant trail walking.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & difficulty",
      body: "Walking max ~3,440 m (Namche). Heli day reaches ~5,545 m at Kala Patthar. Graded Easy vs classic EBC, but altitude gain is rapid — hydrate and report AMS symptoms.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Permits",
      body: "Sagarmatha National Park entry and Khumbu Pasang Lhamu Rural Municipality permit (TIMS typically not required when local permit covers). Summit Seek arranges these.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Helicopter landing rules",
      body: "CAAN limits Kala Patthar landings — typically 1–2 passengers for touchdown. Shared flights with more passengers may overfly EBC/Kala Patthar only. Confirm your preference when booking.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Porters carry main bags on trek days; keep documents, layers, and camera in a daypack. Heli day is cold and bright — pack gloves, sunglasses, and a warm jacket.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece mid-layer",
        "Down or insulated jacket for heli stop",
        "Waterproof shell",
        "Warm hat, gloves, buff",
        "Sun hat",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear",
      items: [
        "Broken-in trekking boots",
        "Trekking poles (recommended for Namche climb)",
        "Camp shoes for lodges",
        "Warm socks",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Daypack & health",
      items: [
        "Daypack with rain cover",
        "Water bottle + purification",
        "Glacier sunglasses / UV protection",
        "SPF 50+ sunscreen and lip balm",
        "Personal first-aid and altitude meds as advised by your doctor",
        "Headlamp",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies + passport photos",
        "Nepal visa as applicable",
        "Insurance covering heli evacuation",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Permit processing and licensed guide / porter logistics",
    "Lukla flight and helicopter coordination as listed",
    "Sleeping bag / down jacket loan if arranged",
    "Emergency helicopter coordination (insurance pays)",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Everest View Trek with Helicopter Tour?",
      answer:
        "A 4-day package: fly to Lukla, trek to Phakding and Namche, then helicopter overfly of Everest Base Camp with a Kala Patthar stop when regulations allow, returning via Lukla to Kathmandu.",
      visible: true,
    },
    {
      id: "q2",
      question: "Do we land at Kala Patthar?",
      answer:
        "Landing is typically limited to 1–2 passengers under CAAN rules. Larger shared helicopters may overfly only. Book a private/shared 1–2 seat configuration if landing is essential.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "Featured listing from US$2,899 (compare US$2,999). Group rates often drop for 2+ pax (e.g. from about US$1,999) because helicopter costs are shared — see the group discount table.",
      visible: true,
    },
    {
      id: "q4",
      question: "What is the maximum altitude?",
      answer:
        "On foot you reach Namche (~3,440 m). By helicopter you reach near Kala Patthar (~5,545 m) and overfly Everest Base Camp (~5,364 m).",
      visible: true,
    },
    {
      id: "q5",
      question: "Is this easier than the classic EBC trek?",
      answer:
        "Yes — only two walking days to Namche instead of a full EBC itinerary. You still need basic fitness and altitude awareness for the heli day.",
      visible: true,
    },
    {
      id: "q6",
      question: "What permits are required?",
      answer:
        "Sagarmatha National Park entry and Khumbu Pasang Lhamu Rural Municipality permit. Summit Seek arranges these with your guide.",
      visible: true,
    },
    {
      id: "q7",
      question: "Is travel insurance necessary?",
      answer:
        "Yes — covering high altitude and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q8",
      question: "When is the best time to go?",
      answer:
        "March–May and September–November usually offer the best weather for walking and flying. Keep buffer days for Lukla delays.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Everest by trek and heli?",
  ctaBody: `Tell us your dates, group size, and whether you need a Kala Patthar landing — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Everest View Trek with Helicopter 4 Days | Summit Seek",
  metaDescription:
    "Book 4-day Everest View Trek with helicopter — Namche trek, EBC overfly, Kala Patthar landing as allowed, Lukla flights & group rates from US$1,899.",
};
