import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_EVEREST_VIEW: TrekPageContent = {
  coverImageUrl: img("photo-1464822759023-fed622ff2c3b", 2000),
  coverTitle: "Everest View Trek - 7 Days",
  coverSubtitle:
    "A short, beginner-friendly Khumbu classic — Lukla flight, Namche Bazaar, and panoramic Everest views from Hotel Everest View (3,880 m).",
  heroMainImageUrl: img("photo-1464822759023-fed622ff2c3b", 2000),
  heroSideImage1Url: img("photo-1486870591958-9b9d0d1dda99", 900),
  heroSideImage2Url: img("photo-1506905925346-21bda4d32df4", 900),
  breadcrumbLabel: "Everest Region · Everest View",
  title: "Everest View Trek - 7 Days",
  regionLabel: "Everest Region",
  rating: 5,
  reviewCount: 28,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 890,
  compareAtPrice: 990,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "10% OFF",
  shortTripBadge: "Short Trek",
  durationLabel: "7 Days",
  difficultyLabel: "Easy",
  groupSizeLabel: "1+",
  bookingNote:
    "Private and small-group departures available. Package includes Kathmandu–Lukla flights, permits, guide, porter, and teahouse meals on trek days. Arrive 1 day early for Lukla flight buffer when possible.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 990, visible: true },
    { id: "gd2", paxLabel: "2-6 pax", price: 890, visible: true },
    { id: "gd3", paxLabel: "7-12 pax", price: 820, visible: true },
    { id: "gd4", paxLabel: "13-20 pax", price: 780, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "7 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Easy", visible: true },
    { id: "f3", label: "Max Altitude", value: "3,880 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Everest / Khumbu", visible: true },
    { id: "f6", label: "Group Size", value: "1+", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Culture", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The Everest View Trek is a seven-day Khumbu adventure for travelers who want to see Mount Everest without the long commitment of Everest Base Camp. It blends a thrilling Lukla flight, forest trails beside the Dudh Koshi, vibrant Namche Bazaar, and a signature hike to Hotel Everest View (3,880 m) — once listed among the world’s highest hotels.\n\nFrom the hotel terrace you look across Everest, Lhotse, Nuptse, Ama Dablam, Thamserku, and Kongde Ri. Along the way you walk through Sagarmatha National Park (UNESCO), Sherpa villages such as Phakding, Monjo, and Jorsalle, and optional culture stops like the Sherpa Culture Museum in Namche.\n\nGradual altitude gain and a full Namche acclimatization day make this one of the most accessible Everest-region treks — popular with first-timers, families, and travelers short on time who still want a real Himalayan experience with Summit Seek guides and clear pricing.",
  overviewImageUrl: img("photo-1544735716-392fe2489ffa"),
  highlightsHeading: "Highlights",
  highlights: [
    "Scenic flight into Lukla — gateway to the Everest region",
    "Namche Bazaar — the lively Sherpa capital of Khumbu",
    "Hotel Everest View (3,880 m) for panoramic Everest & Ama Dablam views",
    "Walk through Sagarmatha National Park (UNESCO World Heritage)",
    "Sherpa villages, suspension bridges & Dudh Koshi riverside trails",
    "Optional Sherpa Culture Museum and Namche markets",
    "Short, beginner-friendly Everest experience in just 7 days",
    "Comfortable teahouse lodging — no camping required",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport pickup and drop-off by private vehicle",
    "Kathmandu ↔ Lukla airfare included (Manthali routing in peak season as required)",
    "Full-board meals (breakfast, lunch, dinner) during the trek",
    "Licensed mountain guide with salary, food, lodging & insurance",
    "Porter support to carry trek luggage (typically shared 2:1)",
    "Teahouse accommodation throughout the trek",
    "TIMS, Sagarmatha / Khumbu permits and entry fees as required",
    "First-aid kit, trekking map, and pre-trek briefing",
  ],
  whyHeading: "Why choose Everest View?",
  whyPoints: [
    "See Everest and neighboring giants without going all the way to Base Camp",
    "Ideal short trek for beginners, families, and limited holiday time",
    "Max altitude stays at Hotel Everest View (3,880 m) — lower AMS risk than EBC",
    "Blend of adventure, Sherpa culture, and comfort-focused teahouses",
    "Easy to combine with Kathmandu sightseeing or extend toward EBC / Gokyo",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "Yes — this is one of the best starter treks in the Everest region. You do not need climbing experience. Daily walking is typically about 3–6 hours (one longer day on the return to Lukla), with lodges every night.\n\nThe hardest stretch is usually Lukla to Namche (mostly uphill). A full rest day in Namche with the Everest View Hotel hike uses “climb high, sleep low” for safer acclimatization. If you can walk several hours with breaks, you can do this trek. Light cardio before you fly helps.\n\nTravel insurance covering trekking to at least 4,000 m and helicopter evacuation is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Do regular walking or light cardio in the weeks before departure",
    "Break in waterproof hiking boots on practice walks",
    "Pack layers for cool Namche mornings and evenings (~3,440 m)",
    "Respect Lukla flight baggage limits (~15 kg total) — leave extras in Kathmandu",
    "Buy travel insurance covering high-altitude trekking and helicopter rescue",
    "Arrive in Kathmandu a day early when possible for Lukla flight buffer",
  ],
  itineraryHeading: "7-day itinerary",
  itineraryIntro:
    "Walking and flight times are estimates and vary with weather and pace. Peak-season Lukla flights often operate via Manthali (Ramechhap). Your Summit Seek guide can adjust the plan for safety and lodge availability.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,400 m",
      meals: "—",
      accommodation: "Hotel in Kathmandu",
      description:
        "Meet and greet at Tribhuvan International Airport and private transfer to your hotel. Trip briefing, gear check, and free time in Thamel. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Fly Kathmandu – Lukla – trek to Phakding",
      maxAltitude: "2,652 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Early scenic flight to Lukla (~30–45 minutes). Meet your trekking team and descend through pine and rhododendron forest along the Dudh Koshi to Phakding (~8 km / about 3 hours). Overnight in Phakding.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Phakding – Namche Bazaar",
      maxAltitude: "3,440 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Trek via Benkar, Monjo, and Jorsalle. Enter Sagarmatha National Park, cross Hillary Bridge, then climb into Namche Bazaar (~10–12 km / about 6 hours). Overnight in Namche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Acclimatization – hike to Hotel Everest View",
      maxAltitude: "3,880 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Acclimatization hike to Hotel Everest View (~3–4 km / about 4 hours) for panoramic views of Everest, Lhotse, Nuptse, Ama Dablam, and Thamserku. Optional Sherpa Culture Museum and Namche markets. Overnight again in Namche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Namche – Lukla",
      maxAltitude: "2,800 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Long downhill day retracing the Dudh Koshi corridor via Monjo and Phakding to Lukla (~18–19 km / about 7 hours). Celebrate with your team. Overnight in Lukla.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Fly Lukla – Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Morning scenic flight to Kathmandu and private hotel transfer. Free afternoon for shopping or rest. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Final departure",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "— (departure day)",
      description:
        "Private transfer to Tribhuvan International Airport for your departure flight. End of the Everest View journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Everest View departures run on private and joining bases year-round. March–May and September–November usually bring the clearest mountain views. Winter is quieter and colder; monsoon means more rain and Lukla delays.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Arrive Kathmandu 1 day early for Lukla flight buffer when possible",
    "Peak-season Lukla flights often operate via Manthali (Ramechhap)",
    "Easy to extend toward EBC, Gokyo, or Kathmandu sightseeing on request",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Single room supplement",
      description: "Private teahouse / hotel rooms where available for solo comfort.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Kathmandu heritage day tour",
      description: "Guided visit to major UNESCO sites in the Kathmandu Valley.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Extend toward EBC or Gokyo",
      description: "Add days to continue to Everest Base Camp or the Gokyo Lakes corridor.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport pickup and drop-off in Kathmandu",
    "Hotel accommodation in Kathmandu as per itinerary (BB basis)",
    "Full-board meals (breakfast, lunch, dinner) during the trek",
    "Kathmandu ↔ Lukla airfare",
    "Teahouse / lodge accommodation during the trek",
    "Licensed mountain guide (salary, food, lodging, insurance, transport, local tax)",
    "Porter to carry trek luggage (typically shared; solo supplement may apply)",
    "TIMS card and required park / entry permits",
    "First-aid kit and trekking map",
    "All government taxes and service charges",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Lunch and dinner in Kathmandu",
    "Travel insurance (mandatory — high-altitude evacuation)",
    "Nepal entry visa fee",
    "International airfare and airport departure tax",
    "Tips for trekking staff",
    "Drinks (hot/soft/cold) and alcohol",
    "Hot showers, device charging, and Wi-Fi on the trail (usually extra)",
    "Personal shopping, laundry, and personal trekking equipment",
    "Any items not listed in the includes section",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Everest-region mountain light",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "High Himalayan panorama",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Alpine ridges toward Khumbu",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Trail atmosphere in the Everest foothills",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "Spring (March–May) brings rhododendrons and mild days. Autumn (September–November) usually has the clearest Everest views. Winter is cold but quieter; monsoon (June–August) brings rain, clouds, and more flight delays.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & AMS",
      body: "Highest point is Hotel Everest View at 3,880 m; overnight max is Namche (~3,440 m). Use the rest day, drink 3–4 liters of water daily, avoid alcohol, and tell your guide early if symptoms worsen.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Rated easy to moderate. The hardest day is usually Phakding to Namche (~6 hours uphill). Trails are well-used with stone steps and suspension bridges — no technical climbing gear required.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Lodges & meals",
      body: "Family-run teahouses with twin rooms. Hot showers and Wi-Fi often cost extra. Expect dal bhat, noodles, fried rice, momos, porridge, eggs, tea, and coffee. Budget ~US$200–300 cash for personal extras.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Lukla flights usually allow about 15 kg total baggage. Porters carry your main bag; you hike with a light daypack. Dress in layers — valleys can feel mild while Namche evenings are cool.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece mid-layer",
        "Warm insulated / down jacket",
        "Waterproof shell",
        "Trekking pants",
        "Warm hat, sun hat, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Camp shoes / sandals",
        "Trekking poles (recommended)",
        "25–35L daypack",
        "Duffel for porter (within flight weight limit)",
        "2–3 pairs trekking socks",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "SPF 50+ sunscreen & lip balm",
        "UV sunglasses",
        "Personal medications & blister care",
        "Water bottle + purification tablets",
        "Headlamp + spare batteries",
        "Trail snacks / energy bars",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance details (print a copy for your guide)",
        "Cash in NPR for personal trail expenses",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Trekking map and pre-trek briefing in Kathmandu",
    "First-aid support with your guiding team",
    "Help arranging Kathmandu hotel buffer nights for Lukla weather",
    "Advice on extending toward EBC, Gokyo, or heritage sightseeing",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Everest View Trek?",
      answer:
        "A short 7-day Khumbu trek focused on Namche Bazaar and Hotel Everest View (3,880 m) for panoramic views of Everest and nearby peaks — without going all the way to Base Camp.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Easy to moderate. Daily walks are typically 3–6 hours, with one longer return day to Lukla. The climb into Namche is the hardest stretch. No technical climbing is required.",
      visible: true,
    },
    {
      id: "q3",
      question: "What is the maximum altitude?",
      answer:
        "Hotel Everest View at approximately 3,880 m. The highest overnight stop is Namche Bazaar at about 3,440 m.",
      visible: true,
    },
    {
      id: "q4",
      question: "Is this trek good for families and beginners?",
      answer:
        "Yes. Moderate altitudes, teahouse lodging, and a dedicated acclimatization day make it popular with first-timers, families, and older travelers with basic fitness.",
      visible: true,
    },
    {
      id: "q5",
      question: "How much does the Everest View Trek cost?",
      answer:
        "This Summit Seek 7-day listing starts at US$890 for 2–6 pax (was US$990), with group discounts shown on the page. Final price depends on group size and any custom add-ons.",
      visible: true,
    },
    {
      id: "q6",
      question: "Is travel insurance necessary?",
      answer:
        "Yes. Cover trekking to at least 4,000 m and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q7",
      question: "When is the best time to go?",
      answer:
        "Spring (March–May) and autumn (September–November) usually offer the clearest Everest views and most reliable Lukla weather.",
      visible: true,
    },
    {
      id: "q8",
      question: "What is the Lukla baggage limit?",
      answer:
        "Airlines typically enforce about 15 kg total (often ~10 kg checked + ~5 kg carry-on). Pack light and store extra luggage at your Kathmandu hotel.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Everest View?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Everest View Trek 7 Days | Summit Seek",
  metaDescription:
    "Book the 7-day Everest View Trek with Summit Seek — Lukla flights, Namche Bazaar, Hotel Everest View (3,880 m), permits, guide, porter & group discounts.",
};
