import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_EVEREST_BASE_CAMP_TREK: TrekPageContent = {
  coverImageUrl: img("photo-1544735716-392fe2489ffa", 2000),
  coverTitle: "Everest Base Camp Trek - 15 Days",
  coverSubtitle:
    "Classic Khumbu journey to Everest Base Camp (5,364 m) and Kala Patthar (5,545 m) — Namche & Dingboche acclimatization, Tengboche Monastery, and Sherpa culture.",
  heroMainImageUrl: img("photo-1544735716-392fe2489ffa", 2000),
  heroSideImage1Url: img("photo-1486870591958-9b9d0d1dda99", 900),
  heroSideImage2Url: img("photo-1464822759023-fed622ff2c3b", 900),
  breadcrumbLabel: "Packages · Everest Region",
  title: "Everest Base Camp Trek - 15 Days",
  regionLabel: "Everest Region",
  rating: 5,
  reviewCount: 22,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 1300,
  compareAtPrice: 1550,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "16% OFF",
  shortTripBadge: "Best Seller",
  durationLabel: "15 Days",
  difficultyLabel: "Moderate",
  groupSizeLabel: "2+",
  bookingNote:
    "Private and daily departures. Package includes Kathmandu hotel nights (BB as listed), Lukla flights (via Manthali if season requires), Sagarmatha & Khumbu permits, licensed guide and porter, full-board trek meals, and twin-sharing lodges. Arrive 1–2 days early for Lukla flight buffers.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 1550, visible: true },
    { id: "gd2", paxLabel: "2-4 pax", price: 1300, visible: true },
    { id: "gd3", paxLabel: "5-10 pax", price: 1249, visible: true },
    { id: "gd4", paxLabel: "11+ pax", price: 1199, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "15 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Moderate", visible: true },
    { id: "f3", label: "Max Altitude", value: "5,545 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Everest / Khumbu", visible: true },
    { id: "f6", label: "Group Size", value: "2 onwards", visible: true },
    { id: "f7", label: "Activities", value: "Trekking", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Oct–Dec",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "Everest Base Camp Trek – 15 Days is the classic grand walk of the Himalayas — following trails made famous after Hillary and Tenzing’s 1953 summit into Sagarmatha National Park, the world’s highest national park.\n\nThis package flies you to Lukla, then treks via Phakding, Namche Bazaar (with Everest View Hotel acclimatization), Tengboche Monastery, Dingboche, Lobuche, and Gorak Shep to Everest Base Camp (5,364 m). The next morning you climb Kala Patthar (5,545 m) for sunrise on Everest, Lhotse, and Nuptse before descending via Pheriche and quieter Phortse toward Monjo and Lukla.\n\nExpect Sherpa hospitality, prayer flags, mani walls, suspension bridges, rhododendron forests, and the Khumbu Glacier. Summit Seek includes Lukla flights, permits, guide, porter, trek meals and lodges, Kathmandu hotels as listed, and clear group pricing.",
  overviewImageUrl: img("photo-1506905925346-21bda4d32df4"),
  highlightsHeading: "Highlights",
  highlights: [
    "Scenic flight into Lukla — gateway to Everest",
    "Stand at Everest Base Camp (5,364 m) beside the Khumbu Icefall",
    "Sunrise from Kala Patthar (5,545 m) — best Everest panorama",
    "Acclimatization hikes: Everest View Hotel & Nangkartshang area",
    "Tengboche Monastery — spiritual heart of the Khumbu",
    "Quieter Phortse village on the descent",
    "Sherpa culture in Namche, Pangboche, and Dingboche",
    "Walk through Sagarmatha National Park UNESCO trails",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport pickups and drops for international and domestic flights",
    "Kathmandu hotel nights with breakfast as listed",
    "Kathmandu–Lukla–Kathmandu flights (via Manthali if season requires)",
    "Twin-sharing lodge lodging and full-board meals on trek",
    "Licensed guide and porter (2:1); assistant guide for larger groups",
    "Sagarmatha National Park, TIMS as applicable, and Khumbu local fees",
    "Down jacket / sleeping bag loan if needed; oximeter; first-aid kit",
    "Achievement certificate; emergency rescue coordination (insurance pays)",
  ],
  whyHeading: "Why choose the 15-day EBC package?",
  whyPoints: [
    "Extra buffer vs shorter itineraries — better acclimatization rhythm",
    "Two dedicated rest/acclimatization days at Namche and Dingboche",
    "Phortse variant adds quieter trails and village atmosphere",
    "Classic Base Camp + Kala Patthar goals in one trip",
    "Clear best-seller pricing with group discounts",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "Many first-time Himalayan trekkers complete EBC with preparation. Expect 5–7 hours of walking on many days and a high point of 5,545 m. No technical climbing skills are required, but solid cardio fitness and broken-in boots matter.\n\nTrain 6–8 weeks ahead. Stay hydrated, follow acclimatization advice, and tell your guide early if you feel unwell. Travel insurance covering helicopter evacuation is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Build endurance with hiking, stairs, and cardio 6–8 weeks before",
    "Break in waterproof ankle-support boots on practice walks",
    "Pack warm layers for Gorak Shep / EBC nights and strong sun protection",
    "Buy insurance covering trekking to 6,000 m and heli evacuation",
    "Arrive Kathmandu 1–2 days early for Lukla flight buffers",
    "Lukla baggage ~15 kg total — pack light; rent gear in Kathmandu if needed",
  ],
  itineraryHeading: "15-day itinerary",
  itineraryIntro:
    "Based on the classic 15-day EBC package with Phortse on the descent. Peak-season Lukla flights often operate via Manthali (Ramechhap). Lodge names may vary with availability.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,360 m",
      meals: "—",
      accommodation: "3-star hotel in Kathmandu",
      description:
        "Airport meet-and-greet and private hotel transfer. Evening trek briefing at the office/hotel. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Fly Lukla – trek to Phakding",
      maxAltitude: "2,840 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Phakding",
      description:
        "Early flight to Lukla (~30–35 min; peak season may route via Manthali with private road transfer). Meet crew and trek via Ghat to Phakding (~3 hours). Overnight lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Trek Phakding – Namche Bazaar",
      maxAltitude: "3,440 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Namche",
      description:
        "Via Benkar, Monjo, and Jorsale into Sagarmatha National Park; cross suspension bridges and climb into Namche Bazaar (~6 hours). Overnight lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Acclimatization day at Namche",
      maxAltitude: "3,880 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Namche",
      description:
        "Side hike toward Hotel Everest View for close Ama Dablam and Everest panoramas (~4 hours), then return to Namche to rest. Overnight lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Trek Namche – Tengboche",
      maxAltitude: "3,870 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Tengboche",
      description:
        "Uphill trail to Tengboche with mountain views; visit Tengboche Monastery (~5 hours). Overnight lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Trek Tengboche – Dingboche",
      maxAltitude: "4,360 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Dingboche",
      description:
        "Follow the Imja Khola via Orsho into Dingboche (~5 hours). Overnight lodge in the alpine village.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Acclimatization day at Dingboche",
      maxAltitude: "5,083 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Dingboche",
      description:
        "Optional hike toward Nangkartshang / Nakarjun hill for Makalu and Ama Dablam views (~4 hours), then rest. Overnight Dingboche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Trek Dingboche – Lobuche",
      maxAltitude: "4,940 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Lobuche",
      description:
        "Via Thukla / Dughla Pass and climbers’ memorials along the Khumbu Glacier moraine to Lobuche (~5–7 hours). Overnight lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Lobuche – Gorak Shep – Everest Base Camp",
      maxAltitude: "5,364 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Gorak Shep",
      description:
        "Trek to Gorak Shep, leave bags, then day hike to Everest Base Camp (5,364 m) and return (~6 hours total). Overnight Gorak Shep.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Kala Patthar sunrise – trek to Pheriche",
      maxAltitude: "5,545 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Pheriche",
      description:
        "Pre-dawn hike to Kala Patthar (5,545 m) for Everest sunrise, breakfast at Gorak Shep, then descend to Pheriche (~7 hours). Overnight lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Trek Pheriche – Phortse",
      maxAltitude: "3,810 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Phortse",
      description:
        "Descend via Pangboche on a quieter trail into Phortse village with Ama Dablam and Thamserku views (~6 hours). Overnight lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Trek Phortse – Monjo",
      maxAltitude: "2,860 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Monjo",
      description:
        "Continue downhill through forest and Sherpa settlements toward Monjo (~6 hours). Overnight lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Trek Monjo – Lukla",
      maxAltitude: "2,840 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Lukla",
      description:
        "Final trek day via Phakding, Ghat, and Chheplung into Lukla (~6 hours). Celebrate with crew. Overnight Lukla.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Fly Lukla – Kathmandu",
      maxAltitude: "1,360 m",
      meals: "Breakfast; farewell dinner as listed",
      accommodation: "3-star hotel in Kathmandu",
      description:
        "Morning flight to Kathmandu (or Manthali + drive). Hotel transfer, free afternoon, and farewell dinner with cultural program as listed. Overnight Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d15",
      dayLabel: "Day 15",
      title: "Departure from Kathmandu",
      maxAltitude: "1,360 m",
      meals: "Breakfast",
      accommodation: "—",
      description:
        "Airport transfer for your international flight. End of the Everest Base Camp journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best in March–May and October–December. Private groups welcome year-round with weather caveats in monsoon and deep winter. Allow Lukla flight buffer nights.",
  availabilityNotes: [
    "Daily private trip departures available",
    "Fully customizable pacing and lodge upgrades on request",
    "Lukla flights are weather-dependent — allow buffers",
    "Optional heli add-ons for Lukla or early exit on request",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Kathmandu–Lukla helicopter",
      description: "Skip Manthali road transfer in peak season (sharing basis).",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Extra Kathmandu nights",
      description: "Buffer nights before or after the trek.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Kathmandu sightseeing day",
      description: "Heritage tour of valley UNESCO sites.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport pickups and drops (international and domestic) as listed",
    "Kathmandu hotel nights with breakfast as listed (typically 2 nights)",
    "Kathmandu–Lukla–Kathmandu flights for members and staff (~15 kg baggage)",
    "Twin-sharing lodge lodging and full-board meals on trek",
    "Licensed guide and porter (2:1); assistant guide for larger groups",
    "Sagarmatha National Park permit, TIMS as applicable, Khumbu local fee",
    "Down jacket and sleeping bag loan if needed (return after trek)",
    "First-aid kit, oximeter, duffel/T-shirt as arranged, achievement certificate, taxes",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "International airfare and Nepal entry visa",
    "Travel insurance (mandatory — altitude & heli evacuation)",
    "Extra Kathmandu hotel nights and meals not listed",
    "Personal expenses: snacks, drinks, hot showers, charging, Wi-Fi",
    "Tips for guide, porter, and drivers",
    "Anything not listed under inclusions",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Classic approaches toward Everest Base Camp",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "Glacier light near Lobuche and Gorak Shep",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Alpine trails above Namche and Tengboche",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1519681393784-d120267933ba"),
      caption: "High Himalayan ridges on a clear day",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May and October–December offer the most reliable windows for clear views and organized trail conditions.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & difficulty",
      body: "Highest point is Kala Patthar at 5,545 m; Everest Base Camp is 5,364 m. Graded Moderate — long walking days plus altitude (~110 km classic distance).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Permits",
      body: "Sagarmatha National Park entry, Khumbu Pasang Lhamu Rural Municipality permit, and TIMS as applicable. Bring passport photos. Summit Seek arranges these.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Routes",
      body: "Kathmandu → Lukla → Phakding → Namche → Tengboche → Dingboche → Lobuche → Gorak Shep / EBC → Kala Patthar → Pheriche → Phortse → Monjo → Lukla → Kathmandu.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Porters carry main bags (~10–12 kg per person share); keep water, layers, documents, and camera in a daypack. Sleeping bag and down jacket can be loaned if arranged.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Trekking shirts and trousers",
        "Fleece mid-layer",
        "Down jacket",
        "Waterproof shell jacket and pants",
        "Warm gloves, hat, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear",
      items: [
        "Broken-in waterproof hiking boots",
        "Trekking poles",
        "Gaiters (optional)",
        "Camp shoes",
        "Warm and hiking socks",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Camp & health",
      items: [
        "Sleeping bag rated for cold high lodges",
        "Headlamp + spare batteries",
        "Water bottle or bladder + purification",
        "Personal first-aid and blister care",
        "SPF 50+ sunscreen and lip balm",
        "Sunglasses",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies + 2 passport photos",
        "Nepal visa as applicable",
        "Insurance covering heli evacuation",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Permit processing and Lukla flight coordination",
    "Licensed guide and porter logistics",
    "Sleeping bag / down jacket loan if arranged",
    "Emergency helicopter coordination (insurance pays)",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the 15-day Everest Base Camp Trek?",
      answer:
        "A Kathmandu-to-Kathmandu package reaching Everest Base Camp (5,364 m) and Kala Patthar (5,545 m) with Namche and Dingboche acclimatization and a quieter Phortse descent.",
      visible: true,
    },
    {
      id: "q2",
      question: "How much does it cost?",
      answer:
        "This listing starts at US$1,300 for 2–4 pax (US$1,550 for 1; US$1,249 for 5–10; US$1,199 for 11+). Market packages elsewhere often list around US$1,425–1,790 depending on group size.",
      visible: true,
    },
    {
      id: "q3",
      question: "How difficult is EBC?",
      answer:
        "Challenging but achievable for fit walkers — about 110 km over ~15 days with high altitude. No technical climbing skills required; prior trek experience helps.",
      visible: true,
    },
    {
      id: "q4",
      question: "What is the maximum altitude?",
      answer:
        "Kala Patthar at 5,545 m. Everest Base Camp itself is 5,364 m.",
      visible: true,
    },
    {
      id: "q5",
      question: "When is the best time to go?",
      answer:
        "March–May and October–December usually offer the best weather and views.",
      visible: true,
    },
    {
      id: "q6",
      question: "Are Lukla flights included?",
      answer:
        "Yes — Kathmandu–Lukla–Kathmandu (or via Manthali in peak season) as listed, typically with ~15 kg baggage allowance.",
      visible: true,
    },
    {
      id: "q7",
      question: "Is travel insurance necessary?",
      answer:
        "Yes — covering high-altitude trekking and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q8",
      question: "Can the itinerary be customized?",
      answer:
        "Yes — private departures can adjust pace, add buffer days, or combine heli options. Contact us with your dates and group size.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Everest Base Camp?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Everest Base Camp Trek 15 Days | Summit Seek",
  metaDescription:
    "Book 15-day Everest Base Camp Trek — EBC 5,364 m, Kala Patthar 5,545 m, Lukla flights, permits, guide, lodges & group rates from US$1,199.",
};
