import type { FeaturedPackagesContent } from "@/types/featured-packages";

const img = (id: string, w = 900) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

function pkg(
  partial: Omit<
    FeaturedPackagesContent["categories"][0]["packages"][0],
    "visible" | "rating" | "reviewCount"
  > & {
    rating?: number;
    reviewCount?: number;
  },
) {
  return {
    ...partial,
    visible: true,
    rating: partial.rating ?? 5,
    reviewCount: partial.reviewCount ?? 1,
  };
}

/** Homepage featured tabs — 4 categories × 4 packages */
export const DEFAULT_FEATURED_PACKAGES: FeaturedPackagesContent = {
  categories: [
    {
      id: "top-treks",
      label: "Top Treks in Nepal",
      icon: "medal",
      packages: [
        pkg({
          id: "tt-1",
          title: "Ghorepani Poonhill Trekking - 5 Days",
          durationDays: 5,
          startLocation: "Pokhara",
          endLocation: "Pokhara",
          price: 399,
          compareAtPrice: 499,
          href: "/treks/poon-hill",
          imageUrl: img("photo-1483728642387-6c3bdd6c93e5"),
        }),
        pkg({
          id: "tt-2",
          title: "Annapurna Base Camp Trek - 11 Days",
          durationDays: 11,
          startLocation: "Pokhara",
          endLocation: "Pokhara",
          price: 890,
          compareAtPrice: 990,
          href: "/treks/annapurna-base-camp",
          imageUrl: img("photo-1585409677983-0f6c41ca9c3b"),
          reviewCount: 12,
        }),
        pkg({
          id: "tt-3",
          title: "Everest Base Camp Trek - 14 Days",
          durationDays: 14,
          startLocation: "Kathmandu",
          endLocation: "Kathmandu",
          price: 1590,
          compareAtPrice: 1790,
          href: "/treks/everest-base-camp",
          imageUrl: img("photo-1544735716-392fe2489ffa"),
          reviewCount: 28,
        }),
        pkg({
          id: "tt-4",
          title: "Mardi Himal Trek - 5 Days",
          durationDays: 5,
          startLocation: "Pokhara",
          endLocation: "Pokhara",
          price: 520,
          compareAtPrice: 590,
          href: "/treks/mardi-himal",
          imageUrl: img("photo-1506905925346-21bda4d32df4"),
          reviewCount: 6,
        }),
      ],
    },
    {
      id: "peak-climbing",
      label: "Peak Climbing",
      icon: "mountain",
      packages: [
        pkg({
          id: "pc-1",
          title: "Yala Peak Climbing - 14 Days",
          durationDays: 14,
          startLocation: "Kathmandu",
          endLocation: "Kathmandu",
          price: 1699,
          compareAtPrice: 1799,
          href: "/treks/yala-peak",
          imageUrl: img("photo-1464822759023-fed622ff2c3b"),
        }),
        pkg({
          id: "pc-2",
          title: "Mera Peak Climbing - 18 Days",
          durationDays: 18,
          startLocation: "Kathmandu",
          endLocation: "Kathmandu",
          price: 2499,
          compareAtPrice: 2699,
          href: "/treks/mera-peak",
          imageUrl: img("photo-1434394354979-a235cd36269d"),
          reviewCount: 4,
        }),
        pkg({
          id: "pc-3",
          title: "Pokalde Peak Climbing - 18 Days",
          durationDays: 18,
          startLocation: "Kathmandu",
          endLocation: "Kathmandu",
          price: 2299,
          compareAtPrice: 2499,
          href: "/treks/pokalde-peak",
          imageUrl: img("photo-1519681393784-d120267933ba"),
        }),
        pkg({
          id: "pc-4",
          title: "Lobuche Peak Climbing with Everest Base Camp Trek - 18 Days",
          durationDays: 18,
          startLocation: "Kathmandu",
          endLocation: "Kathmandu",
          price: 2499,
          compareAtPrice: 2699,
          href: "/treks/lobuche-peak",
          imageUrl: img("photo-1486870591958-9b9d0d1dda99"),
          reviewCount: 3,
        }),
      ],
    },
    {
      id: "nepal-tours",
      label: "Nepal Tours",
      icon: "stupa",
      packages: [
        pkg({
          id: "nt-1",
          title: "Shivapuri Hill Yoga Hike - 1 Day",
          durationDays: 1,
          startLocation: "Kathmandu",
          endLocation: "Kathmandu",
          price: 60,
          compareAtPrice: 70,
          href: "/tours/shivapuri-yoga-hike",
          imageUrl: img("photo-1548013146-72479768bada"),
        }),
        pkg({
          id: "nt-2",
          title: "Bhaktapur City Tour - 1 Day",
          durationDays: 1,
          startLocation: "Kathmandu",
          endLocation: "Bhaktapur",
          price: 60,
          compareAtPrice: 70,
          href: "/tours/bhaktapur-city",
          imageUrl: img("photo-1605640840605-14ac1853827d"),
        }),
        pkg({
          id: "nt-3",
          title: "Janakpur City Tour - 1 Day",
          durationDays: 1,
          startLocation: "Janakpur",
          endLocation: "Janakpur",
          price: 60,
          compareAtPrice: 70,
          href: "/tours/janakpur-city",
          imageUrl: img("photo-1566552881560-0be862a7c445"),
        }),
        pkg({
          id: "nt-4",
          title: "Kathmandu City Day Tour - 1 Day",
          durationDays: 1,
          startLocation: "Kathmandu",
          endLocation: "Kathmandu",
          price: 60,
          compareAtPrice: 70,
          href: "/tours/kathmandu-city",
          imageUrl: img("photo-1587474260584-136574528ed5"),
          reviewCount: 2,
        }),
      ],
    },
    {
      id: "luxury-vip",
      label: "Luxury & VIP Adventure",
      icon: "diamond",
      packages: [
        pkg({
          id: "lv-1",
          title: "Everest View Trek With Helicopter Tour - 4 Days",
          durationDays: 4,
          startLocation: "Kathmandu",
          endLocation: "Kathmandu",
          price: 2899,
          compareAtPrice: 2999,
          href: "/treks/everest-heli-view",
          imageUrl: img("photo-1609137144813-7d9921338f24"),
        }),
        pkg({
          id: "lv-2",
          title: "Luxury Everest Base Camp Trek - 12 Days",
          durationDays: 12,
          startLocation: "Kathmandu",
          endLocation: "Kathmandu",
          price: 4590,
          compareAtPrice: 4990,
          href: "/treks/luxury-everest-base-camp",
          imageUrl: img("photo-1454496522488-7a8e488e8606"),
          reviewCount: 5,
        }),
        pkg({
          id: "lv-3",
          title: "Annapurna Luxury Lodge Trek - 10 Days",
          durationDays: 10,
          startLocation: "Pokhara",
          endLocation: "Pokhara",
          price: 3290,
          compareAtPrice: 3590,
          href: "/treks/annapurna-luxury-lodge",
          imageUrl: img("photo-1519904981063-b0cf448d479e"),
          reviewCount: 2,
        }),
        pkg({
          id: "lv-4",
          title: "VIP Mustang Helicopter Tour - 3 Days",
          durationDays: 3,
          startLocation: "Pokhara",
          endLocation: "Pokhara",
          price: 3890,
          compareAtPrice: 4190,
          href: "/tours/mustang-heli-vip",
          imageUrl: img("photo-1493246507139-91e8fad9978e"),
        }),
      ],
    },
  ],
};
