import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_GOKYO_LAKES: TrekPageContent = {
  coverImageUrl: img("photo-1506905925346-21bda4d32df4", 2000),
  coverTitle: "Gokyo Lakes Trek - 12 Days",
  coverSubtitle:
    "Turquoise Gokyo Lakes, Ngozumpa Glacier, and sunrise from Gokyo Ri over Everest, Lhotse, Makalu, and Cho Oyu — a quieter Khumbu classic.",
  heroMainImageUrl: img("photo-1506905925346-21bda4d32df4", 2000),
  heroSideImage1Url: img("photo-1486870591958-9b9d0d1dda99", 900),
  heroSideImage2Url: img("photo-1544735716-392fe2489ffa", 900),
  breadcrumbLabel: "Everest Region · Gokyo Lakes",
  title: "Gokyo Lakes Trek - 12 Days",
  regionLabel: "Everest Region",
  rating: 5,
  reviewCount: 40,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 1390,
  compareAtPrice: 1590,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "12% OFF",
  shortTripBadge: "Classic Trek",
  durationLabel: "12 Days",
  difficultyLabel: "Challenging",
  groupSizeLabel: "1+",
  bookingNote:
    "Private and small-group departures available. Package includes Kathmandu–Lukla flights, permits, guide, porter, teahouse meals, and acclimatization days. Arrive 1–2 days early for Lukla flight buffer.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 1550, visible: true },
    { id: "gd2", paxLabel: "2-6 pax", price: 1390, visible: true },
    { id: "gd3", paxLabel: "7-12 pax", price: 1199, visible: true },
    { id: "gd4", paxLabel: "13-20 pax", price: 1049, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "12 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Challenging", visible: true },
    { id: "f3", label: "Max Altitude", value: "5,360 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Everest / Gokyo", visible: true },
    { id: "f6", label: "Group Size", value: "1+", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Lakes", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Oct–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The Gokyo Lakes trek is an outstanding teahouse journey in Nepal’s Khumbu Valley — ideal if you want Himalayan adventure away from the busiest Everest Base Camp corridor. The trail leads through serene Gokyo Valley to sparkling aquamarine glacial lakes, the massive Ngozumpa Glacier, and sweeping views from Gokyo Ri.\n\nSunrise from Gokyo Ri (~5,357–5,360 m) is the signature moment: four 8,000 m peaks — Everest, Lhotse, Makalu, and Cho Oyu — in one panorama. Along the way you pass authentic Sherpa villages, yak meadows, pine and rhododendron forests, and stay in cozy local teahouses.\n\nSummit Seek’s 12-day itinerary builds in acclimatization at Namche and a full exploration day at Gokyo, with licensed guides, fair porter support, Lukla flights, and clear pricing.",
  overviewImageUrl: img("photo-1464822759023-fed622ff2c3b"),
  highlightsHeading: "Highlights",
  highlights: [
    "Panoramic sunrise from Gokyo Ri (~5,357 m)",
    "Explore the stunning turquoise Gokyo Lakes",
    "Views of Cho Oyu, Everest, Lhotse & Makalu from one viewpoint",
    "Walk beside the massive Ngozumpa Glacier",
    "Peaceful alternative to the crowded classic EBC trail",
    "Authentic Sherpa culture and cozy teahouses",
    "Scenic trails through rhododendron and pine forests",
    "Hillary Bridge and Namche Bazaar gateway to Khumbu",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport pickup and drop-off by private vehicle",
    "Kathmandu ↔ Lukla airfare included (Manthali routing in peak season as required)",
    "Full-board meals during the trek (breakfast, lunch, dinner)",
    "Licensed mountain guide with salary, food, lodging & insurance",
    "Porter support to carry trek luggage (typically shared 2:1)",
    "Teahouse accommodation throughout the trek",
    "TIMS, Sagarmatha / Khumbu permits and entry fees as required",
    "First-aid kit, trekking map, farewell dinner, and appreciation certificate",
  ],
  whyHeading: "Why choose Gokyo Lakes?",
  whyPoints: [
    "Quieter trails than classic Everest Base Camp with equally dramatic mountains",
    "Unique glacial-lake scenery plus glacier walk ambience",
    "One of the best multi-peak panoramas in the Khumbu from Gokyo Ri",
    "Manageable for fit trekkers with proper acclimatization — often gentler than EBC",
    "Rich Sherpa culture and Buddhist heritage along the valley",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "Gokyo is moderate to challenging due to altitude (overnight at ~4,790 m; Gokyo Ri ~5,360 m), but many fit beginners succeed with preparation. Ascents are often considered gentler than classic EBC, with fewer crowds.\n\nBuild cardio and uphill walking before you fly, stay hydrated, avoid alcohol on the trail, and follow acclimatization days. Travel insurance covering helicopter evacuation up to ~5,500 m is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Do regular cardio and uphill walks in the weeks before departure",
    "Break in waterproof hiking boots on practice hikes",
    "Pack layers for freezing nights around Gokyo (4,790 m) and windy Gokyo Ri",
    "Buy travel insurance covering high-altitude trekking and helicopter evacuation",
    "Arrive in Kathmandu 1–2 days early for Lukla flight buffer",
    "Carry a reusable bottle, purification tablets, and trail snacks",
  ],
  itineraryHeading: "12-day itinerary",
  itineraryIntro:
    "Walking and flight times are estimates and vary with weather and pace. Lodge stops may change with availability. Peak-season Lukla flights often operate via Manthali (Ramechhap). Your Summit Seek guide can adjust the plan for safety.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Fly Kathmandu – Lukla – trek to Phakding",
      maxAltitude: "2,860 m",
      meals: "Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Early scenic flight to Lukla (~30–45 minutes). Meet your team and trek downhill through pine and rhododendron forest to Phakding (~3–4 hours / ~8 km). Optional nearby monastery visit. Overnight in Phakding.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Phakding – Namche Bazaar",
      maxAltitude: "3,440 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Cross Dudh Koshi suspension bridges via Toktok and Benkar. Enter Sagarmatha National Park at Monjo, then climb steeply past Hillary Bridge into Namche Bazaar (about 7–8 hours / ~11 km). Overnight in Namche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Namche acclimatization",
      maxAltitude: "≈ 3,940 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Acclimatization hike toward Everest Viewpoint (~3–4 hours) for views of Everest, Lhotse, Nuptse, Ama Dablam, and Thamserku. Explore Namche — museum, monastery, markets. Overnight again in Namche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Namche – Dole",
      maxAltitude: "≈ 4,038–4,200 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Trail above Namche via Kyangjuma with Everest and Ama Dablam views. Via Mongla and Phortse Thanga through rhododendron and juniper forest to Dole (about 6–9 hours / ~11 km). Overnight in Dole.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Dole – Machhermo",
      maxAltitude: "4,470 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Gradual alpine ascent along the ridge via Lhapharma and Luza with yak pastures and Dudh Koshi views. Reach Machhermo in the afternoon (about 4–7 hours / ~7–8 km). Overnight in Machhermo.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Machhermo – Gokyo",
      maxAltitude: "4,790 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Climb toward Pangka and cross Ngozumpa Glacier moraine past Longpongo and the second lake into Gokyo Village beside the third lake, with Cho Oyu views (about 6–7 hours / ~7–8 km). Overnight in Gokyo.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Gokyo Ri & Fifth Lake exploration",
      maxAltitude: "5,360 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Hike Gokyo Ri (~5,357–5,360 m) for sunrise over Everest, Lhotse, Makalu, Cho Oyu, and the Gokyo Lakes. Optional continuation toward the Fifth Lake. Overnight again in Gokyo.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Gokyo – Dole",
      maxAltitude: "4,038 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Descend the same scenic corridor via Machhermo, Luza, and Lhapharma through rhododendron forest to Dole (about 6–7 hours / ~14–15 km). Overnight in Dole.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Dole – Namche Bazaar",
      maxAltitude: "3,440 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Long downhill day with mountain views of Everest, Lhotse, Ama Dablam, and Cholatse via Mong La viewpoints into Namche (about 7–8 hours / ~11–12 km). Overnight in Namche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Namche – Lukla",
      maxAltitude: "2,860 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Final trail day along the Dudh Koshi with suspension bridges, Sherpa villages, and monasteries back to Lukla (about 7–9 hours / ~18 km). Celebrate with your team. Overnight in Lukla.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Fly Lukla – Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast, Farewell dinner",
      accommodation: "Hotel in Kathmandu",
      description:
        "Morning scenic flight to Kathmandu and private hotel transfer. Free afternoon in Thamel; farewell dinner celebrating your Gokyo Lakes trek. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Final departure",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "— (departure day)",
      description:
        "Private transfer to Tribhuvan International Airport for your departure flight. End of the Gokyo Lakes journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Gokyo departures run on private and joining bases. March–May and October–November usually bring the clearest views. Winter is quieter and colder; monsoon means more rain and Lukla delays.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Arrive Kathmandu 1–2 days early for Lukla flight buffer",
    "Peak-season Lukla flights often operate via Manthali (Ramechhap)",
    "Extensions via Renjo La or combining with EBC available on request",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Single room supplement",
      description: "Private teahouse rooms where available for solo comfort.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Kathmandu heritage day tour",
      description: "Guided visit to major UNESCO sites in the Kathmandu Valley.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Renjo La / EBC extension",
      description: "Add Renjo La or combine with Everest Base Camp for a longer Khumbu circuit.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport pickup and drop-off",
    "Full-board meals (breakfast, lunch, dinner) during the trek",
    "Kathmandu ↔ Lukla airfare",
    "Teahouse / lodge accommodation during the trek",
    "Licensed mountain guide (salary, food, lodging, insurance, transport, local tax)",
    "Porter to carry trek luggage (typically shared; solo supplement may apply)",
    "TIMS card and required park / entry permits",
    "First-aid kit and trekking map",
    "Ground transportation as per itinerary",
    "All government taxes and service charges",
    "Certificate of appreciation and farewell dinner before departure",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Lunch and dinner in Kathmandu",
    "Travel insurance (mandatory — high-altitude evacuation)",
    "Nepal entry visa fee",
    "International airfare and airport departure tax",
    "Tips for trekking staff",
    "Drinks (hot/soft/cold) and alcohol",
    "Personal shopping, laundry, and personal trekking equipment",
    "Any items not listed in the includes section",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Alpine lakes beneath Himalayan peaks",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "High Khumbu mountain panorama",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Glacier approaches toward Gokyo",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Trail light in the Everest region",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "October–November and March–May usually offer clear weather and the best Everest / Cho Oyu / lake views. Winter is colder with snow; monsoon brings rain, mud, and more flight delays.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & AMS",
      body: "Highest overnight is Gokyo (~4,790 m); Gokyo Ri is ~5,360 m. Use Namche and Gokyo rest days, drink water, avoid alcohol, and descend if symptoms worsen. Follow your guide’s pace.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Challenging due to altitude and 5–8 hour walking days, but often considered more manageable than classic EBC with proper fitness. Trails include stone stairs, alpine paths, and glacier moraine.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Lodges & meals",
      body: "Twin-share teahouses with shared toilets are standard. Hot showers and Wi-Fi usually cost extra. Expect dal bhat, noodles, pasta, momos, porridge, eggs, tea, and coffee.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Porter limit is typically about 22 kg shared between two trekkers. Carry a daypack with water, layers, documents, and snacks. Dress in layers — valleys can be mild while Gokyo nights freeze.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece mid-layer",
        "Down / insulated jacket",
        "Waterproof shell",
        "Trekking pants + warm evening layer",
        "Warm hat, sun hat, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Camp shoes",
        "Trekking poles",
        "25–35L daypack",
        "Duffel for porter",
        "3–4 pairs trekking socks",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "SPF 50+ sunscreen & lip balm",
        "UV sunglasses",
        "Personal medications & blister care",
        "Water bottle + purification tablets",
        "Headlamp + spare batteries",
        "Trail snacks / energy bars",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance details",
        "Cash for personal trail expenses",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Trekking map and pre-trek briefing",
    "First-aid support with your guiding team",
    "Help arranging Kathmandu hotels and flight buffer nights",
    "Advice on Renjo La or EBC combination extensions",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Gokyo Lakes trek?",
      answer:
        "A beautiful, less-crowded Everest-region teahouse trek to the turquoise Gokyo Lakes with a panoramic climb of Gokyo Ri overlooking Everest and neighboring giants.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Moderately challenging due to altitude, cold, and uphill days — manageable with good fitness and acclimatization. Often considered easier than classic EBC for many trekkers.",
      visible: true,
    },
    {
      id: "q3",
      question: "What is the altitude of Gokyo Ri?",
      answer:
        "About 5,357–5,360 m. The highest overnight stop is Gokyo village at approximately 4,790 m.",
      visible: true,
    },
    {
      id: "q4",
      question: "How much does the Gokyo Lakes trek cost?",
      answer:
        "Typical packages run roughly US$1,049–US$1,550 depending on group size and services. This Summit Seek 12-day listing starts at US$1,390 for 2–6 pax, with group discounts shown on the page.",
      visible: true,
    },
    {
      id: "q5",
      question: "Do we cross Cho La Pass on this trek?",
      answer:
        "No. The standard Gokyo Lakes itinerary does not cross Cho La. Cho La / Renjo La can be added as extensions on request.",
      visible: true,
    },
    {
      id: "q6",
      question: "Is travel insurance necessary?",
      answer:
        "Yes. Cover high-altitude trekking and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q7",
      question: "When is the best time to go?",
      answer:
        "Spring (March–May) and autumn (especially October–November) offer the clearest mountain and lake views.",
      visible: true,
    },
    {
      id: "q8",
      question: "Are Wi-Fi and charging available?",
      answer:
        "Yes at many lodges, usually for an extra fee. Connections can be slow higher up the valley.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Gokyo Lakes?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Gokyo Lakes Trek 12 Days | Summit Seek",
  metaDescription:
    "Book the 12-day Gokyo Lakes trek with Summit Seek — Gokyo Ri sunrise, turquoise lakes, Ngozumpa Glacier, Lukla flights, permits, guide, porter & group discounts.",
};
