import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_GOSAINKUNDA: TrekPageContent = {
  coverImageUrl: img("photo-1506905925346-21bda4d32df4", 2000),
  coverTitle: "Gosainkunda Trek - 8 Days",
  coverSubtitle:
    "A sacred Langtang pilgrimage — alpine lakes at Gosainkunda, Laurebinayak Pass (4,610 m), and a scenic Helambu descent to Sundarijal.",
  heroMainImageUrl: img("photo-1506905925346-21bda4d32df4", 2000),
  heroSideImage1Url: img("photo-1464822759023-fed622ff2c3b", 900),
  heroSideImage2Url: img("photo-1483728642387-6c3bdd6c93e5", 900),
  breadcrumbLabel: "Langtang Region · Gosainkunda",
  title: "Gosainkunda Trek - 8 Days",
  regionLabel: "Langtang Region",
  rating: 5,
  reviewCount: 22,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 425,
  compareAtPrice: 490,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "13% OFF",
  shortTripBadge: "Sacred Trek",
  durationLabel: "8 Days",
  difficultyLabel: "Moderate",
  groupSizeLabel: "2+",
  bookingNote:
    "Private trips available. Package includes permits, licensed guide, lodge nights on trek, and road transfers as listed. Full-board meals on trek days included with Summit Seek. Arrive Kathmandu the day before Day 1 when possible.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 475, visible: true },
    { id: "gd2", paxLabel: "2-4 pax", price: 425, visible: true },
    { id: "gd3", paxLabel: "5-8 pax", price: 399, visible: true },
    { id: "gd4", paxLabel: "9-12 pax", price: 375, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "8 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Easy–Moderate", visible: true },
    { id: "f3", label: "Max Altitude", value: "4,610 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Langtang / Helambu", visible: true },
    { id: "f6", label: "Group Size", value: "2+", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Pilgrimage", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The Gosainkunda trek is a short yet deeply spiritual Himalayan journey in Nepal’s Langtang region. Sacred Gosainkunda Lake (~4,380 m) is believed in Hindu mythology to have been created by Lord Shiva with his trident — a place of pilgrimage as much as a mountain destination.\n\nThis 8-day route drives from Kathmandu to Dhunche, climbs via Sing Gompa to the alpine lakes, crosses Laurebinayak Pass (4,610 m), then descends through Helambu villages (Tharepati, Kutumsang, Chipling, Chisopani) to Sundarijal and back to Kathmandu.\n\nExpect rhododendron forests, Tamang and Sherpa hospitality, high-altitude lake scenery, and mountain views without Everest or Annapurna logistics. Summit Seek runs private and small-group departures with permits, a licensed guide, lodge nights, trek meals, and clear group pricing.",
  overviewImageUrl: img("photo-1544735716-392fe2489ffa"),
  highlightsHeading: "Highlights",
  highlights: [
    "Sacred Gosainkunda Lake (~4,380 m) — Hindu pilgrimage site",
    "Cross Laurebinayak Pass at 4,610 m",
    "Scenic drive into Langtang via Dhunche",
    "Sing Gompa and alpine approaches above the tree line",
    "Helambu descent via Tharepati, Kutumsang & Chisopani",
    "Finish at Sundarijal with a short drive back to Kathmandu",
    "Ideal short trek for nature lovers and spiritual seekers",
    "Close to Kathmandu — no domestic flights required",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Licensed English-speaking mountain guide with salary, food, lodging & insurance",
    "Langtang National Park permit and TIMS arranged",
    "Lodge / teahouse accommodation during the trek",
    "Full-board meals (breakfast, lunch, dinner) on trek days",
    "Road transfers Kathmandu–Dhunche and Sundarijal–Kathmandu as per itinerary",
    "First-aid support and pre-trek briefing",
    "Private trip options with flexible start dates",
    "Clear group discounts — no hidden trek fees",
  ],
  whyHeading: "Why choose Gosainkunda?",
  whyPoints: [
    "Combine Himalayan scenery with a living pilgrimage tradition",
    "High-pass adventure in only 8 days from Kathmandu",
    "Quieter alternative to Everest and Annapurna classics",
    "Varied landscapes from forest villages to alpine lakes",
    "Easy to combine with Langtang Valley or Helambu extensions",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "Rated easy to moderate. No technical climbing is required, but you walk about 5–7 hours most days on steep, uneven trails and sleep near 4,200 m at Gosainkunda. Fit beginners succeed with preparation; prior multi-day hiking helps.\n\nBring a sleeping bag rated for cold nights, drink plenty of water, and follow your guide’s pacing. Travel insurance covering helicopter evacuation is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Walk or hike several times a week in the weeks before departure",
    "Break in waterproof hiking boots on practice walks",
    "Pack warm layers and a sub-zero-rated sleeping bag for Gosainkunda nights",
    "Buy insurance covering high-altitude trekking and helicopter rescue",
    "Consider private jeep to Dhunche for a smoother road day",
    "Carry photocopies of permits and cash for personal trail extras",
  ],
  itineraryHeading: "8-day itinerary",
  itineraryIntro:
    "Walking and drive times are estimates and vary with road conditions, weather, and pace. Lodge stops (especially Gopte vs Tharepati) may change with availability. Your Summit Seek guide can adjust for safety around Laurebinayak Pass.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Drive Kathmandu – Dhunche",
      maxAltitude: "1,960 m",
      meals: "Lunch, Dinner",
      accommodation: "Lodge / Teahouse",
      description:
        "Drive from Kathmandu to Dhunche (~103 km / about 6–8 hours by local bus or private jeep). Settle into your lodge. Overnight in Dhunche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Dhunche – Sing Gompa",
      maxAltitude: "3,330 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge / Teahouse",
      description:
        "Trek upward through forest and villages (~5–6 hours) to Sing Gompa. Overnight in Sing Gompa.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Sing Gompa – Gosainkunda",
      maxAltitude: "4,200 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge / Teahouse",
      description:
        "Climb into the alpine zone (~5–6 hours) to sacred Gosainkunda Lake (~4,380 m). Explore the lakeshore and temples. Overnight near Gosainkunda.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Gosainkunda – Laurebinayak Pass – Tharepati",
      maxAltitude: "4,610 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge / Teahouse",
      description:
        "Cross Laurebinayak Pass (4,610 m) then descend toward Gopte / Tharepati (~3,650 m) — about 6–7 hours. Overnight in Tharepati (or Gopte as available).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Tharepati – Kutumsang",
      maxAltitude: "2,470 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge / Teahouse",
      description:
        "Descend through Helambu forests and villages (~7 hours) to Kutumsang. Overnight in Kutumsang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Kutumsang – Chipling",
      maxAltitude: "2,170 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge / Teahouse",
      description:
        "Continue through Helambu countryside (~6 hours) to Chipling. Overnight in Chipling.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Chipling – Chisopani",
      maxAltitude: "2,170 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge / Teahouse",
      description:
        "Trek toward Chisopani (~6 hours) with Kathmandu Valley views opening on clear days. Overnight in Chisopani.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Chisopani – Sundarijal – Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "— (return to Kathmandu)",
      description:
        "Descend to Sundarijal (~4–5 hours) through forests and villages, then drive back to Kathmandu. End of the Gosainkunda journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Gosainkunda departures run on private bases year-round. Spring and autumn usually bring the clearest views. Winter can be snowy and cold around the lake and pass; monsoon means rain, leeches, and cloudy views.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Local bus or private jeep to Dhunche",
    "Janai Purnima festival season is especially busy at the lake",
    "Easy to combine with Langtang Valley on request",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Private jeep to Dhunche",
      description: "Upgrade the local bus to a private 4WD for a smoother road day.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Porter service",
      description: "Shared porter support so you hike with a light daypack.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Extra Kathmandu hotel night",
      description: "Add buffer nights before or after the trek.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Licensed English-speaking trekking guide (salary, food, lodging, insurance)",
    "Lodge / teahouse accommodation during the trek",
    "Full-board meals (breakfast, lunch, dinner) on trek days",
    "Langtang National Park permit and TIMS card",
    "Kathmandu–Dhunche transport (local bus; jeep upgrade available)",
    "Sundarijal–Kathmandu transfer at trek end",
    "First-aid kit and pre-trek briefing",
    "Government taxes and service charges as applicable",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "International airfare and Nepal entry visa fee",
    "Travel insurance (mandatory — high-altitude evacuation)",
    "Kathmandu hotel nights before/after the trek (unless added)",
    "Lunch and dinner in Kathmandu",
    "Drinks, snacks, hot showers, charging, and Wi-Fi on the trail",
    "Porter service unless added",
    "Tips for guide, porter, and driver",
    "Personal trekking equipment and any items not listed in includes",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "High alpine lake light",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Langtang-region mountain ridges",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1483728642387-6c3bdd6c93e5"),
      caption: "Forest trails toward Helambu",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Valley approaches near Kathmandu",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "Autumn (Sep–Nov) and spring (Mar–May) usually offer the clearest skies. Winter is cold with possible snow on Laurebinayak; monsoon is lush but wet and cloudy.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & AMS",
      body: "Max pass altitude is Laurebinayak at 4,610 m; overnight near Gosainkunda is about 4,200 m. Ascend steadily, drink water, avoid alcohol, and tell your guide early if symptoms worsen.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Easy to moderate. Expect 5–7 hour days on steep trails. No technical climbing — suitable for fit beginners with preparation.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Lodges & meals",
      body: "Twin-share teahouses with basic bedding. Rooms may be unheated at the lake — bring a warm sleeping bag. Expect dal bhat, noodles, momos, porridge, and eggs.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack for cold alpine nights at Gosainkunda. A quality sleeping bag is strongly recommended even when lodges provide blankets.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece mid-layer",
        "Down / insulated jacket",
        "Waterproof shell",
        "Trekking pants",
        "Warm hat, sun hat, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Camp shoes",
        "Trekking poles (helpful on the pass)",
        "20–30L daypack",
        "Sleeping bag (sub-zero rated)",
        "2–3 pairs trekking socks",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "SPF sunscreen & lip balm",
        "UV sunglasses",
        "Personal medications & blister care",
        "Water bottle + purification",
        "Headlamp + spare batteries",
        "Trail snacks",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance details",
        "Permit photocopies",
        "Cash for personal trail expenses",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Permit arrangement and pre-trek briefing in Kathmandu",
    "First-aid support with your guiding team",
    "Help arranging private jeep and extra hotel nights",
    "Advice on combining with Langtang Valley or Helambu",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Gosainkunda trek?",
      answer:
        "An 8-day Langtang-region trek to sacred Gosainkunda Lake, crossing Laurebinayak Pass (4,610 m) and descending via Helambu to Sundarijal near Kathmandu.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Easy to moderate. Daily walks are typically 5–7 hours on steep trails with high altitude near the lake and pass — no technical climbing required.",
      visible: true,
    },
    {
      id: "q3",
      question: "What is the maximum altitude?",
      answer:
        "Laurebinayak Pass at 4,610 m. Gosainkunda Lake sits around 4,380 m with overnight lodges nearby (~4,200 m).",
      visible: true,
    },
    {
      id: "q4",
      question: "How much does the Gosainkunda trek cost?",
      answer:
        "This Summit Seek listing starts at US$425 for 2–4 pax (US$475 solo), with group rates from US$399 (5–8) and US$375 (9–12).",
      visible: true,
    },
    {
      id: "q5",
      question: "Which permits do I need?",
      answer:
        "Langtang National Park entry permit and a TIMS card. Summit Seek arranges these for you.",
      visible: true,
    },
    {
      id: "q6",
      question: "Is travel insurance necessary?",
      answer:
        "Yes. Cover high-altitude trekking and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q7",
      question: "When is the best time to go?",
      answer:
        "Autumn (September–November) and spring (March–May) usually offer the best weather and mountain views.",
      visible: true,
    },
    {
      id: "q8",
      question: "Where does the trek start and end?",
      answer:
        "It starts with a drive from Kathmandu to Dhunche and ends with a walk to Sundarijal plus a short drive back to Kathmandu.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Gosainkunda?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Gosainkunda Trek 8 Days | Summit Seek",
  metaDescription:
    "Book the 8-day Gosainkunda trek with Summit Seek — sacred lake, Laurebinayak Pass (4,610 m), Helambu descent, permits, guide & group discounts from US$375.",
};
