import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_HELAMBU: TrekPageContent = {
  coverImageUrl: img("photo-1483728642387-6c3bdd6c93e5", 2000),
  coverTitle: "Helambu Trek - 7 Days",
  coverSubtitle:
    "A short mid-hill circuit near Kathmandu — Nagarkot sunrise, Chisopani ridges, Thadepati forests, and Hyalmo culture at Tarke Gyang.",
  heroMainImageUrl: img("photo-1483728642387-6c3bdd6c93e5", 2000),
  heroSideImage1Url: img("photo-1464822759023-fed622ff2c3b", 900),
  heroSideImage2Url: img("photo-1506905925346-21bda4d32df4", 900),
  breadcrumbLabel: "Langtang Region · Helambu",
  title: "Helambu Trek - 7 Days",
  regionLabel: "Langtang Region",
  rating: 5,
  reviewCount: 18,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 555,
  compareAtPrice: 600,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "8% OFF",
  shortTripBadge: "Short Trek",
  durationLabel: "7 Days",
  difficultyLabel: "Easy",
  groupSizeLabel: "1+",
  bookingNote:
    "Private and small-group departures available. Package includes permits, licensed guide, teahouse meals on trek days, and bus/taxi transfers as listed. Ideal short escape from Kathmandu.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 600, visible: true },
    { id: "gd2", paxLabel: "2 pax", price: 580, visible: true },
    { id: "gd3", paxLabel: "3-6 pax", price: 555, visible: true },
    { id: "gd4", paxLabel: "7-12 pax", price: 530, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "7 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Easy", visible: true },
    { id: "f3", label: "Max Altitude", value: "3,690 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Helambu / Langtang", visible: true },
    { id: "f6", label: "Group Size", value: "1+", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Culture", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "Helambu is a short, moderate circuit in the mid-hills of Nepal’s central Himalaya — close to Kathmandu, with views toward Langtang and Jugal Himal and warm hospitality from Tamang and Hyalmo communities.\n\nThe 7-day journey starts with a short drive to historic Sankhu, then climbs to Nagarkot for sunrise over Manaslu, Ganesh, Langtang–Jugal, and Gauri Shankar. The trail continues via Chisopani and Kutumsang into rhododendron–pine forest to Thadepati (~3,690 m), then descends to charming Tarke Gyang and Sermathang before finishing at Melamchi Bazaar and driving back to Kathmandu.\n\nExpect rural farm life, Buddhist monasteries, apple orchards, and cooler hill air without long road approaches or domestic flights. Summit Seek includes permits, a licensed guide, teahouse lodging, trek meals, and clear group pricing.",
  overviewImageUrl: img("photo-1544735716-392fe2489ffa"),
  highlightsHeading: "Highlights",
  highlights: [
    "Closest classic hill trek to Kathmandu — no flights needed",
    "Nagarkot sunrise over Langtang, Ganesh, Manaslu & Gauri Shankar",
    "Chisopani ridge views across the central Himalaya",
    "Thadepati (~3,690 m) amid rhododendron, pine, and magnolia forest",
    "Tarke Gyang — Hyalmo culture, wood carving & monastery visits",
    "Sermathang village and Helambu apple country",
    "Warm Tamang and Hyalmo lodge hospitality",
    "Easy–moderate grade for first-timers and short holidays",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Hotel pickup/drop by taxi as per itinerary",
    "All needed bus transport during the trek package",
    "Breakfast, lunch, dinner, tea and coffee during the trek",
    "Teahouse / mountain lodge accommodation",
    "Licensed guide (salary, food, insurance, equipment)",
    "All required mountain trekking permits",
    "Pre-trek briefing and first-aid support",
    "Clear group discounts — private trips available",
  ],
  whyHeading: "Why choose Helambu?",
  whyPoints: [
    "Short escape into cooler mid-hills without Everest or Annapurna logistics",
    "Rich Hyalmo and Tamang culture in living hill villages",
    "Big Himalayan panoramas from Nagarkot and Chisopani",
    "Forest walks and farm villages at a comfortable pace",
    "Easy to combine with Gosainkunda or Langtang Valley on request",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "Yes. Helambu is a moderate, easy-graded walk with daily hiking of about 4–6 hours. The high point at Thadepati (~3,690 m) is lower than Everest or Gosainkunda pass days, making it a strong starter trek near Kathmandu.\n\nBasic fitness helps for uphill days into the forest. Travel insurance covering trekking is still recommended.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Walk 30–45 minutes several times a week before departure",
    "Break in comfortable waterproof hiking boots",
    "Pack layers for cool nights at Thadepati and Chisopani",
    "Bring a sleeping bag if you prefer extra warmth in lodges",
    "Buy travel insurance covering trekking activities",
    "Carry cash for personal extras (showers, charging, drinks)",
  ],
  itineraryHeading: "7-day itinerary",
  itineraryIntro:
    "Walking and drive times are estimates and vary with pace and weather. Lodge stops may change with availability. Your Summit Seek guide can adjust the plan for comfort and safety.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Drive Sankhu – trek to Nagarkot",
      maxAltitude: "≈ 2,100 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Drive to historic Sankhu on the Kathmandu Valley rim, then trek via Jarsing Pawa and Kartike Bhanjyang to Nagarkot (~6 hours). Sunset/sunrise views toward Manaslu, Ganesh, Langtang–Jugal, and Gauri Shankar. Overnight in Nagarkot.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Nagarkot – Chisopani",
      maxAltitude: "2,165 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Ridge and forest walk via Kartike and Chowki Bhanjyang to Chisopani (~6 hours) with wide Himalayan panoramas. Overnight in Chisopani.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Chisopani – Kutumsang",
      maxAltitude: "2,470 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Sunrise over the peaks, then trek via Pati Bhanjyang, Thodung Danda, and Gul Bhanjyang to Kutumsang farm village (~5 hours). Overnight in Kutumsang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Kutumsang – Thadepati",
      maxAltitude: "3,690 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Climb through pine, fir, magnolia, and rhododendron forest via Kyuola Bhanjyang (~3,280 m) to Thadepati (~3,690 m / about 6 hours). Overnight in Thadepati.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Thadepati – Tarke Gyang",
      maxAltitude: "2,600 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Steep forest descent to Melamchi Gaon, cross Melamchi Khola, then climb to Tarke Gyang (~5 hours) — Hyalmo culture, wood carving, apples, and monastery visits. Overnight in Tarke Gyang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Tarke Gyang – Sermathang",
      maxAltitude: "2,590 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Pleasant forest path past chortens to Sermathang (~4 hours). Free afternoon to visit the old monastery. Overnight in Sermathang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Sermathang – Melamchi – Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast, Lunch",
      accommodation: "— (return to Kathmandu)",
      description:
        "Downhill walk past farm villages to Melamchi Bazaar (~4 hours), then drive about 3 hours back to Kathmandu. End of the Helambu journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Helambu departures run year-round on private and joining bases. Spring and autumn usually bring the clearest mountain views from Nagarkot and Chisopani. Winter is quieter and cooler; monsoon means greener hills with more rain.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Groups of 13–20 from US$500 per person on request",
    "Easy add-on nights in Kathmandu or Nagarkot",
    "Combine with Gosainkunda or Langtang Valley on request",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Porter service",
      description: "Shared porter support so you hike with a light daypack.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Extra Kathmandu hotel night",
      description: "Add buffer nights before or after the trek.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Single room supplement",
      description: "Private rooms where available in lodges.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "All needed transport by bus as per itinerary",
    "Hotel pickup / drop by taxi",
    "Food (breakfast, lunch, dinner) plus tea and coffee during the trek",
    "Mountain teahouse accommodation",
    "Licensed guide (food, salary, insurance, equipment)",
    "All needed mountain trekking permits",
    "Pre-trek briefing and first-aid support",
    "Government taxes as applicable",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Beer, soft drinks, mineral water, hot water, Wi-Fi, battery charging, hot showers",
    "Personal trekking equipment",
    "Travel insurance (mandatory)",
    "Tips for guide and staff",
    "Kathmandu hotel nights outside the trek package",
    "International airfare and Nepal visa fees",
    "Any items not listed in the includes section",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1483728642387-6c3bdd6c93e5"),
      caption: "Mid-hill ridges near Kathmandu",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Himalayan panorama from the Helambu trail",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Alpine forest light toward Thadepati",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Valley approaches in Helambu country",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "Spring (March–May) and autumn (September–November) usually offer the clearest sunrise views from Nagarkot and Chisopani. Winter is cold but quieter; monsoon is lush and wetter underfoot.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude",
      body: "Highest point is Thadepati at about 3,690 m — moderate by Himalayan standards. Stay hydrated and tell your guide early if you feel unwell.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Easy to moderate. Daily walks of roughly 4–6 hours with some steep forest climbs and descents. Suitable for fit beginners and families with older children.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Culture",
      body: "Hyalmo and Tamang communities welcome trekkers in villages like Tarke Gyang and Sermathang. Dress modestly around monasteries and ask before photographing people.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack light for a mid-hill trek. Lodges provide blankets; a sleeping bag adds comfort on cooler nights at Thadepati.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Sun hat / scarf",
        "Warm hat & gloves",
        "Waterproof jacket & pants",
        "Down / warm jacket",
        "Lightweight T-shirts & pants",
        "Running tights (optional)",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Comfortable trekking boots",
        "Thin inner socks (2+ pairs)",
        "Woolen socks",
        "Daypack / trekking bag",
        "Water bottle",
        "Sleeping bag",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "Sunglasses & headlamp",
        "Sunscreen & lip balm",
        "Water purification tablets",
        "Toiletries & toilet paper",
        "Personal medications",
        "Trail snacks",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance details",
        "Cash for personal trail expenses",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Permit arrangement and pre-trek briefing in Kathmandu",
    "First-aid support with your guiding team",
    "Help arranging extra hotel nights",
    "Advice on combining with Gosainkunda or Langtang Valley",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Helambu trek?",
      answer:
        "A 7-day mid-hill circuit near Kathmandu via Nagarkot, Chisopani, Kutumsang, Thadepati, Tarke Gyang, and Sermathang, ending at Melamchi with a drive back to the city.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Easy to moderate. Expect 4–6 hour walking days with some steep forest sections. Max altitude is about 3,690 m at Thadepati.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does the Helambu trek cost?",
      answer:
        "This Summit Seek listing starts at US$555 for 3–6 pax (US$600 solo; US$580 for 2; US$530 for 7–12). Groups of 13–20 from about US$500 on request.",
      visible: true,
    },
    {
      id: "q4",
      question: "Do I need flights?",
      answer:
        "No. Helambu starts and ends with road transfers from Kathmandu — one of the closest classic treks to the capital.",
      visible: true,
    },
    {
      id: "q5",
      question: "When is the best time to go?",
      answer:
        "Spring (March–May) and autumn (September–November) usually offer the clearest mountain views from Nagarkot and Chisopani.",
      visible: true,
    },
    {
      id: "q6",
      question: "Is travel insurance necessary?",
      answer:
        "Yes. Cover trekking activities. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q7",
      question: "Who are the Hyalmo people?",
      answer:
        "Hyalmo (Helambu) communities are hill people with strong Buddhist traditions, famous around Tarke Gyang for hospitality, monasteries, and wood carving.",
      visible: true,
    },
    {
      id: "q8",
      question: "Can I combine Helambu with Gosainkunda?",
      answer:
        "Yes. Many travelers link Helambu with Gosainkunda or Langtang Valley — ask us to customize your itinerary.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Helambu?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Helambu Trek 7 Days | Summit Seek",
  metaDescription:
    "Book the 7-day Helambu trek with Summit Seek — Nagarkot, Chisopani, Thadepati, Tarke Gyang, permits, guide, meals & group discounts from US$500.",
};
