import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_JANAKPUR_CITY: TrekPageContent = {
  coverImageUrl: img("photo-1566552881560-0be862a7c445", 2000),
  coverTitle: "Janakpur City Tour - 1 Day",
  coverSubtitle:
    "Sacred Mithila pilgrimage day in Janakpur Dham — Janaki Mandir, Ram Mandir, Dhanush Sagar, Ram–Sita Vivah Mandap, and living Ramayana heritage.",
  heroMainImageUrl: img("photo-1566552881560-0be862a7c445", 2000),
  heroSideImage1Url: img("photo-1548013146-72479768bada", 900),
  heroSideImage2Url: img("photo-1605640840605-14ac1853827d", 900),
  breadcrumbLabel: "Nepal Tours · City Day Tour",
  title: "Janakpur City Tour - 1 Day",
  regionLabel: "Mithila / Terai",
  rating: 5,
  reviewCount: 6,
  tripAdvisorRating: "4.9",
  googleRating: "4.9",
  trustpilotRating: "5.0",
  price: 60,
  compareAtPrice: 70,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "14% OFF",
  shortTripBadge: "Ramayana Heritage",
  durationLabel: "1 Day",
  difficultyLabel: "Easy",
  groupSizeLabel: "2+",
  bookingNote:
    "Full-day private sightseeing in Janakpur (starts/ends in Janakpur). Package includes local transfers between sites, English-speaking guide, temple entry/donations as listed, bottled water, and lunch as listed. Flights/bus from Kathmandu and accommodation are separate unless you add them.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 70, visible: true },
    { id: "gd2", paxLabel: "2-3 pax", price: 60, visible: true },
    { id: "gd3", paxLabel: "4-6 pax", price: 55, visible: true },
    { id: "gd4", paxLabel: "7+ pax", price: 50, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "1 Day", visible: true },
    { id: "f2", label: "Difficulty", value: "Easy", visible: true },
    { id: "f3", label: "Max Altitude", value: "~90 m (Terai)", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Janakpur", visible: true },
    { id: "f5", label: "Region", value: "Mithila / Janakpur Dham", visible: true },
    { id: "f6", label: "Group Size", value: "2 onwards", visible: true },
    { id: "f7", label: "Activities", value: "Culture & Pilgrimage", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Oct–Mar (festivals Nov–Apr)",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "Janakpur City Tour is a one-day spiritual and cultural immersion in Janakpur Dham — birthplace of Goddess Sita (Janaki) and the legendary kingdom of King Janak from the Ramayana. Hindu pilgrims link Janakpur with Ayodhya as part of the Ram–Sita sacred journey.\n\nYour guide covers Janaki Mandir (built 1910 by Queen Brikha Thakurani; Mithila / Mughal–Rajput marble architecture on the site of Sita’s childhood palace), Ram Mandir, sacred Dhanush Sagar pond, and Ram–Sita Vivah Mandap. Optional stops include Kailashnath Mahadev or Mithila art markets, with time for local food such as litti chokha and Mithila sweets.\n\nSummit Seek includes in-city transport, licensed guide, temple entries/donations as listed, water, lunch as listed, and clear group pricing. Travel to Janakpur from Kathmandu (flight or road) and hotels can be arranged as add-ons.",
  overviewImageUrl: img("photo-1548013146-72479768bada"),
  highlightsHeading: "Highlights",
  highlights: [
    "Janaki Mandir — iconic Mithila marble temple of Goddess Sita",
    "Ram Mandir and daily aarti atmosphere",
    "Dhanush Sagar — sacred pond linked to Rama’s bow legend",
    "Ram–Sita Vivah Mandap — divine wedding memorial",
    "Optional Kailashnath Mahadev or Mithila art markets",
    "Storytelling with guide/priests on Ramayana sites",
    "Taste Mithila street food and sweets",
    "Ideal day for Vivah Panchami, Ram Navami, or Chhath season visits",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Professional English-speaking local guide for the full day",
    "Private local transportation between all main Janakpur sites",
    "Temple entry fees / donations as listed",
    "Bottled water during the tour",
    "Lunch featuring local / Mithila options as listed",
    "Help with temple etiquette and photography guidance",
    "Flexible festival-season timing on request",
    "Optional Kathmandu–Janakpur flight/road add-ons",
  ],
  whyHeading: "Why choose Janakpur?",
  whyPoints: [
    "One of Nepal’s most important Ramayana pilgrimage cities",
    "Janaki Mandir architecture unlike Kathmandu Valley pagodas",
    "Living Mithila art, music, and festival culture",
    "Easy full-day pacing — family and senior friendly",
    "Pairs well with a Kathmandu–Janakpur flight day trip or overnight",
  ],
  beginnersHeading: "Is this tour good for beginners?",
  beginnersBody:
    "Yes — graded Easy and suitable for families and seniors. Most sites are urban and accessible without long walks. Expect warm Terai weather, modest temple dress codes, and removing footwear at shrines.\n\nNo trekking fitness is required. Confirm mobility needs when booking if you prefer shorter temple stops.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Dress modestly (cover shoulders and knees); light breathable fabrics",
    "Wear comfortable shoes you can remove at temples",
    "Bring sun protection — Janakpur can be hot, especially Apr–Sep",
    "Carry small NPR cash for snacks, sweets, and donations",
    "Ask permission before photographing inside temple areas",
    "Arrive Janakpur the night before or morning of the tour if flying from KTM",
  ],
  itineraryHeading: "1-day itinerary",
  itineraryIntro:
    "Typical timing for a full day in Janakpur (~8:00 a.m.–5:00 p.m.). Exact order may shift for festivals, aarti times, or your flight/bus schedule.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Janaki Mandir – Ram Mandir – Dhanush Sagar – Vivah Mandap – markets",
      maxAltitude: "~90 m",
      meals: "Lunch as listed",
      accommodation: "—",
      description:
        "08:00 Meet guide at hotel / bus station / airport in Janakpur. 08:30–10:30 Explore Janaki Mandir — marble courtyards, domes, and Sita devotion. 10:30 Ram Mandir. 11:30 Dhanush Sagar sacred pond. 12:30 Lunch (Mithila / Nepali–Indian options). 13:30 Ram–Sita Vivah Mandap. 14:30 Optional Kailashnath Mahadev or Mithila art & handicraft markets. 16:00 Cultural interaction / free time as available. 17:00 Drop at hotel, bus park, or airport — end of tour.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Operated daily year-round on private request. October–March offers the most comfortable temperatures. Vivah Panchami (Nov–Dec), Ram Navami (Mar–Apr), and Chhath Puja bring special energy — book early for festival dates.",
  availabilityNotes: [
    "Private and customizable start times within Janakpur",
    "Available for solo travelers and large groups",
    "Book ~7 days ahead when possible; earlier for festivals",
    "Kathmandu–Janakpur transport available as a separate add-on",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Kathmandu–Janakpur flights / road transfer",
      description: "Return flights or private vehicle from Kathmandu on request.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Overnight hotel in Janakpur",
      description: "Buffer night before or after the city tour.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Festival-focused itinerary",
      description: "Timing adjusted for Vivah Panchami, Ram Navami, or Chhath.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Professional guide for the full-day Janakpur city tour",
    "Local transportation between main sites in Janakpur",
    "Temple entry fees / donations as listed",
    "Bottled water during the tour",
    "Lunch as listed (local / Mithila options)",
    "Assistance with photography guidance and temple etiquette",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Travel to/from Janakpur (flight, bus, or train) unless added",
    "Accommodation in Janakpur",
    "Personal snacks, drinks, and souvenirs beyond inclusions",
    "Optional activities outside the standard itinerary",
    "Tips for guide and driver",
    "Travel insurance and personal medical expenses",
    "Anything not listed under inclusions",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1566552881560-0be862a7c445"),
      caption: "Temple courtyards and pilgrimage atmospheres",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1548013146-72479768bada"),
      caption: "Nepal heritage day touring",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1605640840605-14ac1853827d"),
      caption: "Pagoda and marble sacred architecture",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1587474260584-136574528ed5"),
      caption: "City culture and local street life",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "October–March is most comfortable (about 15–25°C). Summers can exceed 32°C. Festival seasons (Vivah Panchami, Ram Navami, Chhath) are especially memorable.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & difficulty",
      body: "Janakpur sits on the Terai plains (~70–100 m). Easy urban sightseeing lasting about 6–8 hours — no trekking required.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Getting there",
      body: "Fly Kathmandu–Janakpur (~30–40 min) or travel by road/bus. This package covers the in-city day tour; KTM transfers are optional add-ons.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Routes",
      body: "Hotel/airport meet → Janaki Mandir → Ram Mandir → Dhanush Sagar → lunch → Vivah Mandap → optional Mahadev/markets → drop.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "What to bring",
  equipmentIntro:
    "Travel light for an urban pilgrimage day. Your guide handles pacing and temple etiquette tips.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Modest day clothes (shoulders and knees covered)",
        "Light breathable fabrics for Terai heat",
        "Optional scarf for temple visits",
        "Sun hat or cap",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & bag",
      items: [
        "Comfortable shoes easy to remove at temples",
        "Small daypack or crossbody bag",
        "Reusable water bottle (bottled water also provided as listed)",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Sun & personal",
      items: [
        "Sunglasses and high-SPF sunscreen",
        "Personal medications",
        "Camera or phone",
        "Small NPR cash for sweets and souvenirs",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport or ID",
        "Summit Seek booking confirmation",
        "Flight/bus details if arriving same day",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Licensed local guide and in-city vehicle",
    "Temple fee handling as listed",
    "Lunch arrangement as listed",
    "Optional Kathmandu–Janakpur logistics on request",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What attractions are covered?",
      answer:
        "Typically Janaki Mandir, Ram Mandir, Dhanush Sagar, Ram–Sita Vivah Mandap, plus optional Kailashnath Mahadev or Mithila markets — key Ramayana and Mithila sites in Janakpur.",
      visible: true,
    },
    {
      id: "q2",
      question: "How long does the tour take?",
      answer:
        "About 6–8 hours of full-day sightseeing, usually roughly 8:00 a.m. to 5:00 p.m., depending on pace and traffic.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This listing starts at US$60 for 2–3 pax (US$70 for 1; US$55 for 4–6; US$50 for 7+), matching our featured Nepal Tours pricing.",
      visible: true,
    },
    {
      id: "q4",
      question: "Is travel from Kathmandu included?",
      answer:
        "No — the base package is the Janakpur city day tour. Kathmandu–Janakpur flights or road transfers can be added on request.",
      visible: true,
    },
    {
      id: "q5",
      question: "Are meals included?",
      answer:
        "Lunch is included as listed. Extra snacks and drinks are on your own. Special diet notes welcome when you book.",
      visible: true,
    },
    {
      id: "q6",
      question: "Is it suitable for families and seniors?",
      answer:
        "Yes — sites are mostly accessible without long walks. Tell us about mobility needs so we can pace temple stops comfortably.",
      visible: true,
    },
    {
      id: "q7",
      question: "When is the best time to visit?",
      answer:
        "October–March for comfortable weather. Vivah Panchami, Ram Navami, and Chhath Puja offer special cultural energy — book early.",
      visible: true,
    },
    {
      id: "q8",
      question: "What should I wear?",
      answer:
        "Modest clothing for temples (cover shoulders and knees), comfortable removable shoes, and sun protection for the Terai heat.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Janakpur?",
  ctaBody: `Tell us your preferred date, arrival plan, and group size — we will confirm the day tour and any Kathmandu–Janakpur logistics. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Janakpur City Tour 1 Day | Summit Seek",
  metaDescription:
    "Book 1-day Janakpur City Tour — Janaki Mandir, Ram Mandir, Dhanush Sagar, Vivah Mandap, guide, local transport & group rates from US$50.",
};
