import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_KANCHENJUNGA_NORTH: TrekPageContent = {
  coverImageUrl: img("photo-1486870591958-9b9d0d1dda99", 2000),
  coverTitle: "Kanchenjunga North Base Camp Trek - 18 Days",
  coverSubtitle:
    "Remote far-eastern Himalaya trek to Pangpema (5,143 m) — north base of the world’s third-highest peak — via Ghunsa, Khambachen, and Kanchenjunga Glacier moraine.",
  heroMainImageUrl: img("photo-1486870591958-9b9d0d1dda99", 2000),
  heroSideImage1Url: img("photo-1464822759023-fed622ff2c3b", 900),
  heroSideImage2Url: img("photo-1506905925346-21bda4d32df4", 900),
  breadcrumbLabel: "Kanchenjunga Region · North Base Camp",
  title: "Kanchenjunga North Base Camp Trek - 18 Days",
  regionLabel: "Kanchenjunga Region",
  rating: 5,
  reviewCount: 8,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 2190,
  compareAtPrice: 2490,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "12% OFF",
  shortTripBadge: "Restricted Area",
  durationLabel: "18 Days",
  difficultyLabel: "Strenuous",
  groupSizeLabel: "2+",
  bookingNote:
    "Private and small-group departures. Package includes Kathmandu hotel (BB as listed), Kathmandu–Bhadrapur flights, jeep transfers via Taplejung–Sekathum and return, licensed guide, porter (2:1), trek meals, teahouse lodging, Kanchenjunga restricted & KCAP permits. Minimum typically 2 trekkers with a licensed guide (mandatory in the restricted area).",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "2 pax", price: 2390, visible: true },
    { id: "gd2", paxLabel: "3-5 pax", price: 2190, visible: true },
    { id: "gd3", paxLabel: "6-10 pax", price: 2050, visible: true },
    { id: "gd4", paxLabel: "11-15 pax", price: 1890, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "18 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Strenuous", visible: true },
    { id: "f3", label: "Max Altitude", value: "5,143 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Kanchenjunga / Far East", visible: true },
    { id: "f6", label: "Group Size", value: "2 onwards", visible: true },
    { id: "f7", label: "Activities", value: "Trekking", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Oct–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The Kanchenjunga North Base Camp Trek is a spectacular off-the-beaten-path journey through some of Nepal’s most remote landscapes to Pangpema (~5,143 m), the north base of Mt. Kanchenjunga — the world’s third-highest peak. You pass subtropical valleys, rhododendron and pine forest, Tibetan-influenced villages, then high pastures and Kanchenjunga Glacier moraine.\n\nOpened to trekkers in 1988 and still lightly travelled, the route sits inside the Kanchenjunga Conservation Area and the Sacred Himalayan Landscape. Wildlife may include red panda, snow leopard, and Himalayan birds. Stops at Ghunsa and Khambachen (4,050 m) build acclimatization before the big day to North Base Camp.\n\nThis is a restricted area — a licensed guide and typically a minimum of two trekkers are required. Infrastructure is basic compared with Everest or Annapurna, so the trek suits experienced, fit walkers. Summit Seek includes flights and jeep transfers as listed, permits, guide, porter, meals, and clear group pricing. Prefer both base camps? See our 22-day Kanchenjunga Circuit.",
  overviewImageUrl: img("photo-1464822759023-fed622ff2c3b"),
  highlightsHeading: "Highlights",
  highlights: [
    "Pangpema / Kanchenjunga North Base Camp at ~5,143 m",
    "Views of Kanchenjunga, Yalung Kang, Jannu, and surrounding giants",
    "Empty restricted-area trails far from mainstream routes",
    "Kanchenjunga Conservation Area flora and wildlife",
    "Tibetan Buddhist villages, gompas, and ancient culture",
    "Subtropical forest to high glacier moraine in one journey",
    "Acclimatization days at Ghunsa and Khambachen",
    "Tea gardens en route via Fikkal / Kanyam",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport transfers on tourist vehicle as listed",
    "Kathmandu hotel nights with breakfast as listed",
    "Kathmandu–Bhadrapur flights and return as listed",
    "Jeep / bus transfers Bhadrapur–Taplejung–Sekathum and return",
    "Teahouse lodging and trek meals (B-L-D on trail days)",
    "English-speaking licensed local guide (first-aid trained)",
    "Porter support (max ~20 kg; one between two persons)",
    "Kanchenjunga RAP, KCAP permits; staff insurance; achievement certificate",
  ],
  whyHeading: "Why choose North Base Camp?",
  whyPoints: [
    "Focus on the more dramatic north-side approaches and panoramas",
    "Shorter than the full circuit — 18 days vs 22",
    "Two built-in acclimatization days for safer high camping",
    "True wilderness with almost no crowd even in peak season",
    "Ideal for experienced trekkers seeking challenge beyond EBC",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "No — this is a strenuous trek recommended for experienced hikers with strong fitness. Expect 5–8 hour days, landslide and moraine sections, cold nights, and a long out-and-back to 5,143 m.\n\nA licensed guide is legally required. Travel insurance covering high-altitude helicopter evacuation is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train 6+ weeks with long hikes, stairs, and cardio",
    "Prior multi-day Himalayan trek experience strongly advised",
    "Break in waterproof boots; pack for below-freezing nights",
    "Carry snacks, purification, and a solid personal first-aid kit",
    "Buy insurance covering remote Himalayan helicopter evacuation",
    "Arrive Kathmandu with buffer days for flights and permits",
  ],
  itineraryHeading: "18-day itinerary",
  itineraryIntro:
    "Flight and walking times are estimates and vary with weather — Bhadrapur flights and long jeep roads can delay. Lodge stops may change with availability. Your Summit Seek guide can adjust for acclimatization and safety.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,400 m",
      meals: "—",
      accommodation: "Hotel in Kathmandu",
      description:
        "Airport meet-and-greet and hotel transfer. Free time in Thamel. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Fly Kathmandu – Bhadrapur – drive to Fikkal / Kanyam",
      maxAltitude: "1,500 m",
      meals: "Breakfast",
      accommodation: "Hotel / Lodge",
      description:
        "Morning flight to Bhadrapur (~40–45 min), then drive through tea gardens to Fikkal or Kanyam (~4 hours). Overnight near the tea estates.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Drive Fikkal / Kanyam – Taplejung",
      maxAltitude: "1,800 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge / Teahouse",
      description:
        "Scenic jeep day (~6–7 hours, ~186 km) to Taplejung, gateway to the Kanchenjunga region. Gear check. Overnight in Taplejung.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Drive Taplejung – Sekathum",
      maxAltitude: "1,650 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Jeep ~5–6 hours (~39 km) along the Tamor, with KCAP checkpoint. Overnight in Sekathum — trek start.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Trek Sekathum – Amjilosa",
      maxAltitude: "2,308 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "First walking day across Ghunsa Khola suspension bridges and a steep climb to Amjilosa (~5–6 hours / ~9 km).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Trek Amjilosa – Gyabla",
      maxAltitude: "2,730 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Waterfalls, oak and rhododendron forest, and meadows with grazing yaks (~5–6 hours / ~8 km). Overnight in Gyabla.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Trek Gyabla – Ghunsa",
      maxAltitude: "3,595 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Via Phole to Ghunsa, the largest village with health post and conservation office (~5 hours / ~10.7 km). Overnight in Ghunsa.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Acclimatization day at Ghunsa",
      maxAltitude: "3,595 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Rest day with optional hike to a Jannu viewpoint, Dudh Kunda, or local gompa (~5 hours round-trip options).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Trek Ghunsa – Khambachen",
      maxAltitude: "4,050 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Uphill along Ghunsa Khola through forest, mani walls, streams, and moraine (~5–6 hours / ~11.2 km). Views of Jannu and Phole Peak. Overnight in Khambachen.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Acclimatization day at Khambachen",
      maxAltitude: "4,050 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Second rest day — ridge hike behind the village or optional approach toward Jannu Base Camp via Phaktalung Temple.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Trek Khambachen – Lhonak",
      maxAltitude: "4,780 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Via Ramtang across Kanchenjunga Glacier approaches with views of Mera, Gimmigela, Wedge Peak (~4–5 hours / ~9.6 km). Overnight in Lhonak.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Day hike Pangpema / North Base Camp – return Lhonak",
      maxAltitude: "5,143 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Big day to Pangpema / Kanchenjunga North Base Camp (~5,143 m) and back (~7–8 hours / ~16.5 km). Packed lunch; no lodges at camp. Overnight in Lhonak.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Trek Lhonak – Ghunsa",
      maxAltitude: "3,595 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Long descent via Khambachen to Ghunsa (~7 hours / ~21.6 km). Overnight in Ghunsa.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Trek Ghunsa – Amjilosa",
      maxAltitude: "2,308 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Forest, pastures, and steep ups and downs (~7–8 hours). Overnight in Amjilosa (known for local honey).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d15",
      dayLabel: "Day 15",
      title: "Trek Amjilosa – Sekathum – drive Taplejung",
      maxAltitude: "1,820 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Final trek to Sekathum (~5 hours), then jeep to Taplejung (~3 hours). Overnight in Taplejung.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d16",
      dayLabel: "Day 16",
      title: "Drive Taplejung – Bhadrapur",
      maxAltitude: "91 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge / Hotel",
      description:
        "Long foothill drive to Bhadrapur (~10–11 hours / ~243 km). Overnight in Bhadrapur.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d17",
      dayLabel: "Day 17",
      title: "Fly Bhadrapur – Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast, Dinner",
      accommodation: "Hotel in Kathmandu",
      description:
        "Morning scenic flight to Kathmandu (~40 min). Free afternoon; farewell dinner. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d18",
      dayLabel: "Day 18",
      title: "Departure from Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "—",
      description:
        "Airport transfer for your international flight. End of the Kanchenjunga North Base Camp journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best in March–May and October–November for stable weather and clear views. Private groups of 2+ are welcome. Build buffer days for Bhadrapur flights and long road transfers.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Licensed guide and restricted-area permits mandatory (min. 2 trekkers)",
    "Porter included typically 2 clients : 1 porter",
    "Bhadrapur flights and jeep roads are weather/road-dependent — allow buffers",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Extra Kathmandu nights",
      description: "Buffer nights for flight delays or early arrivals.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Circuit extension",
      description: "Add south base camp / Yalung side for a longer circuit.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Gear rental",
      description: "Sleeping bag, down jacket, and poles as needed.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "International and domestic airport transfers as listed",
    "Kathmandu hotel accommodation with breakfast as listed",
    "All necessary Kanchenjunga trekking permits (RAP & KCAP)",
    "Teahouse lodging (sharing) and breakfast, lunch, dinner on trek days",
    "Licensed English-speaking local guide and porter (2:1, max ~20 kg)",
    "Kathmandu–Bhadrapur–Kathmandu flights",
    "Bhadrapur–Taplejung–Sekathum and return jeep / bus transfers",
    "Staff insurance, meals, and equipment; taxes; achievement certificate",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "International airfare and airport departure taxes",
    "Nepal entry visa fees",
    "Lunch and dinner in Kathmandu (except farewell dinner as listed)",
    "Travel insurance with high-altitude emergency evacuation",
    "Personal trekking gear and equipment",
    "Hot showers, charging, Wi-Fi, and drinks on trek",
    "Tips for guide, porter, and drivers",
    "Extra accommodation and meals outside the itinerary",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "High ridges toward the Kanchenjunga massif",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Alpine approaches on the north base camp route",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Remote eastern Himalaya valleys",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Wilderness trails in the conservation area",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May and October–November offer the most stable weather and clearest mountain views. Trails stay quiet even in peak season.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & permits",
      body: "Highest point is Pangpema / North Base Camp (~5,143 m). You need KCAP (NRs 2,000 pp) and Restricted Area Permit (about USD 20 pp/week for the first weeks), plus a licensed guide. Summit Seek arranges these.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Strenuous — harder than classic EBC for most people. Roughly 175 km total with long days, landslide zones, and glacier approaches. Strong fitness and prior trek experience required.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Lodging & food",
      body: "Simple teahouses. Hot shower, charging, and Wi-Fi cost extra and may be limited. Meals are basic (dal bhat, thukpa; limited menus). Pack snacks. No ATMs on the trail — withdraw cash in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "This remote route has limited shops — pack thoroughly. Porters carry main bags; keep water, layers, documents, snacks, and camera in a daypack.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece mid-layer",
        "Down / insulated jacket",
        "Waterproof shell jacket and pants",
        "Trekking pants and warm socks",
        "Warm hat, sun hat, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Camp shoes",
        "Trekking poles",
        "Duffel + 25–35L daypack",
        "Sleeping bag (cold high camps)",
        "Headlamp + spare batteries / power bank",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "SPF sunscreen, lip balm, UV sunglasses",
        "Personal first-aid kit & blister care",
        "Water bottle + purification",
        "Trail snacks and energy bars",
        "Hand sanitizer & toilet paper",
        "Nepali SIM / offline maps as backup",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies + passport photos",
        "Nepal visa as applicable",
        "Travel insurance details (heli evacuation)",
        "Cash for personal trail extras",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Permit processing and licensed guiding team",
    "Staff insurance and logistics coordination",
    "Achievement certificate on request",
    "Advice on circuit extensions and flight buffers",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What permits are required?",
      answer:
        "Kanchenjunga Restricted Area Permit and KCAP entry permit. Typically at least two trekkers with a licensed guide. Summit Seek handles the paperwork.",
      visible: true,
    },
    {
      id: "q2",
      question: "How long is the trek?",
      answer:
        "This Summit Seek itinerary is 18 days. Similar north-base packages often run 18–22 days.",
      visible: true,
    },
    {
      id: "q3",
      question: "Is it harder than Everest Base Camp?",
      answer:
        "Yes for most trekkers — more remote, fewer facilities, tougher terrain, and a higher commitment. Not ideal for first-time Himalayan trekkers.",
      visible: true,
    },
    {
      id: "q4",
      question: "How much does it cost?",
      answer:
        "This listing starts at US$2,190 for 3–5 pax (US$2,390 for 2; US$2,050 for 6–10; US$1,890 for 11–15).",
      visible: true,
    },
    {
      id: "q5",
      question: "What is the maximum altitude?",
      answer:
        "About 5,143 m at Pangpema / Kanchenjunga North Base Camp, with overnight back in Lhonak (4,780 m).",
      visible: true,
    },
    {
      id: "q6",
      question: "Can I trek alone?",
      answer:
        "No. Foreigners must trek with a registered company and licensed guide; typically a minimum of two trekkers.",
      visible: true,
    },
    {
      id: "q7",
      question: "Is travel insurance necessary?",
      answer:
        "Yes — covering high-altitude emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q8",
      question: "When is the best time to go?",
      answer:
        "March–May and October–November usually offer the best weather and views.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Kanchenjunga North Base Camp?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Kanchenjunga North Base Camp Trek 18 Days | Summit Seek",
  metaDescription:
    "Book the 18-day Kanchenjunga North Base Camp trek with Summit Seek — Pangpema 5,143 m, permits, flights, guide, porter, meals & group discounts from US$1,890.",
};
