import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_KANCHENJUNGA_BC: TrekPageContent = {
  coverImageUrl: img("photo-1506905925346-21bda4d32df4", 2000),
  coverTitle: "Kanchenjunga Base Camp Trek - 22 Days",
  coverSubtitle:
    "Classic far-eastern Himalaya journey to Yalung / Oktang South Base Camp and Pangpema North Base Camp (5,143 m) — Mirgin La & Sele La passes, Rai–Limbu culture, and empty trails.",
  heroMainImageUrl: img("photo-1506905925346-21bda4d32df4", 2000),
  heroSideImage1Url: img("photo-1464822759023-fed622ff2c3b", 900),
  heroSideImage2Url: img("photo-1486870591958-9b9d0d1dda99", 900),
  breadcrumbLabel: "Kanchenjunga Region · Base Camp",
  title: "Kanchenjunga Base Camp Trek - 22 Days",
  regionLabel: "Kanchenjunga Region",
  rating: 5,
  reviewCount: 9,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 2590,
  compareAtPrice: 2990,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "13% OFF",
  shortTripBadge: "Restricted Area",
  durationLabel: "22 Days",
  difficultyLabel: "Difficult",
  groupSizeLabel: "2+",
  bookingNote:
    "Private and small-group departures. Package includes trek lodges and meals (B-L-D as listed), Kathmandu–Bhadrapur flights, overland transfers as listed, licensed guide, porter (2:1), Kanchenjunga RAP & KCAP permits. Kathmandu hotels are typically extra unless added. Arrive Kathmandu the day before Day 1. Minimum typically 2 trekkers with a licensed guide (mandatory in the restricted area).",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "2 pax", price: 2850, visible: true },
    { id: "gd2", paxLabel: "3-5 pax", price: 2590, visible: true },
    { id: "gd3", paxLabel: "6-10 pax", price: 2390, visible: true },
    { id: "gd4", paxLabel: "11-15 pax", price: 2190, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "22 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Difficult", visible: true },
    { id: "f3", label: "Max Altitude", value: "5,143 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Kanchenjunga / Taplejung", visible: true },
    { id: "f6", label: "Group Size", value: "2 onwards", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Culture", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The Kanchenjunga Base Camp Trek is one of Nepal’s most challenging and least-crowded long treks — a 22-day journey through Rai, Limbu, Gurung, and Sherpa country to both the south (Yalung / Oktang) and north (Pangpema, ~5,143 m) approaches of Mt. Kanchenjunga, the world’s third-highest peak.\n\nThis itinerary flies Kathmandu–Bhadrapur and drives via Ilam tea country to Taplejung, then walks the Limbu Cultural Trail toward Cheram / Tseram for acclimatization and a Yalung Base Camp day. You cross four high passes (including Mirgin La ~4,480 m and Sele La) to Ghunsa, continue to Kambachen and Lhonak, and day-hike Kanchenjunga North Base Camp / Pangpema before descending via Gyabla, Amjilosa, and Sekathum.\n\nExpect mountain panoramas that can include Kanchenjunga, Jannu, and on clear days even Everest, Lhotse, and Makalu. Special permits (KCAP and RAP) and a licensed guide are required. Summit Seek includes flights and overland transfers as listed, permits, guide, porter, trek meals, and clear group pricing. Prefer a shorter focus? See our 18-day North or 17-day South packages.",
  overviewImageUrl: img("photo-1464822759023-fed622ff2c3b"),
  highlightsHeading: "Highlights",
  highlights: [
    "Yalung / Oktang South Base Camp and Pangpema North Base Camp (5,143 m)",
    "Cross Sinelapche, Mirgin La, Sinion La, and Sele La passes",
    "Kanchenjunga Conservation Area flora and fauna",
    "Rai, Limbu, Sherpa culture and local cuisine",
    "Views of Kanchenjunga, Jannu, Kabru, Rathong, Kokthang — and distant giants on clear days",
    "Limbu Cultural Trail and Ilam tea country approaches",
    "Acclimatization at Cheram and Kambachen side trips",
    "Empty trails compared with Everest and Annapurna",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Kathmandu–Bhadrapur flights and return as listed",
    "Overland jeep transfers as listed (Taplejung corridor)",
    "Lodge / teahouse lodging on twin-share basis during the trek",
    "Breakfast, lunch, and dinner on trek days as listed",
    "Licensed English-speaking guide (first-aid trained)",
    "Porter support (typically 1 porter for 2 trekkers)",
    "Kanchenjunga RAP and KCAP permits; daily oxygen checks as arranged",
    "Trekking map, water purification, first aid, completion certificate",
  ],
  whyHeading: "Why choose this Base Camp trek?",
  whyPoints: [
    "Both south (Yalung) and north (Pangpema) base camps in one journey",
    "Four-pass day linking the Yalung and Ghunsa corridors",
    "Deeper culture time on the Limbu Cultural Trail",
    "Built-in acclimatization and viewpoint excursions",
    "Ideal for fit trekkers with 20+ days who want the full Kanchenjunga story",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "No — graded difficult. You hike often 5–8 hours, cross high passes near 4,500–4,650 m, and reach 5,143 m at North Base Camp. Weather can change fast; altitude sickness is a real risk.\n\nStrong fitness, prior multi-day trek experience, and solid mental preparation are essential. A licensed guide is legally required. Travel insurance covering helicopter evacuation above 5,000 m is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train at least 4–6 weeks: long walks, stairs, cardio, and stamina",
    "Prior Himalayan trek experience strongly advised",
    "Break in boots; pack for nights around -10°C at high camps",
    "Carry purification, snacks, and a personal first-aid kit",
    "Buy insurance covering remote Himalayan helicopter evacuation",
    "Arrive Kathmandu before Day 1 for rest, briefing, and permits",
  ],
  itineraryHeading: "22-day itinerary",
  itineraryIntro:
    "Based on the classic Kanchenjunga Base Camp routing (south Yalung side first, then north via Sele La). Flight and walking times vary with weather — Bhadrapur flights and jeep roads can delay. Lodge names are indicative. Arrive Kathmandu the day before Day 1.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Fly Kathmandu – Bhadrapur – drive to Taplejung",
      maxAltitude: "1,441 m",
      meals: "Lunch, Dinner",
      accommodation: "Lodge in Taplejung",
      description:
        "Morning flight to Bhadrapur, then ~6–7 hour drive via Ilam tea plantations to Taplejung (Limbu gateway town). Overnight in Taplejung.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Drive Taplejung – Ranipul",
      maxAltitude: "2,265 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge in Ranipul",
      description:
        "Local jeep toward Ranipul (~4 hours / ~60 km) past grasslands and grazing herds. Afternoon rest or short exploration. Overnight in Ranipul.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Trek Ranipul – Kengsra",
      maxAltitude: "2,120 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge in Kengsra",
      description:
        "Down along the Phawa River, cross a large suspension bridge to Kunjuri, then ridges and rocky paths to Kengsra (~5 hours / ~15 km). Distant Kanchenjunga views may appear.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Trek Kengsra – Torangden (Limbu Cultural Trail)",
      maxAltitude: "1,785 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge in Torangden",
      description:
        "Hillsides above the Kabeli Khola via Anpan and Kashawa Khola to the Limbu settlement of Torangden / Tortong (~5 hours / ~14 km).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Trek Torangden – Cheram (Tseram)",
      maxAltitude: "3,870 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge in Cheram",
      description:
        "Ascend along Simbuwa Khola through rhododendron, pine, juniper, and oak into Lalung Valley with Yalung Glacier and Tuplung Peak views (~5 hours / ~14 km). Overnight in Cheram.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Acclimatization day at Cheram",
      maxAltitude: "3,870 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge in Cheram",
      description:
        "Rest and short excursions (~2 hours optional). Explore village life of Limbu and Rai (Kirat) communities while adapting to altitude.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Trek Cheram – Ramche / Ramchaur",
      maxAltitude: "4,580 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge in Ramche",
      description:
        "Climb through rhododendron and juniper with views of Kabru, Rathong, and Kokthang to the stone lodges of Ramche / Ramchaur (~5 hours / ~12 km).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Day hike Yalung / Oktang Base Camp – return Cheram",
      maxAltitude: "4,730 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge in Cheram",
      description:
        "Visit Oktang Monastery and Yalung Base Camp for Jannu Himal and glacier panoramas (~6 hours / ~19 km). Retrace to Cheram for the night.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Trek Cheram – Sele La (four passes)",
      maxAltitude: "4,645 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge near Sele La",
      description:
        "Big pass day: Sinelapche Bhanjyang (~4,645 m), Mirgin La (~4,480 m), Sinion La, then Sele La (~4,290 m camp area) (~6 hours / ~14 km).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Trek Sele La – Ghunsa",
      maxAltitude: "3,595 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge in Ghunsa",
      description:
        "Descend through rhododendron and pine past chortens and prayer flags to rock-and-pine houses of Ghunsa (~5 hours / ~14 km).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Trek Ghunsa – Kambachen",
      maxAltitude: "4,050 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge in Kambachen",
      description:
        "North corridor via wildflowers, rhododendron, and Rampuk Kharkha bridge with waterfall and Jannu views (~5 hours / ~12 km).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Acclimatization — Jannu / Kumbhakarna viewpoint",
      maxAltitude: "4,050 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge in Kambachen",
      description:
        "Day excursion toward Mt. Jannu (Kumbhakarna) viewpoints (~5 hours round trip). Overnight again in Kambachen.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Trek Kambachen – Lhonak",
      maxAltitude: "4,780 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge in Lhonak",
      description:
        "Icy, rocky, and riverside trail with suspension bridges to simple Lhonak (~6 hours / ~14 km). Overnight in Lhonak.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Day hike Pangpema / Kanchenjunga North BC – return Lhonak",
      maxAltitude: "5,143 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge in Lhonak",
      description:
        "Push to Kanchenjunga Base Camp / Pangpema (~5,143 m) for the north face of Kanchenjunga (8,586 m) (~4–6 hours / ~10 km). Windy; overnight back in Lhonak.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d15",
      dayLabel: "Day 15",
      title: "Trek Lhonak – Ghunsa",
      maxAltitude: "3,595 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge in Ghunsa",
      description:
        "Retrace via Kambachen lunch stop and forested descent to Ghunsa (~6 hours / ~15 km).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d16",
      dayLabel: "Day 16",
      title: "Trek Ghunsa – Gyabla",
      maxAltitude: "2,800 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge in Gyabla",
      description:
        "Downhill through streams and Limbu settlements to Gyabla / Gyapla (~5 hours / ~13 km).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d17",
      dayLabel: "Day 17",
      title: "Trek Gyabla – Amjilosa",
      maxAltitude: "2,308 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge in Amjilosa",
      description:
        "Warmer descent via Phale, monasteries, Chhundarangka Khola bridge, waterfalls, and chortens (~5 hours / ~14 km).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d18",
      dayLabel: "Day 18",
      title: "Trek Amjilosa – Sekathum",
      maxAltitude: "1,650 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge in Sekathum",
      description:
        "Along Ghunsa River and Solima pastures, farmland, and cardamom toward the conservation-area exit at Sekathum (~6 hours / ~14 km).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d19",
      dayLabel: "Day 19",
      title: "Trek Sekathum – Tapethok",
      maxAltitude: "1,322 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge in Tapethok",
      description:
        "Continue downhill to Tapethok (~5 hours / ~14 km). Overnight in Tapethok.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d20",
      dayLabel: "Day 20",
      title: "Drive Tapethok – Taplejung",
      maxAltitude: "1,820 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge in Taplejung",
      description:
        "Local jeep back to Taplejung (~4 hours / ~40 km). Afternoon rest. Overnight in Taplejung.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d21",
      dayLabel: "Day 21",
      title: "Drive Taplejung – Bhadrapur / Birtamod",
      maxAltitude: "91 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Hotel in Bhadrapur",
      description:
        "Long drive (~7 hours / ~180 km) with optional Ilam tea-stop. Overnight in Bhadrapur or Birtamod.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d22",
      dayLabel: "Day 22",
      title: "Fly Bhadrapur – Kathmandu",
      maxAltitude: "1,330 m",
      meals: "Breakfast",
      accommodation: "—",
      description:
        "Morning flight to Kathmandu (~45–60 min). End of the Kanchenjunga Base Camp trek with Summit Seek — hotel transfer or onward international departure as arranged.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best in September–November and March–May for clear skies and milder temperatures. Private groups of 2+ are welcome. Build buffer days for Bhadrapur flights and long road transfers.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Licensed guide and restricted-area permits mandatory (min. 2 trekkers)",
    "Porter included typically 2 clients : 1 porter",
    "Arrive Kathmandu before Day 1; Bhadrapur flights are weather-dependent",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Kathmandu hotel nights",
      description: "Pre/post trek nights with breakfast on request.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Gear rental",
      description: "Sleeping bag, down jacket, poles, or spikes as needed.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Personal porter",
      description: "Dedicated porter for lighter daypacks on long days.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a4",
      title: "Kathmandu city tour / extras",
      description: "Heritage tour, spa, or scenic mountain flight on request.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport assistance as arranged for the trek package",
    "All meals during the trek (breakfast, lunch, dinner)",
    "Lodge accommodation (twin share) during the trek",
    "Licensed English-speaking trekking guide",
    "Porter (typically 1 for 2 trekkers)",
    "Kanchenjunga RAP and KCAP permits",
    "Kathmandu–Bhadrapur–Kathmandu flights",
    "Overland transportation as listed; staff costs; taxes; map; first aid; certificate",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Kathmandu hotel accommodation and city meals (unless add-on)",
    "International airfare and Nepal tourist visa",
    "Travel insurance (mandatory — helicopter evacuation)",
    "Drinks, boiled water, hot shower, charging, laundry, desserts",
    "Tips for guide and porters",
    "Personal gear and expenses outside the itinerary",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "High eastern Himalaya light toward Kanchenjunga",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Alpine approaches on the base camp route",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "Remote ridges and glacial valleys",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Wilderness trails in the conservation area",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "Autumn (Sep–Nov) and spring (Mar–May) offer the clearest views and best trail conditions. Winter and monsoon are harder (cold, snow, or slippery paths).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & permits",
      body: "Highest point is Pangpema / North Base Camp (~5,143 m). You need TIMS (as applicable), KCAP, and Kanchenjunga Restricted Area Permit, plus a licensed guide. Summit Seek arranges these.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Difficult — long trek, high passes, 5,000 m+ day, and remote lodges. Strong fitness and prior experience required. Acclimatization days are built in.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Lodging & food",
      body: "Simple teahouses/lodges. Dal bhat is the staple; noodles, soups, momo, and eggs appear where menus allow. Hot shower and charging cost extra. Carry snacks and purification.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "This remote route has limited shops and weak power — pack thoroughly. Porters carry main bags; keep water, layers, documents, snacks, and camera in a daypack. A solar charger helps.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece mid-layer",
        "Down / insulated jacket",
        "Waterproof shell jacket and pants",
        "Trekking pants and warm socks",
        "Warm hat, sun hat, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Camp shoes",
        "Trekking poles",
        "Duffel + 25–35L daypack",
        "Sleeping bag (cold high camps)",
        "Headlamp + power bank / solar charger",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "SPF sunscreen, lip balm, UV sunglasses",
        "Personal first-aid kit & blister care",
        "Water bottle + purification",
        "Trail snacks and energy bars",
        "Toilet paper & hand sanitizer",
        "Adapter for Type D plugs if needed",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies + passport photos",
        "Nepal visa as applicable",
        "Travel insurance details (heli evacuation)",
        "Flight details for domestic connections",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Permit processing and licensed guiding team",
    "Daily oxygen saturation checks as arranged",
    "Water purification support and trek map",
    "Advice on Kathmandu hotel add-ons and buffers",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Kanchenjunga Base Camp trek?",
      answer:
        "A 22-day restricted-area trek visiting both Yalung/Oktang (south) and Pangpema (north, ~5,143 m) approaches of Mt. Kanchenjunga, with high passes between Cheram and Ghunsa.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Difficult. Expect long days, four-pass crossings, and a 5,143 m base-camp day. Best for experienced, fit trekkers — not a beginner trek.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This listing starts at US$2,590 for 3–5 pax (US$2,850 for 2; US$2,390 for 6–10; US$2,190 for 11–15). Kathmandu hotels are usually add-ons.",
      visible: true,
    },
    {
      id: "q4",
      question: "What permits are required?",
      answer:
        "Kanchenjunga Restricted Area Permit, KCAP entry, and TIMS as applicable, plus a licensed guide. Summit Seek arranges these.",
      visible: true,
    },
    {
      id: "q5",
      question: "How long do we hike each day?",
      answer:
        "Typically about 4–6 hours (sometimes longer), covering roughly 10–15 km depending on terrain and altitude.",
      visible: true,
    },
    {
      id: "q6",
      question: "How is drinking water managed?",
      answer:
        "Carry bottles and use boiled, filtered, or purified water (chlorine/iodine). Avoid untreated stream water.",
      visible: true,
    },
    {
      id: "q7",
      question: "Is travel insurance necessary?",
      answer:
        "Yes — covering injuries, medical costs, and helicopter rescue/evacuation above 5,000 m. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q8",
      question: "When is the best time to go?",
      answer:
        "September–November and March–May usually offer the best weather and views.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Kanchenjunga Base Camp?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Kanchenjunga Base Camp Trek 22 Days | Summit Seek",
  metaDescription:
    "Book the 22-day Kanchenjunga Base Camp trek with Summit Seek — Yalung & Pangpema 5,143 m, permits, flights, guide, porter, meals & group discounts from US$2,190.",
};
