import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_KANCHENJUNGA_CIRCUIT: TrekPageContent = {
  coverImageUrl: img("photo-1464822759023-fed622ff2c3b", 2000),
  coverTitle: "Kanchenjunga Circuit Trek - 22 Days",
  coverSubtitle:
    "Remote eastern Himalaya circuit to the north and south base camps of Mt. Kanchenjunga — third-highest peak on Earth — with high passes, Yalung Glacier views, and empty trails.",
  heroMainImageUrl: img("photo-1464822759023-fed622ff2c3b", 2000),
  heroSideImage1Url: img("photo-1486870591958-9b9d0d1dda99", 900),
  heroSideImage2Url: img("photo-1506905925346-21bda4d32df4", 900),
  breadcrumbLabel: "Kanchenjunga Region · Circuit",
  title: "Kanchenjunga Circuit Trek - 22 Days",
  regionLabel: "Kanchenjunga Region",
  rating: 5,
  reviewCount: 11,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 2790,
  compareAtPrice: 3190,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "13% OFF",
  shortTripBadge: "Restricted Area",
  durationLabel: "22 Days",
  difficultyLabel: "Strenuous",
  groupSizeLabel: "2+",
  bookingNote:
    "Private and small-group departures. Package includes Kathmandu hotels (BB as listed), Kathmandu–Bhadrapur flights, jeep transfers Taplejung–Sekathum and Yamphudin–Bhadrapur, licensed guide, porter (2:1), trek meals, teahouse lodging, Kanchenjunga restricted & KCAP permits, and TIMS. Minimum typically 2 trekkers with a licensed guide (mandatory in the restricted area).",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "2 pax", price: 3050, visible: true },
    { id: "gd2", paxLabel: "3-5 pax", price: 2790, visible: true },
    { id: "gd3", paxLabel: "6-10 pax", price: 2590, visible: true },
    { id: "gd4", paxLabel: "11-15 pax", price: 2390, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "22 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Strenuous", visible: true },
    { id: "f3", label: "Max Altitude", value: "5,140 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Kanchenjunga / Far East", visible: true },
    { id: "f6", label: "Group Size", value: "2 onwards", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Culture", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The Kanchenjunga Circuit Trek takes you deep into the wilderness of Nepal’s far eastern Himalayas — to the north base camp (~5,140 m) and south base camp (~4,610 m / Oktang) of Mount Kanchenjunga, the world’s third-highest peak. Also known as the Kanchenjunga Base Camp trek, it suits backpackers who want empty trails beyond Everest and Annapurna.\n\nFrom Kathmandu it takes about two days (flight to Bhadrapur, then jeep via Taplejung) to reach the trailhead at Sekathum. Remoteness, advanced terrain, high altitude, and limited infrastructure keep crowds away even in peak season. You walk through the Kanchenjunga Conservation Area, meet Rai and Limbu communities, and visit ancient Ramtang and Oktang monasteries.\n\nExpect dense forest lower down, then meadows, glaciers, and barren rocky high country near the Sikkim border. Highlights include Yalung Glacier views and a big pass day (Sele Le → Tseram) crossing Sele Le, Sinion La, Mirgin La, and Sinelapcha La. This is a restricted area — special permits and a licensed guide are mandatory. Summit Seek includes flights and drives as listed, permits, guide, porter, meals, and clear group pricing.",
  overviewImageUrl: img("photo-1486870591958-9b9d0d1dda99"),
  highlightsHeading: "Highlights",
  highlights: [
    "North and south base camps of Mt. Kanchenjunga (3rd highest)",
    "Remote far-eastern Himalaya with empty peak-season trails",
    "Kanchenjunga Conservation Area biodiversity",
    "Rai & Limbu culture and mountain village life",
    "Yalung Glacier and panoramas of Tent Peak, Janu, Twins & more",
    "Four-pass day: Sele Le, Sinion La, Mirgin La, Sinelapcha La",
    "Part of the Great Himalayan Trail corridor",
    "Ancient Ramtang and Oktang monasteries",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport transfers and escort as listed",
    "Kathmandu hotel nights with breakfast as listed",
    "Kathmandu heritage sightseeing with entrance fees as listed",
    "Kathmandu–Bhadrapur flights and return as listed",
    "Jeep transfers Bhadrapur–Taplejung–Sekathum and Yamphudin–Bhadrapur",
    "Teahouse lodging and trek meals (B-L-D on trail days)",
    "English-speaking licensed local guide and porter (2:1)",
    "TIMS, KCAP, and Kanchenjunga restricted-area permits; staff insurance",
  ],
  whyHeading: "Why choose Kanchenjunga Circuit?",
  whyPoints: [
    "True wilderness — one of Nepal’s least-crowded major circuits",
    "Both north and south Kanchenjunga base camps in one journey",
    "Advanced high-pass adventure for experienced trekkers",
    "Strong culture and conservation-area biodiversity",
    "Quiet alternative to Everest and Annapurna classics",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "No — this is a strenuous, advanced trek. Expect long days (often 5–8 hours), high altitude above 5,000 m, remote infrastructure, landslide and moraine sections, and a demanding multi-pass day.\n\nStrong fitness, prior Himalayan trekking experience, and solid endurance are strongly recommended. A licensed guide is legally required. Travel insurance covering helicopter evacuation up to at least 5,000+ m is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train at least 6 weeks: long walks, day hikes, strength, and cardio",
    "Build prior multi-day trek experience before booking",
    "Break in waterproof boots; pack for -10°C nights",
    "Carry water purification, snacks, and a full personal first-aid kit",
    "Buy insurance covering remote Himalayan helicopter evacuation",
    "Arrive Kathmandu with buffer days for flights and permits",
  ],
  itineraryHeading: "22-day itinerary",
  itineraryIntro:
    "Flight and walking times are estimates and vary with weather — Bhadrapur flights and long jeep roads can delay. Lodge stops may change with availability. Your Summit Seek guide can adjust the plan for acclimatization and safety.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,330 m",
      meals: "—",
      accommodation: "Hotel in Kathmandu",
      description:
        "Airport meet-and-greet at Tribhuvan International and hotel transfer. Trek briefing after you freshen up. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Kathmandu sightseeing — Bhaktapur, Pashupatinath & Boudhanath",
      maxAltitude: "1,330 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Full-day heritage tour: Bhaktapur (Nyatapola, Palace of 55 Windows, Golden Gate), sacred Pashupatinath on the Bagmati, and Boudhanath stupa. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Fly Kathmandu – Bhadrapur – drive to Taplejung",
      maxAltitude: "1,441 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Morning flight to Bhadrapur (~45–50 min), then scenic jeep drive to Taplejung (~7–8 hours). Overnight in Taplejung.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Drive Taplejung – Sekathum",
      maxAltitude: "1,576 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Jeep via Mitlung, Chirwa, Thapethok, Lelep and checkpoint permit registration (~4–6 hours). Overnight in Sekathum — trek start.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Trek Sekathum – Amjilosa",
      maxAltitude: "2,308 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "First walking day into the Kanchenjunga Conservation Area (~4–6 hours). Overnight in Amjilosa.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Trek Amjilosa – Gyabla",
      maxAltitude: "2,730 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Continue through forested valleys and riverside trails (~5–6 hours). Overnight in Gyabla.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Trek Gyabla – Ghunsa",
      maxAltitude: "3,595 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Ascend to the Tibetan-influenced village of Ghunsa (~4–5 hours), a key logistics and culture stop. Overnight in Ghunsa.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Acclimatization day at Ghunsa",
      maxAltitude: "3,595 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Rest and optional acclimatization hike (e.g. toward Dzonga / nearby viewpoints). Overnight in Ghunsa.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Trek Ghunsa – Kambachen",
      maxAltitude: "4,050 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Higher alpine country toward Kambachen (~4–5 hours). Overnight in Kambachen.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Trek Kambachen – Lhonak",
      maxAltitude: "4,790 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Cross open high country to Lhonak (~4–6 hours), staging for north base camp. Overnight in Lhonak.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Day hike Pangpema / Kanchenjunga North BC – return Lhonak",
      maxAltitude: "5,140 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Out-and-back to Pangpema / Kanchenjunga North Base Camp (~5,140 m) with massive north-face views (~7–8 hours). Overnight back in Lhonak.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Trek Lhonak – Kambachen – Ghunsa",
      maxAltitude: "3,595 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Descend via Kambachen to Ghunsa (~7 hours) to prepare for the southern crossing. Overnight in Ghunsa.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Trek Ghunsa – Sele Le High Camp",
      maxAltitude: "4,290 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge / Camp",
      description:
        "Climb toward Sele Le High Camp (~4–5 hours) for the multi-pass crossing. Overnight at high camp.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Trek Sele Le – Tseram (four passes)",
      maxAltitude: "4,480 m+",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Big highlight day: cross Sele Le, Sinion La, Mirgin La, and Sinelapcha La toward Tseram / Cheram (~3,870 m). Long strenuous day (~7–8 hours). Overnight in Tseram.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d15",
      dayLabel: "Day 15",
      title: "Trek Tseram – Ramche",
      maxAltitude: "4,580 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Ascend the Yalung side toward Ramche with growing glacier and peak views (~4–5 hours). Overnight in Ramche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d16",
      dayLabel: "Day 16",
      title: "Day hike Oktang / South BC – return Tseram",
      maxAltitude: "4,610 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Hike to Oktang / Kanchenjunga South Base Camp area and Yalung Glacier viewpoints, then descend to Tseram (~6–7 hours). Overnight in Tseram.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d17",
      dayLabel: "Day 17",
      title: "Trek Tseram – Tortong",
      maxAltitude: "2,995 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Descend through forested country to Tortong / Torangdin (~4–6 hours). Overnight in Tortong.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d18",
      dayLabel: "Day 18",
      title: "Trek Tortong – Yamphudin",
      maxAltitude: "2,080 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Continue descending to Yamphudin (~7–8 hours), end of the walking circuit. Overnight in Yamphudin.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d19",
      dayLabel: "Day 19",
      title: "Drive Yamphudin – Bhadrapur",
      maxAltitude: "100 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Hotel in Bhadrapur",
      description:
        "Long scenic jeep day to Bhadrapur (~11–12 hours). Overnight in Bhadrapur.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d20",
      dayLabel: "Day 20",
      title: "Fly Bhadrapur – Kathmandu",
      maxAltitude: "1,330 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Morning flight to Kathmandu (~45 min). Hotel transfer. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d21",
      dayLabel: "Day 21",
      title: "Free day in Kathmandu",
      maxAltitude: "1,330 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Optional Durbar Squares, Patan, or Thamel shopping and rest. Buffer for weather delays. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d22",
      dayLabel: "Day 22",
      title: "Departure from Kathmandu",
      maxAltitude: "1,330 m",
      meals: "Breakfast",
      accommodation: "—",
      description:
        "Airport transfer for your international flight. End of the Kanchenjunga Circuit with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best in March–May and September–November when trails are stable and views are clearest. Private groups of 2+ are welcome. Build buffer days for Bhadrapur flights and long road transfers.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Licensed guide and restricted-area permits mandatory",
    "Porter included typically 2 clients : 1 porter",
    "Bhadrapur flights and jeep roads are weather/road-dependent — allow buffers",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Extra Kathmandu nights",
      description: "Buffer nights for flight delays or early arrivals.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "North-only or South-only variant",
      description: "Shorter itineraries focusing on one base camp on request.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Gear rental",
      description: "Sleeping bag, down jacket, and poles as needed.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Arrival and departure airport transfers as listed",
    "Kathmandu accommodation with breakfast as listed",
    "Kathmandu sightseeing with entrance fees as listed",
    "Kathmandu–Bhadrapur–Kathmandu domestic flights",
    "Bhadrapur–Taplejung, Taplejung–Sekathum, and Yamphudin–Bhadrapur drives",
    "Teahouse lodging and breakfast, lunch, dinner on trek days as listed",
    "Licensed trekking guide and porter (typically 1 porter for 2 pax) with insurance",
    "TIMS, Kanchenjunga restricted permit, and KCAP permit; map; water purification tablets; taxes",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "International airfare",
    "Nepal entry visa fees",
    "Travel insurance of any kind (mandatory — helicopter evacuation)",
    "Lunch and dinner in Kathmandu / city hotels (except as listed)",
    "Drinks, desserts, mineral water, Wi-Fi, heater, and hot shower on trek",
    "Personal gear, snacks, and tips for guide, porter, and drivers",
    "Extra accommodation and meals outside the itinerary",
    "Emergency evacuation / roadblock expenses beyond our control",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "High eastern Himalaya ridges toward Kanchenjunga",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "Alpine approaches on the circuit",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Remote valley light in far-east Nepal",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Wilderness trails in the conservation area",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May and September–November offer the most stable weather, clear views, and good trail conditions. Trails stay quiet even in peak season.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & permits",
      body: "Highest point is Kanchenjunga North Base Camp / Pangpema (~5,140 m). You need KCAP (~USD 20 pp) and Kanchenjunga Restricted Area permit (~USD 10 pp/week), plus TIMS. Summit Seek arranges these with your licensed guide.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Strenuous / advanced. Rugged slopes, landslide zones, glacier moraines, long days, and a four-pass crossing. Prior trek experience and strong fitness required.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Lodging & food",
      body: "Simple teahouses (twin rooms). Sleeping bag recommended. Hot shower, charging, and Wi-Fi cost extra and may be limited high up. Dal bhat, noodles, soups, and eggs are common; carry snacks and purification tablets.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "This remote route has limited shops — pack thoroughly. Porters carry main bags; keep water, layers, documents, snacks, and camera in a daypack.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Breathable underwear & base layers",
        "Thermal mid-layers",
        "Trekking shirts and pants",
        "Down jacket & fleece",
        "Waterproof / windproof shell jacket and pants",
        "Warm hat, sun hat, gloves, buff / scarf",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Camp shoes / slippers",
        "Trekking poles",
        "Duffel + 25–35L daypack",
        "Sleeping bag (cold nights to about -10°C)",
        "Headlamp + spare batteries",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "SPF sunscreen, lip balm, UV sunglasses",
        "Personal first-aid kit & blister care",
        "Water bottles + purification tablets",
        "ORS / electrolytes, snacks, energy bars",
        "Toiletries, wet wipes, hand sanitizer",
        "Insect repellent",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Valid passport + copies + passport photos",
        "Nepal visa as applicable",
        "Travel insurance details (heli evacuation)",
        "Cash for personal trail extras",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Permit processing and licensed guiding team",
    "Trekking duffel for porter loads as arranged",
    "Route map and water purification tablets",
    "Advice on north/south variants and flight buffers",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "How far is Kanchenjunga from Kathmandu?",
      answer:
        "Roughly 670 km by land; about 260 km aerial. Reaching the trailhead typically means a ~50-minute flight to Bhadrapur plus about two days of jeep driving.",
      visible: true,
    },
    {
      id: "q2",
      question: "How long is the Kanchenjunga Circuit trek?",
      answer:
        "This Summit Seek itinerary is 22 days. Similar circuits often run 21–26 days and can be customized.",
      visible: true,
    },
    {
      id: "q3",
      question: "Is the Kanchenjunga Circuit trek difficult?",
      answer:
        "Yes — strenuous and best for experienced, fit trekkers. Expect high passes, moraines, landslide zones, and long walking days.",
      visible: true,
    },
    {
      id: "q4",
      question: "How much does it cost?",
      answer:
        "This listing starts at US$2,790 for 3–5 pax (US$3,050 for 2; US$2,590 for 6–10; US$2,390 for 11–15). Market packages often range about US$2,400–3,200 depending on services.",
      visible: true,
    },
    {
      id: "q5",
      question: "Can I trek without a guide?",
      answer:
        "No. Kanchenjunga is a restricted area — foreigners must trek with a licensed guide.",
      visible: true,
    },
    {
      id: "q6",
      question: "Where does the trek start?",
      answer:
        "Walking usually starts at Sekathum after flying to Bhadrapur and driving via Taplejung.",
      visible: true,
    },
    {
      id: "q7",
      question: "Can you see Everest on this trek?",
      answer:
        "Yes — from some sections of the Kanchenjunga Circuit you can see Mt. Everest along with Kanchenjunga massif views.",
      visible: true,
    },
    {
      id: "q8",
      question: "Is travel insurance necessary?",
      answer:
        "Yes. Cover remote trekking and emergency helicopter evacuation applicable in the Himalayas (ideally to 5,000+ m). Summit Seek does not sell insurance.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Kanchenjunga Circuit?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Kanchenjunga Circuit Trek 22 Days | Summit Seek",
  metaDescription:
    "Book the 22-day Kanchenjunga Circuit trek with Summit Seek — north & south base camps, permits, flights, guide, porter, meals & group discounts from US$2,390.",
};
