import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_KANCHENJUNGA_SOUTH: TrekPageContent = {
  coverImageUrl: img("photo-1544735716-392fe2489ffa", 2000),
  coverTitle: "Kanchenjunga South Base Camp Trek - 17 Days",
  coverSubtitle:
    "Remote far-eastern Himalaya trek to Oktang (~4,730 m) — south viewpoint of Mt. Kanchenjunga and the Yalung Glacier — via Ghunsa, Mirgin La, and Tseram.",
  heroMainImageUrl: img("photo-1544735716-392fe2489ffa", 2000),
  heroSideImage1Url: img("photo-1464822759023-fed622ff2c3b", 900),
  heroSideImage2Url: img("photo-1486870591958-9b9d0d1dda99", 900),
  breadcrumbLabel: "Kanchenjunga Region · South Base Camp",
  title: "Kanchenjunga South Base Camp Trek - 17 Days",
  regionLabel: "Kanchenjunga Region",
  rating: 5,
  reviewCount: 7,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 2090,
  compareAtPrice: 2390,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "13% OFF",
  shortTripBadge: "Restricted Area",
  durationLabel: "17 Days",
  difficultyLabel: "Difficult",
  groupSizeLabel: "2+",
  bookingNote:
    "Private and small-group departures. Package includes Kathmandu hotel (BB as listed), Kathmandu–Bhadrapur flights, jeep transfers Taplejung and Thorpu–Bhadrapur, licensed guide, porter (2:1), trek meals, teahouse/lodge lodging, Kanchenjunga restricted & KCAP permits, and TIMS. Minimum typically 2 trekkers with a licensed guide (mandatory in the restricted area).",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "2 pax", price: 2290, visible: true },
    { id: "gd2", paxLabel: "3-5 pax", price: 2090, visible: true },
    { id: "gd3", paxLabel: "6-10 pax", price: 1950, visible: true },
    { id: "gd4", paxLabel: "11-15 pax", price: 1790, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "17 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Difficult", visible: true },
    { id: "f3", label: "Max Altitude", value: "4,730 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Kanchenjunga / Far East", visible: true },
    { id: "f6", label: "Group Size", value: "2 onwards", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Culture", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The Kanchenjunga South Base Camp Trek is a highly adventurous journey through rugged far-eastern Nepal to Oktang (~4,730 m) — the classic south viewpoint of Mt. Kanchenjunga (8,586 m), the “Five Treasures of the Snow” in Limbu language. You walk from subtropical lowlands and rhododendron forest into glacial plateaus above the Yalung Glacier.\n\nThis 17-day itinerary flies Kathmandu–Bhadrapur, drives to Taplejung, then treks via Sinwa, Lelep, Amjilasa, Gyabla, and Ghunsa before crossing Mirgin La toward Tseram. The highlight day reaches Oktang South Base Camp with views of Kokthang, Rathong, Kabru, and the immense south face, overnighting at Ramche. The descent exits via Tortong / Yamphudin, Khebang, and Thorpu toward Bhadrapur.\n\nQuieter than Everest or Annapurna, the region is restricted — a licensed guide and typically two trekkers minimum are required. Summit Seek includes flights and road transfers as listed, permits, guide, porter, meals, and clear group pricing. Want both base camps? See our 22-day Circuit or 18-day North Base Camp.",
  overviewImageUrl: img("photo-1464822759023-fed622ff2c3b"),
  highlightsHeading: "Highlights",
  highlights: [
    "Oktang / Kanchenjunga South Base Camp viewpoint (~4,730 m)",
    "Yalung Glacier approaches and south-face panoramas",
    "Cross Mirgin La between Ghunsa and Tseram",
    "Rhododendron forests and remote Limbu / Rai / Sherpa villages",
    "Kanchenjunga Conservation Area wilderness",
    "Empty trails compared with Everest and Annapurna",
    "Scenic Kathmandu–Bhadrapur flights and eastern hill jeep roads",
    "Cultural stops from subtropical valleys to high Tibetan-influenced hamlets",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport transfers by private vehicle as listed",
    "Kathmandu hotel nights with breakfast as listed",
    "Kathmandu heritage sightseeing option as listed",
    "Kathmandu–Bhadrapur flights and return as listed",
    "Jeep / bus transfers Bhadrapur–Taplejung and Thorpu–Bhadrapur",
    "Teahouse / lodge lodging and trek meals (B-L-D on trail days)",
    "English-speaking licensed guide and porter (2:1)",
    "TIMS, RAP, and KCAP permits; staff insurance; farewell dinner as listed",
  ],
  whyHeading: "Why choose South Base Camp?",
  whyPoints: [
    "Focus on the dramatic Yalung / south-face viewpoints",
    "Slightly shorter than the full circuit or north-only packages",
    "High-pass crossing (Mirgin La) without Pangpema’s 5,140 m day",
    "Rich culture from lowland farms to high Buddhist villages",
    "True wilderness with very few other trekkers",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "No — graded difficult. Expect long walking days (often 5–9 hours), steep forest climbs, high passes around 4,480 m, glacial approaches to 4,730 m, and remote lodging.\n\nPrior multi-day trek experience and strong fitness are strongly recommended. A licensed guide is legally required. Travel insurance covering helicopter evacuation is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train 6+ weeks with long hikes, stairs, and cardio",
    "Prior Himalayan trek experience strongly advised",
    "Break in waterproof boots; pack for cold high camps",
    "Carry snacks, purification, and a personal first-aid kit",
    "Buy insurance covering remote Himalayan helicopter evacuation",
    "Arrive Kathmandu with buffer days for flights and permits",
  ],
  itineraryHeading: "17-day itinerary",
  itineraryIntro:
    "Flight and walking times are estimates and vary with weather — Bhadrapur flights and long jeep roads can delay. Lodge stops may change with availability (Tortong vs Yamphudin on descent). Your Summit Seek guide can adjust for safety.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,400 m",
      meals: "—",
      accommodation: "Hotel in Kathmandu",
      description:
        "Airport meet-and-greet and hotel transfer. Briefing and paperwork if time allows. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Kathmandu sightseeing & trek preparation",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Optional UNESCO heritage tour (Durbar Square, Boudhanath, Swayambhunath, Pashupatinath — or Patan / Bhaktapur). Gear and permit check. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Fly Kathmandu – Bhadrapur – drive to Taplejung",
      maxAltitude: "1,820 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge / Teahouse",
      description:
        "Morning flight to Bhadrapur, then long scenic jeep drive to Taplejung (~1,820 m). Overnight in Taplejung.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Trek Taplejung – Sinwa",
      maxAltitude: "980 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge / Teahouse",
      description:
        "Begin walking into the Tamor corridor toward Sinwa (~6 hours). Overnight lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Trek Sinwa – Lelep / Tamewa",
      maxAltitude: "1,750 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge / Teahouse",
      description:
        "Cross the Tamur on suspension bridges; follow paddy fields, cardamom groves, and riverside trail (~7 hours). Overnight in Lelep or Tamewa.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Trek Lelep – Amjilasa",
      maxAltitude: "2,308 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Mostly flat then a steep climb to Amjilasa, a small village with yak herds (~5 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Trek Amjilasa – Gyabla",
      maxAltitude: "2,730 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Forest trail gently ascending to Gyabla / Gyable (~7 hours). Buddhist village overnight.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Trek Gyabla – Ghunsa",
      maxAltitude: "3,595 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Dense jungle along the Ghunsa River to Tibetan-influenced Ghunsa (~6 hours). Overnight in Ghunsa.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Trek Ghunsa – Mirgin La area",
      maxAltitude: "4,480 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge / High camp",
      description:
        "Climb through forest and high pasture past mani walls and prayer flags toward Mirgin La (~4,480 m) (~7 hours). Overnight near the pass / high lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Trek Mirgin La – Tseram",
      maxAltitude: "3,870 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Stony high country with glacier and snow-peak views, then descend to Tseram / Cheram (~7 hours). Overnight in Tseram.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Day hike Oktang South BC – overnight Ramche",
      maxAltitude: "4,730 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Ascend via ablation valleys and Yalung approaches to Oktang (~4,730 m) — views of Kokthang, Rathong, Kabru, and Kanchenjunga’s south face — then overnight at Ramche (~4,580 m) (~6–7 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Trek Ramche – Tortong / Yamphudin",
      maxAltitude: "2,995 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Descend along Simbuwa Khola through forest and landslide sections toward Tortong (~2,995 m) or continue toward Yamphudin depending on pace and lodging.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Trek Tortong / Yamphudin – Khebang",
      maxAltitude: "2,090 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Continue through cardamom and orchid forest, mixed Sherpa / Limbu / Rai / Gurung villages, to Khebang (~1,740–2,090 m).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Trek Khebang – Thorpu",
      maxAltitude: "1,500 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge",
      description:
        "Long day through farmland and villages to Thorpu, where road transport resumes (~9 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d15",
      dayLabel: "Day 15",
      title: "Drive Thorpu – Bhadrapur",
      maxAltitude: "100 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge / Hotel",
      description:
        "Jeep / bus via hill towns toward Bhadrapur (~6 hours+). Overnight in Bhadrapur.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d16",
      dayLabel: "Day 16",
      title: "Fly Bhadrapur – Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast, Dinner",
      accommodation: "Hotel in Kathmandu",
      description:
        "Morning flight to Kathmandu. Hotel transfer; farewell dinner as listed. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d17",
      dayLabel: "Day 17",
      title: "Departure from Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "—",
      description:
        "Airport transfer for your international flight. End of the Kanchenjunga South Base Camp journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best in March–May and September–November for stable weather and clear views. Private groups of 2+ are welcome. Build buffer days for Bhadrapur flights and long road transfers.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Licensed guide and restricted-area permits mandatory (min. 2 trekkers)",
    "Porter included typically 2 clients : 1 porter",
    "Bhadrapur flights and jeep roads are weather/road-dependent — allow buffers",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Extra Kathmandu nights",
      description: "Buffer nights for flight delays or early arrivals.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "North Base Camp add-on",
      description: "Extend toward Pangpema or upgrade to the full circuit.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Gear rental",
      description: "Sleeping bag, down jacket, and poles as needed.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport pick-up and drop-off by private vehicle as listed",
    "Kathmandu hotel nights with breakfast as listed",
    "Kathmandu sightseeing with guide/vehicle as listed",
    "Kathmandu–Bhadrapur–Kathmandu flights",
    "Land transfers Bhadrapur–Taplejung and Thorpu–Bhadrapur",
    "Teahouse / lodge lodging and breakfast, lunch, dinner on trek days",
    "Licensed guide and porter (typically 1 porter for 2 pax)",
    "TIMS, Kanchenjunga RAP, and KCAP permits; staff insurance; taxes; farewell dinner as listed",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "International airfare",
    "Nepal entry visa fees",
    "Travel insurance (mandatory — helicopter evacuation)",
    "Lunch and dinner in Kathmandu (except farewell dinner as listed)",
    "Kathmandu sightseeing entrance fees if not listed in package",
    "Personal expenses: charging, hot shower, Wi-Fi, drinks, laundry",
    "Tips for guide, porter, and drivers",
    "Extra Kathmandu nights outside the itinerary",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "High eastern Himalaya toward Kanchenjunga",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Alpine approaches on the south base camp route",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "Remote ridges and glacial valleys",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Wilderness trails in far-east Nepal",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May and September–November offer the most stable weather and clearest mountain views on the south approaches.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & permits",
      body: "Highest point is Oktang / South Base Camp viewpoint (~4,730 m); Mirgin La is about 4,480 m. You need KCAP and Kanchenjunga Restricted Area Permit plus a licensed guide. Summit Seek arranges these.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Difficult — long days, high passes, remote lodges, and glacial terrain. Strong fitness and prior trek experience required.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Lodging & culture",
      body: "Simple teahouses and lodges. Expect shared bathrooms and basic menus (dal bhat, noodles). Villages mix Limbu, Rai, Sherpa, and Gurung cultures; higher hamlets show strong Tibetan Buddhist influence.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "This remote route has limited shops — pack thoroughly. Porters carry main bags; keep water, layers, documents, snacks, and camera in a daypack.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Thermal underwear / base layers",
        "Fleece mid-layer",
        "Down jacket",
        "Waterproof / windproof shell",
        "Trekking trousers and warm socks",
        "Warm hat, sun hat, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Camp sandals",
        "Trekking poles",
        "Daypack + duffel / rucksack",
        "Sleeping bag (cold high camps)",
        "Headlamp + spare batteries",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "SPF sunscreen, lip balm, UV sunglasses",
        "Personal first-aid kit & blister care",
        "Water bottle + purification tablets",
        "Energy bars and trail snacks",
        "Hand sanitizer & toilet paper",
        "Gaiters (helpful in snow / mud)",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies + passport photos",
        "Nepal visa as applicable",
        "Travel insurance details (heli evacuation)",
        "Cash for personal trail extras",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Permit processing and licensed guiding team",
    "Staff insurance and logistics coordination",
    "Sleeping bag / down jacket rental on request",
    "Advice on north BC or circuit extensions",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Kanchenjunga South Base Camp trek?",
      answer:
        "A 17-day restricted-area trek in far-eastern Nepal to Oktang (~4,730 m), the classic south viewpoint of Mt. Kanchenjunga above the Yalung Glacier.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Difficult. Expect long days, Mirgin La (~4,480 m), and glacial approaches. Best for experienced, fit trekkers — not ideal as a first Himalayan trek.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This listing starts at US$2,090 for 3–5 pax (US$2,290 for 2; US$1,950 for 6–10; US$1,790 for 11–15).",
      visible: true,
    },
    {
      id: "q4",
      question: "What is the maximum altitude?",
      answer:
        "About 4,730 m at Oktang / South Base Camp viewpoint, with overnight typically at Ramche (~4,580 m).",
      visible: true,
    },
    {
      id: "q5",
      question: "Do I need special permits?",
      answer:
        "Yes — Kanchenjunga Restricted Area Permit, KCAP entry, and TIMS as applicable, plus a licensed guide. Summit Seek arranges these.",
      visible: true,
    },
    {
      id: "q6",
      question: "How is this different from North Base Camp?",
      answer:
        "South focuses on Oktang and the Yalung Glacier / south face (max ~4,730 m). North goes to Pangpema (~5,143 m). The Circuit combines both over more days.",
      visible: true,
    },
    {
      id: "q7",
      question: "Is travel insurance necessary?",
      answer:
        "Yes — covering remote trekking and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q8",
      question: "When is the best time to go?",
      answer:
        "March–May and September–November usually offer the best weather and mountain views.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Kanchenjunga South Base Camp?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Kanchenjunga South Base Camp Trek 17 Days | Summit Seek",
  metaDescription:
    "Book the 17-day Kanchenjunga South Base Camp trek with Summit Seek — Oktang 4,730 m, permits, flights, guide, porter, meals & group discounts from US$1,790.",
};
