import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_LANGTANG_VALLEY_TREK: TrekPageContent = {
  coverImageUrl: img("photo-1486870591958-9b9d0d1dda99", 2000),
  coverTitle: "Langtang Valley Trek - 9 Days",
  coverSubtitle:
    "Classic moderate trek from Dhunche via Thulo Syabru to Kyanjin Gompa — Tamang culture, glaciers, yak cheese, and sunrise from Kyanjin Ri (4,380 m).",
  heroMainImageUrl: img("photo-1486870591958-9b9d0d1dda99", 2000),
  heroSideImage1Url: img("photo-1464822759023-fed622ff2c3b", 900),
  heroSideImage2Url: img("photo-1506905925346-21bda4d32df4", 900),
  breadcrumbLabel: "Packages · Langtang Region",
  title: "Langtang Valley Trek - 9 Days",
  regionLabel: "Langtang Region",
  rating: 5,
  reviewCount: 7,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 790,
  compareAtPrice: 1275,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "38% OFF",
  shortTripBadge: "Best Seller",
  durationLabel: "9 Days",
  difficultyLabel: "Moderate",
  groupSizeLabel: "1–12",
  bookingNote:
    "Private and group joining departures year-round. Package includes Kathmandu hotel night (BB), sharing jeep to/from trailhead, Langtang permits, licensed guide, teahouse meals on trek, and twin-share lodges. Porter and private jeep upgrades available.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 950, visible: true },
    { id: "gd2", paxLabel: "2-4 pax", price: 790, visible: true },
    { id: "gd3", paxLabel: "5-8 pax", price: 750, visible: true },
    { id: "gd4", paxLabel: "9+ pax", price: 720, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "9 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Moderate", visible: true },
    { id: "f3", label: "Max Altitude", value: "4,380 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Langtang", visible: true },
    { id: "f6", label: "Group Size", value: "1–12", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Culture", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "Langtang Valley Trek – 9 Days is a perfect short, low-altitude Himalayan journey close to Kathmandu — no mountain flight required, with guaranteed road access year-round.\n\nThis classic route starts from Dhunche (district headquarters) and follows the Thulo Syabru trail through pine and rhododendron forest to Lama Hotel, Langtang Village, and Kyanjin Gompa (3,870 m). A highlight day hikes Kyanjin Ri (4,380 m) for sweeping views of Langtang Lirung, Ganesh Himal, Dorje Lakpa, and more. Visit the century-old monastery and local yak cheese factory before descending to Syabrubesi.\n\nExpect authentic Tamang and Tibetan heritage, rebuilt mountain villages after the 2015 earthquake, lush valleys, and glacier country. Summit Seek includes permits, guide, teahouse meals and lodges, jeep transfers as listed, and clear group pricing.",
  overviewImageUrl: img("photo-1483728642387-6c3bdd6c93e5"),
  highlightsHeading: "Highlights",
  highlights: [
    "Classic Langtang Valley trek only a day’s drive from Kathmandu",
    "Scenic route via Dhunche and Thulo Syabru — Tamang village culture",
    "Kyanjin Gompa beneath Langtang Lirung glacier and icefall",
    "Sunrise hike to Kyanjin Ri (4,380 m) — optional Tserkuri (4,984 m)",
    "Century-old monastery and Swiss-supported yak cheese factory",
    "Views of Langtang Lirung, Ganesh Himal, Dorje Lakpa & Shishapangma",
    "Langtang National Park forests, rivers, and mani walls",
    "No Lukla flight — road access with year-round departures",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport pickup and drop-off by private vehicle",
    "1 night boutique hotel in Kathmandu with breakfast",
    "Licensed expert trekking guide (salary, insurance, meals, lodging)",
    "TIMS and Langtang National Park permits arranged",
    "Sharing jeep Kathmandu–Syabrubesi–Kathmandu as listed",
    "Three meals daily on trek (breakfast, lunch, dinner)",
    "Twin-share teahouse rooms throughout the trek",
    "Seasonal fruit on trek, first-aid kit, and trek map",
  ],
  whyHeading: "Why choose Langtang Valley?",
  whyPoints: [
    "Closest major valley trek to Kathmandu — less travel hassle than Everest",
    "Moderate grade suitable for fit beginners and families",
    "Rich Tamang culture, monasteries, and cheese-factory visits",
    "Stunning mountain panoramas without extreme altitude",
    "Easy extensions: Gosainkunda, Tamang Heritage, or Helambu",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "Yes for fit beginners. Graded Moderate with gradual altitude gain to Kyanjin Gompa (3,870 m) and an optional viewpoint day at Kyanjin Ri (4,380 m). No technical climbing required.\n\nBasic fitness and day-hiking experience help. Travel insurance covering helicopter evacuation is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Walk or hike several times a week in the month before departure",
    "Break in waterproof hiking boots on practice walks",
    "Pack warm layers for cool nights at Kyanjin Gompa",
    "Buy travel insurance covering high-altitude trekking and evacuation",
    "Consider private jeep upgrade on rough mountain roads",
    "Carry cash for personal trail extras (showers, charging, drinks)",
  ],
  itineraryHeading: "9-day itinerary",
  itineraryIntro:
    "Walking and drive times are estimates and vary with road conditions, weather, and pace. Lodge stops may change with availability. Your Summit Seek guide can adjust the plan for safety.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,350 m",
      meals: "—",
      accommodation: "Hotel in Kathmandu",
      description:
        "Arrive at Tribhuvan International Airport. Private transfer to your hotel. Trek briefing and welcome dinner overview. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Drive Kathmandu to Dhunche",
      maxAltitude: "2,030 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Scenic overland drive west from Kathmandu (~6 hrs) through farm villages to Dhunche — Rasuwa district headquarters and Langtang National Park gateway. Park permit check. Overnight in Dhunche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Trek Dhunche to Thulo Syabru",
      maxAltitude: "2,170 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Trek via paved road to Thulo Bharku then uphill through pine and rhododendron to Thulo Syabru — a large Tamang village with valley views (~6–7 hrs). Overnight in Thulo Syabru.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Trek Thulo Syabru to Lama Hotel",
      maxAltitude: "2,450 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Morning walk through gorge and dense forest past Ghoretabla (horse stable). Gradual altitude gain along the Langtang Khola (~7–8 hrs). Overnight at Lama Hotel.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Trek Lama Hotel to Langtang Village",
      maxAltitude: "3,430 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Uphill through woodland via Thangsep and Gumpa Danda into wider Langtang Valley. Rebuilt Tamang and Bhotia village with mountain views (~7–8 hrs). Overnight in Langtang Village.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Trek Langtang Village to Kyanjin Gompa",
      maxAltitude: "3,830 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Short steep climb into the wide glacial valley with snow peaks on both sides (~3–4 hrs). Visit century-old monastery ruins and yak cheese factory at Kyanjin. Overnight in Kyanjin Gompa.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Hike Kyanjin Ri viewpoint",
      maxAltitude: "4,380 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Acclimatization hike to Kyanjin Ri (4,380 m) for Langtang Lirung, Ganesh Himal, Dorje Lakpa, and Shishapangma views — optional longer push toward Tserkuri (4,984 m) if fit (~5–6 hrs). Overnight in Kyanjin Gompa.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Trek Kyanjin Gompa to Syabrubesi",
      maxAltitude: "1,530 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Long descent via Langtang Village and Lama Hotel following the Langtang Khola to Syabrubesi (~12–14 hrs total walking — may split with overnight at Lama Hotel on slower pace). Overnight in Syabrubesi.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Drive Syabrubesi to Kathmandu",
      maxAltitude: "1,350 m",
      meals: "Breakfast, Lunch",
      accommodation: "— (departure day)",
      description:
        "Sharing jeep back to Kathmandu (~6 hrs). Transfer to hotel or international airport for homeward flight. End of the Langtang Valley trek with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Langtang Valley departures available year-round on private and joining bases. Spring and autumn bring the clearest views. Winter is quieter and colder; monsoon means rain on lower trails.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Sharing jeep included; private jeep upgrade available",
    "Guaranteed road access — no Lukla flight delays",
    "Extensions: Gosainkunda, Tamang Heritage, or Helambu on request",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Porter service",
      description: "Shared porter (typically 2:1, ~20–22 kg) for a lighter daypack.",
      priceLabel: "From US$220",
      visible: true,
    },
    {
      id: "a2",
      title: "Private jeep upgrade",
      description: "Private 4WD Kathmandu–Syabrubesi instead of sharing jeep (~US$170 per way).",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Extra Kathmandu nights",
      description: "Additional hotel nights before or after the trek.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a4",
      title: "Single room supplement",
      description: "Private rooms where available in hotels and teahouses.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport pickup and drop-off by private vehicle",
    "1 night hotel in Kathmandu with breakfast",
    "Licensed trekking guide with salary, insurance, meals, and lodging",
    "TIMS permit and Langtang National Park entry permit",
    "Sharing jeep Kathmandu–Syabrubesi–Kathmandu",
    "Teahouse accommodation on trek (twin sharing)",
    "Three meals daily on trek (breakfast, lunch, dinner)",
    "Hot tea three times daily on trek and seasonal fruit",
    "Trek map, first-aid kit, and government taxes as listed",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Nepal entry visa fee and international airfare",
    "Travel insurance (mandatory)",
    "Porter service unless added",
    "Private jeep upgrade unless selected",
    "Lunch and dinner in Kathmandu (unless stated)",
    "Personal expenses — drinks, hot shower, charging, laundry, Wi-Fi",
    "Tips for guide and staff",
    "Costs from roadblocks, weather, or delays beyond our control",
    "Anything not listed in the includes section",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "Glacier country above Langtang Valley",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Alpine ridges toward Kyanjin Gompa",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "High Himalayan mountain light",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1483728642387-6c3bdd6c93e5"),
      caption: "Forest trail in Langtang National Park",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May and September–November usually offer the clearest Langtang views. Winter is cold but quiet; monsoon brings rain and leeches on lower trails.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & AMS",
      body: "Highest point is Kyanjin Ri at 4,380 m (optional Tserkuri 4,984 m). Overnight at Kyanjin Gompa (3,830 m). Drink water, pace steadily, and report symptoms early to your guide.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "2015 earthquake legacy",
      body: "Langtang Village and Kyanjin were heavily affected in 2015. Rebuilt teahouses and resilient communities welcome trekkers — your visit supports local recovery tourism.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Lodges & meals",
      body: "Twin-share teahouses on the trail. Expect dal bhat, noodles, and hearty mountain breakfasts. Hot showers and Wi-Fi usually cost extra.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack for moderate trekking with cool nights at Kyanjin. Porter optional — daypack for essentials if trekking without porter support.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece mid-layer and light down jacket",
        "Waterproof shell and trekking pants",
        "Warm hat, sun cap, and gloves",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Trekking poles (recommended on descents)",
        "Daypack and duffel if using porter",
        "Water bottle or purification tablets",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "SPF sunscreen, lip balm, sunglasses",
        "Personal medications and blister care",
        "Headlamp for early Kyanjin Ri start",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport, visa, and copies",
        "Travel insurance certificate",
        "Cash for personal trail expenses",
        "Summit Seek booking confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Down jacket, sleeping bag, and duffel bag rental if needed",
    "Route briefing and permit arrangement in Kathmandu",
    "First-aid support with your guiding team",
    "Advice on Gosainkunda or Tamang Heritage extensions",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Langtang Valley Trek?",
      answer:
        "A 9-day moderate teahouse trek from Kathmandu to Kyanjin Gompa via Dhunche and Thulo Syabru, with a Kyanjin Ri viewpoint day and return to Syabrubesi by road.",
      visible: true,
    },
    {
      id: "q2",
      question: "How much does it cost?",
      answer:
        "This listing starts at US$790 for 2–4 pax (US$950 solo; US$750 for 5–8; US$720 for 9+). Compare-at US$1,275.",
      visible: true,
    },
    {
      id: "q3",
      question: "Do I need a mountain flight?",
      answer:
        "No — Langtang is reached by road from Kathmandu. This avoids Lukla flight cancellations and is a major advantage of this trek.",
      visible: true,
    },
    {
      id: "q4",
      question: "What is the maximum altitude?",
      answer:
        "Kyanjin Ri viewpoint at 4,380 m on the highlight day. Overnight highest point is Kyanjin Gompa at 3,830 m.",
      visible: true,
    },
    {
      id: "q5",
      question: "Is this good for beginners?",
      answer:
        "Yes for fit beginners. Graded Moderate with gradual ascent and a well-paced itinerary. Prior day-hiking experience is helpful.",
      visible: true,
    },
    {
      id: "q6",
      question: "When is the best time?",
      answer:
        "Spring (March–May) and autumn (September–November) offer the clearest mountain views. Departures run year-round.",
      visible: true,
    },
    {
      id: "q7",
      question: "Is a porter included?",
      answer:
        "Porter service is optional — typically US$220 shared between two trekkers. You can hike with a light daypack if you add a porter.",
      visible: true,
    },
    {
      id: "q8",
      question: "Can I customize the route?",
      answer:
        "Yes — Gosainkunda Lake, Tamang Heritage Trail, or private jeep upgrades can be arranged on request.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Langtang Valley?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Langtang Valley Trek 9 Days | Summit Seek",
  metaDescription:
    "Book 9-day Langtang Valley trek from Kathmandu — Kyanjin Gompa, Kyanjin Ri views, Tamang culture & group rates from US$720.",
};
