import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_LANGTANG_VALLEY: TrekPageContent = {
  coverImageUrl: img("photo-1464822759023-fed622ff2c3b", 2000),
  coverTitle: "Langtang Valley Trek - 10 Days",
  coverSubtitle:
    "A classic valley trek close to Kathmandu — Syabrubesi to Kyanjin Gompa, glaciers, Tamang culture, and sunrise from Kyanjin Ri (4,773 m).",
  heroMainImageUrl: img("photo-1464822759023-fed622ff2c3b", 2000),
  heroSideImage1Url: img("photo-1506905925346-21bda4d32df4", 900),
  heroSideImage2Url: img("photo-1544735716-392fe2489ffa", 900),
  breadcrumbLabel: "Langtang Region · Valley",
  title: "Langtang Valley Trek - 10 Days",
  regionLabel: "Langtang Region",
  rating: 5,
  reviewCount: 36,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 580,
  compareAtPrice: 595,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "Group Rates",
  shortTripBadge: "Classic Trek",
  durationLabel: "10 Days",
  difficultyLabel: "Moderate",
  groupSizeLabel: "1–10",
  bookingNote:
    "Private and small-group departures available. Package includes Kathmandu hotel nights (BB), public bus to/from Syabrubesi, permits, licensed guide, teahouse meals on trek days. Private jeep upgrade available on request.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 595, visible: true },
    { id: "gd2", paxLabel: "2-4 pax", price: 580, visible: true },
    { id: "gd3", paxLabel: "5-10 pax", price: 550, visible: true },
    { id: "gd4", paxLabel: "11+ pax", price: 520, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "10 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Moderate", visible: true },
    { id: "f3", label: "Max Altitude", value: "4,773 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Langtang", visible: true },
    { id: "f6", label: "Group Size", value: "1–10", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Culture", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The Langtang Valley trek is one of Nepal’s most loved short–medium Himalayan journeys — close to Kathmandu, rich in Tamang culture, and famous as a “valley of glaciers.” In 10 days you drive to Syabrubesi, trek through Langtang National Park via Lama Hotel and Langtang Village to Kyanjin Gompa, then climb for 360° views from Kyanjin Ri (~4,773 m) or optional Tserko Ri.\n\nExpect rhododendron and pine forests, riverside trails along the Bhote Koshi / Langtang Khola, rebuilt mountain villages, cheese factories, and close views of Langtang Lirung, Kimshung, and Langshisha Ri. It is suitable for fit beginners and older travelers with basic fitness — altitude rises above 2,000 m from the trailhead, so steady pacing and acclimatization matter.\n\nSummit Seek includes airport transfers, Kathmandu hotel nights, permits, a licensed English-speaking guide, teahouse meals on trek days, and clear group pricing. Porter service and private jeep to Syabrubesi are available as add-ons.",
  overviewImageUrl: img("photo-1483728642387-6c3bdd6c93e5"),
  highlightsHeading: "Highlights",
  highlights: [
    "Classic Langtang Valley trek only a day’s drive from Kathmandu",
    "Kyanjin Gompa — vibrant Tamang Buddhist village beneath glaciers",
    "Sunrise hike to Kyanjin Ri (4,773 m) or optional Tserko Ri",
    "Views of Langtang Lirung, Kimshung, Langshisha Ri & hanging glaciers",
    "Walk through Langtang National Park forests and riverside trails",
    "Authentic teahouse lodging and cheese-factory culture at Kyanjin",
    "Moderate grade — great value alternative to Everest / Annapurna crowds",
    "Flexible private departures with clear group discounts",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "International airport pickup and final departure drop-off",
    "2 nights Kathmandu hotel on BB basis (as listed)",
    "Public bus Kathmandu ↔ Syabrubesi (private jeep upgrade available)",
    "7 nights teahouse accommodation on trek (twin sharing)",
    "Breakfast, lunch, and dinner during the trek",
    "Licensed English-speaking guide (salary, food, lodging, transport)",
    "All necessary Langtang permits",
    "First-aid support, trek map, and purified drinking-water tablets",
  ],
  whyHeading: "Why choose Langtang Valley?",
  whyPoints: [
    "Closest major Himalayan valley trek to Kathmandu — less travel time",
    "Glacier views and high viewpoints without Everest logistics or Lukla flights",
    "Deep Tamang culture and rebuilt community hospitality after 2015",
    "Moderate challenge with a memorable Kyanjin Ri panorama day",
    "Easy to combine with Gosainkunda, Helambu, or Tamang Heritage on request",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "Yes for fit beginners. The grade is moderate: longer and shorter walking days, with a high point at Kyanjin Ri (~4,773 m). You ascend more than 2,000 m from Syabrubesi, so altitude awareness matters, but the itinerary builds height gradually with a full exploration day at Kyanjin Gompa.\n\nBasic fitness and prior day-hiking help. Travel insurance covering helicopter evacuation is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Walk or hike several times a week in the month before departure",
    "Break in waterproof hiking boots on practice walks",
    "Pack layers for cool nights at Kyanjin Gompa (~3,870 m)",
    "Buy travel insurance covering high-altitude trekking and evacuation",
    "Consider private jeep if you prefer a smoother ride than the public bus",
    "Carry cash for personal trail extras (showers, charging, drinks)",
  ],
  itineraryHeading: "10-day itinerary",
  itineraryIntro:
    "Walking and drive times are estimates and vary with road conditions, weather, and pace. Lodge stops may change with availability. Your Summit Seek guide can adjust the plan for safety.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,400 m",
      meals: "—",
      accommodation: "Hotel in Kathmandu",
      description:
        "Airport pickup and transfer to your hotel. Trip meeting and trek briefing with your Summit Seek leader. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Drive Kathmandu – Syabrubesi",
      maxAltitude: "1,460 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Scenic drive north from Kathmandu to Syabrubesi (~1,460 m), gateway to Langtang Valley. Road conditions can be rough — private jeep upgrade available. Overnight in Syabrubesi.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Syabrubesi – Lama Hotel",
      maxAltitude: "2,460 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Trek into Langtang National Park along the Bhote Koshi / Langtang Khola through forest (~11 km / about 6–7 hours) to Lama Hotel. Overnight in Lama Hotel.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Lama Hotel – Langtang Village",
      maxAltitude: "3,450 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Ascend through forest and alpine meadows (~15 km / about 7–8 hours) toward Langtang Village with growing mountain views. Overnight in Langtang Village.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Langtang Village – Kyanjin Gompa",
      maxAltitude: "3,870 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Shorter trek day (~7 km / about 3–4 hours) into Kyanjin Gompa — cheese factories, monasteries, and glacier views. Overnight in Kyanjin Gompa.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Kyanjin exploration – Kyanjin Ri / Tserko Ri",
      maxAltitude: "4,773 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Acclimatization and exploration day. Hike Kyanjin Ri (~4,773 m) for 360° Langtang panorama, or optional longer climb toward Tserko Ri. Overnight again in Kyanjin Gompa.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Kyanjin Gompa – Lama Hotel",
      maxAltitude: "2,460 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Descend the valley (~21 km / about 7–8 hours) back to Lama Hotel with farewell views of the upper Langtang peaks. Overnight in Lama Hotel.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Lama Hotel – Syabrubesi",
      maxAltitude: "1,460 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Final trail day through forest back to Syabrubesi (~11 km / about 6–7 hours). Celebrate with your team. Overnight in Syabrubesi.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Drive Syabrubesi – Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Return drive to Kathmandu. Free afternoon for rest or shopping. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Final departure",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "— (departure day)",
      description:
        "Airport transfer for your departure flight, or continue with an onward Summit Seek program. End of the Langtang Valley journey.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Langtang Valley departures run year-round on private and joining bases. Spring and autumn usually bring the clearest mountain views. Winter is quieter and colder; monsoon means more rain and leeches on lower trails.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Public bus included; private jeep recommended on rough roads",
    "Groups of 11+ can request special pricing",
    "Easy to combine with Gosainkunda or Helambu on request",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Porter service",
      description:
        "Shared porter (typically 2:1, up to ~25 kg) so you hike with a light daypack.",
      priceLabel: "From US$160",
      visible: true,
    },
    {
      id: "a2",
      title: "Private jeep to Syabrubesi",
      description:
        "Upgrade the public bus to a private 4WD jeep (rough highway — often recommended).",
      priceLabel: "From US$150 one way",
      visible: true,
    },
    {
      id: "a3",
      title: "Single room supplement",
      description: "Private rooms where available in hotels and teahouses.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "International airport pickup and final departure drop-off",
    "2 nights’ accommodation in Kathmandu on BB basis",
    "Public bus ticket Kathmandu ↔ Syabrubesi",
    "7 nights’ teahouse accommodation during the trek (twin sharing)",
    "Three meals a day (breakfast, lunch, dinner) during the trek",
    "Professional English-speaking trekking guide (salary, food, lodging, transport)",
    "Sleeping bag and duffel bag if needed",
    "All necessary Langtang trek permits",
    "Government tax and service charges",
    "Langtang Valley trek map and purified drinking-water tablets",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "International airfare, travel insurance, and Nepal entry visa fee",
    "Extra hotel nights and lunch/dinner in Kathmandu",
    "Private jeep (available as add-on)",
    "Personal expenses (drinks, hot showers, charging, Wi-Fi, laundry, extra meals)",
    "Costs from roadblocks, delays, or events beyond our control",
    "Tips for guide and staff",
    "Porter service unless added",
    "Any items not listed in the includes section",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Alpine ridges above Langtang Valley",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "High Himalayan mountain light",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Valley approaches toward Kyanjin",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1483728642387-6c3bdd6c93e5"),
      caption: "Forest trail atmosphere near Kathmandu",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "Spring (March–May) and autumn (September–November) usually offer the clearest Langtang views. Winter is cold but quieter; monsoon brings rain and muddy lower trails.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & AMS",
      body: "Highest overnight is Kyanjin Gompa (~3,870 m); Kyanjin Ri reaches ~4,773 m. Use the exploration day, drink water, avoid alcohol, and tell your guide early if you feel unwell.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Moderate. Expect several 6–8 hour walking days and a steep viewpoint hike. Suitable for fit beginners with preparation — no technical climbing required.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Lodges & meals",
      body: "Twin-share teahouses on the trail; hotel in Kathmandu. Expect dal bhat, noodles, soups, and simple breakfasts. Hot showers and Wi-Fi usually cost extra.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack light for a valley trek with one high viewpoint day. If you add a porter, keep personal items in a daypack. Dress in layers for cool Kyanjin nights.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece mid-layer",
        "Down / insulated jacket",
        "Waterproof shell",
        "Trekking pants + warm evening layer",
        "Warm hat, sun hat, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Camp shoes",
        "Trekking poles (helpful on descents)",
        "25–35L daypack",
        "Duffel for porter if using",
        "2–3 pairs trekking socks",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "SPF 50+ sunscreen & lip balm",
        "UV sunglasses",
        "Personal medications & blister care",
        "Water bottle + purification tablets",
        "Headlamp + spare batteries",
        "Trail snacks",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance details",
        "Cash for personal trail expenses",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Trek map and pre-trek briefing in Kathmandu",
    "First-aid support with your guiding team",
    "Sleeping bag / duffel if needed (return after trek)",
    "Advice on Gosainkunda, Helambu, or Tamang Heritage extensions",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Langtang Valley trek?",
      answer:
        "A classic 10-day trek north of Kathmandu through Langtang National Park to Kyanjin Gompa, with a panoramic hike to Kyanjin Ri (~4,773 m).",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Moderate. Several 6–8 hour days and altitude gain to nearly 4,800 m on the viewpoint day. Fit beginners succeed with preparation.",
      visible: true,
    },
    {
      id: "q3",
      question: "What is the maximum altitude?",
      answer:
        "Kyanjin Ri at approximately 4,773 m. The highest overnight stop is Kyanjin Gompa at about 3,870 m.",
      visible: true,
    },
    {
      id: "q4",
      question: "How much does the Langtang Valley trek cost?",
      answer:
        "This Summit Seek listing starts at US$580 for 2–4 pax (US$595 solo; US$550 for 5–10). Contact us for groups of 11+.",
      visible: true,
    },
    {
      id: "q5",
      question: "Is a private jeep necessary?",
      answer:
        "Public bus is included. Many travelers upgrade to a private jeep (~US$150 one way) because the highway to Syabrubesi can be rough.",
      visible: true,
    },
    {
      id: "q6",
      question: "Is travel insurance necessary?",
      answer:
        "Yes. Cover high-altitude trekking and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q7",
      question: "When is the best time to go?",
      answer:
        "Spring (March–May) and autumn (September–November) usually offer the clearest mountain views.",
      visible: true,
    },
    {
      id: "q8",
      question: "Can I combine this with Gosainkunda?",
      answer:
        "Yes. Langtang–Gosainkunda and Helambu combinations are popular — ask us to customize your itinerary.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Langtang Valley?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Langtang Valley Trek 10 Days | Summit Seek",
  metaDescription:
    "Book the 10-day Langtang Valley trek with Summit Seek — Kyanjin Ri (4,773 m), Syabrubesi, permits, guide, teahouses & group discounts from US$550.",
};
