import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_LO_MANTHANG: TrekPageContent = {
  coverImageUrl: img("photo-1464822759023-fed622ff2c3b", 2000),
  coverTitle: "Lo Manthang Trek - 12 Days",
  coverSubtitle:
    "From Pokhara to the Forbidden Kingdom — Lo Manthang’s walled capital, arid Upper Mustang trails, monasteries, caves, and a Muktinath finale.",
  heroMainImageUrl: img("photo-1464822759023-fed622ff2c3b", 2000),
  heroSideImage1Url: img("photo-1483728642387-6c3bdd6c93e5", 900),
  heroSideImage2Url: img("photo-1585409677983-0f6c41ca9c3b", 900),
  breadcrumbLabel: "Mustang Region · Lo Manthang",
  title: "Lo Manthang Trek - 12 Days",
  regionLabel: "Mustang Region",
  rating: 5,
  reviewCount: 18,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 1600,
  compareAtPrice: 1790,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "11% OFF",
  shortTripBadge: "Restricted Area",
  durationLabel: "12 Days",
  difficultyLabel: "Moderate",
  groupSizeLabel: "1–12",
  bookingNote:
    "Private and small-group departures from Pokhara. Package includes Pokhara–Jomsom flights (or jeep as preferred), licensed guide, porter (2:1), trek meals, teahouses, Upper Mustang RAP and ACAP/TIMS as required. Licensed agency + guide mandatory in the restricted area.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 1790, visible: true },
    { id: "gd2", paxLabel: "2-3 pax", price: 1600, visible: true },
    { id: "gd3", paxLabel: "4-6 pax", price: 1490, visible: true },
    { id: "gd4", paxLabel: "7-12 pax", price: 1390, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "12 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Moderate", visible: true },
    { id: "f3", label: "Max Altitude", value: "4,023 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Pokhara", visible: true },
    { id: "f5", label: "Region", value: "Upper Mustang", visible: true },
    { id: "f6", label: "Group Size", value: "1–12", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Culture", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The Lo Manthang Trek is a focused 12-day journey into Upper Mustang’s Forbidden Kingdom — arid desert landscapes, Tibetan-Buddhist culture, caves, rock paintings, monasteries, and the walled capital of Lo Manthang itself.\n\nStarting from Pokhara, you fly (or drive) to Jomsom, trek via Kagbeni and Chele/Chuile through Syangboche, Ghami, and Dhakmar to Lo Manthang for a full exploration day, then return via Ghami and Chilling with a sacred stop at Muktinath before flying back to Pokhara.\n\nExpect Annapurna and Dhaulagiri panoramas, wind-sculpted cliffs, and culture closer to Tibet than to Nepal’s green mid-hills. Summit Seek includes RAP/ACAP, guide, porter (2:1), trek meals, teahouses, and clear group pricing. Shorter than the classic 14-day Upper Mustang package — ideal when Lo Manthang is your main goal.",
  overviewImageUrl: img("photo-1483728642387-6c3bdd6c93e5"),
  highlightsHeading: "Highlights",
  highlights: [
    "Walled capital of Lo Manthang — the Forbidden Kingdom",
    "Arid Upper Mustang desert landscapes and high rock hills",
    "Monasteries, gompas, caves, and Tibetan-Buddhist heritage",
    "Views of Annapurna and Dhaulagiri ranges",
    "Scenic Pokhara–Jomsom mountain flight",
    "Exploration day in Lo Manthang and nearby sites",
    "Sacred Muktinath Temple on the return",
    "Focused 12-day itinerary from Pokhara to Pokhara",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Pokhara–Jomsom transport by flight or private vehicle as preferred",
    "All meals on trek (breakfast, lunch, dinner) plus hot drinks as listed",
    "Best available teahouse lodging during the trek",
    "Professional English-speaking licensed guide",
    "Porter support (typically 2 guests : 1 porter)",
    "Upper Mustang RAP, ACAP, and TIMS paperwork as required",
    "Sleeping bag / down jacket / poles support if needed",
    "Travel and rescue coordination support; taxes and service charges",
  ],
  whyHeading: "Why choose the Lo Manthang trek?",
  whyPoints: [
    "Direct focus on Lo Manthang without a longer 14-day loop",
    "Authentic Tibetan culture in a restricted Himalayan kingdom",
    "Moderate altitude with a full exploration day in the capital",
    "Starts and ends in Pokhara — clean flight logistics",
    "Includes Muktinath for a spiritual finale",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "Graded moderate. Suitable for fit trekkers with some multi-day hiking experience. Days often run 4–7 hours on dry, windy, rocky or sandy trails above 3,000 m, with a high point around 4,023 m.\n\nA licensed guide and Upper Mustang RAP are mandatory. Travel insurance covering helicopter evacuation is required.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train 4–6 weeks with long walks, stairs, and light cardio",
    "Break in boots; pack strong sun and wind protection",
    "Carry a buff for dust and warm layers for cool nights",
    "Bring water purification and blister care",
    "Buy insurance covering trekking to ~4,500 m and helicopter evacuation",
    "Arrive Pokhara a day early for briefing and permit processing",
  ],
  itineraryHeading: "12-day itinerary",
  itineraryIntro:
    "Flight and walking times are estimates and vary with weather — Jomsom flights are often morning-only and can delay. Lodge names (Chuile/Chele, Chilling) may vary with local spelling and availability. Your Summit Seek guide can adjust the plan for safety and comfort.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Pokhara – Jomsom flight – Kagbeni",
      maxAltitude: "2,810 m",
      meals: "Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Scenic flight from Pokhara to Jomsom (~20 minutes) with Annapurna views, then trek toward Kagbeni, gateway to Upper Mustang. Overnight in Kagbeni.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Kagbeni – Chuile (Chele)",
      maxAltitude: "≈ 3,050 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Enter the restricted area along the Kali Gandaki corridor to Chuile/Chele (~7 hours). Overnight in Chuile.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Chuile – Syangboche",
      maxAltitude: "≈ 3,800 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Continue through arid high country to Syangboche (~6 hours). Overnight in Syangboche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Syangboche – Ghami",
      maxAltitude: "≈ 3,520 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Trek to Ghami with monastery visit and desert-ridge scenery (~6 hours). Overnight in Ghami.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Ghami – Dhakmar",
      maxAltitude: "≈ 3,820 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Shorter day through dramatic red cliffs and high rock hills to Dhakmar (~4 hours). Overnight in Dhakmar.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Dhakmar – Lo Manthang",
      maxAltitude: "3,840 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Reach the walled capital Lo Manthang with Dhaulagiri views along the way (~6 hours). Overnight in Lo Manthang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Explore Lo Manthang",
      maxAltitude: "3,840 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Full exploration day — monasteries, palace area, landscapes, and nearby caves/gompas as conditions allow. Overnight in Lo Manthang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Lo Manthang – Ghami",
      maxAltitude: "≈ 3,520 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Begin the return trek to Ghami (~7 hours). Overnight in Ghami.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Ghami – Chilling",
      maxAltitude: "≈ 3,050 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Continue descending toward Chilling (~6 hours). Overnight in Chilling.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Chilling – Muktinath",
      maxAltitude: "3,760 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Trek to sacred Muktinath Temple — holy for Hindus and Buddhists (~6 hours). Overnight near Muktinath.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Muktinath – Jomsom",
      maxAltitude: "2,730 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Descend to Jomsom via windy Kali Gandaki trails (~7 hours). Overnight in Jomsom.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Jomsom – Pokhara flight",
      maxAltitude: "822 m",
      meals: "Breakfast",
      accommodation: "— (Pokhara)",
      description:
        "Morning scenic flight back to Pokhara (weather permitting). Trip ends in Pokhara. End of the Lo Manthang journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best in March–May and September–November for clear views and comfortable temperatures. Private and joining groups of 1–12 are welcome. Winter can bring snow and blocked trails; monsoon brings slippery paths and flight risk despite the rain shadow.",
  availabilityNotes: [
    "Private and customizable start dates from Pokhara",
    "Licensed guide and Upper Mustang RAP mandatory",
    "Porter included typically 2 clients : 1 porter",
    "Jomsom flights are weather-dependent — buffer days help",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Extra Pokhara hotel nights",
      description: "Buffer nights before Day 1 or after Day 12 for flights.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Kathmandu connection package",
      description: "Add Kathmandu hotels and airport transfers around your Pokhara trek.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Jeep instead of Jomsom flight",
      description: "Replace flight sectors with private jeep when preferred or weather-bound.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a4",
      title: "Tiji Festival timing",
      description: "Align Lo Manthang stay with the May festival when dates allow.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Pokhara–Jomsom transport by flight or private vehicle as preferred",
    "All meals during the trek (breakfast, lunch, dinner) and hot drinks as listed",
    "Teahouse / lodge accommodation during the trek",
    "Professional English-speaking licensed guide",
    "Porter (typically 2 guests : 1 porter)",
    "Upper Mustang Restricted Area Permit, ACAP, and TIMS as required",
    "Necessary paperwork, taxes, VAT, and service charges",
    "Travel and rescue arrangement support if required (paid by your insurance)",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "International flights and Nepal visa fees",
    "Lunch and dinner in Pokhara",
    "Kathmandu / extra Pokhara hotels outside the trek package",
    "Travel / medical insurance and emergency evacuation costs",
    "Personal expenses (phone, mineral water, bar bills, hot shower, battery charge)",
    "Extra porters and personal gear beyond listed support",
    "Tips for guides and porters",
    "Costs from flight cancellations, roadblocks, or force majeure",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "High Himalayan light toward Mustang country",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1483728642387-6c3bdd6c93e5"),
      caption: "Arid ridgelines of the Upper Mustang rain shadow",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1585409677983-0f6c41ca9c3b"),
      caption: "Dramatic approaches into the Kali Gandaki",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Open plateau atmosphere near Lo Manthang",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May and September–November usually offer the clearest mountain views and the most comfortable trail conditions for this 12-day Lo Manthang journey.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude",
      body: "The trek exceeds 3,000 m for much of the route, with a maximum around 4,023 m. Use the Lo Manthang exploration day, drink water, and tell your guide early if you feel unwell.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Moderate. Rocky and sandy trails, wind, and long days — achievable with good fitness, acclimatization, and an experienced local guide.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Permits",
      body: "Upper Mustang Restricted Area Permit plus ACAP (and TIMS as applicable). Summit Seek arranges paperwork with your licensed guide.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack for strong sun, wind, dust, and cool nights above 3,000 m. Porters carry main bags; keep water, layers, documents, and camera in a daypack.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Windcheater / waterproof shell",
        "Down jacket",
        "Wool / fleece layers and trekking pants",
        "Woolen gloves and warm hiking socks",
        "Sun hat and scarf / buff",
        "Light hiking cotton layers for warmer sections",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Hiking boots or sturdy trekking shoes",
        "Trekking poles",
        "Sleeping bag (provided/rental as arranged)",
        "Headlamp or flashlight",
        "Daypack",
        "Wash towel",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "UV sunglasses",
        "High-SPF sunscreen",
        "Personal toiletries (biodegradable soap)",
        "Basic personal first-aid kit",
        "Water bottles + purification tablets",
        "Snacks and energy bars",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance details",
        "Cash for personal trail extras",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "RAP / ACAP / TIMS processing and licensed guiding team",
    "Sleeping bag / down jacket / pole support if needed",
    "Flight or jeep logistics Pokhara–Jomsom",
    "Advice on festival timing and Kathmandu add-ons",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Lo Manthang trek?",
      answer:
        "A 12-day Upper Mustang trek from Pokhara focused on the walled capital Lo Manthang, with arid trails, monasteries, and a Muktinath return via Jomsom.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Moderate. Expect long dry days above 3,000 m and a high point around 4,023 m. Prior multi-day hiking helps.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This Summit Seek listing starts at US$1,600 for 2–3 pax (US$1,790 solo; US$1,490 for 4–6; US$1,390 for 7–12).",
      visible: true,
    },
    {
      id: "q4",
      question: "What permits do I need?",
      answer:
        "Upper Mustang Restricted Area Permit plus ACAP (and TIMS as applicable). Summit Seek arranges these with a licensed guide.",
      visible: true,
    },
    {
      id: "q5",
      question: "How is this different from the 14-day Upper Mustang trek?",
      answer:
        "This 12-day version is a tighter Pokhara–Pokhara itinerary focused on reaching and exploring Lo Manthang, then returning via Muktinath.",
      visible: true,
    },
    {
      id: "q6",
      question: "Is travel insurance necessary?",
      answer:
        "Yes. Cover high-altitude trekking and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q7",
      question: "When is the best time to go?",
      answer:
        "March–May and September–November usually offer the best weather and clearest mountain views.",
      visible: true,
    },
    {
      id: "q8",
      question: "Are Jomsom flights reliable?",
      answer:
        "Morning flights are common but weather can cancel them. Buffer time helps; jeep alternatives may be available at extra cost.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Lo Manthang?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Lo Manthang Trek 12 Days | Summit Seek",
  metaDescription:
    "Book the 12-day Lo Manthang trek from Pokhara with Summit Seek — Forbidden Kingdom, RAP & ACAP, guide, porter, meals & group discounts from US$1,390.",
};
