import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_LOBUCHE_PEAK: TrekPageContent = {
  coverImageUrl: img("photo-1486870591958-9b9d0d1dda99", 2000),
  coverTitle: "Lobuche Peak Climbing with Everest Base Camp Trek - 18 Days",
  coverSubtitle:
    "Technical Khumbu trekking peak (Lobuche East, 6,119 m) combined with Everest Base Camp and Kala Patthar — steep snow and ice via High Camp, with Sherpa culture and Mahalangur panoramas.",
  heroMainImageUrl: img("photo-1486870591958-9b9d0d1dda99", 2000),
  heroSideImage1Url: img("photo-1464822759023-fed622ff2c3b", 900),
  heroSideImage2Url: img("photo-1519681393784-d120267933ba", 900),
  breadcrumbLabel: "Everest Region · Peak Climbing",
  title: "Lobuche Peak Climbing with Everest Base Camp Trek - 18 Days",
  regionLabel: "Everest Region",
  rating: 5,
  reviewCount: 3,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 2499,
  compareAtPrice: 2699,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "7% OFF",
  shortTripBadge: "EBC + 6,000 m Peak",
  durationLabel: "18 Days",
  difficultyLabel: "Challenging",
  groupSizeLabel: "2+",
  bookingNote:
    "Private and small-group departures. Package includes Kathmandu hotels (BB as listed), Lukla flights, licensed trekking & climbing guide (Sherpa), porters, trek meals, teahouse lodging, tented high camp, Lobuche East climbing permit, and Sagarmatha National Park fees. More technical than Pokalde — crampons, ice axe, and fixed-rope skills apply on summit day.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "2 pax", price: 2699, visible: true },
    { id: "gd2", paxLabel: "3-5 pax", price: 2499, visible: true },
    { id: "gd3", paxLabel: "6-10 pax", price: 2349, visible: true },
    { id: "gd4", paxLabel: "11-15 pax", price: 2199, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "18 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Challenging", visible: true },
    { id: "f3", label: "Max Altitude", value: "6,119 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Khumbu / Everest", visible: true },
    { id: "f6", label: "Group Size", value: "2 onwards", visible: true },
    { id: "f7", label: "Activities", value: "Trek & Climbing", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "Lobuche Peak sits beside the Khumbu Glacier with two main summits — Lobuche East and Lobuche West. Lobuche East (about 6,119 m) is the climb most teams attempt; West is less frequently climbed. From high camp you ascend via the southeast ridge — steep snow and ice that rewards solid crampon and ice-axe technique.\n\nThis 18-day package pairs the classic Everest Base Camp trek with a Lobuche East summit. After Lukla, Phakding, Namche, Tengboche, and Dingboche (with acclimatization), you reach Lobuche, visit Everest Base Camp and Kala Patthar (~5,545 m), then move to Lobuche High Camp (~5,400 m) for the summit push before descending via Pangboche and Namche to Lukla.\n\nExpect Sherpa hospitality, Tengboche Monastery, Thukla memorials, and panoramas of Everest, Lhotse, Nuptse, Ama Dablam, Makalu, and Cho Oyu. Summit Seek includes flights as listed, permits, climbing Sherpa, meals, lodging, group climbing support, and clear group pricing.",
  overviewImageUrl: img("photo-1464822759023-fed622ff2c3b"),
  highlightsHeading: "Highlights",
  highlights: [
    "Summit Lobuche East Peak (6,119 m) — technical Khumbu trekking peak",
    "Everest Base Camp and Kala Patthar viewpoints included",
    "Steep snow/ice southeast ridge with fixed ropes and climbing Sherpa",
    "Tengboche Monastery and Sherpa village culture",
    "Thukla Pass memorials and Khumbu Glacier approaches",
    "Views of Everest, Lhotse, Nuptse, Ama Dablam, Makalu & Cho Oyu",
    "Ideal step up from Pokalde for climbers building 6,000 m skills",
    "Scenic Lukla flights bookending the journey",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport transfers as listed",
    "Kathmandu hotel nights with breakfast as listed",
    "Kathmandu–Lukla flights both ways (via Manthali if required by season)",
    "Teahouse lodging on trek; tented high camp on climb days",
    "All meals during trek and camping as listed",
    "Licensed trekking guide and climbing Sherpa",
    "Lobuche East climbing permit and Sagarmatha National Park fees",
    "Porters (shared as listed); staff insurance; emergency heli coordination",
  ],
  whyHeading: "Why choose Lobuche East with EBC?",
  whyPoints: [
    "Combines iconic EBC / Kala Patthar with a real 6,000 m summit",
    "More technical than Pokalde — strong skills builder before Island Peak",
    "Built-in acclimatization via Namche, Dingboche, EBC, and Kala Patthar",
    "Summit panoramas across the Mahalangur Himal",
    "Clear private and group pricing with climbing support included",
  ],
  beginnersHeading: "Is this climb good for beginners?",
  beginnersBody:
    "Best for fit trekkers who already have multi-day Himalayan experience above ~4,000–5,000 m and want a technical step beyond easier peaks like Pokalde. Summit day uses crampons, ice axe, and fixed ropes on steep snow/ice — prior basic mountaineering practice helps.\n\nA licensed climbing guide is required. Travel insurance covering high-altitude climbing and helicopter evacuation is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train 8+ weeks with long hikes, stairs, and cardio (2+ months ideal)",
    "Prior trek experience above 4,000–5,000 m strongly recommended",
    "Practice steep ups/downs; consider intro ice/crampon skills if new",
    "Pack for cold nights at Lobuche, Gorak Shep, and high camp",
    "Buy insurance covering climbing to 6,200 m+ and heli evacuation",
    "Arrive Kathmandu for briefing, permits, and personal gear rental",
  ],
  itineraryHeading: "18-day itinerary",
  itineraryIntro:
    "Based on the classic EBC + Lobuche East High Camp routing. Lukla flights may operate via Manthali in peak season. Summit day depends on weather and conditions — your climbing Sherpa may adjust.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,400 m",
      meals: "—",
      accommodation: "Hotel in Kathmandu",
      description:
        "Airport meet-and-greet and hotel transfer. Rest or light city stroll. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Kathmandu preparation & climb briefing",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Trip orientation with your guide — passport, photos, and insurance check. Gear shopping or rental as needed. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Fly Lukla – trek to Phakding",
      maxAltitude: "2,840 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Scenic flight to Lukla (~35–40 min), then trek along the Dudh Koshi to Phakding (~3–4 hours / ~6 km). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Trek Phakding – Namche Bazaar",
      maxAltitude: "3,440 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Via Monjo / Jorsale and the Hillary Bridge into Namche Bazaar (~5–6 hours / ~7–8 km). First Everest glimpses. Overnight in Namche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Acclimatization day at Namche Bazaar",
      maxAltitude: "3,440 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Rest day with optional hikes to Khunde, Khumjung, or Everest View Hotel. Overnight in Namche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Trek Namche – Tengboche",
      maxAltitude: "3,870 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Ridge trail with Ama Dablam and Everest views to Tengboche; visit Tengboche Monastery (~5–6 hours / ~10 km).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Trek Tengboche – Dingboche",
      maxAltitude: "4,360 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Via Deboche and Pangboche into alpine terrain to Dingboche (~5–6 hours / ~11–12 km). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Acclimatization day at Dingboche",
      maxAltitude: "4,360 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Optional hike toward Nangkartshang / Nagarjun Hill for views of Ama Dablam, Lhotse, and Makalu, then rest. Overnight in Dingboche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Trek Dingboche – Lobuche",
      maxAltitude: "4,940 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Via Dughla / Thukla Pass and climbers’ memorials along the Khumbu Glacier moraine to Lobuche (~5–6 hours / ~8 km).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Lobuche – Gorak Shep – Everest Base Camp",
      maxAltitude: "5,364 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Trek to Gorak Shep, day hike to Everest Base Camp (~5,364 m) beside the Khumbu Icefall, return to Gorak Shep (~7–8 hours). Overnight at Gorak Shep.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Kala Patthar sunrise – trek to Lobuche",
      maxAltitude: "5,545 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Early hike to Kala Patthar (~5,545 m) for Everest panoramas, then descend via Gorak Shep to Lobuche (~7–8 hours). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Lobuche – Lobuche High Camp",
      maxAltitude: "5,400 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Tented camp",
      description:
        "Rocky glacier approach to Lobuche High Camp (~5,400 m) (~3–4 hours). Rest, gear check, and early night before summit day.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Summit Lobuche East – return to High Camp",
      maxAltitude: "6,119 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Tented camp",
      description:
        "Pre-dawn summit push on snow/ice via the southeast ridge to Lobuche East (6,119 m) with views of Everest, Lhotse, Nuptse, Makalu, and Ama Dablam; descend to High Camp (~8–9 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "High Camp – Pangboche",
      maxAltitude: "3,930 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Descend via Lobuche and Pheriche approaches to Pangboche (~8–9 hours). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d15",
      dayLabel: "Day 15",
      title: "Trek Pangboche – Namche Bazaar",
      maxAltitude: "3,440 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Via Tengboche and Dudh Koshi forest trails back to Namche (~4–5 hours / ~15 km). Overnight in Namche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d16",
      dayLabel: "Day 16",
      title: "Trek Namche – Lukla",
      maxAltitude: "2,840 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Final trek day along the Dudh Koshi to Lukla (~6–7 hours / ~18 km). Celebrate with crew. Overnight in Lukla.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d17",
      dayLabel: "Day 17",
      title: "Fly Lukla – Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Morning flight to Kathmandu (or Manthali + drive). Hotel transfer and free afternoon. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d18",
      dayLabel: "Day 18",
      title: "Departure from Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "—",
      description:
        "Airport transfer for your international flight. End of the Lobuche Peak journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best in March–May and September–November for stable weather on the EBC trail and Lobuche summit. Private groups welcome. Allow buffers for Lukla flights.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Licensed climbing Sherpa required for the peak permit",
    "EBC and Kala Patthar included before the climb",
    "Lukla flights are weather-dependent — allow buffers",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Extra Kathmandu nights",
      description: "Buffer nights for Lukla delays or early arrivals.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Personal climbing gear rental",
      description:
        "Boots, crampons, harness, ice axe, helmet, and related kit in Kathmandu.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Personal climbing guide",
      description: "Dedicated climbing guide for your party on request.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport transfers as listed",
    "Kathmandu hotel nights with breakfast as listed",
    "Kathmandu–Lukla–Kathmandu flights (via Manthali if season requires)",
    "Teahouse lodging on trek; tented high camp on climb days",
    "All meals during the trek and camping as listed",
    "Licensed trekking guide and climbing Sherpa",
    "Lobuche East climbing permit, Sagarmatha National Park, and local fees",
    "Group climbing equipment (ropes, ice screws, snow bars as needed); porter support as listed",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "International airfare",
    "Nepal entry visa fees",
    "Personal clothing and personal climbing equipment",
    "Personal accident insurance and emergency evacuation costs (mandatory cover)",
    "Alcoholic beverages, laundry, and tips",
    "Extra Kathmandu hotel nights and optional city tours beyond the itinerary",
    "Hot showers, Wi-Fi, and charging on trek",
    "Lunch and dinner in Kathmandu (except as listed)",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "Glacier light near Lobuche and the Khumbu",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Alpine approaches on the Everest trail",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1519681393784-d120267933ba"),
      caption: "High Khumbu ridges toward Lobuche Peak",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Mountain panoramas above Namche and Tengboche",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May and September–November offer the most reliable windows for EBC heights and the Lobuche East summit. Spring brings rhododendron color; autumn often clearer skies.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & difficulty",
      body: "Highest point is Lobuche East at 6,119 m (Kala Patthar ~5,545 m; High Camp ~5,400 m). Overall grade is challenging — steep snow/ice on summit day plus long trek days.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Permits",
      body: "Sagarmatha National Park entry, Khumbu Pasang Lhamu Rural Municipality permit, TIMS as applicable, and NMA Lobuche East climbing permit. Summit Seek arranges these with your licensed climbing guide.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Routes",
      body: "Classic EBC trail to Lobuche and Gorak Shep, then Lobuche High Camp and the southeast ridge to Lobuche East. Descent via Pangboche and Namche to Lukla.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Porters carry main bags; keep water, layers, documents, and camera in a daypack. Personal climbing gear can often be rented in Kathmandu.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece mid-layer",
        "Down jacket",
        "Waterproof shell jacket and pants",
        "Warm gloves, hat, buff",
        "Sun hat and glacier sunglasses",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & climbing",
      items: [
        "Insulated mountaineering boots suitable for crampons",
        "Crampons",
        "Ice axe and climbing harness",
        "Helmet",
        "Trekking poles",
        "Gaiters and camp shoes",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Camp & health",
      items: [
        "Sleeping bag rated for cold high camps (−20°C class)",
        "Headlamp + spare batteries",
        "Water bottle + purification",
        "Personal first-aid & blister care",
        "SPF 50+ sunscreen and lip balm",
        "High-energy snacks",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies + passport photos",
        "Nepal visa as applicable",
        "Insurance covering climbing & heli evacuation",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Permit processing and licensed climbing Sherpa",
    "Porter logistics and staff insurance",
    "Tented high-camp arrangement and group climbing equipment",
    "Emergency helicopter coordination (insurance pays)",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is Lobuche Peak climbing with EBC?",
      answer:
        "An 18-day Khumbu trip combining the Everest Base Camp / Kala Patthar trail with a summit of Lobuche East Peak (6,119 m) via High Camp — a more technical climb than easier peaks like Pokalde.",
      visible: true,
    },
    {
      id: "q2",
      question: "Lobuche East or West — which peak do we climb?",
      answer:
        "This package targets Lobuche East, the more commonly climbed summit. Lobuche West is less frequently attempted and is not the default objective.",
      visible: true,
    },
    {
      id: "q3",
      question: "How difficult is Lobuche compared with Pokalde or Island Peak?",
      answer:
        "Lobuche East is more technical than Pokalde (steep snow/ice, fixed ropes). Many climbers use it as a step toward Island Peak or as a skills builder after EBC fitness.",
      visible: true,
    },
    {
      id: "q4",
      question: "How much does it cost?",
      answer:
        "This listing starts at US$2,499 for 3–5 pax (US$2,699 for 2; US$2,349 for 6–10; US$2,199 for 11–15). Market packages elsewhere often start near US$1,800–2,000 depending on inclusions.",
      visible: true,
    },
    {
      id: "q5",
      question: "What is the maximum altitude?",
      answer:
        "Lobuche East summit at 6,119 m. You also reach Kala Patthar (~5,545 m) and Everest Base Camp (~5,364 m).",
      visible: true,
    },
    {
      id: "q6",
      question: "Do we visit Everest Base Camp?",
      answer:
        "Yes. This itinerary includes an afternoon visit to Everest Base Camp from Gorak Shep, plus a Kala Patthar sunrise hike before the climb.",
      visible: true,
    },
    {
      id: "q7",
      question: "What permits are required?",
      answer:
        "Sagarmatha National Park entry, Khumbu rural municipality permit, TIMS as applicable, and an NMA Lobuche East climbing permit with a licensed climbing guide. Summit Seek arranges these.",
      visible: true,
    },
    {
      id: "q8",
      question: "Is travel insurance necessary?",
      answer:
        "Yes — covering high-altitude climbing and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q9",
      question: "When is the best time to go?",
      answer:
        "March–May and September–November usually offer the best weather for the trail and summit.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Lobuche Peak?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Lobuche Peak Climbing with EBC 18 Days | Summit Seek",
  metaDescription:
    "Book 18-day Lobuche East Peak climbing with EBC — 6,119 m summit, Kala Patthar, permits, climbing Sherpa, Lukla flights & group discounts from US$2,199.",
};
