import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_LOWER_DOLPO: TrekPageContent = {
  coverImageUrl: img("photo-1486870591958-9b9d0d1dda99", 2000),
  coverTitle: "Lower Dolpo Trek - 18 Days",
  coverSubtitle:
    "Remote Dolpo circuit — Dho Tarap, Numa La & Baga La, Ringmo, and turquoise Phoksundo Lake through Shey Phoksundo National Park.",
  heroMainImageUrl: img("photo-1486870591958-9b9d0d1dda99", 2000),
  heroSideImage1Url: img("photo-1506905925346-21bda4d32df4", 900),
  heroSideImage2Url: img("photo-1544735716-392fe2489ffa", 900),
  breadcrumbLabel: "Dolpo Region · Lower Dolpo",
  title: "Lower Dolpo Trek - 18 Days",
  regionLabel: "Dolpo Region",
  rating: 5,
  reviewCount: 11,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 2200,
  compareAtPrice: 2490,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "12% OFF",
  shortTripBadge: "Restricted Area",
  durationLabel: "18 Days",
  difficultyLabel: "Challenging",
  groupSizeLabel: "2–10",
  bookingNote:
    "Private and small-group departures. Package includes Kathmandu & Nepalgunj hotels as listed, Kathmandu–Nepalgunj–Juphal flights, licensed guide, porter (2:1), trek meals, teahouse/camping as listed, Lower Dolpo RAP, and Shey Phoksundo National Park permit. Not a beginner trek.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "2 pax", price: 2275, visible: true },
    { id: "gd2", paxLabel: "3 pax", price: 2240, visible: true },
    { id: "gd3", paxLabel: "4-6 pax", price: 2200, visible: true },
    { id: "gd4", paxLabel: "7-10 pax", price: 2100, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "18 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Challenging", visible: true },
    { id: "f3", label: "Max Altitude", value: "5,190 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Lower Dolpo", visible: true },
    { id: "f6", label: "Group Size", value: "2–10", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Culture", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Aug–Oct",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "Lower Dolpo is one of Nepal’s hidden western gems — a restricted, off-the-beaten-path journey behind the Dhaulagiri massif into Shey Phoksundo National Park, Bon Po and Tibetan-influenced villages, and the turquoise waters of Phoksundo Lake (3,611 m).\n\nThis 18-day itinerary flies Kathmandu–Nepalgunj–Juphal, treks via Dunai, Tarakot, Laini, and Nawarpani to Dho Tarap for acclimatization, then crosses Numa La (5,190 m) and Baga La (5,070 m) toward Ringmo and Phoksundo before descending to Shyanta and Juphal for the return flights.\n\nExpect 5–8 hour days, arid alpine scenery, rhododendron and juniper forests, wildlife in the national park, and deep cultural immersion. Summit Seek includes RAP and park permits, domestic flights as listed, guide, porter, trek meals, and clear group pricing. Shorter and less permit-costly than the full Upper Dolpo circuit — still challenging.",
  overviewImageUrl: img("photo-1506905925346-21bda4d32df4"),
  highlightsHeading: "Highlights",
  highlights: [
    "Turquoise Phoksundo Lake in Shey Phoksundo National Park",
    "Cross Numa La (5,190 m) and Baga La (5,070 m)",
    "Dho Tarap — high valley of Bon Po and Chaiba culture",
    "Remote villages: Dunai, Tarakot, Laini, Nawarpani, Ringmo",
    "Views of Dhaulagiri, Annapurna, Kanjirowa & arid Dolpo peaks",
    "Snow leopard country, blue sheep, and Himalayan wildlife habitat",
    "Off-the-beaten-path restricted-area adventure (opened 1991)",
    "Rain-shadow window that can work even in monsoon months",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport pick-up/drop and private transfers as listed",
    "Kathmandu hotel nights and Nepalgunj hotel as listed",
    "Kathmandu sightseeing day with city guide as listed",
    "Teahouse / homestay lodging plus tented camps on pass days",
    "Full-board meals during the trek (B-L-D)",
    "Experienced licensed local trekking guide and porter (2:1)",
    "Lower Dolpo RAP, Shey Phoksundo NP permit, and domestic flights",
    "Staff insurance, farewell dinner, duffel/kit support as arranged",
  ],
  whyHeading: "Why choose Lower Dolpo?",
  whyPoints: [
    "Phoksundo Lake without the full Upper Dolpo RAP cost",
    "Two dramatic high passes with Dhaulagiri panoramas",
    "Authentic Bon and Tibetan cultural immersion",
    "Quieter trails than Everest or Annapurna classics",
    "Challenging but shorter than the 24-day Upper Dolpo circuit",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "No — graded challenging. You need good fitness and ideally prior multi-day high-altitude hiking. Days average 5–8 hours with steep terrain and passes to 5,190 m.\n\nA licensed guide is mandatory in the restricted area. Travel insurance covering helicopter evacuation to 5,500 m+ is required.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train 8–12 weeks with long hikes, stairs, and strength work",
    "Break in boots; pack warm layers for cold high camps",
    "Carry poles, microspikes if icy, and blister care",
    "Practice packing light for remote teahouse/camping days",
    "Buy insurance covering high-altitude trekking and heli evacuation",
    "Arrive Kathmandu early for briefing, sightseeing, and permits",
  ],
  itineraryHeading: "18-day itinerary",
  itineraryIntro:
    "Flight and walking times are estimates and vary with weather — Juphal flights often delay. Lodge/camp stops may change with availability. Your Summit Seek guide can adjust for safety and acclimatization.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Welcome dinner",
      accommodation: "Hotel in Kathmandu",
      description:
        "Airport meet-and-greet and hotel transfer. Welcome dinner and trek briefing. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Kathmandu sightseeing & permits",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "UNESCO heritage tour (Pashupatinath, Boudhanath, Swayambhunath, Durbar Square) and trek preparation / permit processing. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Fly Kathmandu – Nepalgunj",
      maxAltitude: "150 m",
      meals: "Breakfast",
      accommodation: "Hotel in Nepalgunj",
      description:
        "Domestic flight to Nepalgunj (~1 hour). Afternoon free to explore. Overnight in Nepalgunj.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Fly Juphal – trek to Dunai",
      maxAltitude: "2,850 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Scenic flight to Juphal, then trek via terraces and gorges to Dunai with Dhaulagiri–Annapurna views (~2–3 hours). Overnight in Dunai.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Dunai – Tarakot",
      maxAltitude: "2,543 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Follow the Bheri River through gorges, bridges, and villages to hillside Tarakot (~5–6 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Tarakot – Laini",
      maxAltitude: "3,160 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Trek along Tarap Chu via Sandul Gompa with climbs and descents to Laini (~6–7 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Laini – Nawarpani",
      maxAltitude: "3,545 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Continue up the narrowing Tarap canyon to Nawarpani (~5–6 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Nawarpani – Dho Tarap",
      maxAltitude: "4,090 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Climb into the dry inner Himalayan valley to Dho Tarap — Bon Po and Chaiba culture (~7–8 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Acclimatization in Dho Tarap",
      maxAltitude: "4,090 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Rest and explore village life, monasteries, and traditions. Overnight in Dho Tarap.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Dho Tarap – Numa La Base Camp",
      maxAltitude: "4,440 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Tented camp",
      description:
        "Ascend the upper Tarap valley toward Numa La Base Camp (~6–7 hours). Overnight camp.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Cross Numa La – Pelung Tang",
      maxAltitude: "5,190 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Tented camp",
      description:
        "Hardest day — cross Numa La (5,190 m) with Dhaulagiri views, then descend to Pelung Tang. Overnight camp.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Cross Baga La – Dajok Tang",
      maxAltitude: "5,070 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Camp",
      description:
        "Cross Baga La (5,070 m) with Kanjirowa views, then descend to Dajok Tang (~6 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Dajok Tang – Ringmo",
      maxAltitude: "3,600 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Descend to Ringmo village near Phoksundo. Overnight in Ringmo.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Ringmo – Phoksundo Lake",
      maxAltitude: "3,611 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Short trek to turquoise Phoksundo Lake — monasteries, yak caravans, and lakeside overnight.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d15",
      dayLabel: "Day 15",
      title: "Phoksundo – Shyanta",
      maxAltitude: "2,520 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Descend via Chepka and cliffside trails to Shyanta (~5–6 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d16",
      dayLabel: "Day 16",
      title: "Shyanta – Juphal",
      maxAltitude: "2,320 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Final trek day back to Juphal airstrip village. Overnight in Juphal.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d17",
      dayLabel: "Day 17",
      title: "Fly Juphal – Nepalgunj – Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Fly to Nepalgunj and connect to Kathmandu (weather permitting). Farewell dinner as arranged. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d18",
      dayLabel: "Day 18",
      title: "Final departure",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "—",
      description:
        "Airport transfer for your international departure. End of the Lower Dolpo journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best in March–early May and August–October for clear views. Dolpo’s rain shadow can allow monsoon trekking with fewer crowds. Private groups of 2–10 are welcome. Build buffer days for Juphal flights.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Licensed guide and Lower Dolpo RAP mandatory",
    "Porter included typically 2 clients : 1 porter",
    "Juphal flights are weather-dependent — allow buffers",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Extra Kathmandu / Nepalgunj nights",
      description: "Buffer nights for flight delays or early arrivals.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Horse / mule support",
      description: "Riding horse or extra pack animals where trails allow.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Gear rental",
      description: "Sleeping bag, down jacket, poles, microspikes as needed.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport and hotel transfers by private vehicle as listed",
    "Twin-share Kathmandu hotel nights as listed",
    "Kathmandu city sightseeing with professional city guide as listed",
    "Nepalgunj hotel night as listed",
    "Teahouse / homestay lodging during the trek; tented camps on pass days as listed",
    "Full-board meals (breakfast, lunch, dinner) during the trek",
    "Experienced licensed local trekking guide and porter (2:1)",
    "Lower Dolpo Restricted Area Permit and Shey Phoksundo National Park permit",
    "Domestic flights Kathmandu–Nepalgunj–Juphal and return as listed",
    "Staff food, salary, accommodation, and insurance; farewell dinner; taxes",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "International airfare and Nepal visa fees",
    "Travel / medical insurance and emergency evacuation costs",
    "Extra hotel nights due to bad weather or early return",
    "Lunch and dinner in Kathmandu and Nepalgunj (except welcome/farewell as listed)",
    "Alcoholic drinks, bottled water, soft drinks, and personal snacks",
    "Personal trekking gear and clothing",
    "Tips for guide and porters",
    "Costs from flight cancellations, roadblocks, or force majeure",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "High alpine ridgelines toward remote Dolpo",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Wild mountain light near Phoksundo country",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Remote Himalayan valley approaches",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Open high-country atmosphere",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–early May and August–October usually offer the clearest views. Dolpo’s rain shadow can make monsoon trekking more viable than elsewhere in Nepal.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude",
      body: "Highest point is Numa La at 5,190 m; Baga La is about 5,070 m. Use the Dho Tarap rest day, hydrate, and tell your guide early if unwell.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Challenging. Long days, rugged terrain, and two high passes — good fitness and prior multi-day hiking experience strongly recommended.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Permits",
      body: "Lower Dolpo RAP (typically USD 20/week + USD 5/extra day) and Shey Phoksundo National Park permit. Far cheaper than Upper Dolpo RAP. Summit Seek arranges paperwork with your licensed guide.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack for cold high camps and dusty valley days. Porters carry main bags; keep water, layers, documents, and camera in a daypack.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Thermal base layers",
        "Fleece mid-layer",
        "Insulated / down jacket",
        "Waterproof windproof shell",
        "Hiking pants and light layers",
        "Sun hat, warm hat, gloves",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Camp shoes",
        "Trekking poles",
        "Microspikes (recommended for passes)",
        "25–35L daypack",
        "Sleeping bag rated for cold nights",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "High-SPF sunscreen & lip balm",
        "UV sunglasses",
        "Personal medications & blister care",
        "Water bottle + purification",
        "Headlamp + spare batteries",
        "Trail snacks",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance details (heli cover)",
        "Cash for personal trail extras",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "RAP / park permit processing and licensed guiding team",
    "Domestic flight booking assistance",
    "Duffel / kit support and SpO₂ checks as arranged",
    "Buffer-day planning around Juphal weather",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Lower Dolpo trek?",
      answer:
        "An 18-day restricted-area trek through western Nepal’s Dolpo — Dho Tarap, Numa La, Baga La, Ringmo, and turquoise Phoksundo Lake.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Challenging. Expect long days and two high passes (Numa La 5,190 m and Baga La 5,070 m). Prior multi-day hiking experience helps.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This Summit Seek listing starts at US$2,200 for 4–6 pax (US$2,275 for 2; US$2,240 for 3; US$2,100 for 7–10).",
      visible: true,
    },
    {
      id: "q4",
      question: "What is the maximum altitude?",
      answer:
        "Numa La Pass at 5,190 m. Baga La is about 5,070 m. Phoksundo Lake sits near 3,611 m.",
      visible: true,
    },
    {
      id: "q5",
      question: "What permits do I need?",
      answer:
        "Lower Dolpo Restricted Area Permit and Shey Phoksundo National Park permit. Summit Seek arranges these with a licensed guide.",
      visible: true,
    },
    {
      id: "q6",
      question: "How is this different from Upper Dolpo?",
      answer:
        "Lower Dolpo is shorter, focuses on Phoksundo via Numa La/Baga La, and uses a much cheaper RAP than the Upper Dolpo permit.",
      visible: true,
    },
    {
      id: "q7",
      question: "Is travel insurance necessary?",
      answer:
        "Yes. Cover high-altitude trekking to 5,500 m+ and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q8",
      question: "Are Juphal flights reliable?",
      answer:
        "They frequently delay or cancel for weather. Always build buffer days in Kathmandu / Nepalgunj.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Lower Dolpo?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Lower Dolpo Trek 18 Days | Summit Seek",
  metaDescription:
    "Book the 18-day Lower Dolpo trek with Summit Seek — Phoksundo Lake, Numa La & Baga La, RAP, flights, guide, meals & group discounts from US$2,100.",
};
