import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_LOWER_MUSTANG: TrekPageContent = {
  coverImageUrl: img("photo-1585409677983-0f6c41ca9c3b", 2000),
  coverTitle: "Lower Mustang Trek - 8 Days",
  coverSubtitle:
    "Kagbeni to Muktinath, Marpha apple country, Dhumba Lake, and Tatopani hot springs — a shorter Kali Gandaki journey with Annapurna and Dhaulagiri views.",
  heroMainImageUrl: img("photo-1585409677983-0f6c41ca9c3b", 2000),
  heroSideImage1Url: img("photo-1483728642387-6c3bdd6c93e5", 900),
  heroSideImage2Url: img("photo-1506905925346-21bda4d32df4", 900),
  breadcrumbLabel: "Mustang Region · Lower Mustang",
  title: "Lower Mustang Trek - 8 Days",
  regionLabel: "Mustang Region",
  rating: 5,
  reviewCount: 16,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 645,
  compareAtPrice: 799,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "19% OFF",
  shortTripBadge: "Short Trek",
  durationLabel: "8 Days",
  difficultyLabel: "Easy",
  groupSizeLabel: "1–12",
  bookingNote:
    "Private and small-group departures from Pokhara. Package includes licensed guide, porter (2:1), trek meals, teahouse lodging, ACAP/TIMS as required, and jeep transfers Pokhara–Kagbeni and Tatopani–Pokhara as listed. No Upper Mustang restricted permit needed.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 799, visible: true },
    { id: "gd2", paxLabel: "2-3 pax", price: 645, visible: true },
    { id: "gd3", paxLabel: "4-6 pax", price: 595, visible: true },
    { id: "gd4", paxLabel: "7-12 pax", price: 545, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "8 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Easy", visible: true },
    { id: "f3", label: "Max Altitude", value: "3,760 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Pokhara", visible: true },
    { id: "f5", label: "Region", value: "Lower Mustang", visible: true },
    { id: "f6", label: "Group Size", value: "1–12", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Culture", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "Lower Mustang is a shorter, gentler introduction to the Kali Gandaki corridor — jeep into Kagbeni, climb to sacred Muktinath (3,760 m), then descend through Jomsom, turquoise Dhumba Lake, apple-famous Marpha, historic Tukuche, Larjung, Ghasa, and the hot springs at Tatopani before driving back to Pokhara.\n\nExpect Thakali hospitality, whitewashed villages, barren high plains that soften into orchards and subtropical forest, and big views of Annapurna, Nilgiri, and Dhaulagiri — without the Upper Mustang restricted permit.\n\nThis 8-day Summit Seek package suits beginners and time-limited travelers who still want culture, scenery, and spiritual highlights. Includes licensed guide, porter (2:1), trek meals, teahouses, ACAP/TIMS, and jeep transfers as listed. Add Kathmandu nights or a Pokhara–Jomsom flight upgrade on request.",
  overviewImageUrl: img("photo-1483728642387-6c3bdd6c93e5"),
  highlightsHeading: "Highlights",
  highlights: [
    "Scenic jeep ride to Kagbeni via waterfalls and mountain valleys",
    "Sacred Muktinath Temple — holy for Hindus and Buddhists",
    "Thakali culture in Jomsom and whitewashed Marpha (apple country)",
    "Turquoise Dhumba Lake with prayer flags and cliffs",
    "Historic Tukuche and quiet Larjung with Nilgiri–Dhaulagiri views",
    "Rupse Waterfall and natural hot springs at Tatopani",
    "Annapurna, Nilgiri & Dhaulagiri panoramas",
    "No Upper Mustang restricted permit required",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "English-speaking government-registered guide",
    "Three meals a day during the trek as listed",
    "Teahouse / lodge accommodation on the trail",
    "Shared or private jeep transfers as arranged",
    "Porter support (typically one between two persons)",
    "ACAP and TIMS permits as required",
    "First-aid kit and guide expenses covered",
    "Farewell dinner in Pokhara as arranged",
  ],
  whyHeading: "Why choose Lower Mustang?",
  whyPoints: [
    "Shorter and easier than Upper Mustang or classic circuits",
    "Muktinath pilgrimage plus apple-village culture",
    "Great scenery without a restricted-area RAP fee",
    "Ideal for beginners and families with good fitness",
    "Hot springs finale at Tatopani before Pokhara",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "Yes — graded easy to gentle moderate. Most days are 3–7 hours on established trails. The high point is Muktinath at 3,760 m, so drink water, ascend steadily, and tell your guide if you feel unwell.\n\nTravel insurance covering trekking and helicopter evacuation is still required.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Walk regularly for 2–4 weeks before departure",
    "Break in comfortable hiking shoes or light boots",
    "Pack sun protection — the Kali Gandaki valley is bright and windy",
    "Bring a buff for dust and a light warm layer for cooler nights",
    "Carry water purification and blister care",
    "Buy travel insurance covering trekking above 3,000 m",
  ],
  itineraryHeading: "8-day itinerary",
  itineraryIntro:
    "Drive and walking times are estimates and vary with road and weather conditions. Lodge stops may change with availability. Your Summit Seek guide can adjust the plan for comfort and safety.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Drive Pokhara – Kagbeni",
      maxAltitude: "2,810 m",
      meals: "Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Jeep from Pokhara via Nayapul, Kusma, Beni, Tatopani, and Ghasa to Kagbeni (~8–10 hours). Terraced farms, waterfalls, and a shift to arid Kali Gandaki cliffs. Overnight in Kagbeni.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Trek Kagbeni – Muktinath",
      maxAltitude: "3,760 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Ascend through Thakali villages toward sacred Muktinath (3,760 m) with Annapurna, Nilgiri, and Dhaulagiri views (~6–7 hours). Visit the temple complex. Overnight near Muktinath / Ranipauwa.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Trek Muktinath – Jomsom",
      maxAltitude: "2,730 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Descend via Jharkot and Kagbeni toward Jomsom across windy Kali Gandaki plains (~4–5 hours). Overnight in Jomsom.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Dhumba Lake – Marpha",
      maxAltitude: "2,670 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Side visit to turquoise Dhumba Lake, then continue through orchards and Chairo to whitewashed Marpha — famous for apples and cobbled streets (~3–4 hours). Overnight in Marpha.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Marpha – Tukuche – Larjung",
      maxAltitude: "2,535 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Trek via historic Tukuche and Kobang to quiet Larjung with Dhaulagiri and Nilgiri views (~5–6 hours). Overnight in Larjung.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Larjung – Ghasa",
      maxAltitude: "2,010 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Descend via Kalopani and Lete toward greener forests and Ghasa (~5–6 hours). Overnight in Ghasa.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Ghasa – Tatopani via Rupse",
      maxAltitude: "1,200 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Continue downhill past Rupse Waterfall and Dana to Tatopani. Soak in natural hot springs (~6–7 hours). Overnight in Tatopani.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Drive Tatopani – Pokhara",
      maxAltitude: "822 m",
      meals: "Breakfast",
      accommodation: "— (Pokhara) / farewell dinner",
      description:
        "Scenic jeep back to Pokhara via Beni (~6–7 hours). Farewell dinner in Pokhara as arranged. End of the Lower Mustang journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best in March–May and September–November for clear views and comfortable temperatures. Private and joining groups of 1–12 are welcome. Winter is quieter but colder; monsoon trails can be slippery.",
  availabilityNotes: [
    "Private and customizable start dates from Pokhara",
    "ACAP and TIMS only — no Upper Mustang RAP",
    "Porter included typically 2 clients : 1 porter",
    "Jeep roads can be bumpy beyond Beni — buffer time helps",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Kathmandu nights + transfers",
      description: "Add arrival/departure hotel nights and airport transfers.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Pokhara–Jomsom flight upgrade",
      description: "Replace part of the jeep approach with a scenic flight (weather permitting).",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Extra Pokhara hotel night",
      description: "Buffer night after Day 8 for late arrivals or lakeside rest.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "English-speaking government-registered trekking guide",
    "Three meals a day during the trek as listed",
    "Teahouse / lodge accommodation during the trek",
    "Shared or private jeep transfers as arranged (Pokhara–Kagbeni and return sector)",
    "Porter (typically one between two persons)",
    "ACAP and TIMS permits as required",
    "Guide expenses, first-aid kit, and applicable taxes",
    "Farewell dinner in Pokhara as arranged",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "International flights and Nepal visa fees",
    "Kathmandu / Pokhara hotels outside the trek package (unless added)",
    "Travel / medical insurance and emergency rescue costs",
    "Personal expenses (bar bills, charging, Wi‑Fi, hot showers, laundry)",
    "Bottled drinks and personal snacks",
    "Tips for guide and porter",
    "Flight upgrades or costs from road/weather delays",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1585409677983-0f6c41ca9c3b"),
      caption: "Mountain approaches toward the Kali Gandaki",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1483728642387-6c3bdd6c93e5"),
      caption: "High arid light near Lower Mustang",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Open Himalayan valleys and ridgelines",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Classic Nepal mountain scenery",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May and September–November usually offer the clearest Annapurna–Dhaulagiri views and the most comfortable walking weather.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude",
      body: "Highest point is Muktinath at 3,760 m. Ascend steadily, drink water, and tell your guide early if you feel headache, nausea, or dizziness.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Easy overall with one steeper day to Muktinath. Suitable for beginners with basic fitness who can walk 4–7 hours on some days.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Permits",
      body: "ACAP and TIMS are typically required. Upper Mustang Restricted Area Permit is not needed on this lower route.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack light for warm valley days and cooler evenings at Muktinath. Porters carry main bags; keep water, layers, documents, and camera in a daypack.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece mid-layer",
        "Light down / insulated jacket",
        "Windproof shell",
        "Trekking pants",
        "Sun hat, warm hat, gloves, buff for dust",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in hiking shoes or light boots",
        "Camp shoes / sandals (useful at Tatopani)",
        "Trekking poles (optional)",
        "20–30L daypack",
        "Headlamp",
        "Reusable water bottle",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "SPF sunscreen & lip balm",
        "UV sunglasses",
        "Personal medications & blister care",
        "Water purification",
        "Hand sanitizer & toilet paper",
        "Trail snacks",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance details",
        "Cash for personal trail extras",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Permit processing and licensed guiding team",
    "Jeep logistics Pokhara–Kagbeni and return",
    "Farewell dinner arrangement in Pokhara",
    "Advice on flight upgrades and Kathmandu add-ons",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Lower Mustang trek?",
      answer:
        "An 8-day jeep-and-trek journey from Pokhara to Kagbeni, Muktinath, Marpha, and Tatopani — culture and scenery without entering Upper Mustang.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Easy for most fit beginners. The hardest day is usually the climb to Muktinath (3,760 m).",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This Summit Seek listing starts at US$645 for 2–3 pax (US$799 solo; US$595 for 4–6; US$545 for 7–12).",
      visible: true,
    },
    {
      id: "q4",
      question: "Do I need an Upper Mustang permit?",
      answer:
        "No. This route stays in Lower Mustang / Annapurna Conservation Area — typically ACAP and TIMS only.",
      visible: true,
    },
    {
      id: "q5",
      question: "Where does the trek start?",
      answer:
        "From Pokhara. Day 1 is a long jeep to Kagbeni. Kathmandu connections can be added on request.",
      visible: true,
    },
    {
      id: "q6",
      question: "Is travel insurance necessary?",
      answer:
        "Yes. Cover trekking above 3,000 m and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q7",
      question: "When is the best time to go?",
      answer:
        "March–May and September–November usually offer the best weather and mountain views.",
      visible: true,
    },
    {
      id: "q8",
      question: "Can I upgrade to flights?",
      answer:
        "Yes — Pokhara–Jomsom flights can replace part of the jeep approach when weather allows (extra cost).",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Lower Mustang?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Lower Mustang Trek 8 Days | Summit Seek",
  metaDescription:
    "Book the 8-day Lower Mustang trek with Summit Seek — Muktinath, Marpha, Tatopani hot springs, guide, meals & group discounts from US$545.",
};
