import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_LUXURY_EVEREST_BASE_CAMP: TrekPageContent = {
  coverImageUrl: img("photo-1454496522488-7a8e488e8606", 2000),
  coverTitle: "Luxury Everest Base Camp Trek - 12 Days",
  coverSubtitle:
    "Premium Khumbu lodges on a refined 12-day EBC itinerary — Namche, Everest View Hotel, Phortse, Dingboche, Lobuche, Base Camp, and sunrise from Kala Patthar.",
  heroMainImageUrl: img("photo-1454496522488-7a8e488e8606", 2000),
  heroSideImage1Url: img("photo-1544735716-392fe2489ffa", 900),
  heroSideImage2Url: img("photo-1486870591958-9b9d0d1dda99", 900),
  breadcrumbLabel: "Everest Region · Luxury Trek",
  title: "Luxury Everest Base Camp Trek - 12 Days",
  regionLabel: "Everest Region",
  rating: 5,
  reviewCount: 5,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 4590,
  compareAtPrice: 4990,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "8% OFF",
  shortTripBadge: "Luxury Lodges",
  durationLabel: "12 Days",
  difficultyLabel: "Moderate",
  groupSizeLabel: "2+",
  bookingNote:
    "Private luxury departures. Package includes Kathmandu premium hotel nights (BB as listed), Lukla flights (via Manthali if season requires), Sagarmatha & Khumbu permits, licensed guide, private porter support, full-board trek meals, and carefully selected comfort/premium lodges on the trail. Ideal if you want the classic EBC route with upgraded rest nights.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 4990, visible: true },
    { id: "gd2", paxLabel: "2-3 pax", price: 4590, visible: true },
    { id: "gd3", paxLabel: "4-6 pax", price: 4390, visible: true },
    { id: "gd4", paxLabel: "7+ pax", price: 4190, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "12 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Moderate", visible: true },
    { id: "f3", label: "Max Altitude", value: "5,550 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Everest / Khumbu", visible: true },
    { id: "f6", label: "Group Size", value: "2 onwards", visible: true },
    { id: "f7", label: "Style", value: "Luxury lodges + guide", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "Luxury Everest Base Camp Trek – 12 Days follows the iconic Khumbu trail to Everest Base Camp (5,364 m) and Kala Patthar (~5,550 m) with upgraded comfort: premium lodge nights where available, private guide attention, and a refined pacing that still respects acclimatization.\n\nAfter the scenic flight into Lukla you trek to Phakding and Namche, hike to Hotel Everest View (one of the world’s highest luxury hotels) for coffee and panoramas, then continue via quieter Phortse and Upper Pangboche into Dingboche. A Nangkartshang / Nagarjun acclimatization hike prepares you for Lobuche, Gorak Shep, Everest Base Camp beside the Khumbu Icefall, and sunrise on Kala Patthar before descending via Pheriche, Tengboche, Namche, and Lukla.\n\nExpect Sherpa hospitality, Tengboche and Pangboche monasteries, rhododendron forests in season, and views of Everest, Lhotse, Nuptse, Ama Dablam, and Pumori. Summit Seek includes Lukla flights, permits, luxury-level lodge selection, full-board trek meals, guide and porter, and clear group pricing.",
  overviewImageUrl: img("photo-1544735716-392fe2489ffa"),
  highlightsHeading: "Highlights",
  highlights: [
    "Luxury / premium lodge nights on the classic EBC trail",
    "Stand at Everest Base Camp (5,364 m) beneath the Khumbu Icefall",
    "Sunrise from Kala Patthar (~5,550 m) — best Everest panoramas",
    "Acclimatization hike to Hotel Everest View above Namche",
    "Quieter Phortse village routing toward Dingboche",
    "Nangkartshang viewpoint hike for Makalu and Ama Dablam views",
    "Tengboche & Pangboche monasteries and Sherpa culture",
    "Scenic Lukla flights and private guide / porter support",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport transfers by private vehicle as listed",
    "Kathmandu premium hotel nights with breakfast as listed",
    "Kathmandu–Lukla flights both ways (via Manthali if season requires)",
    "Hand-picked comfort / luxury lodges on trek (twin sharing)",
    "Full-board meals on trek days; fresh fruit as arranged",
    "Licensed English-speaking guide and dedicated porter support",
    "Sagarmatha National Park and Khumbu local permits",
    "Oximeter checks, first-aid kit, emergency heli coordination (insurance pays)",
  ],
  whyHeading: "Why choose the luxury 12-day EBC?",
  whyPoints: [
    "Same legendary Base Camp and Kala Patthar goals with upgraded sleep quality",
    "Built-in Namche and Dingboche acclimatization days",
    "Phortse variant for quieter trails and village atmosphere",
    "Everest View Hotel stop adds a true luxury highland moment",
    "Ideal for travelers who want EBC without basic teahouse-only nights",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "Suitable for fit first-time Himalayan trekkers who can walk 5–7 hours on consecutive days with a daypack. Graded Moderate — altitude to 5,550 m is the main challenge, not technical climbing.\n\nPrior multi-day hiking helps. Travel insurance covering high altitude and helicopter evacuation is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train 6–8 weeks with long hikes, stairs, and cardio",
    "Arrive Kathmandu 1–2 days early for Lukla flight buffers",
    "Break in boots; practice downhill with poles",
    "Pack for cold nights at Lobuche and Gorak Shep",
    "Buy insurance covering heli evacuation to 6,000 m+",
    "Confirm luxury lodge room preferences (twin / private where available)",
  ],
  itineraryHeading: "12-day itinerary",
  itineraryIntro:
    "Based on the refined 12-day EBC routing via Phortse with luxury lodge upgrades. Peak-season Lukla flights often operate via Manthali. Lodge names may vary by availability while maintaining comfort standards.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Fly Lukla – trek to Phakding",
      maxAltitude: "2,860 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Premium lodge / teahouse",
      description:
        "Scenic flight to Lukla (~30–35 min). Meet crew, then trek along the Dudh Koshi via Chheplung and Ghat to Phakding (~3 hours / ~8 km). Overnight comfort lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Trek Phakding – Namche Bazaar",
      maxAltitude: "3,445 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Premium lodge in Namche",
      description:
        "Via Benkar, Monjo, and Jorsale; enter Sagarmatha National Park, cross the Hillary Bridge, and climb to Namche Bazaar (~5–6 hours / ~11 km). Overnight premium lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Acclimatization: Hotel Everest View",
      maxAltitude: "3,880 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Premium lodge in Namche",
      description:
        "Morning hike (~2 hours / ~3.5 km) to Hotel Everest View — coffee and panoramas of Everest, Ama Dablam, Lhotse, and Nuptse — then return to Namche to rest. Overnight lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Trek Namche – Phortse",
      maxAltitude: "3,860 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Comfort lodge in Phortse",
      description:
        "Via Sanasa and Mong La (~3,973 m) with views of Cholatse and Taboche, descend to Phortse Thanga, cross the Dudh Koshi, and climb to quiet Phortse village (~6–7 hours / ~6.5 km).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Trek Phortse – Dingboche",
      maxAltitude: "4,410 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Premium lodge in Dingboche",
      description:
        "Through rhododendron forest to Upper Pangboche (ancient monastery), onward via Shomare with Ama Dablam views into the Imja Valley and Dingboche (~5–6 hours / ~12 km).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Acclimatization: Nangkartshang viewpoint",
      maxAltitude: "5,083 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Premium lodge in Dingboche",
      description:
        "Optional hike to Nangkartshang / Nagarjun viewpoint (~3 hours / ~2.3 km) for Makalu, Island Peak, Ama Dablam, and Lobuche Peak views; visit local monastery en route. Overnight Dingboche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Trek Dingboche – Lobuche",
      maxAltitude: "4,940 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Comfort lodge in Lobuche",
      description:
        "Via Dughla / Thukla Pass (~4,830 m) and climbers’ memorials along the Khumbu Glacier moraine to Lobuche (~4–5 hours / ~8 km). Overnight lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Lobuche – Gorak Shep – Everest Base Camp",
      maxAltitude: "5,364 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge in Gorak Shep",
      description:
        "Trek over glacier moraine to Gorak Shep, then day hike to Everest Base Camp (~5,364 m) beside the Khumbu Icefall; return to Gorak Shep (~6–7 hours / ~8 km). Overnight lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Kala Patthar sunrise – trek to Pheriche",
      maxAltitude: "5,550 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Comfort lodge in Pheriche",
      description:
        "Pre-dawn climb to Kala Patthar (~5,550 m) for Everest sunrise, breakfast at Gorak Shep, then descend via Lobuche and Dughla to Pheriche (~6–7 hours / ~12 km).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Trek Pheriche – Namche Bazaar",
      maxAltitude: "3,445 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Premium lodge in Namche",
      description:
        "Via Pangboche and Tengboche Monastery, then descend through Phunki Thenga to Namche (~6–7 hours / ~14 km). Overnight premium lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Trek Namche – Lukla",
      maxAltitude: "2,860 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Premium lodge in Lukla",
      description:
        "Final descent via Monjo, Phakding, and Chheplung to Lukla (~6–7 hours / ~13 km). Celebrate with crew. Overnight lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Fly Lukla – Kathmandu",
      maxAltitude: "1,350 m",
      meals: "Breakfast; farewell dinner as listed",
      accommodation: "Premium hotel in Kathmandu",
      description:
        "Morning flight to Kathmandu (or Manthali + drive). Hotel transfer and optional farewell dinner. End of the luxury Everest Base Camp journey.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best in March–May and September–November for clear views and reliable Lukla flying. Private luxury groups welcome. Allow buffer nights in Kathmandu for weather delays.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Luxury lodge inventory is limited — book early in peak season",
    "Lukla flights are weather-dependent — allow buffers",
    "Optional Kathmandu–Lukla heli upgrade on request",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Kathmandu–Lukla helicopter",
      description: "Skip Manthali road transfer in peak season (sharing basis).",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Extra Kathmandu luxury nights",
      description: "Buffer nights at a 4–5★ hotel before or after the trek.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Single-room upgrade",
      description: "Private room on trek nights where lodges allow.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport transfers by private vehicle as listed",
    "Kathmandu premium hotel nights with breakfast as listed",
    "Kathmandu–Lukla–Kathmandu flights (via Manthali if season requires)",
    "Comfort / luxury lodge accommodation on trek (twin sharing)",
    "Full-board meals during the trek as listed",
    "Licensed English-speaking guide and porter support",
    "Sagarmatha National Park and Khumbu Pasang Lhamu permits",
    "Sleeping bag / down jacket loan if arranged; oximeter; first-aid; taxes",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "International airfare and Nepal visa fees",
    "Travel insurance including helicopter evacuation (mandatory)",
    "Personal expenses: laundry, charging, hot showers, Wi-Fi, bottled water",
    "Alcoholic drinks, desserts beyond inclusions, and bar bills",
    "Tips for guide, porter, and drivers",
    "Extra nights from early arrival, late departure, or flight delays",
    "Kathmandu sightseeing entrance fees (unless added)",
    "Anything not listed under inclusions",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1454496522488-7a8e488e8606"),
      caption: "High Himalayan light toward Everest country",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Classic Khumbu approaches to Base Camp",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "Glacier light near Lobuche and Gorak Shep",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Alpine trails above Namche and Tengboche",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May and September–November offer the most reliable windows for luxury lodge availability, clear Kala Patthar views, and Lukla flights.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & difficulty",
      body: "Highest point is Kala Patthar at ~5,550 m; Everest Base Camp is 5,364 m. Graded Moderate — long walking days plus altitude.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Permits",
      body: "Sagarmatha National Park entry and Khumbu Pasang Lhamu Rural Municipality permit. Summit Seek arranges these with your guide.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Routes",
      body: "Lukla → Phakding → Namche → Everest View → Phortse → Dingboche → Lobuche → Gorak Shep / EBC → Kala Patthar → Pheriche → Namche → Lukla → Kathmandu.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Porters carry main bags; keep water, layers, documents, and camera in a daypack. Luxury lodges are warmer than basic teahouses, but Lobuche and Gorak Shep nights remain cold.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece mid-layer",
        "Down jacket",
        "Waterproof shell jacket and pants",
        "Warm gloves, hat, buff",
        "Sun hat and glacier sunglasses",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear",
      items: [
        "Sturdy waterproof trekking boots",
        "Trekking poles",
        "Gaiters (optional)",
        "Camp shoes / slippers",
        "Warm socks",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Camp & health",
      items: [
        "Sleeping bag rated for cold high lodges (or use company loan)",
        "Headlamp + spare batteries",
        "Water bottle + purification",
        "Personal first-aid & blister care",
        "SPF 50+ sunscreen and lip balm",
        "High-energy snacks",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies + passport photos",
        "Nepal visa as applicable",
        "Insurance covering high altitude & heli evacuation",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Luxury lodge booking and Lukla flight coordination",
    "Permit processing and licensed guide / porter team",
    "Sleeping bag and down jacket loan if arranged",
    "Emergency helicopter coordination (insurance pays)",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What makes this a luxury EBC trek?",
      answer:
        "You follow the classic Base Camp and Kala Patthar goals on a 12-day plan, but sleep in carefully selected comfort/premium lodges, with upgraded Kathmandu hotels, private guide attention, and fuller inclusions versus a basic teahouse package.",
      visible: true,
    },
    {
      id: "q2",
      question: "How does the 12-day route differ from 14-day EBC?",
      answer:
        "It is a tighter schedule with the Phortse variant and two key acclimatization days (Namche / Everest View and Dingboche / Nangkartshang), still reaching EBC and Kala Patthar.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This luxury listing starts at US$4,590 for 2–3 pax (US$4,990 for 1; US$4,390 for 4–6; US$4,190 for 7+). Standard teahouse EBC packages elsewhere often start near US$1,000–1,200.",
      visible: true,
    },
    {
      id: "q4",
      question: "What is the maximum altitude?",
      answer:
        "Kala Patthar at about 5,550 m. Everest Base Camp is 5,364 m. Nangkartshang viewpoint on the acclimatization day can exceed 5,000 m.",
      visible: true,
    },
    {
      id: "q5",
      question: "Do we stay at Hotel Everest View?",
      answer:
        "Day 3 includes a hike and coffee stop at Hotel Everest View above Namche. Overnight remains in a premium Namche lodge unless you request an Everest View night as an add-on.",
      visible: true,
    },
    {
      id: "q6",
      question: "What permits are required?",
      answer:
        "Sagarmatha National Park entry and Khumbu Pasang Lhamu Rural Municipality permit. Summit Seek arranges these.",
      visible: true,
    },
    {
      id: "q7",
      question: "Is travel insurance necessary?",
      answer:
        "Yes — covering high-altitude trekking and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q8",
      question: "When is the best time to go?",
      answer:
        "March–May and September–November usually offer the best weather and lodge availability. Book early for luxury rooms in peak months.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for luxury Everest Base Camp?",
  ctaBody: `Tell us your preferred dates and room preferences — we will confirm luxury lodge availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Luxury Everest Base Camp Trek 12 Days | Summit Seek",
  metaDescription:
    "Book 12-day Luxury Everest Base Camp Trek — premium lodges, EBC & Kala Patthar, Phortse route, permits, guide, Lukla flights & group rates from US$4,190.",
};
