import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_MAKALU_BC: TrekPageContent = {
  coverImageUrl: img("photo-1544735716-392fe2489ffa", 2000),
  coverTitle: "Makalu Base Camp Trek - 20 Days",
  coverSubtitle:
    "Remote Makalu–Barun wilderness trek to the foot of the world’s fifth-highest peak — Shipton La, Barun Valley meadows, and views of Makalu, Everest’s Kangshung face, Lhotse, and Chamlang.",
  heroMainImageUrl: img("photo-1544735716-392fe2489ffa", 2000),
  heroSideImage1Url: img("photo-1464822759023-fed622ff2c3b", 900),
  heroSideImage2Url: img("photo-1486870591958-9b9d0d1dda99", 900),
  breadcrumbLabel: "Makalu Region · Base Camp",
  title: "Makalu Base Camp Trek - 20 Days",
  regionLabel: "Makalu Region",
  rating: 5,
  reviewCount: 10,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 2390,
  compareAtPrice: 2790,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "14% OFF",
  shortTripBadge: "National Park",
  durationLabel: "20 Days",
  difficultyLabel: "Difficult",
  groupSizeLabel: "1–12",
  bookingNote:
    "Private and small-group departures. Package includes Kathmandu hotel (BB as listed), Kathmandu–Tumlingtar flights, road transfers as listed, licensed guide, porters, trek meals, teahouse/tent lodging as listed, TIMS, and Makalu–Barun National Park permits. Expect 6–8 hour walking days on remote trails.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "2 pax", price: 2650, visible: true },
    { id: "gd2", paxLabel: "3-5 pax", price: 2390, visible: true },
    { id: "gd3", paxLabel: "6-10 pax", price: 2190, visible: true },
    { id: "gd4", paxLabel: "11-12 pax", price: 1990, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "20 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Difficult", visible: true },
    { id: "f3", label: "Max Altitude", value: "4,870–5,000 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Makalu–Barun / East Nepal", visible: true },
    { id: "f6", label: "Group Size", value: "1–12", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Hiking", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–Apr & Oct–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The Makalu Base Camp Trek is a high-altitude journey through rhododendron forests, Gurung and Rai villages, and the wild Barun Valley to the foot of Mount Makalu (8,481 m) — the world’s fifth-highest peak — inside Makalu–Barun National Park.\n\nThis 20-day itinerary flies Kathmandu–Tumlingtar, drives to Chichila, then treks via Num, Seduwa, and Tashigaon to Khongma for acclimatization. You cross Shipton La (~4,210 m) into Dobate, continue through Yangle Kharka, Merek, and Shersong, and day-hike Makalu Base Camp (~4,870–5,000 m) with panoramas of Makalu’s towering cliffs, hanging glaciers, and — on clear days — Everest’s Kangshung face, Lhotse, Chamlang, and distant Kanchenjunga.\n\nQuieter than Everest or Annapurna, the route is demanding (often 6–8 hours and 15–20 km a day) and suits experienced trekkers who want wilderness, red-panda habitat, and unspoiled scenery. Summit Seek includes flights and transfers as listed, park permits, guide, porters, meals, and clear group pricing.",
  overviewImageUrl: img("photo-1464822759023-fed622ff2c3b"),
  highlightsHeading: "Highlights",
  highlights: [
    "Makalu Base Camp at the foot of the world’s 5th-highest peak",
    "Makalu–Barun National Park wilderness and biodiversity",
    "Cross Shipton La (~4,210 m) into the Barun Valley",
    "Views of Makalu, Everest (Kangshung face), Lhotse, Chamlang & more",
    "Off-the-beaten-path trails with few other trekkers",
    "Rhododendron forests, farmlands, and remote village culture",
    "Scenic Kathmandu–Tumlingtar flight and Arun Valley approaches",
    "Possible red panda and Himalayan wildlife habitat",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport pick-up and drop as listed",
    "Twin-sharing Kathmandu hotel with breakfast as listed",
    "Kathmandu–Tumlingtar–Kathmandu flights",
    "Road transfers to and from the trail as listed",
    "Twin-share teahouse or tent lodging during the trek as listed",
    "Three meals a day on trek (breakfast, lunch, dinner) plus tea/coffee as listed",
    "Licensed guide and necessary porters with insurance",
    "TIMS and Makalu–Barun National Park permits; taxes and service charges",
  ],
  whyHeading: "Why choose Makalu Base Camp?",
  whyPoints: [
    "True wilderness alternative to crowded Everest trails",
    "Fifth-highest mountain base camp with huge peak panoramas",
    "Shipton La high-pass adventure into Barun Valley",
    "Rich forests, meadows, and remote village culture",
    "Ideal for experienced trekkers seeking solitude",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "No — graded difficult. Expect long days, steep climbs, early high-pass crossings (Shipton La ~4,210 m), and altitudes near 5,000 m with limited infrastructure above Tashigaon.\n\nPrior multi-day trek experience and strong fitness are strongly recommended. Travel insurance covering helicopter evacuation is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train 6+ weeks with long hikes, stairs, and cardio",
    "Prior Himalayan trek experience strongly advised",
    "Break in waterproof boots; pack for cold high camps",
    "Carry snacks, purification, and a solid first-aid kit",
    "Buy insurance covering remote Himalayan helicopter evacuation",
    "Arrive Kathmandu with buffer for Tumlingtar flights",
  ],
  itineraryHeading: "20-day itinerary",
  itineraryIntro:
    "Based on the classic Mission Eco Trek–style Makalu Base Camp 20-day routing. Flight and walking times vary with weather — Tumlingtar flights and jeep roads can delay. Lodging may be teahouse or tent in remote sections. Day 16 fills the natural descent between Mumbuk and Tashigaon.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,400 m",
      meals: "—",
      accommodation: "Hotel in Kathmandu",
      description:
        "Airport meet-and-greet and hotel transfer. Trek briefing. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Kathmandu sightseeing & trek preparation",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Optional heritage sightseeing and gear/permit preparation with your guide. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Fly Tumlingtar – drive to Chichila",
      maxAltitude: "1,840 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge / Teahouse",
      description:
        "Scenic flight to Tumlingtar, then jeep drive into the hills to Chichila (~1,840 m). Overnight in Chichila.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Trek Chichila – Num",
      maxAltitude: "1,500 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Walk through ridge villages and farmland toward Num on the Arun approaches (~5–6 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Trek Num – Seduwa",
      maxAltitude: "1,540 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Steep descent toward the Arun, cross the river, then climb to Seduwa / Sedhuwa and national-park entry (~6–7 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Trek Seduwa – Tashigaon",
      maxAltitude: "2,070 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Terraces, forest, and hillside villages to Tashigaon — often the last major permanent settlement (~4–5 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Trek Tashigaon – Khongma",
      maxAltitude: "3,560 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge / Camp",
      description:
        "Steep climb through forest and ridges to Khongma Danda (~6–7 hours). Overnight at Khongma.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Acclimatization day at Khongma",
      maxAltitude: "3,560 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge / Camp",
      description:
        "Rest day with optional short hike toward Khongma La viewpoints before the high-pass crossing.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Cross Shipton La – trek to Dobate",
      maxAltitude: "4,210 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge / Camp",
      description:
        "Cross Shipton La (~4,210 m) and neighboring high cols, then descend through rhododendron toward Dobate (~3,650 m) (~6–7 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Trek Dobate – Yangle Kharka",
      maxAltitude: "3,600 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge / Camp",
      description:
        "Steep forest descent into Barun Valley, then riverside meadows to Yangle / Yangri Kharka (~5–6 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Trek Yangle Kharka – Merek",
      maxAltitude: "4,500 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge / Camp",
      description:
        "Ascend the Barun Valley through herder camps and alpine terrain toward Merek / Langmale area (~5–6 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Trek Merek – Shersong",
      maxAltitude: "4,650 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge / Camp",
      description:
        "Continue toward Shersong with growing views of Makalu and surrounding giants. Overnight near Shersong.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Day hike Makalu Base Camp – return Shersong",
      maxAltitude: "4,870–5,000 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge / Camp",
      description:
        "Day tour to Makalu Base Camp (~4,870–5,000 m) for close views of Makalu’s cliffs and glaciers; optional higher viewpoint if conditions allow. Overnight back at Shersong.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Trek Shersong – Yangle Kharka",
      maxAltitude: "3,600 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge / Camp",
      description:
        "Begin the return descent through the Barun Valley to Yangle Kharka (~6–7 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d15",
      dayLabel: "Day 15",
      title: "Trek Yangle Kharka – Mumbuk / Dobate",
      maxAltitude: "3,650 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge / Camp",
      description:
        "Climb out of the Barun toward Mumbuk / Dobate forest camps (~6–7 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d16",
      dayLabel: "Day 16",
      title: "Trek Mumbuk – Khongma",
      maxAltitude: "3,560 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge / Camp",
      description:
        "Recross the high cols toward Khongma Danda (~5–6 hours). Overnight at Khongma.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d17",
      dayLabel: "Day 17",
      title: "Trek Khongma – Tashigaon",
      maxAltitude: "2,070 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Long descent through forest to Tashigaon (~4–5 hours). Overnight in Tashigaon.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d18",
      dayLabel: "Day 18",
      title: "Trek Tashigaon – Num",
      maxAltitude: "1,500 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Continue via Seduwa and the Arun crossing toward Num (~6–7 hours). Overnight in Num.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d19",
      dayLabel: "Day 19",
      title: "Trek / drive Num – Chichila – Tumlingtar",
      maxAltitude: "1,840 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge / Hotel in Tumlingtar",
      description:
        "Walk or jeep toward Chichila, then transfer to Tumlingtar for the next day’s flight. Overnight in Tumlingtar.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d20",
      dayLabel: "Day 20",
      title: "Fly Tumlingtar – Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "—",
      description:
        "Morning flight to Kathmandu. End of the Makalu Base Camp journey with Summit Seek — hotel transfer or onward departure as arranged.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best in March–April and October–November for clear, stable weather. Private groups of 1–12 are welcome. Build buffer days for Tumlingtar flights.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Licensed guide; TIMS and national-park permits required",
    "Porter support included as listed",
    "Tumlingtar flights are weather-dependent — allow buffers",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Extra Kathmandu nights",
      description: "Buffer nights for flight delays or early arrivals.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Barun Valley / Sherpani Col extension",
      description: "Longer wilderness or high-col variants on request.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Gear rental",
      description: "Sleeping bag, down jacket, and poles as needed.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport pick-up and drop transfer as listed",
    "Twin-sharing hotel with breakfast in Kathmandu as listed",
    "Kathmandu–Tumlingtar–Kathmandu flights",
    "Transportation to and from trek start/end as listed",
    "Twin-share teahouse or tent lodging during the trek as listed",
    "Three meals a day on trek (breakfast, lunch, dinner) including tea/coffee as listed",
    "Licensed trekking guide and necessary porters (salary, meals, insurance)",
    "TIMS and Makalu–Barun National Park permits; government taxes and service charge",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "International airfare",
    "Nepal entry visa fees",
    "Lunch and dinner in Kathmandu",
    "Kathmandu city tour (unless added)",
    "Personal trekking equipment",
    "Alcoholic and soft drinks, laundry, phone, personal expenses",
    "Travel / rescue insurance (mandatory)",
    "Tips for guide and porters",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "High eastern Himalaya toward Makalu country",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Alpine approaches in Makalu–Barun",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "Remote ridges and high valleys",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Wilderness trails in east Nepal",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–April and October–November usually offer the clearest views and most stable weather for Makalu Base Camp.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & permits",
      body: "Highest point is Makalu Base Camp (~4,870–5,000 m); Shipton La is about 4,210 m. You need TIMS and Makalu–Barun National Park entry. Summit Seek arranges these with your guide.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Difficult — long days (often 6–8 hours), steep forest climbs, high passes early in the trek, and remote lodging. Strong fitness required.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Lodging & food",
      body: "Mix of teahouses and simple camps in higher sections. Menus are basic (dal bhat, noodles, soups). Hot shower and charging cost extra where available. Pack snacks.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "This remote route has limited shops — pack thoroughly. Porters carry main bags; keep water, layers, documents, snacks, and camera in a daypack.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece mid-layer",
        "Down / insulated jacket",
        "Waterproof shell jacket and pants",
        "Trekking pants and warm socks",
        "Warm hat, sun hat, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Camp shoes",
        "Trekking poles",
        "Duffel + 25–35L daypack",
        "Sleeping bag (cold high camps)",
        "Headlamp + spare batteries / power bank",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "SPF sunscreen, lip balm, UV sunglasses",
        "Personal first-aid kit & blister care",
        "Water bottle + purification",
        "Trail snacks and energy bars",
        "Hand sanitizer & toilet paper",
        "Insect repellent for lower valleys",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies + passport photos",
        "Nepal visa as applicable",
        "Travel insurance details (heli evacuation)",
        "Cash for personal trail extras",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Permit processing and licensed guiding team",
    "Porter logistics and staff insurance",
    "Advice on Barun / Sherpani Col extensions",
    "Flight buffer and Tumlingtar transfer coordination",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Makalu Base Camp trek?",
      answer:
        "A 20-day remote trek in Makalu–Barun National Park to the base of Mt. Makalu (8,481 m), crossing Shipton La and the Barun Valley.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Difficult. Expect 6–8 hour days, high passes around 4,210 m, and altitudes near 5,000 m. Best for experienced, fit trekkers.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This listing starts at US$2,390 for 3–5 pax (US$2,650 for 2; US$2,190 for 6–10; US$1,990 for 11–12). Market packages often range about US$1,950–2,890.",
      visible: true,
    },
    {
      id: "q4",
      question: "What is the maximum altitude?",
      answer:
        "Makalu Base Camp is typically about 4,870 m; day viewpoints may reach around 5,000 m depending on conditions.",
      visible: true,
    },
    {
      id: "q5",
      question: "What permits are required?",
      answer:
        "TIMS and Makalu–Barun National Park entry permits. Summit Seek arranges these with your licensed guide.",
      visible: true,
    },
    {
      id: "q6",
      question: "When is the best time to go?",
      answer:
        "March–April and October–November usually offer the clearest, most stable weather.",
      visible: true,
    },
    {
      id: "q7",
      question: "Is travel insurance necessary?",
      answer:
        "Yes — covering remote trekking and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q8",
      question: "Can I see Everest on this trek?",
      answer:
        "Yes — on clear days from high points you can see Everest’s Kangshung face along with Lhotse, Chamlang, and Makalu.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Makalu Base Camp?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Makalu Base Camp Trek 20 Days | Summit Seek",
  metaDescription:
    "Book the 20-day Makalu Base Camp trek with Summit Seek — Shipton La, Barun Valley, permits, flights, guide, porter, meals & group discounts from US$1,990.",
};
