import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_MAKALU_BARUN: TrekPageContent = {
  coverImageUrl: img("photo-1464822759023-fed622ff2c3b", 2000),
  coverTitle: "Makalu Barun Valley Trek - 18 Days",
  coverSubtitle:
    "Remote eastern Nepal wilderness through Makalu–Barun National Park — Shipton La, the paradise Barun Valley, and Makalu Base Camp (4,870 m) beneath the world’s fifth-highest peak.",
  heroMainImageUrl: img("photo-1464822759023-fed622ff2c3b", 2000),
  heroSideImage1Url: img("photo-1544735716-392fe2489ffa", 900),
  heroSideImage2Url: img("photo-1486870591958-9b9d0d1dda99", 900),
  breadcrumbLabel: "Makalu Region · Barun Valley",
  title: "Makalu Barun Valley Trek - 18 Days",
  regionLabel: "Makalu Region",
  rating: 5,
  reviewCount: 7,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 1990,
  compareAtPrice: 2290,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "13% OFF",
  shortTripBadge: "National Park",
  durationLabel: "18 Days",
  difficultyLabel: "Strenuous",
  groupSizeLabel: "1–6",
  bookingNote:
    "Private and small-group departures. Package includes Kathmandu–Tumlingtar flights, jeep transfers via Khandbari–Num–Seduwa, licensed guide, porter support, trek meals, teahouse/lodge lodging as listed, TIMS, and Makalu–Barun National Park permits. Expect 5–6 hour walking days on remote trails.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "2 pax", price: 2190, visible: true },
    { id: "gd2", paxLabel: "3-5 pax", price: 1990, visible: true },
    { id: "gd3", paxLabel: "6 pax", price: 1850, visible: true },
    { id: "gd4", paxLabel: "7+ pax", price: 1690, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "18 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Strenuous", visible: true },
    { id: "f3", label: "Max Altitude", value: "4,870 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Makalu–Barun / East Nepal", visible: true },
    { id: "f6", label: "Group Size", value: "1–6", visible: true },
    { id: "f7", label: "Activities", value: "Tea-house Trekking", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Spring & Autumn",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The Makalu Barun Valley Trek is one of Nepal’s most strenuous, least-crowded long routes — an off-the-beaten-path journey through eastern Nepal’s Makalu–Barun National Park to the foot of Mt. Makalu (8,463 m), the world’s fifth-highest peak.\n\nThis 18-day itinerary flies Kathmandu–Tumlingtar, transfers to Khandbari, then jeep to Num and Seduwa for park entry. You climb via Tashigaon to Khongma, cross Ghenguru La, Shipton La (~4,216 m), and Keke La into Dobate, then descend into the legendary Barun Valley — often called a paradise on earth — via Yangle Kharka and Langmale Kharka to Makalu Base Camp (4,870 m). An exploration day opens viewpoints toward Barun Pokhari, Shersong, and higher lookouts when conditions allow.\n\nExpect incredible biodiversity (rhododendrons, orchids, medicinal herbs; habitat for red panda and snow leopard), empty trails compared with Everest, and basic but improving teahouse lodging. Summit Seek includes flights and jeep logistics as listed, permits, guide, porter, meals, and clear group pricing. Prefer a longer buffer itinerary? See our 20-day Makalu Base Camp package.",
  overviewImageUrl: img("photo-1544735716-392fe2489ffa"),
  highlightsHeading: "Highlights",
  highlights: [
    "Barun Valley — remote alpine paradise beneath Makalu",
    "Makalu Base Camp (4,870 m) at the fifth-highest peak",
    "Cross Ghenguru La, Shipton La (~4,216 m), and Keke La",
    "Makalu–Barun National Park biodiversity & wildlife habitat",
    "Views of Makalu, Chamlang, Baruntse, Peak 6 & Peak 7",
    "Quiet trails far from Everest crowds",
    "Tea-house trek with local Rai / Sherpa culture",
    "Scenic Tumlingtar flight and Khandbari gateway",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Kathmandu–Tumlingtar flights and return as listed",
    "Reserved jeep transfers Tumlingtar–Khandbari–Num–Seduwa and return",
    "Teahouse / lodge lodging during the trek as listed",
    "Breakfast, lunch, and dinner on trek days as listed",
    "Licensed guide and porter support with insurance",
    "TIMS and Makalu–Barun National Park entrance fees",
    "Khandbari hotel nights as listed in the itinerary",
    "Clear group discounts and private departure options",
  ],
  whyHeading: "Why choose Makalu Barun Valley?",
  whyPoints: [
    "Shorter than our 20-day Makalu BC package — focused Barun corridor",
    "High-pass adventure into one of Nepal’s wildest valleys",
    "Base-camp night plus a full exploration day",
    "True solitude compared with commercial Everest trails",
    "Ideal for experienced trekkers with strong fitness",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "No — graded strenuous, comparable in challenge to Kanchenjunga Base Camp for many walkers. You cross multiple 4,000 m+ passes, climb steeply to Khongma, and sleep at 4,870 m.\n\nExcellent physical fitness and prior high-altitude trek experience are strongly recommended. Travel insurance covering helicopter evacuation is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train 6+ weeks with long hikes, stairs, and cardio",
    "Prior Himalayan trek experience strongly advised",
    "Break in boots; consider micro-spikes for snowy passes",
    "Carry water filter/Steripen, power bank, and trail snacks",
    "Buy insurance covering remote Himalayan helicopter evacuation",
    "Withdraw enough cash before leaving Khandbari (no ATMs on trail)",
  ],
  itineraryHeading: "18-day itinerary",
  itineraryIntro:
    "Based on the classic Barun Valley / Makalu Base Camp routing via Khandbari and Seduwa. Flight and jeep times vary with weather and road conditions. Lodge stops may change with availability.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Fly Kathmandu – Tumlingtar – transfer to Khandbari",
      maxAltitude: "1,036 m",
      meals: "—",
      accommodation: "Hotel in Khandbari",
      description:
        "Buddha Air (or similar) ~30-minute flight to Tumlingtar. Jeep/auto to Khandbari hotel. Meet guide/porter, pack, and brief for the trek. Overnight in Khandbari.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Drive Khandbari – Num – trek to Seduwa",
      maxAltitude: "1,540 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Seduwa",
      description:
        "Reserved jeep toward Num (~4 hours), continue toward Chamla Kharka, then walk down to the Arun, cross the suspension bridge, and climb to Seduwa (~1,540 m). Register TIMS and Makalu–Barun NP entry. Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Trek Seduwa – Tashigaon",
      maxAltitude: "2,070 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Tashigaon",
      description:
        "Mostly uphill via Chyaksedanda to Tashigaon / Tasigaun (~4–5 hours / ~8.7 km). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Trek Tashigaon – Khongma",
      maxAltitude: "3,560 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge at Khongma",
      description:
        "Climb via Danda Kharka, Chipla, and Unishisha to Khongma Danda (~3,560 m) (~4–5 hours). First altitude caution. Overnight at Khongma.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Trek Khongma – Dobate via three passes",
      maxAltitude: "4,216 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Dobate",
      description:
        "Cross Ghenguru La (~4,045 m), Shipton La (~4,216 m), and Keke La (~4,150 m) with views of Chamlang, Baruntse, Peak 6 & 7, then descend to Dobate (~4–5 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Trek Dobate – Yangle Kharka",
      maxAltitude: "3,600 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse at Yangle Kharka",
      description:
        "Descend via Phematang, cross the Barun River bridge, and reach Yangle Kharka meadows (~4–5 hours). Overnight in the Barun Valley.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Trek Yangle Kharka – Langmale Kharka",
      maxAltitude: "4,400 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse at Langmale",
      description:
        "Ascend via Nghe, Ripuk, and Jhak Kharka to Langmale Kharka (~4,400 m) (~4–6 hours). Overnight at Langmale.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Acclimatization day at Langmale Kharka",
      maxAltitude: "4,400 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse at Langmale",
      description:
        "Rest day with optional short walks and Peak 3 / Peak 4 / Chamlang viewpoints. Overnight again at Langmale.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Trek Langmale – Makalu Base Camp",
      maxAltitude: "4,870 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse at Makalu Base Camp",
      description:
        "Walk ~4–5 hours (~8.5 km) to Makalu Base Camp (4,870 m) beneath Mt. Makalu. Overnight at base camp teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Exploration day at Makalu Base Camp",
      maxAltitude: "4,870 m+",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse at Makalu Base Camp",
      description:
        "Optional hikes toward Barun Pokhari (~4,950 m), Shersong approaches, or higher lookouts (conditions permitting; viewpoints can reach ~5,900 m for very strong parties). Overnight at MBC.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Trek Makalu Base Camp – Yangle Kharka",
      maxAltitude: "3,600 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse at Yangle Kharka",
      description:
        "Begin the return descent to Yangle Kharka. Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Trek Yangle Kharka – Dobate",
      maxAltitude: "3,550 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Dobate",
      description:
        "Climb out of the Barun toward Dobate (~5–6 hours). Overnight in Dobate.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Trek Dobate – Khongma via Shipton La",
      maxAltitude: "4,216 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse at Khongma",
      description:
        "Recross the high passes toward Khongma (~3–5 hours). Overnight at Khongma.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Trek Khongma – Tashigaon",
      maxAltitude: "2,070 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Tashigaon",
      description:
        "Long descent to Tashigaon (~4–6 hours). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d15",
      dayLabel: "Day 15",
      title: "Trek Tashigaon – Seduwa",
      maxAltitude: "1,540 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse in Seduwa",
      description:
        "Continue descending carefully to Seduwa (~4–6 hours). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d16",
      dayLabel: "Day 16",
      title: "Jeep Seduwa – Khandbari",
      maxAltitude: "1,036 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Hotel in Khandbari",
      description:
        "Reserved jeep back to Khandbari (~5–6 hours). Overnight hotel.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d17",
      dayLabel: "Day 17",
      title: "Khandbari free / exploration day",
      maxAltitude: "1,036 m",
      meals: "Breakfast",
      accommodation: "Hotel in Khandbari",
      description:
        "Buffer and rest day — local market, short walks, or community visits as arranged. Flight-weather buffer. Overnight in Khandbari.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d18",
      dayLabel: "Day 18",
      title: "Drive Tumlingtar – fly to Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "—",
      description:
        "Short jeep to Tumlingtar and flight to Kathmandu. End of the Makalu Barun Valley journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best in spring (March–May) for rhododendron bloom and autumn (September–November) for clear skies. Private groups of 1–6 are welcome. Build buffer days for Tumlingtar flights and rough jeep roads.",
  availabilityNotes: [
    "Private and customizable start dates",
    "TIMS and Makalu–Barun National Park permits required",
    "Porter/guide support included as listed",
    "Tumlingtar flights and Num jeep roads are weather/road-dependent",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Extra Kathmandu nights",
      description: "Pre/post trek nights with breakfast on request.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Extended MBC exploration",
      description: "Extra high viewpoint day if weather and fitness allow.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Gear rental",
      description: "Sleeping bag, down jacket, poles, or micro-spikes.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Kathmandu–Tumlingtar–Kathmandu domestic flights as listed",
    "Reserved jeep transfers Tumlingtar–Khandbari–Num–Seduwa and return as listed",
    "Khandbari hotel nights as listed",
    "Teahouse / lodge lodging during the trek as listed",
    "Breakfast, lunch, and dinner on trek days as listed",
    "Licensed guide and porter support with insurance",
    "TIMS and Makalu–Barun National Park entrance fees",
    "Agency service charge and applicable taxes",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "International airfare",
    "Nepal entry visa fees",
    "Kathmandu hotel and city meals (unless add-on)",
    "Travel / medical / helicopter evacuation insurance (mandatory)",
    "Personal expenses: hot shower, charging, laundry, bar bills, snacks",
    "Tips for guide and porters",
    "Emergency charter helicopter or unforeseen delay costs",
    "Services not listed in the package",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Alpine light toward Makalu–Barun country",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "High ridges and wilderness valleys",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "Remote eastern Himalaya approaches",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Barun Valley wilderness trails",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "Spring (Mar–May) for rhododendrons and wildlife potential; autumn (Sep–Nov) for clear skies and stable weather. Both are peak seasons for Makalu–Barun.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & permits",
      body: "Highest overnight is Makalu Base Camp (4,870 m). Passes include Shipton La (~4,216 m) and Keke La (~4,150 m). You need TIMS and Makalu–Barun NP entry (park fee typically NPR 3,000 pp). Summit Seek arranges these.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Strenuous — steeper and quieter than classic EBC for most people. Rough jeep access, landslide sections, and high snowy passes are possible. Strong fitness required.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Connectivity & cash",
      body: "Mobile data may work to about Tashigaon; signal fades higher. No ATMs beyond Khandbari — carry enough Nepali rupees for personal extras.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Remote teahouse trek — pack thoroughly. Guide/porter carries main load; keep water, layers, documents, snacks, and camera in a daypack.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece mid-layer",
        "Down / insulated jacket",
        "Waterproof shell",
        "Trekking pants and warm socks",
        "Warm hat, sun hat, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Camp shoes",
        "Trekking poles (highly recommended)",
        "Daypack + duffel",
        "Warm sleeping bag",
        "Micro-spikes for snowy passes (seasonal)",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & power",
      items: [
        "SPF sunscreen, lip balm, UV sunglasses",
        "Water filter / Steripen / purification",
        "Personal first-aid kit & blister care",
        "Power bank or solar charger",
        "Trail snacks, tea/coffee sachets",
        "Toilet paper & hand sanitizer",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies + passport photos",
        "Nepal visa as applicable",
        "Travel insurance details (heli evacuation)",
        "Cash in NPR for personal trail extras",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Permit processing and licensed guiding team",
    "Jeep and Tumlingtar flight coordination",
    "Advice on viewpoint days and weather buffers",
    "Support for custom day additions on request",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Makalu Barun Valley trek?",
      answer:
        "An 18-day strenuous tea-house trek through Makalu–Barun National Park, crossing Shipton La into the Barun Valley and reaching Makalu Base Camp (4,870 m).",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it compared with Everest Base Camp?",
      answer:
        "Generally harder and quieter — multiple 4,000 m+ passes, remoter infrastructure, and long ascents/descents. Excellent fitness required.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This listing starts at US$1,990 for 3–5 pax (US$2,190 for 2; US$1,850 for 6; US$1,690 for larger groups as listed).",
      visible: true,
    },
    {
      id: "q4",
      question: "What is the maximum altitude?",
      answer:
        "Makalu Base Camp at 4,870 m. Optional exploration viewpoints can go higher (up to ~5,900 m) only if conditions and fitness allow.",
      visible: true,
    },
    {
      id: "q5",
      question: "What permits are required?",
      answer:
        "TIMS and Makalu–Barun National Park entrance. Summit Seek arranges these with your guide.",
      visible: true,
    },
    {
      id: "q6",
      question: "When is the best time to go?",
      answer:
        "March–May and September–November offer the best weather and views.",
      visible: true,
    },
    {
      id: "q7",
      question: "Are there ATMs on the trail?",
      answer:
        "No. Withdraw cash in Kathmandu or Khandbari before starting the jeep/trek section.",
      visible: true,
    },
    {
      id: "q8",
      question: "Is travel insurance necessary?",
      answer:
        "Yes — covering remote trekking and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Makalu Barun Valley?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Makalu Barun Valley Trek 18 Days | Summit Seek",
  metaDescription:
    "Book the 18-day Makalu Barun Valley trek with Summit Seek — Shipton La, Barun Valley, Makalu Base Camp 4,870 m, permits, flights & group discounts from US$1,690.",
};
