import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_MANASLU_CIRCUIT: TrekPageContent = {
  coverImageUrl: img("photo-1486870591958-9b9d0d1dda99", 2000),
  coverTitle: "Manaslu Circuit Trek - 14 Days",
  coverSubtitle:
    "Restricted-area circuit around the world’s 8th-highest peak — Larkya La (5,106 m), Samagaun, Manaslu Base Camp, and Nubri culture from Machha Khola to Besisahar.",
  heroMainImageUrl: img("photo-1486870591958-9b9d0d1dda99", 2000),
  heroSideImage1Url: img("photo-1506905925346-21bda4d32df4", 900),
  heroSideImage2Url: img("photo-1464822759023-fed622ff2c3b", 900),
  breadcrumbLabel: "Manaslu Region · Circuit",
  title: "Manaslu Circuit Trek - 14 Days",
  regionLabel: "Manaslu Region",
  rating: 5,
  reviewCount: 42,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 925,
  compareAtPrice: 1175,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "21% OFF",
  shortTripBadge: "Restricted Area",
  durationLabel: "14 Days",
  difficultyLabel: "Challenging",
  groupSizeLabel: "1+",
  bookingNote:
    "Licensed guide required (restricted area). Package includes special Manaslu permit, MCAP, ACAP, guide, trek meals, and local-bus transfers. Porter and private jeep available as add-ons. Microspikes strongly recommended for Larkya La.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 1050, visible: true },
    { id: "gd2", paxLabel: "2-4 pax", price: 925, visible: true },
    { id: "gd3", paxLabel: "5-8 pax", price: 875, visible: true },
    { id: "gd4", paxLabel: "9-12 pax", price: 825, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "14 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Challenging", visible: true },
    { id: "f3", label: "Max Altitude", value: "5,106 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Manaslu / Annapurna", visible: true },
    { id: "f6", label: "Group Size", value: "1+", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Culture", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The Manaslu Circuit is a raw, spiritual restricted-area trek around Mount Manaslu (8,163 m) — the world’s eighth-highest peak. From Machha Khola through Nubri villages to Tilje, the route crosses Larkya La (5,106 m) and links the Manaslu and Annapurna conservation areas.\n\nExpect ancient monasteries, Milarepa caves, mani walls, Birendra Lake, multiethnic villages (Gurung, Sherpa, Tibetan-influenced Nubri communities), and side hikes such as Manaslu Base Camp (~4,800 m) and Pungyen Monastery. The trail remains less crowded than Everest or classic Annapurna Circuit while offering commercial teahouse infrastructure.\n\nSummit Seek provides a licensed government guide (mandatory), Manaslu special permit, MCAP & ACAP, trek meals, twin-share lodges, and clear group pricing. Customize with Tsum Valley or adjust roadheads (Soti Khola / Dharapani) by season.",
  overviewImageUrl: img("photo-1544735716-392fe2489ffa"),
  highlightsHeading: "Highlights",
  highlights: [
    "Circuit around Mt. Manaslu (8,163 m) — world’s 8th-highest peak",
    "Cross challenging Larkya La Pass (5,106 m)",
    "Acclimatization hike toward Manaslu Base Camp (~4,800 m)",
    "Pungyen Monastery, Nubri culture & Birendra Lake",
    "Two iconic regions: Manaslu and Annapurna (ACAP finish)",
    "Rivers, waterfalls, suspension bridges & diverse vegetation",
    "Visit toward the Tibet border from Samdo",
    "Off-the-beaten yet well-supported teahouse trek",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport pickup and drop-off by private vehicle",
    "Two nights boutique / standard hotel in Kathmandu with breakfast",
    "Full-board meals (breakfast, lunch, dinner) during the trek",
    "Licensed mountain guide (salary, food, lodging, transport, insurance)",
    "Manaslu Special Permit, MCAP, ACAP, and local entrance fees as required",
    "Kathmandu–Machha Khola and Besisahar–Kathmandu by local bus",
    "Tilje–Besisahar local sharing jeep",
    "Twin-share rooms on trek, tea/coffee, seasonal fruit, first-aid kit",
  ],
  whyHeading: "Why choose Manaslu Circuit?",
  whyPoints: [
    "Restricted-area authenticity with fewer crowds than Everest/Annapurna classics",
    "One of Nepal’s great high-pass days at Larkya La",
    "Rich Nubri Buddhist heritage and mountain village life",
    "Links Manaslu wilderness with the Annapurna roadhead finish",
    "Easy to combine with Tsum Valley for a longer expedition",
  ],
  beginnersHeading: "Who is this trek for?",
  beginnersBody:
    "Challenging. Prior multi-day high-altitude trekking is strongly recommended. Expect long days (often 7–9 hours), landslide-prone sections, and a demanding pre-dawn Larkya La crossing with possible ice and scree.\n\nA licensed guide is mandatory. Solo trekkers may join with a registered company and guide under current rules. Travel insurance covering helicopter evacuation to ~6,000 m is mandatory. Microspikes are strongly advised for the pass.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train 6+ weeks with long hikes, stairs, cardio, and loaded daypack practice",
    "Break in waterproof boots; pack microspikes and trekking poles",
    "Bring a bright headlamp for the early Larkya La start",
    "Pack serious warm layers for Dharamsala and the pass",
    "Buy insurance covering high-altitude trekking and helicopter rescue",
    "Arrive Kathmandu 1 day early for permit processing and gear checks",
  ],
  itineraryHeading: "14-day itinerary",
  itineraryIntro:
    "Times and roadheads vary with season and conditions. In early autumn, buses may stop at Soti Khola instead of Machha Khola; after Larkya La, jeep access may start at Tilje or Dharapani. Your Summit Seek guide adjusts for safety — especially around Larkya La.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,365 m",
      meals: "—",
      accommodation: "Hotel in Kathmandu",
      description:
        "Airport pickup and transfer to your hotel (~25 minutes). Trek briefing and permit preparation. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Drive Kathmandu – Machha Khola",
      maxAltitude: "890 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Long drive (~157 km / 9–10 hours) via Aarughat to Machha Khola trailhead (bumpy section after Aarughat). Overnight in Machha Khola.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Machha Khola – Jagat",
      maxAltitude: "1,410 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Trek along the Budhi Gandaki (~13.5 km / 7–8 hours) through forests and villages to Jagat, entry for restricted-area checks. Overnight in Jagat.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Jagat – Dyang",
      maxAltitude: "1,800 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Continue up-valley (~20 km / 8–9 hours) past waterfalls and suspension bridges toward Dyang. Overnight in Dyang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Dyang – Namrung",
      maxAltitude: "2,660 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Climb into cooler forests and Tibetan-influenced villages (~19 km / 7–8 hours) to Namrung. Overnight in Namrung.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Namrung – Shyala",
      maxAltitude: "3,500 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Ascend through Lho and alpine meadows (~18 km / 8–9 hours) with growing Manaslu views to Shyala. Overnight in Shyala.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Shyala – Samagaun via Pungyen",
      maxAltitude: "4,020 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Side visit toward Pungyen Monastery then continue to Samagaun (~17 km / 7–8 hours), the main Nubri village beneath Manaslu. Overnight in Samagaun.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Samagaun acclimatization – Manaslu Base Camp",
      maxAltitude: "4,800 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Acclimatization hike toward Manaslu Base Camp / Birendra Lake (~13.5 km / 7–8 hours). Overnight again in Samagaun.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Samagaun – Samdo",
      maxAltitude: "3,860 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Shorter high-valley walk (~8.5 km / 4–5 hours) to Samdo near the Tibetan border approaches. Overnight in Samdo.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Samdo – Larkya La Phedi (Dharamsala)",
      maxAltitude: "4,460 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Trek to Dharamsala / Larkya Phedi (~9 km / 4–5 hours), the last lodge before the pass. Rest early for the big day. Overnight in Dharamsala.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Cross Larkya La – Bhimthang",
      maxAltitude: "5,106 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Pre-dawn start to cross Larkya La (5,106 m) with views of Manaslu, Cheo Himal, Himlung, and more, then long descent to Bhimthang (~16 km / 8–9 hours). Overnight in Bhimthang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Bhimthang – Tilje – drive Besisahar",
      maxAltitude: "3,790 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Hotel / Lodge in Besisahar",
      description:
        "Trek to Tilje (~13 km / about 4 hours), then local sharing jeep to Besisahar (~3 hours). Overnight in Besisahar.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Drive Besisahar – Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Local bus back to Kathmandu (~7–8 hours / ~175 km). Optional Pokhara finish on request. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Final departure",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "— (departure day)",
      description:
        "Private airport transfer for your international departure. End of the Manaslu Circuit journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Manaslu Circuit runs best in autumn (Sep–Nov) and spring (Mar–May). Winter snow can block Larkya La; monsoon brings landslides and difficult road access to Machha Khola.",
  availabilityNotes: [
    "Private and joining dates available",
    "Licensed guide mandatory; permits arranged by Summit Seek",
    "Roadhead may shift (Soti Khola / Dharapani) by season",
    "Tsum Valley extension available on request",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Porter service",
      description: "Porter support for the full trip (about US$290 on reference packages; confirm current rate).",
      priceLabel: "From US$290",
      visible: true,
    },
    {
      id: "a2",
      title: "Private jeep to Machha Khola",
      description: "Upgrade local bus Kathmandu–Machha Khola to private jeep.",
      priceLabel: "From US$200",
      visible: true,
    },
    {
      id: "a3",
      title: "Tsum Valley extension",
      description: "Add days into sacred Tsum Valley before rejoining the circuit.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport pickup and drop-off by private car",
    "Two nights hotel in Kathmandu with breakfast",
    "Full-board meals (breakfast, lunch, dinner) during the trek",
    "Licensed mountain guide (salary, food, lodging, transport, insurance)",
    "Manaslu Special Permit, MCAP, and ACAP",
    "Local municipality entrance fees as required",
    "Kathmandu–Machha Khola and Besisahar–Kathmandu by local bus",
    "Tilje–Besisahar local sharing jeep",
    "Twin-share teahouse rooms on trek; tea/coffee and seasonal fruit",
    "Sleeping bag / down jacket / duffel if required (return after trek); first-aid kit",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Travel insurance (mandatory — high-altitude evacuation)",
    "Porter (available as add-on)",
    "Private jeep upgrade (available as add-on)",
    "Nepal visa and international flights",
    "Lunch and dinner in Kathmandu",
    "Bar bills and personal expenses (laundry, charging, bottled/hot water, showers)",
    "Tips for guide and porter",
    "Any items not listed in the includes section",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "High Himalayan pass light",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Alpine ridges toward Manaslu",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Mountain panorama on the circuit",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Valley approaches in the restricted area",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "September–November and March–May usually offer the clearest views and most reliable Larkya La conditions. Winter snow can close the pass; monsoon increases landslide and road risk.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & AMS",
      body: "Max altitude is Larkya La at 5,106 m; overnight high points include Dharamsala (~4,460 m) and Samagaun (~3,500 m). Use the Samagaun rest day, hydrate, and descend if symptoms worsen.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Challenging. Long walking days, rough trails, and a tough pass crossing. Prior high-altitude trekking experience strongly recommended. Microspikes and poles highly advised.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Permits",
      body: "Manaslu Restricted Area Permit, MCAP, ACAP, and local entrance fees apply. Summit Seek arranges these with your licensed guide — unguided trekking is not allowed.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack for a cold, early Larkya La start and a long scree descent. Microspikes are considered mandatory by many guides for ice near the pass.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers & thermals",
        "Fleece mid-layer",
        "Heavy down / insulated jacket",
        "Waterproof hard shell",
        "Warm trekking pants + insulated evening layer",
        "Warm hat, sun hat, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Microspikes (strongly recommended)",
        "Trekking poles",
        "25–35L daypack",
        "Duffel for porter if using",
        "Bright headlamp (200+ lumens) + spare batteries",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "Category 3–4 UV sunglasses",
        "SPF sunscreen & lip balm",
        "Personal medications (discuss Diamox with your doctor)",
        "Water bottle + purification",
        "Blister care & first-aid basics",
        "High-energy snacks",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance (high-altitude evacuation)",
        "Passport photos if needed for permits",
        "Cash for personal trail expenses",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Permit processing and licensed guide assignment",
    "Sleeping bag / down jacket / duffel if required (return after trek)",
    "First-aid kit on trail; evacuation coordination via your insurance",
    "Advice on Tsum Valley extensions and private jeep upgrades",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Manaslu Circuit trek?",
      answer:
        "A 14-day restricted-area circuit around Mt. Manaslu crossing Larkya La (5,106 m), from Machha Khola through Samagaun to the Annapurna-side roadhead at Besisahar.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Challenging. Long days, high altitude, and a demanding pass crossing. Prior multi-day Himalayan trekking experience is strongly recommended.",
      visible: true,
    },
    {
      id: "q3",
      question: "What is the maximum altitude?",
      answer:
        "Larkya La Pass at 5,106 m. The Manaslu Base Camp acclimatization hike reaches about 4,800 m.",
      visible: true,
    },
    {
      id: "q4",
      question: "How much does the Manaslu Circuit cost?",
      answer:
        "This Summit Seek listing starts at US$925 for 2–4 pax (US$1,050 solo), with group rates from US$875 (5–8) and US$825 (9–12).",
      visible: true,
    },
    {
      id: "q5",
      question: "Do I need a guide and special permits?",
      answer:
        "Yes. A licensed guide is mandatory. You need the Manaslu Special Permit, MCAP, ACAP, and local fees — Summit Seek arranges these.",
      visible: true,
    },
    {
      id: "q6",
      question: "Is travel insurance necessary?",
      answer:
        "Yes. Cover high-altitude trekking and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q7",
      question: "When is the best time to go?",
      answer:
        "Autumn (September–November) and spring (March–May) usually offer the clearest weather for Larkya La.",
      visible: true,
    },
    {
      id: "q8",
      question: "Can I combine with Tsum Valley?",
      answer:
        "Yes. Adding Tsum Valley is a popular extension — ask us to customize a longer Manaslu–Tsum itinerary.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Manaslu Circuit?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Manaslu Circuit Trek 14 Days | Summit Seek",
  metaDescription:
    "Book the 14-day Manaslu Circuit with Summit Seek — Larkya La (5,106 m), Samagaun, restricted permits, licensed guide, meals & group discounts from US$825.",
};
