import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_MANASLU_TSUM: TrekPageContent = {
  coverImageUrl: img("photo-1544735716-392fe2489ffa", 2000),
  coverTitle: "Manaslu Tsum Valley Trek - 21 Days",
  coverSubtitle:
    "Manaslu Circuit plus sacred Tsum Valley — Mu Gompa, Samagaun, and Larkya La (5,160 m) on Nepal’s classic restricted-area combined adventure.",
  heroMainImageUrl: img("photo-1544735716-392fe2489ffa", 2000),
  heroSideImage1Url: img("photo-1486870591958-9b9d0d1dda99", 900),
  heroSideImage2Url: img("photo-1506905925346-21bda4d32df4", 900),
  breadcrumbLabel: "Manaslu Region · Circuit + Tsum",
  title: "Manaslu Tsum Valley Trek - 21 Days",
  regionLabel: "Manaslu Region",
  rating: 5,
  reviewCount: 28,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 2150,
  compareAtPrice: 2750,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "Group Rates",
  shortTripBadge: "Restricted Area",
  durationLabel: "21 Days",
  difficultyLabel: "Challenging",
  groupSizeLabel: "1+",
  bookingNote:
    "Private departures. Package includes Kathmandu hotels (BB), private vehicle road transfers, licensed guide, porter (2:1), full-board trek meals, Manaslu RAP, MCAP, ACAP & TIMS. Microspikes strongly recommended for Larkya La.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 2750, visible: true },
    { id: "gd2", paxLabel: "2-3 pax", price: 2150, visible: true },
    { id: "gd3", paxLabel: "4-9 pax", price: 1950, visible: true },
    { id: "gd4", paxLabel: "10-14 pax", price: 1800, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "21 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Strenuous", visible: true },
    { id: "f3", label: "Max Altitude", value: "5,160 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Manaslu / Tsum", visible: true },
    { id: "f6", label: "Group Size", value: "1+", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Culture", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The Manaslu Tsum Valley Trek combines the wild Manaslu Circuit with sacred Tsum Valley — a restricted Himalayan sanctuary that opened to trekkers only in 2008. From Machha Khola along the Budhi Gandaki, you divert into Tsum to Chumling, Chhokang Paro, Nile, and Mu Gompa before rejoining the circuit via Deng toward Samagaun, Samdo, and Larkya La (5,160 m).\n\nExpect Tibetan-Buddhist heritage, ancient monasteries (Mu Gompa, Rachen Gompa, Pungyen, Ribung), mani walls, cliff trails, and views of Mt. Manaslu (8,163 m). After the pass, descend via Bimthang to Dharapani and drive back to Kathmandu.\n\nSummit Seek runs this as a private trip with licensed guide, porter support (2:1), restricted permits, private vehicle transfers, full-board trek meals, and clear group pricing.",
  overviewImageUrl: img("photo-1464822759023-fed622ff2c3b"),
  highlightsHeading: "Highlights",
  highlights: [
    "Combine Manaslu Circuit with sacred Tsum Valley in one journey",
    "Visit Mu Gompa and Tibetan-Buddhist villages near the Nepal–Tibet border",
    "Cross Larkya La Pass (5,160 m) with Manaslu panoramas",
    "Acclimatization hike toward Manaslu Base Camp / Birendra Lake",
    "Remote Budhi Gandaki trails — suspension bridges, waterfalls, cliffs",
    "Villages of Lho, Samagaun, Samdo, Chumling & Chhokang Paro",
    "Less-crowded restricted-area alternative to Everest/Annapurna classics",
    "Private vehicle road transfers Kathmandu ↔ trailheads",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport transfers on a tourist vehicle",
    "2 nights 3-star Kathmandu hotel with breakfast (twin sharing)",
    "18 nights twin-share / dormitory guesthouse lodging on trek",
    "Full-board meals on trek days (18B / 18L / 18D) plus seasonal fruit",
    "Private tourist vehicle Kathmandu–Machha Khola and Dharapani–Kathmandu",
    "Licensed English-speaking guide (2 guides for groups of 7+)",
    "Porter support (1 porter per 2 clients) with staff wages, meals & insurance",
    "Manaslu RAP, MCAP, ACAP, TIMS, first-aid kit with oximeter, farewell dinner",
  ],
  whyHeading: "Why choose Manaslu + Tsum?",
  whyPoints: [
    "Two restricted worlds in one itinerary — Circuit drama plus Tsum spirituality",
    "Mu Gompa and upper Tsum remain among Nepal’s most authentic high valleys",
    "Built-in acclimatization before Larkya La for safer high-pass success",
    "Quieter trails than Everest and classic Annapurna Circuit",
    "Strong cultural depth with Tibetan-Buddhist monastic life",
  ],
  beginnersHeading: "Who is this trek for?",
  beginnersBody:
    "Strenuous / challenging. Long walking days and high altitude (Larkya La 5,160 m; Dharamsala 4,460 m) demand solid fitness and prior multi-day trekking experience. A positive mindset matters as much as stamina.\n\nLicensed guide and restricted permits are mandatory. Travel insurance covering helicopter evacuation is required. Microspikes are strongly advised for the pass.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train 6–8 weeks with long hikes, stairs, cardio, and a loaded daypack",
    "Break in waterproof boots; pack microspikes and trekking poles",
    "Bring a bright headlamp for the early Larkya La start",
    "Pack serious warm layers for Mu Gompa, Dharamsala, and the pass",
    "Buy insurance covering high-altitude trekking and helicopter rescue",
    "Arrive Kathmandu a day early for briefing and permit checks",
  ],
  itineraryHeading: "21-day itinerary",
  itineraryIntro:
    "Walking and drive times are estimates and vary with weather and road conditions. Lodge stops may change with availability. Your Summit Seek guide adjusts for safety — especially around Larkya La and high Tsum.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,400 m",
      meals: "—",
      accommodation: "3-star hotel",
      description:
        "Airport transfer to your hotel. Welcome briefing. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Drive Kathmandu – Machha Khola",
      maxAltitude: "869 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guesthouse",
      description:
        "Scenic private tourist vehicle drive via Soti Khola (~8–10 hours) to Machha Khola. Overnight in Machha Khola.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Machha Khola – Jagat",
      maxAltitude: "1,340 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guesthouse",
      description:
        "Trek the Budhi Gandaki corridor (~6–7 hours) to Jagat. Overnight in Jagat.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Jagat – Lokpa (enter Tsum)",
      maxAltitude: "2,240 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guesthouse",
      description:
        "Leave the main circuit for the Tsum Valley route to Lokpa, gateway to the sacred valley (~6–7 hours). Overnight in Lokpa.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Lokpa – Chumling",
      maxAltitude: "2,386 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guesthouse",
      description:
        "Trek into lower Tsum via Siyar Khola to Chumling (~5–6 hours) — stone lanes and Chumling Gompa. Overnight in Chumling.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Chumling – Chhokang Paro",
      maxAltitude: "3,031 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guesthouse",
      description:
        "Climb deeper into upper Tsum via Gho to Chhokang Paro (~5–6 hours). Overnight in Chhokang Paro.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Chhokang Paro – Nile",
      maxAltitude: "3,361 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guesthouse",
      description:
        "Demanding Tsum day with monastery visits en route to Nile (~5–6 hours). Overnight in Nile.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Mu Gompa exploration – return Nile",
      maxAltitude: "3,700 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guesthouse / Gompa",
      description:
        "Acclimatization hike to Mu Gompa (~3,700 m), Tsum’s most important monastery, then return to Nile (~5–6 hours). Overnight in Nile.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Nile – Chumling",
      maxAltitude: "2,386 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guesthouse",
      description:
        "Descend from upper Tsum back to Chumling (~6–7 hours). Overnight in Chumling.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Chumling – Deng (rejoin Circuit)",
      maxAltitude: "1,860 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guesthouse",
      description:
        "Leave Tsum and rejoin the Manaslu Circuit near Nyak toward Deng (~5–6 hours). Overnight in Deng.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Deng – Namrung",
      maxAltitude: "2,630 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guesthouse",
      description:
        "Continue the circuit through forest and villages to Namrung (~5–6 hours). Overnight in Namrung.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Namrung – Lho",
      maxAltitude: "3,180 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guesthouse",
      description:
        "Ascend with growing Manaslu views to Lho (~6–7 hours). Overnight in Lho.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Lho – Samagaon",
      maxAltitude: "3,520 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guesthouse",
      description:
        "Shorter day into Samagaun (~3–4 hours), the main Nubri village beneath Manaslu. Overnight in Samagaon.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Samagaon acclimatization",
      maxAltitude: "4,895 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guesthouse",
      description:
        "Optional hike to Birendra Lake or toward Manaslu Base Camp (~7–8 hours). Overnight again in Samagaon.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d15",
      dayLabel: "Day 15",
      title: "Samagaon – Samdo",
      maxAltitude: "3,875 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guesthouse",
      description:
        "High-valley walk to Samdo near Tibetan trade approaches (~3–4 hours). Overnight in Samdo.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d16",
      dayLabel: "Day 16",
      title: "Samdo – Dharamsala",
      maxAltitude: "4,460 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guesthouse",
      description:
        "Trek via Larkya Bazar to Dharamsala / Larkya Phedi (~4–5 hours). Rest early for pass day. Overnight in Dharamsala.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d17",
      dayLabel: "Day 17",
      title: "Cross Larkya La – Bimthang",
      maxAltitude: "5,160 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guesthouse",
      description:
        "Big pass day: cross Larkya La (5,160 m) then descend to Bimthang (~8–9 hours). Overnight in Bimthang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d18",
      dayLabel: "Day 18",
      title: "Bimthang – Goa",
      maxAltitude: "2,515 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guesthouse",
      description:
        "More relaxed descent after the pass to Goa (~4–5 hours). Overnight in Goa.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d19",
      dayLabel: "Day 19",
      title: "Goa – Dharapani",
      maxAltitude: "1,963 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guesthouse",
      description:
        "Final trail day into Dharapani on the Annapurna-side road (~3–4 hours). Overnight in Dharapani.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d20",
      dayLabel: "Day 20",
      title: "Drive Dharapani – Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast, Farewell dinner",
      accommodation: "3-star hotel",
      description:
        "Private tourist vehicle via Besisahar to Kathmandu (~9–10 hours). Farewell dinner. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d21",
      dayLabel: "Day 21",
      title: "Final departure",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "— (departure day)",
      description:
        "Airport transfer for your international flight. End of the Manaslu Tsum Valley journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "This trek is organized as a private trip. Best seasons are March–May and September–November. Winter snow can block Larkya La; monsoon increases landslide and road risk.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Licensed guide and restricted permits mandatory",
    "Porter included at 2 clients : 1 porter",
    "Microspikes strongly recommended for Larkya La",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Private room in Kathmandu",
      description: "Upgrade twin-share hotel room to private.",
      priceLabel: "From US$35 / room",
      visible: true,
    },
    {
      id: "a2",
      title: "Sleeping bag / down jacket rental",
      description: "Four-season bag or puffy jacket rental if needed.",
      priceLabel: "From US$35 each",
      visible: true,
    },
    {
      id: "a3",
      title: "Extra Kathmandu night",
      description: "Add buffer nights before or after the trek.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport transfers on a tourist vehicle",
    "2 nights twin-share 3-star hotel in Kathmandu with breakfast",
    "18 nights twin-share / dormitory guesthouse lodging on trek",
    "18 breakfasts, 18 lunches, 18 dinners on trek plus seasonal fruit",
    "Farewell dinner on the last night in Nepal",
    "Purified drinking water on trek (filter / tablets)",
    "Private tourist vehicle Kathmandu–Machha Khola and Dharapani–Kathmandu",
    "Licensed English-speaking guide (2 guides for groups of 7+)",
    "Porters (1 per 2 clients) with staff wages, meals, lodging, insurance",
    "Manaslu RAP, MCAP, ACAP, TIMS; first-aid kit with oximeter; duffel/map/sun hat; taxes",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Lunch and dinner in Kathmandu (except farewell dinner)",
    "International airfare and airport departure tax",
    "Nepal entry visa fees",
    "Travel insurance with high-altitude emergency evacuation",
    "Beverages including bottled and boiled water extras",
    "Tips for trekking staff and driver",
    "Personal trekking gear and equipment",
    "Any expenses other than the includes section",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Remote valley approaches toward Manaslu",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "High Himalayan pass light",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Alpine ridges near Larkya La",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Mountain panorama on the combined route",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May and September–November usually offer the clearest skies for Tsum and Larkya La. Winter snow can close the pass; monsoon means landslides and muddy trails.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & AMS",
      body: "Max altitude is Larkya La at 5,160 m. Built-in exploration at Mu Gompa and Samagaun helps acclimatization — follow your guide’s pacing and hydrate well.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Strenuous due to length, long days, and high pass. Prior multi-day Himalayan experience strongly recommended.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Permits",
      body: "Restricted Area Permit for Manaslu/Tsum, MCAP, ACAP, and TIMS are required. Summit Seek arranges these with your licensed guide.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack for cold nights above 4,000 m and a long Larkya La day. Porters carry main bags; keep water, layers, documents, and camera in a daypack.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers & thermals",
        "Fleece mid-layer",
        "Hooded down jacket (essential above 4,000 m)",
        "Waterproof hard shell",
        "Warm trekking pants + insulated evening layer",
        "Warm hat, sun hat, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Microspikes (strongly recommended)",
        "Trekking poles",
        "25–35L daypack",
        "Four-season sleeping bag (rental available)",
        "Bright headlamp + spare batteries",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "Category 3–4 UV sunglasses",
        "SPF sunscreen & lip balm",
        "Personal medications & blister care",
        "Water bottle (purification provided on trek)",
        "Toilet paper, sanitizer, small towel",
        "High-energy snacks",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance (high-altitude evacuation)",
        "Cash for personal trail extras (~US$15–20/day)",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Duffel/kit bag, trekking map, sun hat, buff",
    "First-aid kit with daily oximeter checks",
    "Trip completion certificate and farewell dinner",
    "Permit processing and licensed guiding team",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Manaslu Tsum Valley trek?",
      answer:
        "A 21-day combined journey: sacred Tsum Valley (Mu Gompa) plus the Manaslu Circuit crossing Larkya La (5,160 m), starting and ending in Kathmandu.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Strenuous / moderate-to-strenuous due to length, long days, and high altitude. Prior multi-day trekking experience is strongly recommended.",
      visible: true,
    },
    {
      id: "q3",
      question: "What is the maximum altitude?",
      answer:
        "Larkya La Pass at approximately 5,160 m. Mu Gompa is about 3,700 m; Manaslu Base Camp optional hike reaches ~4,895 m.",
      visible: true,
    },
    {
      id: "q4",
      question: "How much does it cost?",
      answer:
        "This Summit Seek listing starts at US$2,150 for 2–3 pax (US$2,750 solo; US$1,950 for 4–9; US$1,800 for 10–14).",
      visible: true,
    },
    {
      id: "q5",
      question: "Are porters included?",
      answer:
        "Yes. One porter is included for every two clients. Guide wages, meals, lodging, and insurance for staff are covered.",
      visible: true,
    },
    {
      id: "q6",
      question: "Is travel insurance necessary?",
      answer:
        "Yes. Cover high-altitude trekking and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q7",
      question: "When is the best time to go?",
      answer:
        "March–May and September–November usually offer the best weather for Tsum and Larkya La.",
      visible: true,
    },
    {
      id: "q8",
      question: "Do I need special permits?",
      answer:
        "Yes. Restricted Area Permit, MCAP, ACAP, and TIMS are required. Summit Seek arranges these with your licensed guide.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Manaslu + Tsum?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Manaslu Tsum Valley Trek 21 Days | Summit Seek",
  metaDescription:
    "Book the 21-day Manaslu Tsum Valley trek with Summit Seek — Mu Gompa, Larkya La (5,160 m), permits, guide, porter, meals & group discounts from US$1,800.",
};
