import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_MANASLU_CIRCUIT_TREK: TrekPageContent = {
  coverImageUrl: img("photo-1506905925346-21bda4d32df4", 2000),
  coverTitle: "Manaslu Circuit Trek - 14 Days",
  coverSubtitle:
    "Restricted-area circuit around Mt. Manaslu (8,163 m) — Larkya La (5,106 m), Samagaun, Manaslu Base Camp, Nubri monasteries, and finish at Besisahar.",
  heroMainImageUrl: img("photo-1506905925346-21bda4d32df4", 2000),
  heroSideImage1Url: img("photo-1486870591958-9b9d0d1dda99", 900),
  heroSideImage2Url: img("photo-1464822759023-fed622ff2c3b", 900),
  breadcrumbLabel: "Packages · Manaslu Region",
  title: "Manaslu Circuit Trek - 14 Days",
  regionLabel: "Manaslu Region",
  rating: 5,
  reviewCount: 6,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 950,
  compareAtPrice: 1520,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "38% OFF",
  shortTripBadge: "Best Seller",
  durationLabel: "14 Days",
  difficultyLabel: "Challenging",
  groupSizeLabel: "2+",
  bookingNote:
    "Restricted area — licensed guide mandatory; minimum 2 trekkers per permit group (solo joiners can be paired). Package includes Manaslu special permit, MCAP, ACAP, Tsum Nubri entrance fee, guide, trek meals, and local-bus/jeep transfers as listed. Porter and private jeep upgrades available.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax (join group)", price: 1200, visible: true },
    { id: "gd2", paxLabel: "2-4 pax", price: 950, visible: true },
    { id: "gd3", paxLabel: "5-8 pax", price: 900, visible: true },
    { id: "gd4", paxLabel: "9+ pax", price: 850, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "14 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Challenging", visible: true },
    { id: "f3", label: "Max Altitude", value: "5,106 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Manaslu / Annapurna", visible: true },
    { id: "f6", label: "Group Size", value: "2+ (restricted)", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Culture", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "Manaslu Circuit Trek – 14 Days is a raw, spiritual journey inside Nepal’s restricted Manaslu area — circling the world’s 8th-highest peak, Mt. Manaslu (8,163 m), from Machha Khola to Tilje via Larkya La Pass (5,106 m).\n\nExpect ancient monasteries, Milarepa caves, mani walls, suspension bridges over the roaring Budhi Gandaki, and Nubri Tibetan culture in Samagaun and Samdo. Acclimatize with a hike to Manaslu Base Camp (4,800 m) and visit Pungyen Monastery before the pre-dawn crossing of Larkya La — one of the Himalayas’ great high-pass days.\n\nThe trail spans MCAP and ACAP landscapes from subtropical gorges to alpine tundra, finishing with a jeep from Tilje to Besisahar. Summit Seek provides a licensed guide (mandatory), all permits, trek meals, twin-share lodges, and clear group pricing. Tsum Valley extensions available on request.",
  overviewImageUrl: img("photo-1544735716-392fe2489ffa"),
  highlightsHeading: "Highlights",
  highlights: [
    "Up-close views of Mt. Manaslu (8,163 m) from Namrung and Shyala",
    "Cross Larkya La Pass (5,106 m) with prayer flags and glacier panoramas",
    "Acclimatization hike to Manaslu Base Camp (4,800 m) & Birendra Lake",
    "Pungyen Monastery, Lho Gompa, and Nubri village culture",
    "Suspension bridges and wild Budhi Gandaki gorges",
    "Two conservation areas — Manaslu (MCAP) and Annapurna (ACAP)",
    "Samdo village near the Tibet border approaches",
    "Off-the-beaten yet well-supported teahouse trek",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport pickup and drop-off by private vehicle",
    "2 nights boutique hotel in Kathmandu with breakfast",
    "Licensed mountain guide (salary, food, lodging, transport, insurance)",
    "Manaslu Special Permit, MCAP, ACAP & Tsum Nubri entrance fee",
    "Full-board meals (breakfast, lunch, dinner) during the trek",
    "Kathmandu–Machha Khola and Besisahar–Kathmandu by local bus",
    "Tilje–Besisahar sharing jeep as listed",
    "Twin-share teahouse rooms, hot tea, seasonal fruit, and first-aid kit",
  ],
  whyHeading: "Why choose Manaslu Circuit?",
  whyPoints: [
    "Restricted-area authenticity with fewer crowds than Everest or Annapurna",
    "One of Nepal’s most scenic high-pass crossings at Larkya La",
    "Rich Nubri Buddhist heritage and ancient monastery visits",
    "Links Manaslu wilderness with the Annapurna roadhead finish",
    "Popular Tsum Valley extension for a longer expedition",
  ],
  beginnersHeading: "Who is this trek for?",
  beginnersBody:
    "Challenging — prior multi-day high-altitude trekking strongly recommended. Expect long days (7–9 hours), landslide-prone sections, and a demanding pre-dawn Larkya La crossing with possible ice and scree. Crampons/microspikes and trekking poles are highly advised.\n\nA licensed guide is mandatory; minimum 2 trekkers per permit (solo travelers can join a group). Travel insurance covering helicopter evacuation to ~6,000 m is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train 6+ weeks with long hikes, stairs, cardio, and loaded daypack practice",
    "Break in waterproof boots; pack microspikes and trekking poles",
    "Bring a bright headlamp for the early Larkya La start",
    "Pack serious warm layers for Dharamsala and the pass",
    "Buy insurance covering high-altitude trekking and helicopter rescue",
    "Arrive Kathmandu 1 day early for permit processing and gear checks",
  ],
  itineraryHeading: "14-day itinerary",
  itineraryIntro:
    "Times and roadheads vary with season. In early autumn, buses may stop at Soti Khola instead of Machha Khola; jeep access after Larkya La may start at Tilje or Dharapani. Your Summit Seek guide adjusts for safety — especially around Larkya La.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,365 m",
      meals: "—",
      accommodation: "Hotel in Kathmandu",
      description:
        "Airport pickup and transfer to your hotel. Trek briefing, gear check, and permit preparation with your licensed guide. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Drive Kathmandu to Machha Khola",
      maxAltitude: "890 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Long scenic drive (~157 km / 9–10 hrs) via Aarughat and Soti Khola following the Trisuli and Budhi Gandaki rivers. Bumpy off-road section after Aarughat. Overnight in Machha Khola.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Trek Machha Khola to Jagat",
      maxAltitude: "1,410 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Trek upstream along the Budhi Gandaki (~13.5 km / 7–8 hrs) past Tatopani hot springs and villages to Jagat — restricted-area entry and permit check. Overnight in Jagat.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Trek Jagat to Dyang",
      maxAltitude: "1,860 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Continue through Philim and bamboo forest (~20 km / 8–9 hrs) with suspension bridges and terraced fields. Overnight in Dyang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Trek Dyang to Namrung",
      maxAltitude: "2,660 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Climb through fir, oak, and rhododendron forest with Tibetan mani walls (~19 km / 7–8 hrs). Manaslu views begin to open at Namrung. Overnight in Namrung.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Trek Namrung to Shyala via Lho",
      maxAltitude: "3,500 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Gradual ascent through Lho village with its large Buddhist monastery (~18 km / 7–8 hrs). Close Manaslu views at Shyala surrounded by peaks. Overnight in Shyala.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Trek Shyala to Samagaun via Pungyen Monastery",
      maxAltitude: "3,560 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Visit Pungyen Monastery then trek through pine and juniper to Samagaun (~17 km / 6–7 hrs) — main Nubri village beneath Manaslu. Overnight in Samagaun.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Acclimatization — hike Manaslu Base Camp",
      maxAltitude: "4,800 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Rest day hike to Manaslu Base Camp and Birendra Lake (~13.5 km / 7–8 hrs). Essential acclimatization before Larkya La. Overnight again in Samagaun.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Trek Samagaun to Samdo",
      maxAltitude: "3,860 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Shorter walk (~8.5 km / 4–5 hrs) to Samdo — last major village before the pass, near Tibet border trade routes. Overnight in Samdo.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Trek Samdo to Larkya La Phedi (Dharamsala)",
      maxAltitude: "4,460 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Trek to Dharamsala / Larkya Phedi (~9 km / 4–5 hrs) with rapid altitude gain. Short acclimatization walk recommended. Early sleep for pass day. Overnight in Dharamsala.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Cross Larkya La — trek to Bhimthang",
      maxAltitude: "5,106 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Pre-dawn start to cross Larkya La (5,106 m) with views of Manaslu, Cheo Himal, Himlung, and Larkya Peak, then long descent to Bhimthang (~16 km / 8–9 hrs). Crampons/poles recommended. Overnight in Bhimthang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Trek Bhimthang to Tilje — drive Besisahar",
      maxAltitude: "2,300 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house in Besisahar",
      description:
        "Pleasant descent through rhododendron and pine forest to Tilje (~13 km / 4 hrs), then sharing jeep to Besisahar (~3 hrs). Trail joins the Annapurna Circuit route. Overnight in Besisahar.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Drive Besisahar to Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast, Lunch",
      accommodation: "Hotel in Kathmandu",
      description:
        "Local bus back to Kathmandu (~7–8 hrs / ~175 km). Optional Pokhara finish on request. Farewell evening. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Final departure",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "— (departure day)",
      description:
        "Private airport transfer for your international departure. End of the Manaslu Circuit journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Manaslu Circuit runs best in autumn (Sep–Nov) and spring (Mar–May). Winter snow can block Larkya La; monsoon brings landslides and difficult road access to Machha Khola.",
  availabilityNotes: [
    "Private and joining dates available (minimum 2 trekkers per permit)",
    "Licensed guide mandatory — permits arranged by Summit Seek",
    "Roadhead may shift (Soti Khola / Dharapani) by season",
    "Tsum Valley extension available on request",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Porter service",
      description: "Full-trip porter support (~US$290 reference rate; confirm when booking).",
      priceLabel: "From US$290",
      visible: true,
    },
    {
      id: "a2",
      title: "Private jeep to Machha Khola",
      description: "Upgrade local bus Kathmandu–Machha Khola to private jeep (~US$200).",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Tsum Valley extension",
      description: "Add days into sacred Tsum Valley before rejoining the circuit.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a4",
      title: "Single room supplement",
      description: "Private rooms where available in hotels and teahouses.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport pickup and drop-off by private car",
    "2 nights hotel in Kathmandu with breakfast",
    "Licensed mountain guide with salary, food, lodging, transport, and insurance",
    "Manaslu Special Permit, MCAP, ACAP, and Tsum Nubri entrance fee",
    "Full-board meals (breakfast, lunch, dinner) during the trek",
    "Kathmandu–Machha Khola and Besisahar–Kathmandu by local bus",
    "Tilje–Besisahar sharing jeep",
    "Twin-share teahouse rooms; hot tea/coffee and seasonal fruit on trek",
    "Down jacket, sleeping bag, duffel if needed; first-aid kit and trek map",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Travel insurance (mandatory — high-altitude evacuation)",
    "Porter service unless added",
    "Private jeep upgrade unless selected",
    "Nepal visa and international flights",
    "Lunch and dinner in Kathmandu (unless stated)",
    "Bar bills and personal expenses (laundry, charging, showers, bottled water)",
    "Tips for guide and porter",
    "Costs from roadblocks, weather, or delays beyond our control",
    "Anything not listed in the includes section",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Alpine ridges toward Manaslu",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "High Himalayan pass light",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Mountain panorama on the circuit",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Budhi Gandaki valley approaches",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "September–November and March–May usually offer the clearest views and most reliable Larkya La conditions. Winter snow can close the pass; monsoon increases landslide and road risk.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & AMS",
      body: "Max altitude is Larkya La at 5,106 m. Use the Samagaun rest day, hydrate, and descend if symptoms worsen. Dharamsala (~4,460 m) is the last lodge before the pass.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Restricted area rules",
      body: "Minimum 2 trekkers per permit group with a licensed guide. Summit Seek arranges Manaslu Special Permit, MCAP, ACAP, and local fees — unguided trekking is not allowed.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Difficulty",
      body: "Challenging. Long walking days, rough trails, and a tough pass crossing. Microspikes and trekking poles highly recommended for ice and scree near Larkya La.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack for a cold, early Larkya La start and a long scree descent. Microspikes are strongly recommended for ice near the pass.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers & thermals",
        "Fleece mid-layer and heavy down jacket",
        "Waterproof hard shell",
        "Warm trekking pants + insulated evening layer",
        "Warm hat, sun hat, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Microspikes (strongly recommended)",
        "Trekking poles",
        "25–35L daypack + duffel for porter",
        "Bright headlamp + spare batteries",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "Category 3–4 UV sunglasses",
        "SPF sunscreen & lip balm",
        "Personal medications and blister care",
        "Water bottle + purification",
        "High-energy snacks",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance (high-altitude evacuation)",
        "Passport photos if needed for permits",
        "Cash for personal trail expenses",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Permit processing and licensed guide assignment",
    "Down jacket, sleeping bag, and duffel rental if required",
    "First-aid kit on trail; evacuation coordination via your insurance",
    "Advice on Tsum Valley extensions and private jeep upgrades",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Manaslu Circuit trek?",
      answer:
        "A 14-day restricted-area circuit around Mt. Manaslu crossing Larkya La (5,106 m), from Machha Khola through Samagaun to Besisahar via Tilje.",
      visible: true,
    },
    {
      id: "q2",
      question: "How much does it cost?",
      answer:
        "This listing starts at US$950 for 2–4 pax (US$1,200 solo joiner; US$900 for 5–8; US$850 for 9+). Compare-at US$1,520.",
      visible: true,
    },
    {
      id: "q3",
      question: "Can I trek solo?",
      answer:
        "Solo independent trekking is not allowed in the restricted area. Minimum 2 trekkers per permit — solo travelers can join a group departure with Summit Seek.",
      visible: true,
    },
    {
      id: "q4",
      question: "What is the maximum altitude?",
      answer:
        "Larkya La Pass at 5,106 m. The Manaslu Base Camp acclimatization hike reaches 4,800 m.",
      visible: true,
    },
    {
      id: "q5",
      question: "What permits are required?",
      answer:
        "Manaslu Special Permit, MCAP, ACAP, and Tsum Nubri rural municipality entrance fee — all arranged by Summit Seek with your licensed guide.",
      visible: true,
    },
    {
      id: "q6",
      question: "When is the best time?",
      answer:
        "Autumn (September–November) and spring (March–May) usually offer the clearest weather for Larkya La.",
      visible: true,
    },
    {
      id: "q7",
      question: "Is travel insurance necessary?",
      answer:
        "Yes. Cover high-altitude trekking and emergency helicopter evacuation to at least 6,000 m.",
      visible: true,
    },
    {
      id: "q8",
      question: "Can I combine with Tsum Valley?",
      answer:
        "Yes — Tsum Valley is a popular extension. Ask us to customize a Manaslu Circuit + Tsum Valley itinerary.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Manaslu Circuit?",
  ctaBody: `Tell us your preferred dates and group size (minimum 2) — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Manaslu Circuit Trek 14 Days | Summit Seek",
  metaDescription:
    "Book 14-day Manaslu Circuit trek — Larkya La (5,106 m), Samagaun, restricted permits, licensed guide & group rates from US$850.",
};
