import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_MARDI_HIMAL: TrekPageContent = {
  coverImageUrl: img("photo-1464822759023-fed622ff2c3b", 2000),
  coverTitle: "Mardi Himal Trek - 5 Days",
  coverSubtitle:
    "A short offbeat Annapurna ridge trek from Pokhara — forests, High Camp, and Mardi Himal Base Camp views of Fishtail, Annapurna, and Hiunchuli.",
  heroMainImageUrl: img("photo-1464822759023-fed622ff2c3b", 2000),
  heroSideImage1Url: img("photo-1585409677983-0f6c41ca9c3b", 900),
  heroSideImage2Url: img("photo-1483728642387-6c3bdd6c93e5", 900),
  breadcrumbLabel: "Annapurna Region · Mardi Himal",
  title: "Mardi Himal Trek - 5 Days",
  regionLabel: "Annapurna Region",
  rating: 5,
  reviewCount: 12,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 399,
  compareAtPrice: 499,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "20% OFF",
  shortTripBadge: "Short Trip",
  durationLabel: "5 Days",
  difficultyLabel: "Moderate",
  groupSizeLabel: "1+",
  bookingNote:
    "Pokhara start and end. Private and small-group departures available year-round. Ideal if you are already in Pokhara and want a quieter alternative to ABC or Poon Hill.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 450, visible: true },
    { id: "gd2", paxLabel: "2-6 pax", price: 399, visible: true },
    { id: "gd3", paxLabel: "7-12 pax", price: 370, visible: true },
    { id: "gd4", paxLabel: "13-20 pax", price: 350, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "5 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Moderate", visible: true },
    { id: "f3", label: "Max Altitude", value: "4,500 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Pokhara", visible: true },
    { id: "f5", label: "Region", value: "Annapurna", visible: true },
    { id: "f6", label: "Group Size", value: "1+", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Nature", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The short Mardi Himal trek starts and ends in Pokhara — a hidden-gem ridge route in the Annapurna region, opened more widely to trekkers around 2012. East of the classic Annapurna Base Camp corridor, it offers a quieter, more wilderness-focused alternative to crowded Annapurna trails.\n\nIn five days you drive to Kande and ascend via Australian Camp, Pothana, Pitam Deurali, Low Camp, Badal Danda, and High Camp before reaching Mardi Himal Base Camp for sunrise over Annapurna, Machhapuchhre (Fishtail), Hiunchuli, Nilgiri, and Dhaulagiri. The return descends toward Siding and a jeep back to Pokhara.\n\nSummit Seek keeps daily walking manageable with licensed guides, fair porter support (shared), clear pricing, and flexible private departures — ideal for short schedules and first-time Himalayan adventurers who still want real altitude and big views.",
  overviewImageUrl: img("photo-1544735716-392fe2489ffa"),
  highlightsHeading: "Highlights",
  highlights: [
    "Short trek from Pokhara — perfect if you are already lakeside",
    "Quieter ridge alternative to ABC and Ghorepani Poon Hill",
    "Dense rhododendron and oak forests opening onto steep alpine ridges",
    "Mardi Himal Base Camp sunrise over Annapurna, Fishtail & Hiunchuli",
    "Entry-level offbeat route with strong wilderness character",
    "Diverse terrain and flora/fauna along ~40–50 km of trail",
    "Mountain village feel near Siding on the final descent",
    "Great value short trek for limited time and budget",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Licensed English-speaking guide with salary, food, lodging & insurance",
    "Porter support (typically 2 guests : 1 porter; solo porter available as add-on)",
    "Private transfer Pokhara → Kande and local jeep Siding → Pokhara",
    "ACAP & TIMS permits arranged",
    "Teahouse lodging and meals on trek days as listed",
    "First-aid support on trail; emergency evacuation coordination via your insurance",
    "Pre-trek briefing in Pokhara and daily plan with your guide",
  ],
  whyHeading: "Why choose Mardi Himal?",
  whyPoints: [
    "Big Annapurna views without the crowds of classic ABC trails",
    "Fits neatly into a one-week Pokhara stay",
    "Remote forest-to-ridge atmosphere with rewarding base-camp payoff",
    "Suitable for fit beginners with preparation — no technical climbing",
    "Easy to combine or extend toward Poon Hill / Khopra on request",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "Yes — with decent fitness. Mardi Himal is often marketed as an entry-level offbeat trek, but the High Camp to Base Camp section is steep and can feel challenging. Expect 5–7 hours of walking on most days and a high point around 4,500 m.\n\nPrior multi-day hiking helps but is not required. Build cardio before you fly, stay hydrated, and tell your guide early if you feel unwell. Travel insurance covering helicopter evacuation is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Walk regularly and add cardio (jogging, cycling, day hikes) in the weeks before departure",
    "Break in waterproof hiking boots on practice walks",
    "Pack layers for cold forest shade and windy ridges, plus rain shell and sun protection",
    "Buy travel insurance covering trekking and helicopter evacuation",
    "Carry snacks/energy bars — teahouse menus are simpler on this quieter trail",
    "Confirm dietary needs and any allergies with Summit Seek before you start",
  ],
  itineraryHeading: "5-day itinerary",
  itineraryIntro:
    "Walking and drive times are estimates and vary with pace and weather. Lodges may change with availability. Your guide can adjust the plan for safety or comfort. This package is Pokhara-based; Kathmandu–Pokhara transport and city hotels are available as add-ons.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Pokhara – Kande – Pitam Deurali",
      maxAltitude: "2,125 m",
      meals: "Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Drive from Pokhara to Kande (about 40 minutes) with countryside and mountain views. Trek via lush hillsides and Australian Camp toward Pothana, then continue to Pitam Deurali (about 3–4 hours / ~5.5 km). Overnight lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Pitam Deurali – Low Camp",
      maxAltitude: "3,050 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Ascend north into dense rhododendron forest with limited sunlight and cool air. Reach Low Camp with close views of Machhapuchhre / Fishtail (about 5–6 hours / ~6.8 km). Overnight at Low Camp.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Low Camp – High Camp",
      maxAltitude: "3,580 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Climb through oak and rhododendron forest to Middle Camp, then up to Badal Danda for outstanding mountain views. Continue along the Mardi Himal ridge to High Camp with Annapurna, Fishtail, and Hiunchuli panoramas (about 4 hours / ~8.5 km).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "High Camp – Mardi Himal Base Camp – Low Camp / Badal Danda",
      maxAltitude: "4,500 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Early start on a narrow steep trail to Mardi Himal Base Camp (~4,500 m) for sunrise over Annapurna, Hiunchuli, Fishtail, Nilgiri, and Dhaulagiri. Descend the same route to overnight at Badal Danda or Low Camp (about 6–7 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Low Camp / Badal Danda – Siding – Pokhara",
      maxAltitude: "822 m (Pokhara)",
      meals: "Breakfast, Lunch",
      accommodation: "— (return to Pokhara hotel)",
      description:
        "Final trek through forests and settlements to Siding (~1,200 m), then local jeep back to Pokhara (about 6 hours walking / ~11.3 km plus drive). Hotel drop-off; free afternoon lakeside. Overnight hotel in Pokhara is not included unless added.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Mardi Himal departures run on private and joining bases year-round. Spring and autumn offer the clearest views; winter can bring snow on higher ridges; monsoon trails are muddy and slippery.",
  availabilityNotes: [
    "Private departures with flexible Pokhara start dates",
    "Small-group joining available with advance booking",
    "Customizable — extend toward Poon Hill or Khopra on request",
    "Confirmed booking after deposit and Pokhara briefing",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Solo / extra porter",
      description: "Dedicated porter for solo travelers or extra luggage (within ethical load limits).",
      priceLabel: "From US$150",
      visible: true,
    },
    {
      id: "a2",
      title: "Pokhara hotel night",
      description: "Add twin-sharing hotel nights with breakfast before or after the trek.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Kathmandu ↔ Pokhara flight / bus",
      description: "We can arrange road or flight links if your trip starts from Kathmandu.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Breakfast, lunch, and dinner (main course) on trek days as per itinerary",
    "Teahouse / lodge accommodation during the trek (typically twin share, shared toilets)",
    "Private transport Pokhara → Kande (trek start)",
    "Local sharing jeep Siding → Pokhara (trek end)",
    "Licensed English-speaking trekking guide (salary, food, lodging, insurance)",
    "Porter support for 2 guests : 1 porter (solo porter as add-on)",
    "Annapurna Conservation Area Permit (ACAP) & TIMS card",
    "Summit Seek service charge and local coordination",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Airport transfers and international airfare",
    "Hotels and meals in Kathmandu / Pokhara (except trek meals listed)",
    "Kathmandu ↔ Pokhara transportation",
    "Travel insurance (mandatory — must cover helicopter evacuation)",
    "Personal trekking gear (boots, poles, sleeping bag, down jacket, etc.)",
    "Tips for guide and porter",
    "Drinks, desserts, bottled water, hot showers, Wi-Fi, charging, laundry",
    "Local government taxes / personal expenses not listed in includes",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Ridge trails toward Mardi Himal",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1585409677983-0f6c41ca9c3b"),
      caption: "Annapurna massif from the Mardi approach",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1483728642387-6c3bdd6c93e5"),
      caption: "Sunrise light on Himalayan peaks",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Forest and mountain trail atmosphere",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May and September–November usually bring the most stable weather and clearest panoramas. Winter is possible with snow higher up; June–August is wetter and slipperier underfoot.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Difficulty & altitude",
      body: "Expect moderate effort with steep sections especially High Camp → Base Camp. Max altitude ~4,500 m. Stay hydrated and pace yourself; inform your guide at the first sign of altitude symptoms.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Permits",
      body: "ACAP (about NPR 3,000) and TIMS (about NPR 2,000) are required. Both are included in this Summit Seek package — we need your passport details and photos to process them.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Lodges & meals",
      body: "Family-run teahouses with twin beds and shared toilets. Menus are simpler than on busier Annapurna routes — dal bhat, noodles, pasta, eggs, porridge, and similar. Hot showers and charging often cost extra.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack light — typical duffel limit is about 10 kg per person for the shared porter. Carry a daypack with water, layers, documents, and snacks. Many items can be rented in Pokhara or Kathmandu.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base / thermal layers",
        "Fleece mid-layer",
        "Down / insulated jacket",
        "Windbreaker and rain shell",
        "Trekking pants + warm evening layer",
        "Gloves, scarf/buff, sun hat, beanie, socks",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in trekking boots",
        "Camp slippers / crocs",
        "Trekking poles",
        "Daypack + duffel for porter",
        "Reusable water bottle + purification tablets",
        "Headlamp / torch + spare batteries",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "SPF sunscreen & lip balm",
        "Sunglasses",
        "Personal medications (including altitude advice from your doctor)",
        "Blister care / basic first aid",
        "Wet wipes & toilet paper",
        "Snacks and energy bars",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies / photos for permits",
        "Travel insurance details",
        "Nepali cash in small denominations",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Duffel bag for porter use on many packages (return after trek)",
    "Pokhara hotel pickup for the trek start transfer",
    "Sleeping bag / down jacket rental options on request",
    "Help arranging Pokhara hotels and Kathmandu–Pokhara links",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "How high is Mardi Himal Base Camp?",
      answer:
        "Mardi Himal Base Camp sits at approximately 4,500 m (14,764 ft) — the highest point on this 5-day itinerary.",
      visible: true,
    },
    {
      id: "q2",
      question: "How much does the short Mardi Himal trek cost?",
      answer:
        "This Summit Seek package is listed from US$399 per person (2–6 pax), with solo and larger-group rates shown in the group discount table. Exact quotes depend on dates and add-ons.",
      visible: true,
    },
    {
      id: "q3",
      question: "Is there an age limit?",
      answer:
        "No fixed age limit. If you are fit enough to walk 5–6+ hours on rugged terrain and comfortable with high altitude, you can join. Tell us ages and fitness when you enquire.",
      visible: true,
    },
    {
      id: "q4",
      question: "What mountain views will I see?",
      answer:
        "Expect panoramas of Annapurna, Machhapuchhre (Fishtail), Hiunchuli, Nilgiri, Dhaulagiri, Mardi Himal, and surrounding ridges — especially from High Camp and Base Camp.",
      visible: true,
    },
    {
      id: "q5",
      question: "Is drinking water safe?",
      answer:
        "Boiled water is widely available at lodges and is safer and cheaper than plastic bottles. You can also use purification tablets. We discourage single-use plastic bottles on the trail.",
      visible: true,
    },
    {
      id: "q6",
      question: "Do I need a guide?",
      answer:
        "Yes. Trekking without a licensed guide is restricted in the Annapurna Conservation Area. Solo packages are available as a private guided trek (porter optional add-on).",
      visible: true,
    },
    {
      id: "q7",
      question: "What are the hardest days?",
      answer:
        "High Camp to Mardi Himal Base Camp (steep ascent) and the long descent toward Siding are typically the most demanding sections.",
      visible: true,
    },
    {
      id: "q8",
      question: "Do I need travel insurance?",
      answer:
        "Yes. Cover trekking at altitude and helicopter evacuation. Summit Seek does not sell insurance — we can help you confirm altitude limits before you buy.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Mardi Himal?",
  ctaBody: `Tell us your preferred Pokhara dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Mardi Himal Trek 5 Days | Summit Seek",
  metaDescription:
    "Book the 5-day Mardi Himal trek from Pokhara with Summit Seek — ridge wilderness, Base Camp sunrise, ACAP & TIMS, guide, porter options, and group discounts.",
};
