import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_MERA_PEAK: TrekPageContent = {
  coverImageUrl: img("photo-1434394354979-a235cd36269d", 2000),
  coverTitle: "Mera Peak Climbing - 18 Days",
  coverSubtitle:
    "Nepal’s highest trekking peak (6,476 m) via the quiet Hinku Valley — Sherpa villages, high-camp glacier approach, and summit panoramas of Everest, Lhotse, Makalu, Cho Oyu, and Kanchenjunga.",
  heroMainImageUrl: img("photo-1434394354979-a235cd36269d", 2000),
  heroSideImage1Url: img("photo-1464822759023-fed622ff2c3b", 900),
  heroSideImage2Url: img("photo-1486870591958-9b9d0d1dda99", 900),
  breadcrumbLabel: "Everest Region · Peak Climbing",
  title: "Mera Peak Climbing - 18 Days",
  regionLabel: "Everest Region",
  rating: 5,
  reviewCount: 7,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 2499,
  compareAtPrice: 2699,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "7% OFF",
  shortTripBadge: "Highest Trekking Peak",
  durationLabel: "18 Days",
  difficultyLabel: "Strenuous",
  groupSizeLabel: "2+",
  bookingNote:
    "Private and small-group departures. Package includes Kathmandu hotels (BB as listed), Lukla flights (via Kathmandu or Manthali as season requires), licensed trekking & climbing guide, porter, trek meals, teahouse lodging, high-camp tent night, climbing permits, and group climbing support. Ideal first 6,000 m peak for fit climbers with prior trek experience.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "2 pax", price: 2699, visible: true },
    { id: "gd2", paxLabel: "3-5 pax", price: 2499, visible: true },
    { id: "gd3", paxLabel: "6-10 pax", price: 2349, visible: true },
    { id: "gd4", paxLabel: "11-15 pax", price: 2199, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "18 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Strenuous", visible: true },
    { id: "f3", label: "Max Altitude", value: "6,476 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Khumbu / Hinku Valley", visible: true },
    { id: "f6", label: "Group Size", value: "2 onwards", visible: true },
    { id: "f7", label: "Activities", value: "Trek & Climbing", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Oct–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "Mera Peak Climbing is Nepal’s classic high trekking-peak expedition — the country’s highest trekking peak at 6,476 m (Mera North), with Central (6,461 m) and South (6,065 m) summits. The climbing slopes rarely exceed ~30°, so with Sherpa-fixed ropes and training at Khare it is widely recommended as a first 6,000 m peak for new climbers who already trek well.\n\nThis 18-day itinerary flies to Lukla, then follows a quieter Khumbu approach through Paiya, Panggom, and the Hinku Valley to Kothe, Thaknak, and Khare for acclimatization and pre-climb training. You move to Mera High Camp (~5,800 m), summit (typically Central/North as conditions allow), keep a contingency day, then exit via Thuli Kharka and Zatrwa La to Lukla.\n\nSummit views can include Everest, Lhotse, Makalu, Cho Oyu, and Kanchenjunga. Summit Seek includes flights as listed, permits, guide, porter, meals, teahouses, high-camp camping, and clear group pricing.",
  overviewImageUrl: img("photo-1464822759023-fed622ff2c3b"),
  highlightsHeading: "Highlights",
  highlights: [
    "Summit Nepal’s highest trekking peak (up to 6,476 m)",
    "Non-technical glacier climb ideal for first-time peak climbers",
    "Quiet Hinku / Hongu valley approaches — fewer crowds than EBC",
    "Views of five 8,000 m peaks from the summit area",
    "Pre-climb training and rope practice at Khare",
    "Sherpa villages, forests, and Makalu–Barun park approaches",
    "High Camp (~5,800 m) with Everest–Makalu panorama",
    "Return via Zatrwa La to Lukla",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport transfers by private vehicle as listed",
    "Kathmandu hotel nights with breakfast as listed",
    "Lukla flights (Kathmandu or Manthali as season requires) with transfers",
    "Teahouse lodging on trek; tent night at high camp as listed",
    "Meals during the trek and climb as listed",
    "Licensed English-speaking trekking & climbing guide and porter",
    "All applicable climbing, national park, and local permits",
    "Sleeping bag / duffel / poles as arranged; first-aid kit; map; taxes",
  ],
  whyHeading: "Why choose Mera Peak?",
  whyPoints: [
    "Highest trekking peak in Nepal — big altitude, moderate technical demand",
    "Better “first 6,000 m” choice than Island Peak for many climbers",
    "Quieter trails than classic Everest Base Camp",
    "Built-in training day and contingency summit buffer",
    "Unforgettable 8,000 m mountain panorama from the top",
  ],
  beginnersHeading: "Is this climb good for beginners?",
  beginnersBody:
    "Suitable for fit climbers with solid prior trekking experience (ideally above 5,000 m). Technically it is not advanced — slopes are moderate and ropes are fixed — but the altitude, long days, and remote logistics make it strenuous.\n\nA licensed climbing guide is required for the permit. Travel insurance covering high-altitude climbing and helicopter evacuation is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train 4–6 weeks: endurance, strength, and hikes with a loaded pack",
    "Prior high-altitude trek experience strongly recommended",
    "Break in boots; practice with a daypack on long hills",
    "Pack for cold high camps and glacier sun",
    "Buy insurance covering climbing to 6,500 m and heli evacuation",
    "Arrive Kathmandu for briefing, gear check, and optional rental",
  ],
  itineraryHeading: "18-day itinerary",
  itineraryIntro:
    "Based on the classic Hinku Valley Mera Peak routing. Lukla flights may operate via Manthali (Ramechhap) in peak season — early morning transfers apply. Summit and contingency days depend on weather.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,400 m",
      meals: "—",
      accommodation: "Hotel in Kathmandu",
      description:
        "Airport meet-and-greet and hotel transfer. Free time to rest or explore. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Kathmandu free day & expedition briefing",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Gear check and pre-trek briefing with your guide. Optional Thamel rental shopping. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Fly Lukla – trek to Paiya",
      maxAltitude: "2,730 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Flight to Lukla (~30 min; may be via Manthali in peak season). Trek via Surke and Chutok La to Paiya (~5–6 hours). Overnight lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Trek Paiya – Panggom",
      maxAltitude: "2,850 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Via Kari La through rhododendron and bamboo with Dudhkoshi Valley views (~5–6 hours). Overnight in Panggom.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Trek Panggom – Ningsow",
      maxAltitude: "2,863 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Cross Panggom La and continue via Peeng Kharka to Ningsow (~4–5 hours). Overnight lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Trek Ningsow – Chhetra Khola",
      maxAltitude: "3,122 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Via Ramailo Danda with Mera Peak views; enter Makalu–Barun approaches toward Chhatra / Chhetra Khola (~7–8 hours). Overnight lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Trek Chhetra Khola – Kothe",
      maxAltitude: "3,580 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Follow the Mera trail via Majang and Hinku Khola to Kothe (~6–7 hours). Overnight lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Trek Kothe – Thaknak",
      maxAltitude: "4,358 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Along Hinku Khola past Gondishung and Lungsumgba Gompa to Thaknak (~3–4 hours). Overnight lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Trek Thaknak – Khare",
      maxAltitude: "5,000 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Via Dig Kharka and glacier moraine to Khare (~5,000 m) with views of Mera’s north face (~3–4 hours). Overnight lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Acclimatization & pre-climb training at Khare",
      maxAltitude: "5,000 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Rest day with basic climbing techniques, rope practice, and equipment familiarization. Overnight in Khare.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Khare – Mera High Camp",
      maxAltitude: "5,800 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Tent camp",
      description:
        "Ascend via rocky trail and Mera La to High Camp (~5,800 m) with Everest–Makalu–Cho Oyu views. Overnight tent camp.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Summit Mera Peak – descend to Khare",
      maxAltitude: "6,461–6,476 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Pre-dawn summit push (~3 am start) on fixed ropes as needed. Panorama of Everest, Lhotse, Makalu, Cho Oyu, Kanchenjunga, and more. Descend to Khare for overnight.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Reserve / contingency day at Khare",
      maxAltitude: "5,000 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Weather buffer for a delayed summit attempt. If already successful, rest day in Khare.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Trek Khare – Kothe",
      maxAltitude: "3,580 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Descend via Thaknak to Kothe (~4–5 hours). Overnight lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d15",
      dayLabel: "Day 15",
      title: "Trek Kothe – Thuli Kharka",
      maxAltitude: "4,200 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Ups and downs along Inkhu Khola branches to Thuli Kharka (~5–6 hours). Overnight lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d16",
      dayLabel: "Day 16",
      title: "Trek Thuli Kharka – Lukla via Zatrwa La",
      maxAltitude: "4,610 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Cross Zatrwa La (~4,600 m) and descend to Lukla (~6–7 hours). Overnight in Lukla.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d17",
      dayLabel: "Day 17",
      title: "Fly Lukla – Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Morning flight to Kathmandu or Manthali (then drive). Free afternoon; optional shopping. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d18",
      dayLabel: "Day 18",
      title: "Final departure",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "—",
      description:
        "Airport transfer for your international flight. End of the Mera Peak expedition with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best in March–early May and October–November for stable summit weather. Private groups welcome. Allow buffers for Lukla flights (often via Manthali in peak season).",
  availabilityNotes: [
    "Private and customizable start dates",
    "Licensed climbing guide mandatory for permits",
    "Contingency summit day built into the itinerary",
    "Lukla flights are weather-dependent — allow buffers",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Extra Kathmandu nights",
      description: "Buffer nights for Lukla delays or early arrivals.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Extra porter",
      description: "Additional porter support (up to ~20 kg) on request.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Personal climbing gear rental",
      description: "Boots, crampons, harness, ice axe, down suit items in Kathmandu.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "International airport pickup and final drop as listed",
    "Kathmandu hotel nights with breakfast as listed",
    "Teahouse twin-share lodging on trek; tent night at high camp as listed",
    "Meals during the trek and climb as listed (tea/coffee with breakfast)",
    "Licensed English-speaking trekking & climbing guide and porter",
    "Staff wages, food, equipment, and insurance",
    "All applicable climbing, national park, and local permits",
    "Kathmandu/Manthali–Lukla flights both ways with airport transfers as listed",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "International airfare",
    "Nepal entry visa fees",
    "Travel / health insurance covering emergency rescue and evacuation (mandatory)",
    "Personal trekking and climbing gear",
    "Snacks, alcohol, bottled water, hot shower, Wi-Fi, charging on trek",
    "Lunch and dinner in Kathmandu; extra hotel nights",
    "Optional extra porter hire",
    "Tips for guide and porters",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1434394354979-a235cd36269d"),
      caption: "High Himalayan light toward Mera Peak country",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Alpine approaches in the Hinku Valley",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "Glacier and ridgeline terrain near high camp",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Remote Khumbu valleys on the Mera approach",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–early May and October–November offer the most stable summit windows. Spring is peak mountaineering season with clearer flight reliability.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & difficulty",
      body: "Highest point is Mera Peak up to 6,476 m. Technically moderate (fixed ropes); physically strenuous due to altitude, long days, and remote facilities.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Permits",
      body: "Climbing permit plus national park / local permits are required and must be arranged through a registered company with a licensed guide. Summit Seek handles these.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Lodging & cash",
      body: "Teahouses to Khare; tents at high camp. No ATMs on the route — withdraw cash in Kathmandu. Charging available for a fee in lodges; use a power bank / solar above base camp.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Porters carry main bags; keep water, layers, documents, and camera in a daypack. Technical personal gear can often be rented in Kathmandu.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece / softshell mid-layers",
        "Down jacket (expedition warmth)",
        "Waterproof shell jacket and pants",
        "Warm gloves, mitts, balaclava, buff",
        "Sun hat and glacier glasses (Cat 3–4)",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & climbing",
      items: [
        "Broken-in mountaineering / insulated boots",
        "Crampons compatible with boots",
        "Ice axe and climbing harness",
        "Helmet, carabiners, belay device as advised",
        "Trekking poles and gaiters",
        "Camp shoes",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Camp & health",
      items: [
        "Sleeping bag (cold rating for high camp)",
        "Headlamp + spare batteries",
        "Water bottles + purification",
        "Personal first-aid & blister care",
        "SPF 50+ sunscreen and lip balm",
        "High-calorie snacks and electrolytes",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies + passport photos",
        "Nepal visa as applicable",
        "Insurance covering climbing to 6,500 m + heli rescue",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Permit processing and licensed climbing team",
    "Sleeping bag, duffel, and poles as arranged (return after trip)",
    "Pre-climb training at Khare",
    "Rescue coordination support (insurance covers costs)",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the highest trekking peak in Nepal?",
      answer:
        "Mera Peak — up to 6,476 m (North summit). Central summit is about 6,461 m and is commonly climbed.",
      visible: true,
    },
    {
      id: "q2",
      question: "Is Mera Peak harder than Island Peak?",
      answer:
        "Island Peak is generally more technical. Mera is higher but with a more straightforward snow slope — often preferred as a first 6,000 m peak.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This listing starts at US$2,499 for 3–5 pax (US$2,699 for 2; US$2,349 for 6–10; US$2,199 for 11–15).",
      visible: true,
    },
    {
      id: "q4",
      question: "Can I climb without a guide?",
      answer:
        "No. A licensed guide and registered company are required to obtain the climbing permit.",
      visible: true,
    },
    {
      id: "q5",
      question: "Can you see Everest from Mera Peak?",
      answer:
        "Yes — plus Lhotse, Makalu, Cho Oyu, Kanchenjunga, and many other giants on a clear summit day.",
      visible: true,
    },
    {
      id: "q6",
      question: "How long does Mera Peak take?",
      answer:
        "Itineraries typically run 12–21 days. This Summit Seek package is 18 days with training and a contingency day.",
      visible: true,
    },
    {
      id: "q7",
      question: "Is travel insurance necessary?",
      answer:
        "Yes — covering high-altitude climbing and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q8",
      question: "When is the best time to climb?",
      answer:
        "March–early May and October–November usually offer the best summit conditions.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Mera Peak?",
  ctaBody: `Tell us your preferred dates, experience level, and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Mera Peak Climbing 18 Days | Summit Seek",
  metaDescription:
    "Book 18-day Mera Peak climbing with Summit Seek — 6,476 m highest trekking peak, Hinku Valley, permits, guide, Lukla flights & group discounts from US$2,199.",
};
