import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_MUSTANG_JEEP: TrekPageContent = {
  coverImageUrl: img("photo-1506905925346-21bda4d32df4", 2000),
  coverTitle: "Mustang Jeep Tour - 7 Days",
  coverSubtitle:
    "Private jeep into the Forbidden Kingdom — Lo Manthang, Jhong Cave, desert cliffs, and Kali Gandaki scenery without long trekking days.",
  heroMainImageUrl: img("photo-1506905925346-21bda4d32df4", 2000),
  heroSideImage1Url: img("photo-1483728642387-6c3bdd6c93e5", 900),
  heroSideImage2Url: img("photo-1585409677983-0f6c41ca9c3b", 900),
  breadcrumbLabel: "Mustang Region · Jeep Tour",
  title: "Mustang Jeep Tour - 7 Days",
  regionLabel: "Mustang Region",
  rating: 5,
  reviewCount: 11,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 850,
  compareAtPrice: 1090,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "22% OFF",
  shortTripBadge: "Restricted Area",
  durationLabel: "7 Days",
  difficultyLabel: "Easy",
  groupSizeLabel: "1–12",
  bookingNote:
    "Private and small-group jeep departures. Package includes Pokhara hotel nights (BB as listed), private overland jeep as per itinerary, licensed guide, tour meals on Mustang days, Upper Mustang RAP and ACAP as required. Ideal if you want Lo Manthang without a full trek.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 1090, visible: true },
    { id: "gd2", paxLabel: "2-3 pax", price: 850, visible: true },
    { id: "gd3", paxLabel: "4-6 pax", price: 790, visible: true },
    { id: "gd4", paxLabel: "7-12 pax", price: 740, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "7 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Easy", visible: true },
    { id: "f3", label: "Max Altitude", value: "3,960 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Upper Mustang", visible: true },
    { id: "f6", label: "Group Size", value: "1–12", visible: true },
    { id: "f7", label: "Activities", value: "Jeep Tour & Culture", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The Mustang Jeep Tour is a one-week private overland journey into Upper Mustang’s Forbidden Kingdom — arid valleys, eroded cliffs, ancient caves, historic monasteries, and the walled capital of Lo Manthang — designed for travelers who want the culture and landscapes without long trekking days.\n\nFrom Kathmandu you drive to Pokhara, then continue by private jeep via Jomsom and Chhusang into Lo Valley, climbing toward Lo La (~3,960 m) before descending into Lo Manthang. A full exploration day covers Jhong Cave, Nyiphu and Garphu monasteries, and key heritage sites, then you return via Marpha apple country to Pokhara and Kathmandu.\n\nExpect Gurung, Thakali, and Lowa hospitality, Buddhist and Bon heritage, and big Annapurna–Dhaulagiri panoramas. Summit Seek includes RAP/ACAP, licensed guide, private jeep logistics, lodge lodging, and clear group pricing. Time your trip for Tiji Festival on request.",
  overviewImageUrl: img("photo-1483728642387-6c3bdd6c93e5"),
  highlightsHeading: "Highlights",
  highlights: [
    "One-week private jeep tour through Kali Gandaki and Lo Valley",
    "Walled city of Lo Manthang — ancient capital of Upper Mustang",
    "2,500-year-old Jhong Cave and Chhoser cave dwellings",
    "Nyiphu, Garphu, Thubchen & Namgyal monastery visits",
    "Panoramas of Annapurna I, Dhaulagiri, Nilgiri, Machhapuchhre & more",
    "Desert cliffs, deep gorges, and rain-shadow landscapes",
    "Marpha apple village on the return",
    "Optional timing for Tiji Festival (usually May)",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport pick-up in Kathmandu as listed",
    "Pokhara hotel nights with breakfast as listed",
    "Private overland jeep transportation as per itinerary",
    "Twin-share lodge / hotel accommodation along the tour",
    "Meals (breakfast, lunch, dinner) on tour days as listed",
    "English-speaking government-registered tour guide",
    "Upper Mustang special permit and ACAP as required",
    "Daily oxygen saturation check, map, certificate; taxes included",
  ],
  whyHeading: "Why choose the jeep tour?",
  whyPoints: [
    "Reach Lo Manthang in a week without long trek days",
    "Ideal for travelers who prefer driving to high culture sites",
    "Same restricted-area permits and Forbidden Kingdom access",
    "Flexible for mixed ages and moderate fitness",
    "Easy to combine with Pokhara adventures or festival timing",
  ],
  beginnersHeading: "Is this tour good for beginners?",
  beginnersBody:
    "Yes — graded easy as a jeep-based cultural tour. Most days are scenic drives (5–8 hours) with short walks at viewpoints and heritage sites. You still reach ~3,800–3,960 m around Lo Manthang / Lo La, so hydrate, rest, and tell your guide if you feel altitude symptoms.\n\nTravel insurance covering high altitude and helicopter evacuation is required.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Pack for dusty, bumpy mountain roads and strong sun",
    "Bring motion-sickness remedies if you are sensitive to jeep travel",
    "Carry a buff, sunglasses, and high-SPF sunscreen",
    "Light warm layers for cool nights in Lo Manthang",
    "Buy insurance covering travel to ~4,000 m and evacuation",
    "Arrive Kathmandu a day early for briefing and permit processing",
  ],
  itineraryHeading: "7-day itinerary",
  itineraryIntro:
    "Drive times are estimates and vary with road and weather conditions. Lodge stops may change with availability. Your Summit Seek guide can adjust the plan for comfort and safety.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Drive Kathmandu – Pokhara",
      maxAltitude: "822 m",
      meals: "Breakfast",
      accommodation: "Hotel in Pokhara",
      description:
        "Tourist bus / vehicle along the Trishuli corridor to Pokhara (~5–6 hours / ~200 km). Lakeside evening free. Overnight in Pokhara.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Drive Pokhara – Chhusang",
      maxAltitude: "2,980 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge / Teahouse",
      description:
        "Long scenic jeep day via Jomsom and the Kali Gandaki riverbed to Chhusang (~8 hours / ~170 km). Afternoon village stroll. Overnight in Chhusang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Drive Chhusang – Lo Manthang",
      maxAltitude: "3,960 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge / Hotel",
      description:
        "Jeep into Lo Valley toward Lo Manthang (~6 hours / ~50 km), crossing Lo La (~3,960 m) for the first views of the walled city. Overnight in Lo Manthang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Explore Jhong Cave & monasteries",
      maxAltitude: "3,840 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge / Hotel",
      description:
        "Jeep sightseeing (~3 hours driving/touring) to Nyiphu and Garphu monasteries, Jhong Cave (~44 chambers), Summer Palace area, and Namgyal Gompa. Overnight in Lo Manthang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Drive Lo Manthang – Marpha",
      maxAltitude: "2,650 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge / Hotel",
      description:
        "Return south by jeep to Marpha, the clean apple capital of Lower Mustang (~6 hours / ~80 km). Overnight in Marpha.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Drive Marpha – Pokhara",
      maxAltitude: "822 m",
      meals: "Breakfast, Lunch",
      accommodation: "Hotel in Pokhara",
      description:
        "Continue by jeep via the Kali Gandaki corridor (Rupse / Tatopani area) back to Pokhara (~8 hours / ~150 km). Free lakeside afternoon; farewell dinner as arranged. Overnight in Pokhara.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Drive Pokhara – Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "— (Kathmandu)",
      description:
        "Return drive to Kathmandu along the Trishuli corridor (~6 hours / ~200 km). Trip ends in Kathmandu. End of the Mustang Jeep Tour with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best in March–May and September–November for clear views and smoother roads. Private and joining groups of 1–12 are welcome. Winter can be very cold; monsoon means slippery dirt roads and possible delays.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Licensed guide and Upper Mustang RAP mandatory",
    "Private jeep logistics as per itinerary",
    "Tiji Festival timing available on request (usually May)",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Kathmandu–Pokhara flights",
      description: "Replace tourist bus with domestic flights (one way or round trip).",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Jomsom–Pokhara flight",
      description: "Skip part of the long road return with a scenic flight when weather allows.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Lo Manthang lodge upgrade",
      description: "Upgrade selected nights in Lo Manthang to a higher-category resort/lodge.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a4",
      title: "Pokhara adventures",
      description: "Add paragliding, zipline, or guided lakeside sightseeing.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport pick-up in Kathmandu and hotel transfer as listed",
    "Pokhara hotel accommodation with breakfast as listed",
    "Private overland jeep transportation as per itinerary",
    "Twin-share lodge / hotel lodging along the tour",
    "Meals (breakfast, lunch, dinner) along the tour as listed",
    "English-speaking government-registered tour guide (food, salary, insurance)",
    "Upper Mustang special permit and ACAP as required",
    "Tour map, daily SpO₂ check, water purification support, certificate",
    "Emergency rescue coordination support; government tax and service charge",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Hotel accommodation and meals in Kathmandu",
    "Lunch and dinner in Pokhara (except farewell dinner if arranged)",
    "International flights and Nepal visa fees",
    "Personal travel / medical insurance and evacuation costs",
    "Table drinks, bottled water, hot showers, battery charging, desserts",
    "City tour entrance fees",
    "Tips for the tour guide",
    "Costs from roadblocks, weather delays, or force majeure",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Open Himalayan valleys on the jeep approach",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1483728642387-6c3bdd6c93e5"),
      caption: "Arid ridgelines of Upper Mustang",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1585409677983-0f6c41ca9c3b"),
      caption: "Mountain light toward the Kali Gandaki",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "High plateau atmosphere near Lo Manthang",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May and September–November usually offer the clearest mountain views and the most reliable jeep-road conditions into Upper Mustang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude",
      body: "You sleep near 3,840 m in Lo Manthang and may cross Lo La around 3,960 m. Drink water, rest, and tell your guide early if you feel unwell.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Easy jeep-based touring with long bumpy drive days. Short walks at caves and monasteries. Suitable for most travelers comfortable with mountain roads.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Permits",
      body: "Upper Mustang Restricted Area Permit plus ACAP. Summit Seek arranges paperwork with your licensed guide. RAP is typically charged per day inside the restricted zone.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack light for dusty jeep days and cool Lo Manthang nights. Keep documents, camera, water, and layers in a day bag inside the vehicle.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Comfortable layers for long drives",
        "Light down / fleece for cool evenings",
        "Windproof shell",
        "Sun hat and buff for dust",
        "Warm hat and light gloves",
        "Modest clothing for monastery visits",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Comfortable closed shoes for short walks",
        "Sandals for hotels / evenings",
        "Small daypack",
        "Sunglasses (UV)",
        "Power bank (outages are common)",
        "Motion-sickness remedies if needed",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "High-SPF sunscreen & lip balm",
        "Personal medications",
        "Hand sanitizer & wet wipes",
        "Reusable water bottle",
        "Snacks for long road days",
        "Basic first-aid items",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance details",
        "Cash for personal extras",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "RAP / ACAP processing and licensed guiding",
    "Private jeep logistics and lodge bookings",
    "Daily SpO₂ checks and emergency coordination support",
    "Advice on festival timing and flight upgrades",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Mustang Jeep Tour?",
      answer:
        "A 7-day private overland tour from Kathmandu/Pokhara into Upper Mustang and Lo Manthang by jeep — caves, monasteries, and desert scenery without a full trek.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Easy overall. Expect long bumpy drives and short walks. Altitude near 3,800–3,960 m still requires pacing and hydration.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This Summit Seek listing starts at US$850 for 2–3 pax (US$1,090 solo; US$790 for 4–6; US$740 for 7–12).",
      visible: true,
    },
    {
      id: "q4",
      question: "Do I need special permits?",
      answer:
        "Yes. Upper Mustang Restricted Area Permit and ACAP are required. Summit Seek arranges these with a licensed guide.",
      visible: true,
    },
    {
      id: "q5",
      question: "Is this the same as Upper Mustang Trek?",
      answer:
        "No. This is a jeep-based cultural tour covering similar highlights in fewer days with far less walking.",
      visible: true,
    },
    {
      id: "q6",
      question: "Is travel insurance necessary?",
      answer:
        "Yes. Cover high-altitude travel and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q7",
      question: "When is the best time to go?",
      answer:
        "March–May and September–November usually offer the best weather and clearest mountain views.",
      visible: true,
    },
    {
      id: "q8",
      question: "Can I see Tiji Festival?",
      answer:
        "Yes — ask us to align dates with Tiji (typically May) when festival timing matches your travel window.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for the Mustang Jeep Tour?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Mustang Jeep Tour 7 Days | Summit Seek",
  metaDescription:
    "Book the 7-day Upper Mustang jeep tour with Summit Seek — Lo Manthang, Jhong Cave, private jeep, RAP & ACAP, guide, meals & group discounts from US$740.",
};
