import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_MUSTANG_HELI_VIP: TrekPageContent = {
  coverImageUrl: img("photo-1493246507139-91e8fad9978e", 2000),
  coverTitle: "VIP Mustang Helicopter Tour - 3 Days",
  coverSubtitle:
    "Exclusive helicopter charter into Upper Mustang’s Forbidden Kingdom — Lo Manthang landing, ancient gompas and sky caves, Annapurna–Dhaulagiri aerial panoramas.",
  heroMainImageUrl: img("photo-1493246507139-91e8fad9978e", 2000),
  heroSideImage1Url: img("photo-1506905925346-21bda4d32df4", 900),
  heroSideImage2Url: img("photo-1483728642387-6c3bdd6c93e5", 900),
  breadcrumbLabel: "Mustang Region · VIP Helicopter",
  title: "VIP Mustang Helicopter Tour - 3 Days",
  regionLabel: "Upper Mustang",
  rating: 5,
  reviewCount: 4,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 3890,
  compareAtPrice: 4190,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "7% OFF",
  shortTripBadge: "VIP Heli + Lo Manthang",
  durationLabel: "3 Days",
  difficultyLabel: "Easy",
  groupSizeLabel: "1–5",
  bookingNote:
    "VIP private/shared helicopter charter (up to 5 passengers). Package includes airport transfers, Upper Mustang Restricted Area Permit (~USD 500 pp), ACAP, government taxes, and Kathmandu–Jomsom–Lo Manthang–Kathmandu heli routing as listed (via Pokhara as flight plan requires). Overnight in Lo Manthang. Weather can cancel flights — keep buffer days in Nepal.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 4190, visible: true },
    { id: "gd2", paxLabel: "2-3 pax", price: 3890, visible: true },
    { id: "gd3", paxLabel: "4 pax", price: 3690, visible: true },
    { id: "gd4", paxLabel: "5 pax", price: 3490, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "3 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Easy", visible: true },
    { id: "f3", label: "Max Altitude", value: "3,800 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Upper Mustang", visible: true },
    { id: "f6", label: "Group Size", value: "1–5 (heli capacity)", visible: true },
    { id: "f7", label: "Activities", value: "Helicopter & Culture", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "VIP Mustang Helicopter Tour – 3 Days opens Nepal’s Forbidden Kingdom by air — turning a multi-day trek or rough jeep approach into an exclusive aerial journey to Lo Manthang, the walled capital of Upper Mustang where Tibetan-influenced culture thrives behind dramatic desert cliffs.\n\nAfter arrival in Kathmandu, your charter flies toward Jomsom along the Kali Gandaki corridor with Annapurna and Dhaulagiri panoramas, then continues to Lo Manthang (~3,700–3,800 m) for landing time at the Royal Palace area, ancient gompas (Jampa, Thubchen, Chodey), medieval lanes, and sky-cave viewpoints before overnighting in the walled city. Day three returns by helicopter to Kathmandu.\n\nSummit Seek includes Upper Mustang RAP and ACAP as listed, VIP heli charter logistics for up to five passengers, airport transfers, and clear group pricing. Morning departures maximize weather success; build 3–4 buffer days into your Nepal stay.",
  overviewImageUrl: img("photo-1506905925346-21bda4d32df4"),
  highlightsHeading: "Highlights",
  highlights: [
    "VIP helicopter charter into Upper Mustang’s restricted area",
    "Land in Lo Manthang — walled capital of the Forbidden Kingdom",
    "Aerial views of Annapurna, Dhaulagiri, and Kali Gandaki landscapes",
    "Visit Royal Palace complex and ancient gompas",
    "Photograph Tibetan-style sky caves from the approach",
    "Skip 10–14 days of trekking or multi-day jeep travel",
    "Upper Mustang RAP and ACAP handled for you",
    "Optional timing for Tiji Festival (usually May) on request",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport pickup and drop in Kathmandu as listed",
    "Helicopter charter routing Kathmandu–Jomsom–Lo Manthang–Kathmandu (via Pokhara as required)",
    "Upper Mustang Restricted Area Permit as listed",
    "Annapurna Conservation Area Permit (ACAP)",
    "All applicable government taxes and service charges as listed",
    "Experienced mountain-heli operator coordination",
    "Weather monitoring and reschedule support within your stay",
    "Clear VIP group pricing by passenger count",
  ],
  whyHeading: "Why choose VIP Mustang by helicopter?",
  whyPoints: [
    "Reach Lo Manthang in hours instead of weeks on foot",
    "Unmatched aerial photography of desert cliffs and trade routes",
    "Brief altitude exposure vs multi-day trek acclimatization",
    "Exclusive access to a restricted Himalayan kingdom",
    "Ideal for limited-time luxury and VIP travelers",
  ],
  beginnersHeading: "Is this tour good for beginners?",
  beginnersBody:
    "Yes — graded Easy with no trekking required. You fly and walk short distances in Lo Manthang. Brief exposure near 3,800 m rarely causes serious altitude illness, but those with heart or lung conditions should consult a doctor.\n\nMotion sickness medication before flight helps some passengers. Travel insurance covering helicopter tours and high-altitude evacuation is strongly recommended.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Book 7+ days ahead for RAP processing; 2–3 weeks in peak season",
    "Keep 3–4 weather buffer days in your Nepal itinerary",
    "Pack windproof layers, sunglasses, SPF 50+, and camera spare batteries",
    "Travel light — small daypack only; respect heli weight limits (~100 kg pp)",
    "Take anti-nausea medication 30 minutes before flight if needed",
    "Confirm insurance covers helicopter tours above 4,000 m",
  ],
  itineraryHeading: "3-day itinerary",
  itineraryIntro:
    "VIP charter schedule. Exact flight times depend on weather and ATC. Morning departures have the highest success rate; afternoon winds in the Kali Gandaki can delay operations.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu – briefing",
      maxAltitude: "1,350 m",
      meals: "—",
      accommodation: "Hotel in Kathmandu",
      description:
        "Airport meet-and-greet and hotel transfer. Trip introduction, permit check, and helicopter safety briefing. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Helicopter to Lo Manthang via Jomsom",
      maxAltitude: "3,800 m",
      meals: "As arranged on tour",
      accommodation: "Lodge / hotel in Lo Manthang",
      description:
        "Early hotel pickup and domestic heliport check-in. Fly Kathmandu toward Jomsom (~45–90 min depending on routing/refuel) with Annapurna–Dhaulagiri and Kali Gandaki views; continue ~25–35 min to Lo Manthang. Land and explore the walled city — Royal Palace area, gompas, medieval lanes, and sky-cave viewpoints. Overnight in Lo Manthang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Helicopter return to Kathmandu",
      maxAltitude: "1,350 m",
      meals: "Breakfast as arranged",
      accommodation: "Hotel in Kathmandu (or onward)",
      description:
        "Morning heli flight Lo Manthang–Jomsom–Kathmandu (routing may include Pokhara as required). Hotel transfer. End of the VIP Mustang helicopter tour — afternoon free for other activities or departure connections.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best in March–May and September–November for clear flying weather. Avoid monsoon (high cancellation) and deep winter winds when possible. Tiji Festival (usually May) is a special landing window — book early.",
  availabilityNotes: [
    "Private VIP charter for up to 5 passengers",
    "Shared seats sometimes available — ask when booking",
    "Minimum ~7 days for permit processing",
    "Full refund or free reschedule options if weather cancels (per operator policy)",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Extra Lo Manthang night",
      description: "Extend ground time for gompas, caves, or festival days.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Tiji Festival timing",
      description: "Align charter dates with May Tiji celebrations when possible.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Pokhara overnight extension",
      description: "Add lakeside nights before or after the heli sector.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport pickup and drop as listed",
    "Helicopter charter for up to 5 persons (KTM–Jomsom–Lo Manthang–KTM routing as listed)",
    "Upper Mustang Restricted Area Permit as listed",
    "Annapurna Conservation Area Permit (ACAP)",
    "All applicable government taxes and company service charge as listed",
    "Flight coordination and permit processing support",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Nepal entry visa fees",
    "Lunch and dinner in Kathmandu (unless arranged)",
    "Lo Manthang meals and hotel upgrades beyond package standard",
    "Tips, drinks, and personal expenses",
    "Travel insurance covering helicopter tours (strongly recommended)",
    "Costs from weather delays beyond operator reschedule policy",
    "Anything not listed under inclusions",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1493246507139-91e8fad9978e"),
      caption: "High desert ridges and Himalayan light",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Aerial mountain panoramas toward Annapurna country",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1483728642387-6c3bdd6c93e5"),
      caption: "Windswept plateaus of Upper Mustang",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1585409677983-0f6c41ca9c3b"),
      caption: "Remote Himalayan valleys from the air",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May and September–November offer the most reliable visibility. Morning flights succeed more often than afternoon sectors.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & difficulty",
      body: "Lo Manthang sits around 3,700–3,800 m. Graded Easy — short walks only. Helicopters carry supplemental oxygen; consult a doctor if you have cardiac/respiratory conditions.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Permits",
      body: "Upper Mustang RAP (about USD 500 pp for the standard window) plus ACAP. Summit Seek processes these with advance passport copies and photos.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Routes",
      body: "Kathmandu → (Pokhara as required) → Jomsom → Lo Manthang overnight → return by heli to Kathmandu. Exact legs depend on fuel, weather, and ATC.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "What to bring",
  equipmentIntro:
    "Travel extremely light. Soft daypack only — no large suitcases on the helicopter.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Windproof jacket and warm mid-layer",
        "Comfortable day clothes for Lo Manthang walks",
        "Gloves and warm hat for landing stops",
        "Modest clothing for monastery visits",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Sun & altitude",
      items: [
        "Glacier / UV sunglasses",
        "SPF 50+ sunscreen and lip balm",
        "Reusable water bottle",
        "Optional motion-sickness tablets",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Camera & bag",
      items: [
        "Camera with extra batteries (cold drains power)",
        "Small daypack only",
        "No drones (prohibited in Upper Mustang)",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies + passport photos for RAP",
        "Travel insurance certificate",
        "Summit Seek booking confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "RAP / ACAP processing and heli operator coordination",
    "Airport transfers as listed",
    "Weather updates and reschedule support",
    "Optional combine packages (e.g. Everest heli day) on request",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the VIP Mustang Helicopter Tour?",
      answer:
        "A 3-day package with Kathmandu arrival, helicopter charter to Lo Manthang (via Jomsom) with overnight in Upper Mustang, and heli return — including restricted-area permits as listed.",
      visible: true,
    },
    {
      id: "q2",
      question: "How much does it cost?",
      answer:
        "This VIP listing starts at US$3,890 for 2–3 pax (US$4,190 for 1; US$3,690 for 4; US$3,490 for 5). Market day-shared flights elsewhere can start near US$1,200–1,300 without the full 3-day VIP overnight package.",
      visible: true,
    },
    {
      id: "q3",
      question: "Is Upper Mustang permit included?",
      answer:
        "Yes — the Upper Mustang Restricted Area Permit (about USD 500 pp) and ACAP are included as listed.",
      visible: true,
    },
    {
      id: "q4",
      question: "What if weather cancels the flight?",
      answer:
        "Reputable operators typically offer full refund or free rescheduling within your Nepal stay. Keep buffer days and carry insurance covering heli tour disruptions.",
      visible: true,
    },
    {
      id: "q5",
      question: "Can children join?",
      answer:
        "Yes, with adult supervision. Infants under 2 often fly free on a lap (operator policy). Confirm weight and seating when booking.",
      visible: true,
    },
    {
      id: "q6",
      question: "Is altitude sickness a concern?",
      answer:
        "Brief exposure near 3,800 m rarely causes serious AMS. Helicopters carry oxygen. People with heart/lung conditions should get medical advice first.",
      visible: true,
    },
    {
      id: "q7",
      question: "Can we customize the itinerary?",
      answer:
        "Private VIP charters allow limited flexibility on timing and ground time. Special photography or research needs require advance planning.",
      visible: true,
    },
    {
      id: "q8",
      question: "How far ahead should I book?",
      answer:
        "At least 7 days for permits; 2–3 weeks in October–November peak season. Last-minute seats are rare.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for VIP Mustang by helicopter?",
  ctaBody: `Tell us your preferred dates and passenger count (1–5) — we will confirm charter availability, permits, and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "VIP Mustang Helicopter Tour 3 Days | Summit Seek",
  metaDescription:
    "Book 3-day VIP Upper Mustang helicopter tour — Lo Manthang landing, RAP & ACAP, charter for up to 5, Annapurna–Dhaulagiri views & rates from US$3,490.",
};
