import type { PermitsTimsContent } from "@/types/permits-tims-cms";
import { SITE } from "@/lib/constants";

export const DEFAULT_PERMITS_TIMS: PermitsTimsContent = {
  coverImageUrl:
    "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=2000&q=80",
  coverTitle: "Trekking Permits & Entry Fees",
  coverSubtitle:
    "TIMS updates, restricted-area permits, and national park entry fees — arranged clearly for Summit Seek guests.",
  introEyebrow: "Travel Info",
  introHeading: "Which permits do you need for Nepal treks?",
  introBody:
    "Most Himalayan routes require one or more official permits. Requirements depend on the region — conservation or national park entry for popular trails, plus special restricted-area permits for places like Upper Mustang or Manaslu. When you trek with Summit Seek, we arrange the right paperwork through registered channels so you can focus on the trail.\n\nPermits are non-transferable and non-refundable. Carry them (and your passport) at all times — checkpoints may ask to see them.",
  timsHeading: "TIMS card — what travelers should know",
  timsBody:
    "TIMS (Trekkers’ Information Management System) rules have changed for some regions and may continue to evolve. Certain popular areas no longer require a TIMS card the way they once did, while other destinations still need conservation / park permits or restricted-area permits.\n\nSummit Seek checks current requirements for your itinerary before departure and includes the correct permits in your trip plan. Always treat published fees as guidance — official rates can be updated by government offices.",
  restrictedHeading: "Restricted area trekking permits",
  restrictedIntro:
    "Restricted regions are issued through the Department of Immigration via a registered trekking agency. Many require a minimum of two trekkers. Fees below are commonly published rates (USD) — confirm before booking.",
  restrictedPermits: [
    {
      id: "rp1",
      region: "Upper Mustang (Lomanthang / Lo-Ghekar Damodarkunda / Baragung areas as gazetted)",
      fee: "USD 500 per person (first 10 days); USD 50 per person / day beyond 10 days",
      visible: true,
    },
    {
      id: "rp2",
      region: "Upper Dolpa (Dolpo Buddha / Shey Phoksundo / Charka Tangsong areas as gazetted)",
      fee: "USD 500 per person (first 10 days); USD 50 per person / day beyond 10 days",
      visible: true,
    },
    {
      id: "rp3",
      region: "Manaslu area — Gorkha (Chumnubri RM wards as gazetted)",
      fee: "Sep–Nov: USD 100 / person / week + USD 15 / day after; Dec–Aug: USD 75 / week + USD 10 / day after",
      visible: true,
    },
    {
      id: "rp4",
      region: "Tsum Valley — Gorkha (Chumnubri wards as gazetted)",
      fee: "Sep–Nov: USD 40 / person / week + USD 7 / day after; Dec–Aug: USD 30 / week + USD 7 / day after",
      visible: true,
    },
    {
      id: "rp5",
      region: "Humla (Simikot / Namkha / Changkheli areas as gazetted)",
      fee: "USD 50 per person / week; USD 10 per person / day beyond 1 week",
      visible: true,
    },
    {
      id: "rp6",
      region: "Lower Dolpa area (municipalities / RMs as gazetted)",
      fee: "USD 20 per person / week; USD 5 per person / day beyond 1 week",
      visible: true,
    },
    {
      id: "rp7",
      region: "Nar-Phu / Manang restricted wards (Narpa / Nasho as gazetted)",
      fee: "Sep–Nov: USD 100 / person / week + USD 15 / day after; Dec–Aug: USD 75 / week + USD 15 / day after",
      visible: true,
    },
    {
      id: "rp8",
      region: "Taplejung restricted wards (Phantanglung / Mikwakhola / Sirijunga as gazetted)",
      fee: "USD 20 / person / week (first 4 weeks); USD 25 / person / week beyond 4 weeks",
      visible: true,
    },
    {
      id: "rp9",
      region: "Sankhuwasabha (Bhotkhola / Makalu wards as gazetted)",
      fee: "USD 20 / person / week (first 4 weeks); USD 25 / person / week beyond 4 weeks",
      visible: true,
    },
    {
      id: "rp10",
      region: "Solukhumbu — Khumbu Pasang Lhamu RM (ward areas as gazetted)",
      fee: "USD 20 / person / week (first 4 weeks); USD 25 / person / week beyond 4 weeks",
      visible: true,
    },
    {
      id: "rp11",
      region: "Dolakha — Gaurishankar / Bigu wards as gazetted",
      fee: "USD 20 per person / week",
      visible: true,
    },
    {
      id: "rp12",
      region: "Rasuwa — Gosaikunda RM (wards as gazetted)",
      fee: "USD 20 per person / week",
      visible: true,
    },
    {
      id: "rp13",
      region: "Bajhang — Saipal RM",
      fee: "USD 90 per person / first week; USD 15 per person / day beyond 1 week",
      visible: true,
    },
    {
      id: "rp14",
      region: "Mugu — Mugumakarmarong RM",
      fee: "USD 100 per person / week; USD 15 per person / day beyond 1 week",
      visible: true,
    },
    {
      id: "rp15",
      region: "Darchula — Vyas RM",
      fee: "USD 90 per person / week; USD 15 per person / day beyond 1 week",
      visible: true,
    },
  ],
  parksHeading: "National park & conservation area entry fees",
  parksIntro:
    "Popular routes also need park or conservation entry permits. Amounts below are commonly published in Nepalese rupees (NRs) per person per entry. Children under 10 are often free — confirm at the counter.",
  parkEntries: [
    {
      id: "pk1",
      name: "Sagarmatha National Park (Everest)",
      nepali: "NRs 100",
      saarc: "NRs 1,500",
      foreigner: "NRs 3,000",
      childNote: "Below 10 yrs free",
      whereToPay: "Monjo entry / DNPWC Bhrikutimandap, Kathmandu",
      visible: true,
    },
    {
      id: "pk2",
      name: "Annapurna Conservation Area (ACAP)",
      nepali: "NRs 100",
      saarc: "NRs 1,000",
      foreigner: "NRs 3,000",
      childNote: "Below 10 yrs free",
      whereToPay: "ACAP Kathmandu / Pokhara counters",
      visible: true,
    },
    {
      id: "pk3",
      name: "Langtang National Park",
      nepali: "NRs 100",
      saarc: "NRs 1,500",
      foreigner: "NRs 3,000",
      childNote: "Below 10 yrs free",
      whereToPay: "Dhunche entry / DNPWC Bhrikutimandap",
      visible: true,
    },
    {
      id: "pk4",
      name: "Manaslu Conservation Area",
      nepali: "NRs 100",
      saarc: "NRs 1,000",
      foreigner: "NRs 3,000",
      childNote: "Below 10 yrs free",
      whereToPay: "ACAP Kathmandu / Pokhara counters",
      visible: true,
    },
    {
      id: "pk5",
      name: "Gaurishankar Conservation Area",
      nepali: "NRs 100",
      saarc: "NRs 1,000",
      foreigner: "NRs 3,000",
      childNote: "Below 10 yrs free",
      whereToPay: "ACAP Counter, Bhrikutimandap, Kathmandu",
      visible: true,
    },
    {
      id: "pk6",
      name: "Makalu-Barun National Park",
      nepali: "NRs 100",
      saarc: "NRs 1,500",
      foreigner: "NRs 3,000",
      childNote: "Below 10 yrs free",
      whereToPay: "Entry point / DNPWC Bhrikutimandap",
      visible: true,
    },
    {
      id: "pk7",
      name: "Kanchenjunga Conservation Area",
      nepali: "NRs 100",
      saarc: "NRs 500",
      foreigner: "NRs 2,000",
      childNote: "Below 10 yrs free",
      whereToPay: "Entry point / DNPWC Bhrikutimandap",
      visible: true,
    },
    {
      id: "pk8",
      name: "Chitwan National Park",
      nepali: "NRs 150",
      saarc: "NRs 1,000",
      foreigner: "NRs 2,000",
      childNote: "Below 10 yrs free",
      whereToPay: "At entry point",
      visible: true,
    },
    {
      id: "pk9",
      name: "Bardiya National Park",
      nepali: "NRs 100",
      saarc: "NRs 750",
      foreigner: "NRs 1,500",
      childNote: "Below 10 yrs free",
      whereToPay: "At entry point",
      visible: true,
    },
    {
      id: "pk10",
      name: "Rara National Park",
      nepali: "NRs 100",
      saarc: "NRs 1,500",
      foreigner: "NRs 3,000",
      childNote: "Below 10 yrs free",
      whereToPay: "Entry point / DNPWC Bhrikutimandap",
      visible: true,
    },
    {
      id: "pk11",
      name: "Shey-Phoksundo National Park",
      nepali: "NRs 100",
      saarc: "NRs 1,500",
      foreigner: "NRs 3,000",
      childNote: "Below 10 yrs free",
      whereToPay: "Entry point / DNPWC Bhrikutimandap",
      visible: true,
    },
    {
      id: "pk12",
      name: "Shivapuri-Nagarjun National Park",
      nepali: "NRs 100",
      saarc: "NRs 600",
      foreigner: "NRs 1,000",
      childNote: "Below 10 yrs free",
      whereToPay: "At entry point",
      visible: true,
    },
  ],
  notesHeading: "Practical permit notes",
  notes: [
    "Restricted permits must usually be arranged through a registered trekking agency — Summit Seek handles this for guests.",
    "For Upper Mustang / Upper Dolpa, if mountain expedition royalty paid is less than the trekking permit fee, the difference is typically due.",
    "Group restricted permits need an application and supporting documents via a registered agency.",
    "Confirm itinerary and dates before we issue permits — they are non-refundable and non-transferable.",
    "Fees and TIMS rules can change; your Summit Seek confirmation lists what is included for your trek.",
  ],
  ctaHeading: "Want us to arrange every permit?",
  ctaBody: `Share your trek name and dates. Summit Seek prepares park, conservation, and restricted permits with clear inclusions. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Contact Summit Seek",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Nepal visa guide",
  ctaSecondaryHref: "/travel-guide/nepal-visa",
  metaTitle: "Trekking Permits & Entry Fees | Summit Seek Travels & Tours",
  metaDescription:
    "Nepal trekking permits, TIMS guidance, restricted-area fees, and national park entry costs — clear Travel Info from Summit Seek Travels & Tours.",
};
