import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_PHOKSUNDO: TrekPageContent = {
  coverImageUrl: img("photo-1464822759023-fed622ff2c3b", 2000),
  coverTitle: "Phoksundo Lake Trek - 12 Days",
  coverSubtitle:
    "Turquoise Shey Phoksundo Lake in remote Dolpo — teahouse trails through Shey Phoksundo National Park, Ringmo culture, and Dhaulagiri–Kanjirowa views.",
  heroMainImageUrl: img("photo-1464822759023-fed622ff2c3b", 2000),
  heroSideImage1Url: img("photo-1506905925346-21bda4d32df4", 900),
  heroSideImage2Url: img("photo-1486870591958-9b9d0d1dda99", 900),
  breadcrumbLabel: "Dolpo Region · Phoksundo Lake",
  title: "Phoksundo Lake Trek - 12 Days",
  regionLabel: "Dolpo Region",
  rating: 5,
  reviewCount: 15,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 1475,
  compareAtPrice: 1690,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "13% OFF",
  shortTripBadge: "Restricted Area",
  durationLabel: "12 Days",
  difficultyLabel: "Moderate",
  groupSizeLabel: "2–10",
  bookingNote:
    "Private and small-group departures. Package includes Kathmandu hotels (BB as listed), Kathmandu–Nepalgunj–Juphal flights, licensed guide, porter (2:1), trek meals, teahouse lodging, Lower Dolpo / Phoksundo permits, and TIMS as required. Minimum typically 2 trekkers with a licensed guide.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "2 pax", price: 1575, visible: true },
    { id: "gd2", paxLabel: "3-4 pax", price: 1475, visible: true },
    { id: "gd3", paxLabel: "5-7 pax", price: 1390, visible: true },
    { id: "gd4", paxLabel: "8-10 pax", price: 1290, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "12 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Moderate", visible: true },
    { id: "f3", label: "Max Altitude", value: "3,610 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Lower Dolpo", visible: true },
    { id: "f6", label: "Group Size", value: "2–10", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Culture", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Aug–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The Phoksundo Lake Trek is a shorter gateway into remote Dolpo — Nepal’s deepest turquoise alpine lake at ~3,610 m, sacred to Tibetan Buddhists and Bon Po, set inside Shey Phoksundo National Park (the country’s largest).\n\nThis 12-day journey flies Kathmandu–Nepalgunj–Juphal, treks via Dunai and Chhapka to Jharana Hotel with early lake views, then reaches Phoksundo for a full exploration day (Ringmo, gompas, Bon sites). The return descends via Sangta to Juphal and flights back to Kathmandu.\n\nExpect pine, oak, and birch forests, deep gorges, waterfalls, Dhaulagiri and Kanjirowa views, and quieter trails than Everest or Annapurna classics. Opened to tourists around 1990, the route is now largely teahouse-based. Summit Seek includes flights as listed, permits, guide, porter, meals, and clear group pricing. Extend toward Shey Gompa on request.",
  overviewImageUrl: img("photo-1506905925346-21bda4d32df4"),
  highlightsHeading: "Highlights",
  highlights: [
    "Turquoise Phoksundo Lake (~3,610 m) — sacred Bon & Buddhist site",
    "Scenic flights Kathmandu–Nepalgunj–Juphal",
    "Shey Phoksundo National Park flora and fauna",
    "Views of Dhaulagiri and Kanjirowa ranges",
    "Ringmo village culture and ancient gompas",
    "Quieter off-the-beaten-path Dolpo trails",
    "Teahouse trekking with local hospitality",
    "Full exploration day at the lake",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport transfers and escort as listed",
    "Three nights Kathmandu hotel with breakfast as listed",
    "Kathmandu–Nepalgunj–Juphal flights and return as listed",
    "Teahouse lodging and trek meals (B-L-D on trail days)",
    "English-speaking licensed local guide",
    "Porter support (max ~20 kg; one between two persons)",
    "TIMS and Phoksundo / Lower Dolpo permits as required",
    "Sleeping bag / first-aid / oximeter support; staff insurance; farewell dinner; certificate",
  ],
  whyHeading: "Why choose Phoksundo Lake?",
  whyPoints: [
    "Shorter Dolpo experience without high 5,000 m passes",
    "One of Nepal’s most beautiful alpine lakes",
    "Moderate max altitude (~3,610 m) vs Upper Dolpo circuits",
    "Quiet restricted-area trails with strong culture",
    "Easy to extend toward Shey Gompa if you have more time",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "Graded moderate and suitable for fit beginners and seasoned trekkers. Days often run 5–7 hours with steep ups and downs on rocky trails, but the high point is only about 3,610 m.\n\nA licensed guide and typically a minimum of two trekkers are required in the restricted area. Travel insurance covering helicopter evacuation is required.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train 4–6 weeks with long walks, stairs, and light cardio",
    "Break in waterproof hiking boots",
    "Pack layers for cool nights near the lake",
    "Carry water purification and blister care",
    "Buy insurance covering remote trekking and evacuation",
    "Arrive Kathmandu a day early for briefing and permits",
  ],
  itineraryHeading: "12-day itinerary",
  itineraryIntro:
    "Flight and walking times are estimates and vary with weather — Juphal flights often delay. Lodge stops may change with availability. Your Summit Seek guide can adjust the plan for comfort and safety.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,400 m",
      meals: "—",
      accommodation: "Hotel in Kathmandu",
      description:
        "Airport meet-and-greet and hotel transfer. Trek briefing. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Kathmandu sightseeing & preparation",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "UNESCO heritage visits (Pashupatinath, Boudhanath, Swayambhunath, Patan) and gear/permit check with your guide. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Fly Kathmandu – Nepalgunj",
      maxAltitude: "150 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Hotel / Lodge in Nepalgunj",
      description:
        "Domestic flight to Nepalgunj in the western Terai. Overnight in Nepalgunj.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Fly Juphal – trek to Dunai",
      maxAltitude: "2,475 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Short flight to Juphal (~35 min), then trek via riverside villages to Dunai, Dolpa’s district headquarters. Overnight in Dunai.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Dunai – Chhapka",
      maxAltitude: "2,670 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Trek into the Phoksundo corridor toward Chhapka. Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Chhapka – Jharana Hotel",
      maxAltitude: "3,170 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Climb through cedar forest and open country with distant Phoksundo views to Jharana (waterfall) Hotel.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Jharana Hotel – Phoksundo Lake",
      maxAltitude: "3,610 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Descend through birch forest to the Phoksundo River, then reach the turquoise lake shore near the ranger station. Overnight by the lake.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Rest day at Phoksundo Lake",
      maxAltitude: "3,610 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Full exploration — lake viewpoints, Ringmo, and Bon / Buddhist gompas. Overnight at Phoksundo.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Phoksundo – Sangta",
      maxAltitude: "2,520 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Begin the return descent to Sangta (~4–5 hours). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Sangta – Juphal",
      maxAltitude: "2,475 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Final trek day back to Juphal airstrip village. Overnight in Juphal.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Fly Juphal – Nepalgunj – Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast, Dinner",
      accommodation: "Hotel in Kathmandu",
      description:
        "Fly to Nepalgunj and connect to Kathmandu (weather permitting). Farewell dinner. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Departure from Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "—",
      description:
        "Airport transfer for your international departure. End of the Phoksundo Lake journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best in March–May and August–November. Dolpo’s rain shadow also makes monsoon more feasible than many Nepal trails. Private groups of 2–10 are welcome. Build buffer days for Juphal flights.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Licensed guide and restricted-area permits mandatory",
    "Porter included typically 2 clients : 1 porter",
    "Juphal flights are weather-dependent — allow buffers",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Extra Kathmandu nights",
      description: "Buffer nights for flight delays or early arrivals.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Shey Gompa extension",
      description: "Add 2–3 days toward Shey Gompa for deeper cultural exploration.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Gear rental",
      description: "Sleeping bag, down jacket, and poles as needed.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport transfers and escort as listed",
    "Three nights’ accommodation in Kathmandu with breakfast as listed",
    "Food and local-lodge lodging during the trek as listed (~8 nights / 9 trek days)",
    "Kathmandu–Nepalgunj–Juphal flights and return as listed",
    "English-speaking licensed local guide",
    "Porters (max ~20 kg; typically one porter between two persons)",
    "TIMS and Phoksundo / Lower Dolpo special permits as required",
    "Equipment for staff; sleeping bag / first-aid / oximeter support as provided",
    "Insurance for staff and porters; farewell dinner; achievement certificate",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Nepal visa fees",
    "International flights",
    "Travel insurance (mandatory — helicopter evacuation)",
    "Lunch and dinner during Kathmandu hotel stays (except farewell dinner)",
    "Electronic charging fees and hot showers on trek",
    "Alcoholic drinks, candies, and personal snacks",
    "Extra accommodation and meals outside the itinerary",
    "Personal gear (available on hire) and tips",
    "Emergency evacuation / roadblock expenses beyond our control",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "High mountain light toward Dolpo country",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Alpine valley approaches near Phoksundo",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "Remote ridgelines in the rain shadow",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Wilderness trails toward Lower Dolpo",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May and August–November usually offer the best conditions. Monsoon is more feasible here than on many Nepal treks thanks to the rain shadow.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude",
      body: "Highest point is Phoksundo Lake at about 3,610 m. Use the rest day, drink water, and tell your guide early if you feel unwell.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Moderate. Rocky trails with steep sections and 5–7 hour days — doable for fit beginners with good preparation.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Culture & permits",
      body: "Bathing and fishing in Phoksundo Lake are prohibited (sacred Bon / Buddhist site). Lower Dolpo RAP and Shey Phoksundo NP permits are required; Summit Seek arranges these with your licensed guide.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack for cool lake nights and dusty trails. Porters carry main bags; keep water, layers, documents, and camera in a daypack.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece mid-layer",
        "Down / insulated jacket",
        "Waterproof shell",
        "Trekking pants",
        "Warm hat, sun hat, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Camp shoes",
        "Trekking poles (helpful on descents)",
        "25–35L daypack",
        "Sleeping bag (provided/rental as arranged)",
        "Headlamp + spare batteries",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "SPF sunscreen & lip balm",
        "UV sunglasses",
        "Personal medications & blister care",
        "Water bottle + purification",
        "Hand sanitizer & toilet paper",
        "Trail snacks",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance details",
        "Cash for personal trail extras",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Permit processing and licensed guiding team",
    "Sleeping bag / first-aid / oximeter support as arranged",
    "Farewell dinner and trek completion certificate",
    "Advice on Shey Gompa extensions and flight buffers",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Phoksundo Lake trek?",
      answer:
        "A 12-day teahouse trek into Lower Dolpo to sacred turquoise Phoksundo Lake (~3,610 m) inside Shey Phoksundo National Park.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Moderate. Expect 5–7 hour days with steep rocky sections, but no 5,000 m passes. Fit beginners can manage with preparation.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This Summit Seek listing starts at US$1,475 for 3–4 pax (US$1,575 for 2; US$1,390 for 5–7; US$1,290 for 8–10).",
      visible: true,
    },
    {
      id: "q4",
      question: "What is the maximum altitude?",
      answer:
        "About 3,610 m at Phoksundo Lake, with a full rest/exploration day.",
      visible: true,
    },
    {
      id: "q5",
      question: "Do I need special permits?",
      answer:
        "Yes. Lower Dolpo / Phoksundo restricted permits and Shey Phoksundo National Park entry (plus TIMS as applicable). Summit Seek arranges these with a licensed guide.",
      visible: true,
    },
    {
      id: "q6",
      question: "Can I swim in the lake?",
      answer:
        "No. Bathing and fishing are prohibited for cultural and spiritual reasons among Bon and Tibetan Buddhist communities.",
      visible: true,
    },
    {
      id: "q7",
      question: "Is travel insurance necessary?",
      answer:
        "Yes. Cover remote trekking and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q8",
      question: "When is the best time to go?",
      answer:
        "March–May and August–November usually offer the best weather; monsoon is more doable here than on many Nepal treks.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Phoksundo Lake?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Phoksundo Lake Trek 12 Days | Summit Seek",
  metaDescription:
    "Book the 12-day Phoksundo Lake trek with Summit Seek — turquoise Dolpo lake, permits, flights, guide, porter, meals & group discounts from US$1,290.",
};
