import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_POKALDE_PEAK: TrekPageContent = {
  coverImageUrl: img("photo-1519681393784-d120267933ba", 2000),
  coverTitle: "Pokalde Peak Climbing - 18 Days",
  coverSubtitle:
    "Easier Khumbu trekking peak (5,806 m) combined with Everest Base Camp and Kala Patthar — via Kongma La, Pokalde Base Camp, and High Camp, with Sherpa culture and Mahalangur panoramas.",
  heroMainImageUrl: img("photo-1519681393784-d120267933ba", 2000),
  heroSideImage1Url: img("photo-1464822759023-fed622ff2c3b", 900),
  heroSideImage2Url: img("photo-1486870591958-9b9d0d1dda99", 900),
  breadcrumbLabel: "Everest Region · Peak Climbing",
  title: "Pokalde Peak Climbing - 18 Days",
  regionLabel: "Everest Region",
  rating: 5,
  reviewCount: 6,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 2299,
  compareAtPrice: 2499,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "8% OFF",
  shortTripBadge: "Beginner Peak + EBC",
  durationLabel: "18 Days",
  difficultyLabel: "Strenuous",
  groupSizeLabel: "2+",
  bookingNote:
    "Private and small-group departures. Package includes Kathmandu hotels (BB as listed), Lukla flights, licensed trekking & climbing guide (Sherpa), porters, trek meals, teahouse lodging, basic camping on climb days, Pokalde climbing permit, and Sagarmatha National Park fees. One of the more accessible Khumbu peaks — ideal after solid trek fitness.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "2 pax", price: 2499, visible: true },
    { id: "gd2", paxLabel: "3-5 pax", price: 2299, visible: true },
    { id: "gd3", paxLabel: "6-10 pax", price: 2150, visible: true },
    { id: "gd4", paxLabel: "11-15 pax", price: 1990, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "18 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Strenuous", visible: true },
    { id: "f3", label: "Max Altitude", value: "5,806 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Khumbu / Everest", visible: true },
    { id: "f6", label: "Group Size", value: "2 onwards", visible: true },
    { id: "f7", label: "Activities", value: "Trek & Climbing", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "Pokalde Peak Climbing is designed for thrill-seekers who want a real Himalayan summit with less technical complexity than Island Peak or Lobuche. At 5,806 m, north of Kongma La and above the Khumbu Glacier opposite Lobuche, it is widely regarded as one of the easier climbs in the Khumbu — while still delivering big mountain views.\n\nThis 18-day package follows the classic Everest Base Camp route via Lukla, Phakding, Namche, Tengboche, Dingboche, and Lobuche, with visits to Everest Base Camp and Kala Patthar (5,550 m). From Lobuche you cross Kongma La (~5,535 m) to Pokalde Base Camp, move to High Camp (~5,000 m), summit Pokalde, then descend via Chhukung to Lukla.\n\nExpect Sherpa culture, Tengboche Monastery, and panoramas of Makalu, Pumori, Ama Dablam, Nuptse, and Lhotse. Summit Seek includes flights as listed, permits, climbing Sherpa guide, meals, lodging, and clear group pricing.",
  overviewImageUrl: img("photo-1464822759023-fed622ff2c3b"),
  highlightsHeading: "Highlights",
  highlights: [
    "Summit Pokalde Peak (5,806 m) — accessible Khumbu trekking peak",
    "Everest Base Camp and Kala Patthar viewpoints included",
    "Cross Kongma La Pass (~5,535 m) to Pokalde Base Camp",
    "Tengboche Monastery and Sherpa village culture",
    "Classic Khumbu trail: Namche, Dingboche, Lobuche, Chhukung",
    "Views of Makalu, Ama Dablam, Pumori, Nuptse & Lhotse",
    "Ideal first peak for climbers seeking less technical terrain",
    "Scenic Lukla flights bookending the journey",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport transfers as listed",
    "Kathmandu hotel nights with breakfast as listed",
    "Kathmandu–Lukla flights both ways (via Manthali if required by season)",
    "Teahouse lodging on trek; basic camping on climb days",
    "All meals during trek and camping as listed",
    "Licensed trekking guide and climbing Sherpa",
    "Pokalde climbing permit and Sagarmatha National Park fees",
    "Porters (15–18 kg pp); staff insurance; emergency heli coordination",
  ],
  whyHeading: "Why choose Pokalde Peak?",
  whyPoints: [
    "One of the easier Khumbu peaks — great first summit after EBC fitness",
    "Combines iconic EBC / Kala Patthar with a real peak climb",
    "Less technical than Island Peak for many climbers",
    "Kongma La approach with dramatic glacier and peak views",
    "Shorter summit day than Mera Peak’s 6,476 m objective",
  ],
  beginnersHeading: "Is this climb good for beginners?",
  beginnersBody:
    "Suitable for fit trekkers with prior multi-day Himalayan experience who want a first peak. The climb is less complex than many Khumbu peaks, but the overall trip is strenuous: EBC heights, Kongma La, and a long summit day (often 8–9 hours).\n\nA licensed climbing guide is required. Travel insurance covering high-altitude climbing and helicopter evacuation is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train 6+ weeks with long hikes, stairs, and cardio",
    "Prior trek experience (ideally above 4,000–5,000 m) recommended",
    "Break in boots; practice steep ups and downs",
    "Pack for cold nights at Lobuche, Gorak Shep, and high camp",
    "Buy insurance covering climbing to 6,000 m and heli evacuation",
    "Arrive Kathmandu for briefing, permits, and optional gear rental",
  ],
  itineraryHeading: "18-day itinerary",
  itineraryIntro:
    "Based on the classic EBC + Kongma La + Pokalde routing. Lukla flights may operate via Manthali in peak season. Summit day depends on weather and conditions — your climbing Sherpa may adjust.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,400 m",
      meals: "—",
      accommodation: "Hotel in Kathmandu",
      description:
        "Airport meet-and-greet and hotel transfer. Rest or light city stroll. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Kathmandu valley sightseeing & briefing",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "UNESCO heritage visits (Pashupatinath, Boudhanath, Swayambhunath, Durbar Squares) and climb briefing / gear check. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Fly Lukla – trek to Phakding",
      maxAltitude: "2,860 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Scenic flight to Lukla (~35–40 min), then trek along the Dudh Koshi to Phakding (~3 hours / ~9 km). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Trek Phakding – Namche Bazaar",
      maxAltitude: "3,440 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Via Monjo / Jorsale and the Hillary Bridge into Namche Bazaar (~6 hours / ~12 km). First Everest glimpses. Overnight in Namche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Acclimatization day at Namche Bazaar",
      maxAltitude: "3,440 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Rest day with optional hikes to Khunde, Khumjung, or Everest View Hotel. Overnight in Namche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Trek Namche – Tengboche",
      maxAltitude: "3,860 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Through Khumjung approaches and pine forest to Tengboche; visit Tengboche Monastery (~5 hours / ~10 km).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Trek Tengboche – Dingboche",
      maxAltitude: "4,360 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Via Pangboche and Orsho into alpine terrain to Dingboche (~5 hours / ~12 km). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Trek Dingboche – Lobuche",
      maxAltitude: "4,910 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Rocky glacier moraine trail past memorials to Lobuche (~6 hours / ~12 km). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Lobuche – Gorak Shep – Everest Base Camp",
      maxAltitude: "5,365 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Trek to Gorak Shep, then day hike to Everest Base Camp (~5,365 m) and return to Gorak Shep (~7–8 hours). Overnight at Gorak Shep.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Kala Patthar sunrise – trek to Lobuche",
      maxAltitude: "5,550 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Early hike to Kala Patthar (~5,550 m) for Everest panoramas, then descend to Lobuche (~6–7 hours). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Lobuche – Pokalde Base Camp via Kongma La",
      maxAltitude: "5,535 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping / Lodge",
      description:
        "Cross Kongma La (~5,535 m) to Pokalde Base Camp (~4,400 m) (~6–7 hours). Climbing tips and gear check. Overnight at base camp.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Pokalde Base Camp – High Camp",
      maxAltitude: "5,000 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Short but rocky ~600 m ascent to High Camp (~4–5 hours) with views of Nuptse, Lhotse, and Makalu. Overnight high camp.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Summit Pokalde Peak – descend to Chhukung",
      maxAltitude: "5,806 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Early summit push to Pokalde (5,806 m) (~4–5 hours up) with views of Makalu, Pumori, and Ama Dablam; descend via base camp to Chhukung (~8–9 hours total).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Trek Chhukung – Tengboche",
      maxAltitude: "3,860 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Descend via Pheriche / Pangboche approaches to Tengboche (~6–7 hours). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d15",
      dayLabel: "Day 15",
      title: "Trek Tengboche – Monjo",
      maxAltitude: "2,835 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Via Namche and Dudh Koshi crossings to Monjo (~6–7 hours). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d16",
      dayLabel: "Day 16",
      title: "Trek Monjo – Lukla",
      maxAltitude: "2,840 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Final trek day along the Dudh Koshi to Lukla (~5–6 hours). Overnight in Lukla.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d17",
      dayLabel: "Day 17",
      title: "Fly Lukla – Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Morning flight to Kathmandu (or Manthali + drive). Hotel transfer and rest. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d18",
      dayLabel: "Day 18",
      title: "Departure from Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "—",
      description:
        "Airport transfer for your international flight. End of the Pokalde Peak journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best in March–May and September–November for stable weather on Kongma La and the summit. Private groups welcome. Allow buffers for Lukla flights.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Licensed climbing Sherpa required for the peak permit",
    "EBC and Kala Patthar included before the climb",
    "Lukla flights are weather-dependent — allow buffers",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Extra Kathmandu nights",
      description: "Buffer nights for Lukla delays or early arrivals.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Personal climbing gear rental",
      description: "Boots, crampons, harness, ice axe, helmet in Kathmandu.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Extended Kathmandu sightseeing",
      description: "Additional heritage or cultural tours on request.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport transfers as listed",
    "Kathmandu hotel nights with breakfast as listed",
    "Kathmandu–Lukla–Kathmandu flights (via Manthali if season requires)",
    "Teahouse lodging on trek; basic camping on climb days",
    "All meals during the trek and camping as listed",
    "Licensed trekking guide and climbing Sherpa",
    "Pokalde peak climbing permit and Sagarmatha National Park entrance",
    "Porters (about 15–18 kg per person); staff accident insurance",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "International airfare",
    "Nepal entry visa fees",
    "Personal clothing and climbing equipment",
    "Personal accident insurance and emergency evacuation costs (mandatory cover)",
    "Alcoholic beverages, laundry, and tips",
    "Extra Kathmandu hotel nights and optional city tours beyond the itinerary",
    "Hot showers, Wi-Fi, and charging on trek",
    "Lunch and dinner in Kathmandu (except as listed)",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1519681393784-d120267933ba"),
      caption: "High Khumbu ridges toward Pokalde and Kongma La",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Alpine approaches on the Everest trail",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "Glacier light near Lobuche and the Khumbu",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Mountain panoramas above Namche and Tengboche",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May and September–November offer the most reliable windows for EBC heights, Kongma La, and the Pokalde summit.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & difficulty",
      body: "Highest point is Pokalde Peak at 5,806 m (Kala Patthar ~5,550 m; Kongma La ~5,535 m). Climb is relatively accessible; overall trip is strenuous due to length and altitude.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Permits",
      body: "Sagarmatha National Park entry, TIMS as applicable, and NMA Pokalde climbing permit. Summit Seek arranges these with your licensed climbing guide.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Routes",
      body: "Approaches via Bibre, Dughla, or Kongma La are used. This itinerary uses Lobuche → Kongma La → Pokalde Base Camp, then High Camp and summit, exiting via Chhukung.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Porters carry main bags; keep water, layers, documents, and camera in a daypack. Personal climbing gear can often be rented in Kathmandu.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece mid-layer",
        "Down jacket",
        "Waterproof shell jacket and pants",
        "Warm gloves, hat, buff",
        "Sun hat and glacier sunglasses",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & climbing",
      items: [
        "Sturdy waterproof boots suitable for light climbing",
        "Crampons (as advised by guide)",
        "Ice axe and harness if required for conditions",
        "Helmet",
        "Trekking poles",
        "Gaiters and camp shoes",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Camp & health",
      items: [
        "Sleeping bag rated for cold high camps",
        "Headlamp + spare batteries",
        "Water bottle + purification",
        "Personal first-aid & blister care",
        "SPF 50+ sunscreen and lip balm",
        "High-energy snacks",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies + passport photos",
        "Nepal visa as applicable",
        "Insurance covering climbing & heli evacuation",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Permit processing and licensed climbing Sherpa",
    "Porter logistics and staff insurance",
    "Basic camping arrangement on climb days",
    "Emergency helicopter coordination (insurance pays)",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is Pokalde Peak climbing?",
      answer:
        "An 18-day Khumbu trip combining the Everest Base Camp / Kala Patthar trail with a summit of Pokalde Peak (5,806 m) via Kongma La — one of the more accessible peaks in the region.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is Pokalde compared with Island Peak?",
      answer:
        "Pokalde is generally considered less technical and a good first Khumbu peak. Island Peak is typically more demanding on the final rock/ice section.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This listing starts at US$2,299 for 3–5 pax (US$2,499 for 2; US$2,150 for 6–10; US$1,990 for 11–15). Similar market packages often start around US$2,150.",
      visible: true,
    },
    {
      id: "q4",
      question: "What is the maximum altitude?",
      answer:
        "Pokalde Peak summit at 5,806 m. You also reach Kala Patthar (~5,550 m) and Kongma La (~5,535 m).",
      visible: true,
    },
    {
      id: "q5",
      question: "Do we visit Everest Base Camp?",
      answer:
        "Yes. This itinerary includes an afternoon visit to Everest Base Camp from Gorak Shep, plus a Kala Patthar sunrise hike.",
      visible: true,
    },
    {
      id: "q6",
      question: "What permits are required?",
      answer:
        "Sagarmatha National Park entry, TIMS as applicable, and an NMA Pokalde climbing permit with a licensed climbing guide. Summit Seek arranges these.",
      visible: true,
    },
    {
      id: "q7",
      question: "Is travel insurance necessary?",
      answer:
        "Yes — covering high-altitude climbing and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q8",
      question: "When is the best time to go?",
      answer:
        "March–May and September–November usually offer the best weather for the trail and summit.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Pokalde Peak?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Pokalde Peak Climbing 18 Days | Summit Seek",
  metaDescription:
    "Book 18-day Pokalde Peak climbing with Summit Seek — 5,806 m summit, EBC & Kala Patthar, Kongma La, permits, guide, Lukla flights & group discounts from US$1,990.",
};
