import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_POON_HILL: TrekPageContent = {
  coverImageUrl: img("photo-1483728642387-6c3bdd6c93e5", 2000),
  coverTitle: "Ghorepani Poonhill Trekking - 5 Days",
  coverSubtitle:
    "Sunrise above Annapurna & Dhaulagiri, Gurung–Magar villages, and rhododendron forests — a short classic for every fitness level.",
  heroMainImageUrl: img("photo-1483728642387-6c3bdd6c93e5", 2000),
  heroSideImage1Url: img("photo-1464822759023-fed622ff2c3b", 900),
  heroSideImage2Url: img("photo-1432405972618-c60b0225b8f9", 900),
  breadcrumbLabel: "Annapurna Region · Poon Hill",
  title: "Ghorepani Poonhill Trekking - 5 Days",
  regionLabel: "Annapurna Region",
  rating: 5,
  reviewCount: 1,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 399,
  compareAtPrice: 499,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "20% OFF",
  shortTripBadge: "Short Trip",
  durationLabel: "5 Days",
  difficultyLabel: "Easy",
  groupSizeLabel: "1+",
  bookingNote:
    "Private and small-group departures available year-round. Itinerary is customizable for families and first-time trekkers.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 499, visible: true },
    { id: "gd2", paxLabel: "2-10 pax", price: 399, visible: true },
    { id: "gd3", paxLabel: "11-20 pax", price: 370, visible: true },
    { id: "gd4", paxLabel: "21-30 pax", price: 350, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "5 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Easy", visible: true },
    { id: "f3", label: "Max Altitude", value: "3,210 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Pokhara", visible: true },
    { id: "f5", label: "Region", value: "Annapurna", visible: true },
    { id: "f6", label: "Group Size", value: "1+", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Culture", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "Ghorepani Poon Hill is one of Nepal’s most loved short treks — approachable for beginners, rewarding for photographers, and rich in Gurung and Magar culture. From Pokhara you travel into terraced hillsides, oak and rhododendron forests, and classic teahouse villages. The highlight is an early climb to Poon Hill (3,210 m) for sunrise across Annapurna South, Machhapuchhre (Fishtail), Dhaulagiri, Nilgiri, Hiunchuli, and more.\n\nSummit Seek keeps daily walking distances manageable, lodges carefully selected, and guides attentive — so you enjoy the views without rushing the experience.",
  overviewImageUrl: img("photo-1544735716-392fe2489ffa"),
  highlightsHeading: "Highlights",
  highlights: [
    "Golden sunrise from Poon Hill over Annapurna and Dhaulagiri",
    "Gurung & Magar village hospitality along the trail",
    "Spring rhododendron forests and autumn clear skies",
    "Short 5-day window — ideal if your Nepal trip is time-limited",
    "Teahouse lodging with warm meals after each trek day",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Licensed English-speaking guide with salary, food, lodging & insurance included",
    "Porter support (typically 2 guests : 1 porter) with fair pay and insurance",
    "Private transfer Pokhara ↔ trek start / end points",
    "TIMS & Annapurna Conservation Area permits arranged",
    "First-aid kit on trail; emergency evacuation coordination (via your insurance)",
    "Clear pre-trek briefing in Pokhara and daily evening plan with your guide",
  ],
  whyHeading: "Why choose Poon Hill?",
  whyPoints: [
    "Big Himalayan panoramas without a long high-altitude commitment",
    "Genuine cultural encounters in living mountain villages",
    "Comfortable teahouse network with reliable food and beds",
    "Suitable for most fitness levels — families and first-timers welcome",
    "Fits neatly into a one-week Pokhara / Annapurna side trip",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "Yes. Poon Hill is widely considered one of the best starter treks in the Annapurna region. Days involve several hours of walking with ups and downs, but the trails are well used and the altitude stays moderate compared with Everest or Manaslu.\n\nBuild a little cardio before you fly, stay hydrated, and tell your guide early if you feel unwell. If you have medical conditions, check with your doctor before booking.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Walk 30–45 minutes several times a week in the month before departure",
    "Break in waterproof hiking boots on practice walks",
    "Pack layers, rain shell, sun protection, and a small daypack",
    "Buy travel insurance covering trekking and helicopter evacuation",
    "Read our packing checklist and confirm any dietary needs with Summit Seek",
  ],
  itineraryHeading: "5-day itinerary",
  itineraryIntro:
    "Walking times are estimates and vary with pace and weather. Lodges may change with availability. Your guide can adjust the plan for safety or comfort.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Pokhara – Nayapul – Ulleri (drive)",
      maxAltitude: "≈ 2,050 m",
      meals: "Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Meet your guide and porter in Pokhara and drive toward the Annapurna foothills via Nayapul and Tikhedhunga. The road journey takes roughly 3–4 hours depending on conditions. Settle into Ulleri, enjoy mountain glimpses of Annapurna South and Hiunchuli, and receive your evening briefing for the trek days ahead.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Ulleri – Ghorepani",
      maxAltitude: "2,874 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Begin walking through forested trails and stone steps toward Ghorepani (about 4–5 hours). Spring brings rhododendron bloom; autumn brings crisp air. Pause for lunch in a trail village, then continue to Ghorepani for sunset views toward Annapurna and Dhaulagiri before dinner and rest.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Poon Hill sunrise – Tadapani",
      maxAltitude: "3,210 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Pre-dawn walk to Poon Hill for sunrise over a wide Himalayan arc — Annapurna I, Annapurna South, Machhapuchhre, Dhaulagiri, Nilgiri, and more. Return to Ghorepani for breakfast, then trek via Deurali toward Tadapani (about 6–7 hours total walking with breaks). Overnight in Tadapani.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Tadapani – Ghandruk – Landruk",
      maxAltitude: "≈ 1,990 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Descend through forest and waterfall country into Ghandruk, a celebrated Gurung village. Explore culture, views, and local lunch options, then continue across the Modi Khola toward Landruk. Celebrate your last full trek evening with your team.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Landruk – Kande – Pokhara",
      maxAltitude: "822 m (Pokhara)",
      meals: "Breakfast, Lunch",
      accommodation: "— (return to Pokhara)",
      description:
        "After breakfast with Fishtail and Annapurna views, walk toward Kande (about 4–5 hours), then drive by private vehicle back to Pokhara. Drop-off at your hotel. Farewell from your Summit Seek guide — until the next adventure.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Poon Hill departures run throughout the year on private and small-group bases. Spring and autumn are the clearest seasons; winter is quieter and colder; monsoon brings greener hills with more rain on lower trails.",
  availabilityNotes: [
    "Daily private departures with flexible start dates",
    "Small-group joining available with advance booking",
    "Fully customizable for families, solos, and larger groups",
    "Instant enquiry and confirmed booking after deposit",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Kathmandu ↔ Pokhara flight",
      description: "We can arrange domestic flights to connect your trek with Kathmandu.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Deluxe tourist bus",
      description: "Comfortable road transfer between Kathmandu and Pokhara.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Extra Pokhara hotel night",
      description: "Add rest days before or after the trek in lakeside Pokhara.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Annapurna Conservation Area permit & TIMS",
    "Licensed English-speaking guide (salary, food, lodging, insurance)",
    "Porter support (2:1 typical) with insurance and fair wages",
    "Teahouse / lodge accommodation during the trek",
    "Breakfast, lunch, dinner & tea/coffee on trek days as listed",
    "Private vehicle Pokhara ↔ trek start/end points",
    "First-aid kit carried by the guiding team",
    "Government taxes as per itinerary",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Nepal visa fees",
    "International flights",
    "Kathmandu / Pokhara hotel meals & city nights (unless added)",
    "Kathmandu ↔ Pokhara transport (available as add-on)",
    "Travel insurance (mandatory — must cover helicopter evacuation)",
    "Personal expenses (charging, hot showers, snacks, drinks, laundry)",
    "Tips for guide, porter, and driver",
    "Costs from delays beyond our control (weather, strikes, roadblocks)",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1483728642387-6c3bdd6c93e5"),
      caption: "Annapurna ridgelines at first light",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Stone trails through green hills",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "High Himalayan panorama",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Mountain morning atmosphere",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "September–November and March–May usually bring the clearest mountain views and the most comfortable daytime temperatures. Pack layers year-round — mornings at Ghorepani can be cold.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Climate on the trail",
      body: "Expect mild days and cool nights in peak seasons. Winter can bring frost and occasional snow near Ghorepani. Monsoon (Jun–Aug) is lush but wetter underfoot on lower paths.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Culture along the route",
      body: "Gurung and Magar communities welcome travelers through villages like Ghandruk and Ghorepani. Dress modestly in villages, ask before photographing people, and enjoy local dal bhat and hospitality.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Lodges & facilities",
      body: "Teahouses offer twin or shared rooms with blankets. Hot showers and device charging are often available for a small fee. Carry toilet paper, sanitizer, and a quick-dry towel.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack light and smart. Many bulky items can be rented in Kathmandu or Pokhara. Summit Seek can advise after you book.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece or mid-layer",
        "Down / insulated jacket",
        "Waterproof shell",
        "Trekking pants + evening pants",
        "Warm hat, sun hat, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in hiking boots",
        "Camp shoes / sandals",
        "3–4 pairs trekking socks",
        "30–35L daypack",
        "Duffel for porter (within weight limit)",
        "Trekking poles (optional but helpful)",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "Personal medications & blister care",
        "Sunscreen SPF 50+ & lip balm",
        "Sunglasses",
        "Water bottle / bladder + purification",
        "Hand sanitizer & wet wipes",
        "Headlamp + spare batteries",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance details",
        "Passport photos for permits",
        "Cash (NPR) for personal trail expenses",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Duffel bag for porter use on many packages (return after trek)",
    "Route briefing and maps guidance in Pokhara",
    "Sleeping bag / down jacket rental options on request",
    "Help arranging city hotels and Kathmandu–Pokhara links",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "How hard is the Poon Hill trek?",
      answer:
        "It is generally easy-to-moderate. Expect several hours of walking daily with stone steps and hills, but no extreme altitude like Everest Base Camp.",
      visible: true,
    },
    {
      id: "q2",
      question: "Can children join?",
      answer:
        "Yes, many families complete this trek. Pace is adjusted for younger walkers — tell us ages when you enquire so we can tailor the day plan.",
      visible: true,
    },
    {
      id: "q3",
      question: "How long is the walk to Poon Hill from Ghorepani?",
      answer:
        "Usually 45–60 minutes uphill before sunrise, depending on fitness and conditions.",
      visible: true,
    },
    {
      id: "q4",
      question: "When is the best time to go?",
      answer:
        "Spring (Mar–May) and autumn (Sep–Nov) offer the most reliable views. Winter is possible with warmer layers; monsoon is greener but wetter.",
      visible: true,
    },
    {
      id: "q5",
      question: "Do I need travel insurance?",
      answer:
        "Yes. Your policy should cover trekking and helicopter evacuation. Summit Seek does not sell insurance — we can help you confirm altitude limits.",
      visible: true,
    },
    {
      id: "q6",
      question: "Where does the trek start?",
      answer:
        "Your Summit Seek team meets you in Pokhara. Day 1 is typically a private drive toward Ulleri via Nayapul before overnight lodges and walking days begin.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Poon Hill sunrise?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Ghorepani Poonhill Trekking 5 Days | Summit Seek",
  metaDescription:
    "Book the 5-day Ghorepani Poon Hill trek with Summit Seek — sunrise views, Gurung villages, easy itinerary, permits, guide & porter from Pokhara.",
};
