import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_RUPINA_LA: TrekPageContent = {
  coverImageUrl: img("photo-1483728642387-6c3bdd6c93e5", 2000),
  coverTitle: "Rupina La Trek - 18 Days",
  coverSubtitle:
    "Remote Manaslu high pass at 4,720 m with Tsum Valley, Mu Gompa, and Ganesh Himal Base Camp — camping, teahouses, and Tibetan-Buddhist culture.",
  heroMainImageUrl: img("photo-1483728642387-6c3bdd6c93e5", 2000),
  heroSideImage1Url: img("photo-1464822759023-fed622ff2c3b", 900),
  heroSideImage2Url: img("photo-1506905925346-21bda4d32df4", 900),
  breadcrumbLabel: "Manaslu Region · Rupina La",
  title: "Rupina La Trek - 18 Days",
  regionLabel: "Manaslu Region",
  rating: 5,
  reviewCount: 12,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 1390,
  compareAtPrice: 1690,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "18% OFF",
  shortTripBadge: "Restricted Area",
  durationLabel: "18 Days",
  difficultyLabel: "Strenuous",
  groupSizeLabel: "1–10",
  bookingNote:
    "Private and small-group departures. Package includes Kathmandu hotel (BB as listed), licensed guide, porter (2:1), trek meals, tented camps on the high section, teahouses in Tsum, Manaslu/Tsum restricted permits (MRAP, TVRAP, MCAP), and private jeep transfers as listed. Licensed guide mandatory.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 1690, visible: true },
    { id: "gd2", paxLabel: "2-3 pax", price: 1390, visible: true },
    { id: "gd3", paxLabel: "4-6 pax", price: 1340, visible: true },
    { id: "gd4", paxLabel: "7-10 pax", price: 1290, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "18 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Strenuous", visible: true },
    { id: "f3", label: "Max Altitude", value: "4,720 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Manaslu / Tsum", visible: true },
    { id: "f6", label: "Group Size", value: "1–10", visible: true },
    { id: "f7", label: "Activities", value: "Pass & Camping", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The Rupina La Pass Trek is a remote, high-altitude adventure through the Manaslu region that culminates at Rupina La (4,720 m) with 360° views of Manaslu, Himalchuli, Boudha Himal, and Ganesh Himal. Trails stay largely untainted by mass tourism — Gurung villages like Barpak, alpine meadows, forests of rhododendron, pine, oak and birch, and genuine Tibetan-Buddhist culture in Tsum Valley.\n\nThis 18-day journey drives from Kathmandu to Bhaluwa, climbs via Barpak to Rupina La Base Camp, crosses the pass to Kharka and Buddha Himal Glacier Camp, then links into Tsum: Lokpa, Chumling, Chhokang Paro, Nile (via Milarepa’s cave), Mu Gompa, Gumba Lungdang, and a side trip to Ganesh Himal Base Camp (~4,600 m) before descending via Jagat and Machha Khola to Soti Khola and the jeep return to Kathmandu.\n\nExpect a mix of teahouses and fully supported tented camps on the high section. Summit Seek includes licensed guide, porter (2:1), restricted permits, trek meals, camping support where needed, and clear group pricing. Combine with Larkya La / Manaslu Circuit on request.",
  overviewImageUrl: img("photo-1464822759023-fed622ff2c3b"),
  highlightsHeading: "Highlights",
  highlights: [
    "Cross Rupina La Pass at 4,720 m with 360° Himalayan views",
    "Remote Manaslu trails via Barpak and Rupina La Base Camp",
    "Buddha Himal Glacier Camp and alpine meadows",
    "Sacred Tsum Valley — Chumling, Chhokang Paro, Nile & Mu Gompa",
    "Milarepa’s Cave (Piren Phu) and Gumba Lungdang nunnery",
    "Side trip to Ganesh Himal Base Camp (~4,600 m)",
    "Gurung & Tibetan-Buddhist cultural immersion",
    "Mix of tented camps and local teahouses",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport transfers and hotel pickup/drop for the trek",
    "Kathmandu hotel night with breakfast as listed",
    "Teahouse and tented-camp lodging with trek meals (B-L-D)",
    "English-speaking licensed mountain guide",
    "Porter (typically one between two; ~20–25 kg limit)",
    "Manaslu RAP, Tsum RAP, and MCAP permits as required",
    "Private jeep Kathmandu–Bhaluwa and Soti Khola–Kathmandu",
    "Sleeping bag / duffel / first-aid / oximeter support; farewell dinner; certificate",
  ],
  whyHeading: "Why choose Rupina La?",
  whyPoints: [
    "One of Nepal’s least-travelled high-pass routes in Manaslu",
    "Combines a serious 4,720 m pass with sacred Tsum Valley culture",
    "Optional Ganesh Himal Base Camp side trip",
    "Camping adventure plus authentic teahouse nights",
    "Can extend toward Larkya La / Manaslu Circuit",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "No — graded strenuous. You need solid fitness and ideally prior multi-day high-altitude hiking. Days run 5–8 hours with steep climbs, remote camping above ~4,000 m, and a high point of 4,720 m at Rupina La (plus ~4,600 m at Ganesh Himal Base Camp).\n\nA licensed guide is mandatory in the restricted area. Travel insurance covering helicopter evacuation to 5,000 m+ is required.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Build cardio 8–12 weeks out (running, stairs, hiking with a pack)",
    "Add leg and core strength; practice on steep terrain",
    "Break in waterproof boots; pack warm layers for -15 °C nights",
    "Carry headlamp, water purification, blister care, and personal meds",
    "Buy insurance covering high-altitude trekking and helicopter evacuation",
    "Arrive Kathmandu a day early for briefing and permit processing",
  ],
  itineraryHeading: "18-day itinerary",
  itineraryIntro:
    "Walking and drive times are estimates and vary with weather, snow on the pass, and road conditions. High camps may shift for safety. Your Summit Seek guide can adjust the plan for fitness and conditions.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Drive Kathmandu – Bhaluwa",
      maxAltitude: "1,200 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Lodge / Hotel",
      description:
        "Scenic drive (~7–9 hours) via Prithvi Highway and Gorkha toward Bhaluwa on the Daraudi River. Overnight in Bhaluwa.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Trek Bhaluwa – Barpak",
      maxAltitude: "1,900 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Tented camp / Lodge",
      description:
        "Climb beside the Daraudi through terraced fields to Barpak, a major Gurung village with stone-roofed houses. Overnight in Barpak (~6–7 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Trek Barpak – Rupina La Base Camp",
      maxAltitude: "3,976 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Tented camp",
      description:
        "Ascend through forest and alpine meadows via Sumrung Kharka toward Rupina La Base Camp. Overnight camp for acclimatization (~6–7 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Cross Rupina La Pass – Kharka",
      maxAltitude: "4,720 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Tented camp",
      description:
        "Hard climb over Rupina La (4,720 m) with views of Manaslu, Boudha Himal and surrounding peaks, then descend glacial terrain to Kharka. Overnight camp (~7–8 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Trek Kharka – Buddha Himal Glacier Camp",
      maxAltitude: "3,750 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Tented camp",
      description:
        "Descend through pastures and rocky ridges toward Buddha Himal Glacier Camp. Overnight under the stars (~5–6 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Trek Glacier Camp – Nyak",
      maxAltitude: "2,300 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Tented camp",
      description:
        "Descend via Gai Kharka through meadows and forest to Nyak with Himalchuli and Boudha Himal views. Overnight camp (~6–7 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Trek Nyak – Lokpa",
      maxAltitude: "2,240 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Continue via Philim and the Budhi Gandaki toward Lokpa, gateway to Tsum Valley. Overnight teahouse (~5–6 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Trek Lokpa – Chumling",
      maxAltitude: "2,386 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Enter lower Tsum through pine and rhododendron forest, crossing the Siar Khola to Chumling. Overnight teahouse (~5–6 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Trek Chumling – Chhokang Paro",
      maxAltitude: "3,031 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Climb via Domje into upper Tsum to Chhokang Paro with Ganesh Himal and Himalchuli views. Overnight teahouse (~6–7 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Trek to Nile via Milarepa Cave",
      maxAltitude: "3,347 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Walk toward Nile with a detour to Piren Phu (Milarepa’s cave). Overnight in Nile (~5–6 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Excursion Mu Gompa – return Chhokang Paro",
      maxAltitude: "3,700 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Day visit to Mu Gompa (~3,700 m), the largest monastery in Tsum, then return to Chhokang Paro. Overnight teahouse (~6–7 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Trek Chhokang Paro – Gumba Lungdang",
      maxAltitude: "3,200 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Monastery",
      description:
        "Descend to Domje then climb steeply to Gumba Lungdang nunnery with Ganesh Himal views. Overnight at the nunnery (~6–7 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Side trip Ganesh Himal Base Camp",
      maxAltitude: "4,600 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camp / Lodge",
      description:
        "Ascend through forest and yak pastures toward Ganesh Himal Base Camp (~4,600 m) beside Torogumba glacier views. Overnight at base camp (~7–8 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Trek Base Camp – Lokpa",
      maxAltitude: "2,240 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Descend via birch forest, Ripchet, and river trails back to Lokpa. Overnight teahouse (~6–7 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d15",
      dayLabel: "Day 15",
      title: "Trek Lokpa – Jagat",
      maxAltitude: "1,300 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Rejoin the Budhi Gandaki corridor via Philim toward Jagat. Overnight teahouse (~6–7 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d16",
      dayLabel: "Day 16",
      title: "Trek Jagat – Machha Khola",
      maxAltitude: "886 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Continue riverside trails and suspension bridges to Machha Khola. Overnight teahouse (~6–7 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d17",
      dayLabel: "Day 17",
      title: "Trek Machha Khola – Soti Khola",
      maxAltitude: "700 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Final trek day through Khorlabesi and Lapubesi to Soti Khola. Overnight teahouse (~5–6 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d18",
      dayLabel: "Day 18",
      title: "Drive Soti Khola – Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast, Lunch",
      accommodation: "Hotel in Kathmandu (as listed)",
      description:
        "Private jeep return to Kathmandu (~8–10 hours) via Dhading and the Trishuli corridor. Transfer to hotel or airport as arranged. End of the Rupina La journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best in March–May and September–November for clear skies and safer pass conditions. Private and joining groups of 1–10 are welcome. Winter snow can close the pass; monsoon brings landslides and leeches.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Licensed guide and restricted permits mandatory",
    "Porter included typically 2 clients : 1 porter",
    "Tented camps on the high Rupina La section; teahouses in Tsum",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Extra Kathmandu hotel nights",
      description: "Add buffer nights before Day 1 or after Day 18 for flights.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Kathmandu sightseeing day",
      description: "Guided heritage sites before or after the trek.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Manaslu Circuit / Larkya La extension",
      description: "Continue from Philim toward Samagaun and Larkya La.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport transfers and hotel pickup/drop for the trek",
    "Kathmandu twin-share hotel night with breakfast as listed",
    "Teahouse / tented-camp lodging during the trek as per itinerary",
    "Breakfast, lunch, and dinner on trek days (as listed)",
    "English-speaking licensed mountain guide (salary, food, insurance)",
    "Porter for two trekkers (~20–25 kg) with salary, food, and insurance",
    "Manaslu Restricted Area Permit, Tsum Valley RAP, and MCAP as required",
    "Private transport Kathmandu–Bhaluwa and Soti Khola–Kathmandu",
    "Sleeping bag / duffel / down jacket support (refundable as arranged)",
    "First-aid kit, oximeter checks, farewell dinner, achievement certificate",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "International airfare and Nepal visa fees",
    "Travel / medical insurance and emergency evacuation costs",
    "Extra Kathmandu nights outside the listed itinerary",
    "Lunch and dinner in Kathmandu (except farewell dinner)",
    "Personal expenses (SIM, Wi‑Fi, charging, hot showers, laundry, alcohol)",
    "Personal clothing, trekking gear, and medical kit",
    "Bottled / boiled drinking water beyond purification tablets provided",
    "Tips for guide and porter",
    "Costs from roadblocks, weather delays, or force majeure",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1483728642387-6c3bdd6c93e5"),
      caption: "High Himalayan ridges toward Manaslu country",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Alpine light near remote high passes",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Mountain meadows and glacial approaches",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Remote valley trails toward Tsum",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May and September–November usually offer the clearest views and the safest window for crossing Rupina La (4,720 m).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude",
      body: "Highest points: Rupina La 4,720 m and Ganesh Himal Base Camp ~4,600 m. Acclimatize carefully, drink water, and tell your guide early if you feel unwell.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Strenuous remote trek with long days, steep pass climbing, and camping above 4,000 m. Prior high-altitude experience strongly recommended.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Culture & permits",
      body: "Restricted Manaslu / Tsum area. Dress modestly at gompas. Summit Seek arranges MRAP, TVRAP, and MCAP with your licensed guide.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack for cold camping nights near the pass and warmer lower valleys. Porters carry main bags; keep water, layers, documents, and camera in a daypack.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece mid-layer",
        "Down / insulated jacket (to -15 °C)",
        "Waterproof shell jacket and pants",
        "Trekking pants and warm camp pants",
        "Warm hat, sun hat, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Camp shoes / sandals",
        "Trekking poles (strongly recommended)",
        "25–35L daypack",
        "Sleeping bag rated for cold nights (provided/rental as arranged)",
        "Headlamp + spare batteries",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "SPF sunscreen & lip balm",
        "UV sunglasses",
        "Personal medications & blister care",
        "Water bottle + purification",
        "Hand sanitizer & toilet paper",
        "High-energy trail snacks",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance details (helicopter cover)",
        "Cash for personal trail extras",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Permit processing and licensed guiding team",
    "Camping kit and sleeping support as arranged",
    "Farewell dinner and trek completion certificate",
    "Advice on Larkya La / Manaslu Circuit extensions",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Rupina La trek?",
      answer:
        "An 18-day remote Manaslu adventure crossing Rupina La (4,720 m), then exploring Tsum Valley monasteries and an optional Ganesh Himal Base Camp side trip.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Strenuous. Expect long days, steep pass climbing, camping above 4,000 m, and prior high-altitude trekking experience is strongly recommended.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This Summit Seek listing starts at US$1,390 for 2–3 pax (US$1,690 solo; US$1,340 for 4–6; US$1,290 for 7–10).",
      visible: true,
    },
    {
      id: "q4",
      question: "What is the maximum altitude?",
      answer:
        "Rupina La Pass at 4,720 m. Ganesh Himal Base Camp reaches about 4,600 m on Day 13.",
      visible: true,
    },
    {
      id: "q5",
      question: "Do I need special permits?",
      answer:
        "Yes. Manaslu Restricted Area Permit, Tsum Valley RAP, and MCAP are required. Summit Seek arranges these with a licensed guide.",
      visible: true,
    },
    {
      id: "q6",
      question: "Is travel insurance necessary?",
      answer:
        "Yes. Cover high-altitude trekking (to 5,000 m+) and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q7",
      question: "When is the best time to go?",
      answer:
        "March–May and September–November usually offer the best weather and clearest mountain views for the pass.",
      visible: true,
    },
    {
      id: "q8",
      question: "Teahouse or camping?",
      answer:
        "Both. High Rupina La section uses supported tented camps; Tsum Valley and lower valleys use local teahouses.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Rupina La?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Rupina La Trek 18 Days | Summit Seek",
  metaDescription:
    "Book the 18-day Rupina La Pass trek with Summit Seek — 4,720 m pass, Tsum Valley, Ganesh Himal Base Camp, permits, camping & group discounts from US$1,290.",
};
