import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_SHERPANI_COL: TrekPageContent = {
  coverImageUrl: img("photo-1486870591958-9b9d0d1dda99", 2000),
  coverTitle: "Sherpani Col Trek - 24 Days",
  coverSubtitle:
    "Technical Makalu–to–Everest high-col expedition — Sherpani Col (6,146 m), West Col, and Amphu Labtsa — via Makalu Base Camp into the Khumbu.",
  heroMainImageUrl: img("photo-1486870591958-9b9d0d1dda99", 2000),
  heroSideImage1Url: img("photo-1464822759023-fed622ff2c3b", 900),
  heroSideImage2Url: img("photo-1544735716-392fe2489ffa", 900),
  breadcrumbLabel: "Makalu Region · Sherpani Col",
  title: "Sherpani Col Trek - 24 Days",
  regionLabel: "Makalu Region",
  rating: 5,
  reviewCount: 5,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 2890,
  compareAtPrice: 3290,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "12% OFF",
  shortTripBadge: "Technical Expedition",
  durationLabel: "24 Days",
  difficultyLabel: "Technically Challenging",
  groupSizeLabel: "1–20",
  bookingNote:
    "Private expedition-style departures. Package includes Kathmandu hotels (BB as listed), Kathmandu–Tumlingtar and Lukla–Kathmandu flights, camping and teahouse lodging as listed, climbing Sherpa support for the cols, cook team meals on camping days, guide/porters, Makalu–Barun and Sagarmatha permits. For seasoned trekkers/climbers only — rope work and glacier travel required.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "2 pax", price: 3290, visible: true },
    { id: "gd2", paxLabel: "3-6 pax", price: 2890, visible: true },
    { id: "gd3", paxLabel: "7-10 pax", price: 2690, visible: true },
    { id: "gd4", paxLabel: "11-15 pax", price: 2490, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "24 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Technically Challenging", visible: true },
    { id: "f3", label: "Max Altitude", value: "6,146 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Makalu–Barun → Everest", visible: true },
    { id: "f6", label: "Group Size", value: "1–20", visible: true },
    { id: "f7", label: "Activities", value: "Trek / Climbing", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The Makalu Sherpani Col Trek is a 24-day technically challenging expedition linking Makalu–Barun with the Everest region across three high cols: Sherpani Col (~6,146 m), West Col (~6,143 m), and Amphu Labtsa (~5,845 m). It sits between serious trekking and peak climbing — for seasoned trekkers and climbers only.\n\nYou fly Kathmandu–Tumlingtar, trek via Num, Seduwa, Tashigaon, and Shipton La to Makalu Base Camp (4,870 m), then move onto glacier camps for the col crossings with climbing Sherpa support. After Amphu Labtsa you descend into Chhukung and walk out through Pangboche, Tengboche, Namche, and Lukla.\n\nExpect views of Everest, Lhotse, Nuptse, Makalu, Ama Dablam, and distant Kanchenjunga, plus Rai, Limbu, and Sherpa culture on the approach. Summit Seek includes camping equipment, cook meals on high camps, permits for Makalu–Barun and Sagarmatha, flights as listed, and clear group pricing. Market packages for this route often run higher depending on rope/climbing support level.",
  overviewImageUrl: img("photo-1464822759023-fed622ff2c3b"),
  highlightsHeading: "Highlights",
  highlights: [
    "Cross Sherpani Col (~6,146 m) and West Col (~6,143 m)",
    "Technical Amphu Labtsa (~5,845 m) into the Khumbu",
    "Visit Makalu Base Camp (4,870 m)",
    "Makalu–Barun Conservation Area wilderness",
    "Views of Everest, Lhotse, Makalu, Ama Dablam & more",
    "Rai, Limbu, and Sherpa cultural approaches",
    "Camping expedition with climbing Sherpa support",
    "Exit via Chhukung–Namche–Lukla classic Everest trail",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport transfers and Kathmandu hotel with breakfast as listed",
    "Kathmandu–Tumlingtar and Lukla–Kathmandu flights",
    "Organized camping with quality tents and kitchen/toilet tents",
    "Cook-prepared meals on camping days; teahouse meals as listed",
    "Licensed guide, porters, and high-altitude climbing Sherpa support",
    "Makalu–Barun and Sagarmatha National Park permits",
    "Portable altitude chamber (PAC) for emergency use as arranged",
    "Staff insurance, wages, farewell dinner, and completion certificate",
  ],
  whyHeading: "Why choose Sherpani Col?",
  whyPoints: [
    "True technical adventure — not a standard tea-house trek",
    "Links Makalu Base Camp to Everest region in one journey",
    "Three high cols above 5,800 m with glacier travel",
    "Fewer crowds than classic Everest Base Camp",
    "Ideal next step for climbers after tough Himalayan treks",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "No. This is a technically challenging expedition comparable to peak climbing. You need prior high-altitude trek experience, comfort with crampons/ice axe/rope, and strong fitness for camps above 5,500 m.\n\nTravel insurance covering technical mountaineering / glacier travel and helicopter evacuation above 6,000 m is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Prior 5,000 m+ Himalayan trek or climbing experience required",
    "Practice crampon, ice-axe, and fixed-rope skills before departure",
    "Train 8+ weeks: cardio, strength, and loaded hikes",
    "Pack expedition boots, harness, helmet, and cold-weather layers",
    "Buy insurance covering glacier/col crossings and heli evacuation",
    "Arrive Kathmandu with buffer days for gear checks and flights",
  ],
  itineraryHeading: "24-day itinerary",
  itineraryIntro:
    "Based on the classic Makalu Sherpani Col expedition routing. Col days depend heavily on weather and snow conditions — your climbing Sherpa team may adjust camps. Lukla and Tumlingtar flights often delay; Day 23 is a buffer.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,350 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Hotel in Kathmandu",
      description:
        "Airport transfer to hotel. Welcome briefing. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Preparation day in Kathmandu",
      maxAltitude: "1,350 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Hotel in Kathmandu",
      description:
        "Gear check, permit processing, and expedition briefing with guide and climbing team. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Fly Tumlingtar – drive to Num",
      maxAltitude: "1,560 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Flight to Tumlingtar, then jeep toward Num (~1,560 m). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Trek Num – Seduwa",
      maxAltitude: "1,500 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Descend to the Arun, cross, and climb to Seduwa / Sedua (~5–6 hours). Park entry as required. Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Trek Seduwa – Tashigaon",
      maxAltitude: "2,100 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Ascend through hillside villages to Tashigaon (~5 hours). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Trek Tashigaon – Kauma / Khongma",
      maxAltitude: "3,760 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Steep climb to Kauma / Khongma (~3,760 m) (~6 hours). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Acclimatization day at Kauma",
      maxAltitude: "3,760 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Rest and local acclimatization hike. Overnight at Kauma.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Trek Kauma – Dobate via Shipton La",
      maxAltitude: "4,170 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Cross Shipton La (~4,170 m) and descend to Dobate (~6–7 hours). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Trek Dobate – Yangle Kharka",
      maxAltitude: "3,520 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Descend into Barun Valley to Yangle Kharka (~6 hours). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Trek Yangle Kharka – Sherson",
      maxAltitude: "4,630 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Ascend the Barun corridor to Sherson (~4,630 m) (~6–7 hours). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Acclimatization day at Sherson",
      maxAltitude: "4,630 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Rest and local hike to prepare for Makalu Base Camp. Overnight at Sherson.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Trek Sherson – Makalu Base Camp",
      maxAltitude: "4,870 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Walk to Makalu Base Camp (4,870 m) (~4–5 hours). Begin camping phase. Overnight camp.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Acclimatization at Makalu Base Camp",
      maxAltitude: "4,870 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Rest, rope practice, and short acclimatization walks. Overnight camp at MBC.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Climb to Intermediate Camp",
      maxAltitude: "5,260 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Move up the glacier approach to Intermediate Camp (~5,260 m) (~4–5 hours). Overnight camp.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d15",
      dayLabel: "Day 15",
      title: "Climb to High Camp",
      maxAltitude: "5,650 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Ascend to High Camp (~5,650 m) (~4–5 hours) for the col crossing. Overnight camp.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d16",
      dayLabel: "Day 16",
      title: "Sherpani Col – West Col – Honku Glacier Camp",
      maxAltitude: "6,146 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Technical day: climb Sherpani Col (~6,146 m), cross Baruntse Glacier to West Col (~6,143 m), descend to Honku Glacier Camp (~5,500 m). Overnight camp.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d17",
      dayLabel: "Day 17",
      title: "Trek to Amphu Labtsa Base Camp",
      maxAltitude: "5,527 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Move toward Amphu Labtsa Base Camp (~5,527 m) (~3–4 hours). Overnight camp.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d18",
      dayLabel: "Day 18",
      title: "Cross Amphu Labtsa – descend to Chhukung",
      maxAltitude: "5,845 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Climb Amphu Labtsa (~5,845 m) and descend into the Imja Valley to Chhukung (~4,730 m). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d19",
      dayLabel: "Day 19",
      title: "Trek Chhukung – Pangboche",
      maxAltitude: "3,930 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Descend via Dingboche approaches to Pangboche (~6–7 hours). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d20",
      dayLabel: "Day 20",
      title: "Trek Pangboche – Monjo via Tengboche & Namche",
      maxAltitude: "3,440 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Classic Khumbu trail via Tengboche and Namche Bazaar to Monjo (~2,825 m) (~6–7 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d21",
      dayLabel: "Day 21",
      title: "Trek Monjo – Lukla",
      maxAltitude: "2,860 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Final trek day to Lukla (~4–5 hours). Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d22",
      dayLabel: "Day 22",
      title: "Fly Lukla – Kathmandu",
      maxAltitude: "1,350 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Morning flight to Kathmandu (~30 min). Hotel transfer. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d23",
      dayLabel: "Day 23",
      title: "Reserve / buffer day in Kathmandu",
      maxAltitude: "1,350 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Weather buffer for Lukla delays; free time or farewell dinner as listed. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d24",
      dayLabel: "Day 24",
      title: "Final departure",
      maxAltitude: "1,350 m",
      meals: "Breakfast",
      accommodation: "—",
      description:
        "Airport transfer for your international flight. End of the Sherpani Col expedition with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best in March–May and September–November when high cols are most feasible. Private groups of 1–20 are welcome. Build generous buffers for Tumlingtar/Lukla flights and weather on the cols.",
  availabilityNotes: [
    "Private expedition departures — dates on request",
    "Climbing Sherpa and rope support mandatory on col days",
    "Camping gear and cook team included as listed",
    "Col crossings are weather-critical — itinerary may shift",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Extra Kathmandu nights",
      description: "Buffer nights for flight delays or early arrivals.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Personal climbing gear rental",
      description: "Crampons, harness, ice axe, helmet as available.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Extra climbing Sherpa",
      description: "Higher client-to-Sherpa ratios for technical days.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "International and domestic airport transfers as listed",
    "Kathmandu hotel with complimentary breakfast as listed",
    "Kathmandu–Tumlingtar and Lukla–Kathmandu flights",
    "Camping equipment (tents, mattresses, kitchen/toilet tents) as listed",
    "Everyday meals on trek/camping days prepared by the cook team",
    "Teahouse lodging on approach and Khumbu exit days as listed",
    "Guide, porters, and high-altitude climbing Sherpa with wages and insurance",
    "Makalu–Barun and Sagarmatha permits; PAC as arranged; taxes; farewell dinner; certificate",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "International airfare",
    "Nepal entry visa fees",
    "Travel / mountaineering insurance (mandatory — heli evacuation above 6,000 m)",
    "Personal climbing gear (boots, harness, crampons, ice axe, helmet)",
    "Lunch and dinner in Kathmandu (except farewell dinner as listed)",
    "Personal expenses, bar bills, hot showers, charging, laundry",
    "Tips for guide, Sherpas, cook, and porters",
    "Emergency helicopter or unused buffer-day costs beyond our control",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "High alpine approaches toward the Makalu cols",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Glacier and ridgeline light in east Nepal",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Wilderness terrain linking Makalu and Khumbu",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Remote high camps before the col crossings",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May and September–November offer the most reliable windows for Sherpani Col, West Col, and Amphu Labtsa. Winter and monsoon are not suitable.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & technical grade",
      body: "Highest point is Sherpani Col (~6,146 m). Expect fixed ropes, glacier travel, and steep ice/snow. Comparable in demand to a short peak climb.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Permits",
      body: "Makalu–Barun Conservation Area and Sagarmatha National Park permits are required (plus TIMS as applicable). Summit Seek arranges these with your expedition team.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Camping & safety",
      body: "High sections are full camping with cook and climbing Sherpas. A portable altitude chamber (PAC) is carried as arranged. Follow guide decisions on weather delays.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Expedition packing list — bring technical climbing kit. Porters/high-altitude crew carry group loads; keep personal climbing gear accessible.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Expedition down jacket and pants",
        "Gore-Tex shell jacket and pants",
        "Thermal base layers (multiple)",
        "Fleece / softshell mid-layers",
        "Warm gloves, mitts, balaclava, buff",
        "Sun hat and glacier glasses (Cat 4)",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Technical & footwear",
      items: [
        "Double / expedition mountaineering boots",
        "Crampons compatible with boots",
        "Ice axe and climbing harness",
        "Helmet, carabiners, figure-8 / ATC",
        "Trekking poles",
        "Gaiters",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Camp & health",
      items: [
        "Warm sleeping bag (comfort −20°C or better)",
        "Headlamp + spare batteries",
        "Personal first-aid and blister care",
        "Water bottles + purification",
        "High-calorie snacks and electrolytes",
        "Sunscreen SPF 50+ and lip balm",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies + passport photos",
        "Nepal visa as applicable",
        "Insurance covering glacier / col crossings",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Permit processing and expedition logistics",
    "Camping tents, kitchen gear, and cook team",
    "Climbing Sherpa support on col days",
    "PAC and emergency coordination as arranged",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Sherpani Col trek?",
      answer:
        "A 24-day technical expedition from Makalu Base Camp across Sherpani Col, West Col, and Amphu Labtsa into the Everest / Khumbu region, exiting via Lukla.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Technically challenging — glacier travel, fixed ropes, and camps above 5,500 m. For experienced trekkers/climbers only, not beginners.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This listing starts at US$2,890 for 3–6 pax (US$3,290 for 2; US$2,690 for 7–10; US$2,490 for 11–15). Specialized market packages often range about US$3,500–4,500 depending on support level.",
      visible: true,
    },
    {
      id: "q4",
      question: "What is the maximum altitude?",
      answer:
        "About 6,146 m on Sherpani Col (West Col ~6,143 m; Amphu Labtsa ~5,845 m).",
      visible: true,
    },
    {
      id: "q5",
      question: "Do I need climbing experience?",
      answer:
        "Yes. Prior use of crampons, ice axe, and ropes at altitude is strongly recommended. Climbing Sherpas support the col days, but you must be competent and fit.",
      visible: true,
    },
    {
      id: "q6",
      question: "What permits are required?",
      answer:
        "Makalu–Barun Conservation Area and Sagarmatha National Park permits (plus TIMS as applicable). Summit Seek arranges these.",
      visible: true,
    },
    {
      id: "q7",
      question: "Is travel insurance necessary?",
      answer:
        "Yes — covering technical mountaineering/glacier travel and helicopter evacuation above 6,000 m. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q8",
      question: "When is the best time to go?",
      answer:
        "March–May and September–November are the primary seasons for feasible col conditions.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Sherpani Col?",
  ctaBody: `Tell us your experience level, preferred dates, and group size — we will confirm a clear expedition quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Sherpani Col Trek 24 Days | Summit Seek",
  metaDescription:
    "Book the 24-day Makalu Sherpani Col expedition with Summit Seek — 6,146 m cols, Makalu BC to Khumbu, camping, climbing Sherpa, permits & group rates from US$2,490.",
};
