import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_SHEY_GOMPA: TrekPageContent = {
  coverImageUrl: img("photo-1544735716-392fe2489ffa", 2000),
  coverTitle: "Shey Gompa Trek - 21 Days",
  coverSubtitle:
    "Sacred Upper Dolpo pilgrimage — turquoise Phoksundo Lake, Crystal Mountain approaches, and the 11th-century Shey Gompa monastery in restricted wilderness.",
  heroMainImageUrl: img("photo-1544735716-392fe2489ffa", 2000),
  heroSideImage1Url: img("photo-1506905925346-21bda4d32df4", 900),
  heroSideImage2Url: img("photo-1486870591958-9b9d0d1dda99", 900),
  breadcrumbLabel: "Dolpo Region · Shey Gompa",
  title: "Shey Gompa Trek - 21 Days",
  regionLabel: "Dolpo Region",
  rating: 5,
  reviewCount: 9,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 4800,
  compareAtPrice: 7000,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "31% OFF",
  shortTripBadge: "Restricted Area",
  durationLabel: "21 Days",
  difficultyLabel: "Strenuous",
  groupSizeLabel: "2–16",
  bookingNote:
    "Private and small-group camping expedition into Upper Dolpo. Package includes Kathmandu & Nepalgunj hotels as listed, Kathmandu–Nepalgunj–Juphal flights, licensed guide, porters (2:1), trek meals, camping/teahouse lodging, Upper Dolpo RAP, and Shey Phoksundo NP permit. Experienced high-altitude trekkers only.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 7000, visible: true },
    { id: "gd2", paxLabel: "2 pax", price: 5000, visible: true },
    { id: "gd3", paxLabel: "3-5 pax", price: 4800, visible: true },
    { id: "gd4", paxLabel: "6-10 pax", price: 4200, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "21 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Strenuous", visible: true },
    { id: "f3", label: "Max Altitude", value: "5,350 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Upper Dolpo", visible: true },
    { id: "f6", label: "Group Size", value: "2–16", visible: true },
    { id: "f7", label: "Activities", value: "Camping Trek", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Feb–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The Shey Gompa Trek is a focused Upper Dolpo pilgrimage into Nepal’s restricted western wilderness — rain-shadow deserts, turquoise Phoksundo Lake, and the iconic 11th-century Shey Gompa (Shey Monastery) beneath Crystal Mountain, famous for the rare Shey Mela festival held once every 12 years.\n\nThis 21-day Summit Seek package covers Kathmandu heritage sightseeing, flights via Nepalgunj to Juphal, the approach through Dunai and Chhepka to Phoksundo, the high crossing toward Shey via Salla Ghari and Lar Tsa (Sela La / Mendok Ding La ~5,160 m), exploration at Shey, then the cultural arc through Namgung, Saldang, Sibu, Jeng La country, Tokyu, and Dho Tarap before returning via Tarakot and Dunai.\n\nExpect strenuous high-altitude days, camping and teahouse nights, Bon and Tibetan-Buddhist culture, and genuine isolation away from busy classic trails. Includes RAP, park permits, flights as listed, guide, porters, meals, and clear group pricing.",
  overviewImageUrl: img("photo-1506905925346-21bda4d32df4"),
  highlightsHeading: "Highlights",
  highlights: [
    "11th-century Shey Gompa — spiritual heart of Upper Dolpo",
    "Turquoise Shey Phoksundo Lake with cliffs and waterfalls",
    "Crystal Mountain approaches and high pass panoramas",
    "Villages of Dunai, Saldang, and Dho Tarap — living Tibetan culture",
    "Rain-shadow wilderness away from crowded trek routes",
    "Kanjirowa and Dhaulagiri mountain views",
    "Restricted-area adventure with licensed camping support",
    "Optional timing interest for the rare Shey Mela festival",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport pick-up and hotel transfers as listed",
    "Kathmandu 3-star hotel nights with breakfast as listed",
    "Nepalgunj hotel night with meals as listed",
    "Kathmandu–Nepalgunj–Juphal flights and return as listed",
    "All trek meals (breakfast, lunch, dinner)",
    "Camping and teahouse lodging as per itinerary",
    "Licensed guide and porters (1 porter for 2 clients)",
    "Upper Dolpo special permits, park paperwork, first-aid kit, farewell dinner",
  ],
  whyHeading: "Why choose Shey Gompa?",
  whyPoints: [
    "Direct focus on Phoksundo Lake and sacred Shey Monastery",
    "Deep Tibetan-Buddhist and Bon cultural immersion",
    "True restricted Upper Dolpo wilderness",
    "Shorter than the full 24-day Upper Dolpo circuit, same spiritual core",
    "Rain-shadow scenery unique among Nepal treks",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "No — graded strenuous / difficult. You need strong fitness and prior high-altitude multi-day experience, preferably with camping. Days often run 5–8 hours with passes around 5,000–5,350 m.\n\nA licensed agency and guide are mandatory. Travel insurance covering helicopter evacuation to 6,000 m+ is required.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train 3+ months with long hikes, stairs, strength, and pack weight",
    "Prior high-altitude trek experience strongly recommended",
    "Pack expedition layers for freezing high camps",
    "Carry poles, microspikes, and a solid personal first-aid kit",
    "Buy insurance covering remote camping and heli evacuation",
    "Arrive Kathmandu early for briefing, sightseeing, and permits",
  ],
  itineraryHeading: "21-day itinerary",
  itineraryIntro:
    "Flight and walking times are estimates and vary with weather — Juphal flights often delay. Camps may shift for safety. Your Summit Seek guide adjusts the plan for conditions and acclimatization.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,400 m",
      meals: "—",
      accommodation: "Hotel in Kathmandu",
      description:
        "Airport meet-and-greet and hotel transfer. Rest and trek briefing. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Kathmandu sightseeing & preparation",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "UNESCO heritage tour (Swayambhunath, Pashupatinath, Boudhanath) and trek gear/permit preparation. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Fly Kathmandu – Nepalgunj",
      maxAltitude: "150 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Hotel in Nepalgunj",
      description:
        "Domestic flight to Nepalgunj. Overnight hotel with full-board as listed.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Fly Juphal – trek to Dunai",
      maxAltitude: "2,475 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Camp",
      description:
        "Scenic flight to Juphal, then trek toward Dunai, administrative center of Dolpo. Overnight in Dunai.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Dunai – Chhepka",
      maxAltitude: "2,838 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Camp",
      description:
        "Enter Shey Phoksundo National Park via Silughar checkpoint and continue to Chhepka.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Chhepka – Palam",
      maxAltitude: "3,820 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Camp",
      description:
        "Forest and riverside trails with ups and downs toward Palam (~3,820 m).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Palam – Phoksundo Lake",
      maxAltitude: "3,640 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping / Lodge",
      description:
        "Reach turquoise Phoksundo Lake — cliffs, peaks, and waterfalls. Overnight by the lake.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Explore Phoksundo Lake",
      maxAltitude: "3,722 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping / Lodge",
      description:
        "Full exploration and acclimatization day around Phoksundo and nearby viewpoints.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Phoksundo – Salla Ghari",
      maxAltitude: "3,640 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Enter the Upper Dolpo restricted corridor along traditional Tibet trade trails to Salla Ghari (~4–5 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Salla Ghari – Lar Tsa",
      maxAltitude: "4,120 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Continue to riverside Lar Tsa camp for acclimatization before the Shey approach.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Lar Tsa – Shey Gompa via Sela La",
      maxAltitude: "5,160 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Demanding ascent over Sela La / Mendok Ding La (~5,160 m) toward Crystal Mountain country, then down to camp below Shey Gompa (~7–8 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Explore Shey Gompa",
      maxAltitude: "4,570 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Acclimatization and monastery exploration — Shey Gompa (~800+ years) and optional Tsakang viewpoints.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Shey Gompa – Namgung",
      maxAltitude: "4,460 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Trek to Namgung Village with high desert landscapes. Overnight camp.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Namgung – Saldang",
      maxAltitude: "4,046 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Continue to Saldang, one of Upper Dolpo’s main settlements with ancient monasteries.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d15",
      dayLabel: "Day 15",
      title: "Saldang – Sibu",
      maxAltitude: "4,000 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Trek to Sibu Village across windswept high country.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d16",
      dayLabel: "Day 16",
      title: "Sibu – Tokyu via Jeng La",
      maxAltitude: "≈ 5,150 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Cross the Jeng La section toward Tokyu Gaon in the Tarap approaches. Overnight camp.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d17",
      dayLabel: "Day 17",
      title: "Tokyu Gaon – Dho Tarap",
      maxAltitude: "4,200 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping / Lodge",
      description:
        "Enter Dho Tarap valley — Bon and Buddhist culture in one of the world’s highest settlements.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d18",
      dayLabel: "Day 18",
      title: "Dho Tarap – Tarakot via Serkam",
      maxAltitude: "3,623 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Camp",
      description:
        "Long descent via Serkam toward historic Tarakot. Overnight in Tarakot.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d19",
      dayLabel: "Day 19",
      title: "Tarakot – Dunai",
      maxAltitude: "2,150 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Continue down-valley to Dunai. Teahouse overnight.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d20",
      dayLabel: "Day 20",
      title: "Dunai – Juphal",
      maxAltitude: "2,475 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Final trek day to Juphal. Celebration dinner with crew. Overnight in Juphal.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d21",
      dayLabel: "Day 21",
      title: "Fly Juphal – Kathmandu & departure",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "— (Kathmandu) / departure",
      description:
        "Fly Juphal–Nepalgunj–Kathmandu (weather permitting). Farewell dinner if overnight; otherwise airport transfer. End of the Shey Gompa journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best in February–May and September–November for clearer skies. Upper Dolpo’s rain shadow can allow summer travel, but spring and autumn are preferred. Private groups of 2–16 are welcome. Build buffer days for Juphal flights.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Licensed guide and Upper Dolpo RAP mandatory",
    "Porter included typically 2 clients : 1 porter",
    "Juphal flights are weather-dependent — allow buffers",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Extra Kathmandu nights",
      description: "Buffer nights for flight delays or early arrivals.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Extended Shey exploration",
      description: "Add a day for Crystal Mountain kora when conditions allow.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Gear rental",
      description: "Sleeping bag, down jacket, poles, microspikes as needed.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport pick-up and hotel transfers as listed",
    "Kathmandu 3-star hotel nights with breakfast as listed",
    "Nepalgunj hotel night with meals as listed",
    "Kathmandu sightseeing with private vehicle and city guide as listed",
    "Kathmandu–Nepalgunj–Juphal flights and return sectors as listed",
    "All meals during the trek (breakfast, lunch, dinner)",
    "Camping and teahouse accommodation as per itinerary",
    "Licensed guide and porters (1 porter for 2 clients)",
    "Upper Dolpo special permits, park paperwork, and TIMS as required",
    "First-aid kit, government taxes, and farewell dinner as arranged",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Nepal visa fees and international airfare",
    "Kathmandu heritage site entrance fees",
    "Extra Kathmandu nights due to early arrival, late departure, or weather",
    "Meals in Kathmandu (except breakfast / farewell as listed)",
    "Travel / rescue insurance (mandatory)",
    "Personal expenses (calls, laundry, bar bills, charging, hot showers, bottled water)",
    "Extra porters beyond the included ratio",
    "Tips for guide and porters",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Remote Himalayan approaches toward Dolpo",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "High alpine light in restricted wilderness",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "Wild ridgelines near Crystal Mountain country",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Open high-plateau atmosphere",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "February–May and September–November usually offer the most stable weather and clearest mountain views for Shey Gompa and Phoksundo.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude",
      body: "High points include Sela La / Mendok Ding La around 5,160 m and overall max about 5,350 m. Use Phoksundo and Shey rest days — report symptoms early.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Strenuous remote camping trek with long days, high passes, and isolation. Experienced trekkers only.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Permits",
      body: "Upper Dolpo Restricted Area Permit plus Shey Phoksundo National Park permit (and TIMS as applicable). Summit Seek arranges paperwork with your licensed team.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack for a full high-altitude camping expedition. Porters carry main loads; keep water, layers, documents, and camera in a daypack.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Expedition base layers",
        "Thick fleece mid-layers",
        "Down jacket for deep cold",
        "Hard shell jacket and pants",
        "Insulated camp pants",
        "Warm hat, sun hat, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in stiff hiking boots",
        "Camp shoes",
        "Trekking poles",
        "Microspikes for icy passes",
        "25–35L daypack",
        "Cold-rated sleeping bag",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "High-SPF sunscreen & lip balm",
        "UV sunglasses (spare helpful)",
        "Personal medications & blister care",
        "Water bottles + purification",
        "Headlamp + spare batteries",
        "High-calorie trail snacks",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance with heli cover to 6,000 m+",
        "Cash for personal extras",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "RAP / park permit processing and full guiding team",
    "Domestic flight booking assistance",
    "Camping logistics and first-aid support",
    "Buffer-day planning around Juphal weather",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Shey Gompa trek?",
      answer:
        "A 21-day Upper Dolpo expedition focused on Phoksundo Lake and the sacred 11th-century Shey Gompa monastery beneath Crystal Mountain.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Strenuous. Long high-altitude days, camping, and passes around 5,000–5,350 m. Experienced trekkers only.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This Summit Seek listing starts at US$4,800 for 3–5 pax (US$7,000 solo; US$5,000 for 2; US$4,200 for 6–10).",
      visible: true,
    },
    {
      id: "q4",
      question: "What is the maximum altitude?",
      answer:
        "Around 5,350 m overall, with Sela La / Mendok Ding La near 5,160 m on the Shey approach.",
      visible: true,
    },
    {
      id: "q5",
      question: "What permits do I need?",
      answer:
        "Upper Dolpo Restricted Area Permit and Shey Phoksundo National Park permit. Summit Seek arranges these with a licensed guide.",
      visible: true,
    },
    {
      id: "q6",
      question: "How is this different from Upper Dolpo 24 days?",
      answer:
        "This 21-day package keeps the Shey Gompa and Phoksundo core with a tighter return via Saldang and Dho Tarap.",
      visible: true,
    },
    {
      id: "q7",
      question: "Is travel insurance necessary?",
      answer:
        "Yes — mandatory. Cover remote high-altitude camping and helicopter evacuation to 6,000 m+. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q8",
      question: "Are Juphal flights reliable?",
      answer:
        "They frequently delay or cancel for weather. Always build buffer days in Kathmandu / Nepalgunj.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Shey Gompa?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear expedition quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Shey Gompa Trek 21 Days | Summit Seek",
  metaDescription:
    "Book the 21-day Shey Gompa trek with Summit Seek — Phoksundo Lake, Crystal Mountain, Upper Dolpo RAP, camping team & group discounts from US$4,200.",
};
