import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_SHIVAPURI_YOGA_HIKE: TrekPageContent = {
  coverImageUrl: img("photo-1548013146-72479768bada", 2000),
  coverTitle: "Shivapuri Hill Yoga Hike - 1 Day",
  coverSubtitle:
    "One-day forest hike north of Kathmandu — Budhanilkantha, Nagi Gompa, Shivapuri Nagarjun National Park, guided yoga & meditation, and Himalayan valley views.",
  heroMainImageUrl: img("photo-1548013146-72479768bada", 2000),
  heroSideImage1Url: img("photo-1506905925346-21bda4d32df4", 900),
  heroSideImage2Url: img("photo-1464822759023-fed622ff2c3b", 900),
  breadcrumbLabel: "Nepal Tours · Day Hike",
  title: "Shivapuri Hill Yoga Hike - 1 Day",
  regionLabel: "Kathmandu Valley",
  rating: 5,
  reviewCount: 12,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 60,
  compareAtPrice: 70,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "14% OFF",
  shortTripBadge: "Yoga + Day Hike",
  durationLabel: "1 Day",
  difficultyLabel: "Easy",
  groupSizeLabel: "2+",
  bookingNote:
    "Private and small-group day departures from Kathmandu. Package includes hotel pickup/drop, English-speaking guide and yoga instructor, Shivapuri Nagarjun National Park entrance, yoga mat, and packed lunch as listed. Ideal soft adventure if you have only one free day in the valley.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 70, visible: true },
    { id: "gd2", paxLabel: "2-3 pax", price: 60, visible: true },
    { id: "gd3", paxLabel: "4-6 pax", price: 55, visible: true },
    { id: "gd4", paxLabel: "7+ pax", price: 50, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "1 Day", visible: true },
    { id: "f2", label: "Difficulty", value: "Easy", visible: true },
    { id: "f3", label: "Max Altitude", value: "2,732 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Shivapuri / Kathmandu", visible: true },
    { id: "f6", label: "Group Size", value: "2 onwards", visible: true },
    {
      id: "f7",
      label: "Activities",
      value: "Yoga, Meditation & Hiking",
      visible: true,
    },
    {
      id: "f8",
      label: "Best Season",
      value: "Sep–Jun (best Mar–May & Sep–Nov)",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "Shivapuri Hill Yoga Hike is a one-day escape that blends Kathmandu Valley nature with guided yoga and meditation. Shivapuri rises about 14 km north of the city inside Shivapuri Nagarjun National Park — the second-highest hill station around the valley — with views toward Langtang, Manaslu, Ganesh Himal, and Gaurishankar on clear days.\n\nYou start with a short drive to Budhanilkantha (Narayanthan) and the reclining Vishnu temple, enter the park, and hike through rhododendron, pine, fir, magnolia, and oak forest via Nagi Gompa (a Buddhist nunnery). Continue under cool forest shade to Shivapuri Hill (~2,540–2,732 m), where your yoga instructor leads practice against a Himalayan and valley backdrop, then descend and drive back to Kathmandu.\n\nThe park hosts rich birdlife (177+ species), butterflies, and wildlife including deer and rhesus monkeys. Summit Seek includes private transport, guide/yoga teacher, park fees, yoga mats, and clear group pricing — perfect if you want Nepal’s outdoors and mindfulness in a single day.",
  overviewImageUrl: img("photo-1506905925346-21bda4d32df4"),
  highlightsHeading: "Highlights",
  highlights: [
    "One-day yoga hike just north of Kathmandu",
    "Visit Budhanilkantha — sacred reclining Vishnu temple",
    "Forest trail through Shivapuri Nagarjun National Park",
    "Stop at Nagi Gompa Buddhist nunnery",
    "Guided yoga and meditation with valley & Himalaya views",
    "Panoramas toward Langtang, Ganesh Himal, Manaslu & Gaurishankar",
    "Birdlife, butterflies, and serene least-crowded trails",
    "Hotel pickup and drop included",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Private vehicle pickup and drop in Kathmandu",
    "English-speaking guide and professional yoga teacher",
    "Shivapuri Nagarjun National Park entrance fees",
    "Yoga mat for each participant",
    "Packed lunch as listed / on request",
    "First-aid kit carried by the guide",
    "All applicable government and local taxes as listed",
    "Emergency evacuation coordination (insurance pays)",
  ],
  whyHeading: "Why choose Shivapuri for yoga hiking?",
  whyPoints: [
    "Quick escape from Kathmandu noise into protected forest",
    "Combines physical hiking with yoga and mindfulness",
    "Accessible difficulty for most fitness levels",
    "Sacred stop at Budhanilkantha plus Nagi Gompa culture",
    "Ideal when you only have one free day in Nepal",
  ],
  beginnersHeading: "Is this hike good for beginners?",
  beginnersBody:
    "Yes — graded Easy and suitable for travelers with moderate fitness. Expect several hours of uphill walking (typically 5–7 hours round trip depending on pace), with rest stops for yoga and views.\n\nNo advanced yoga experience is required; sessions are guided for mixed levels. Wear sturdy shoes with grip and bring layers for cooler hilltop breezes.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Wear broken-in hiking shoes or trail runners with good grip",
    "Pack light daypack (about 5–8 kg max) with water and snacks",
    "Bring sun protection, light rain shell, and a warm layer",
    "Wear comfortable yoga-friendly clothing you can hike in",
    "Eat a light breakfast before the morning pickup",
    "Check the weather — monsoon trails can be slippery",
  ],
  itineraryHeading: "1-day itinerary",
  itineraryIntro:
    "Typical timing from Kathmandu hotels. Exact pickup (often around 8:30–9:00 a.m.) is confirmed when you book. Pace and yoga stops flex with your group and weather.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Budhanilkantha – Shivapuri yoga hike – return Kathmandu",
      maxAltitude: "2,732 m",
      meals: "Packed lunch as listed",
      accommodation: "—",
      description:
        "Morning hotel pickup and ~30-minute drive north to Budhanilkantha (Narayanthan). Visit the reclining Vishnu temple, then continue to the Shivapuri Nagarjun National Park gate. Hike through rhododendron and oak forest via Nagi Gompa to Shivapuri Hill (~2,540–2,732 m) with views of Ganesh–Langtang–Jugal ranges and the Kathmandu Valley. Guided yoga and meditation at a scenic clearing or hilltop; packed lunch; descend to the road head and drive back to Kathmandu (typically mid/late afternoon).",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Operated most days year-round on private request. Spring (Mar–May) and autumn (Sep–Nov) offer the clearest mountain views; winter mornings can be chilly; monsoon brings lush forests but slippery trails.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Ideal add-on before or after longer treks",
    "Minimum group size 2 recommended; solo on request",
    "Park entry ticket required — included in the package",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Private photographer",
      description: "Capture yoga and summit moments on request.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Extended Kathmandu city tour",
      description: "Combine with heritage sites the same evening or next day.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Private yoga teacher upgrade",
      description: "Dedicated instructor for your party only.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Private vehicle for pickup and drop in Kathmandu",
    "Professional yoga teacher / English-speaking guide with wages",
    "Shivapuri Nagarjun National Park entrance fees",
    "Packed lunch as listed or on request",
    "Yoga mat for each member",
    "Company T-shirt / cap / city map if arranged",
    "Applicable government and local taxes as listed",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Meals other than those listed (extra lunch/snacks as preferred)",
    "Personal travel and health insurance",
    "Tips for guide, yoga teacher, and driver",
    "Personal expenses and souvenirs",
    "Anything not listed under inclusions",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1548013146-72479768bada"),
      caption: "Kathmandu Valley hills and temple atmospheres",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Forest ridges and mountain light near Shivapuri",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Alpine forest trails for mindful hiking",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "Open sky practice spaces above the valley",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "September–June works for most travelers; March–May and September–November usually give the best views and walking weather. Monsoon trails can be muddy.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & difficulty",
      body: "Shivapuri summit is about 2,732 m (park board). The hike is Easy–moderate: uphill forest walking for several hours, suitable for beginners with basic fitness.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Permits",
      body: "Shivapuri Nagarjun National Park entry ticket is required (included). Carry passport/ID for the checkpoint as requested.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Routes",
      body: "Classic routing: Kathmandu → Budhanilkantha → park gate → Nagi Gompa → Shivapuri Hill → descend to road head → Kathmandu.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Travel light. Summit Seek can provide a yoga mat; rent or buy any missing items in Thamel if needed.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking t-shirt or yoga top",
        "Light fleece or mid-layer",
        "Packable rain shell",
        "Comfortable yoga pants or trekking pants",
        "Extra socks",
        "Light scarf or buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & daypack",
      items: [
        "Sturdy hiking shoes or trail runners",
        "Comfortable daypack (5–8 kg)",
        "Reusable water bottle",
        "Optional yoga sandals for the session",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Sun & personal",
      items: [
        "Hat / cap and UV sunglasses",
        "SPF 50+ sunscreen and lip balm",
        "Energy snacks",
        "Personal medications and blister care",
        "Hand sanitizer and tissues",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport or ID",
        "Summit Seek booking confirmation",
        "Small cash in NPR for extras",
        "Phone + power bank",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Park entry processing and local logistics",
    "Yoga mats and guided sessions",
    "Private vehicle and licensed guide",
    "First-aid kit on the trail",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What happens on the Shivapuri Hill yoga hike?",
      answer:
        "Your guide picks you up in Kathmandu, you visit Budhanilkantha, hike through Shivapuri Nagarjun National Park (often via Nagi Gompa), practice guided yoga/meditation at scenic stops or the hilltop, then descend and return to the city.",
      visible: true,
    },
    {
      id: "q2",
      question: "What is the altitude of Shivapuri?",
      answer:
        "According to the Shivapuri Nagarjun National Park information board, the summit is about 2,732 m / 8,963 ft.",
      visible: true,
    },
    {
      id: "q3",
      question: "How long does the hike take?",
      answer:
        "Typically about 5–7 hours of walking/time on trail depending on pace, yoga stops, and weather, plus short drives to and from Kathmandu.",
      visible: true,
    },
    {
      id: "q4",
      question: "How much does it cost?",
      answer:
        "This listing starts at US$60 for 2–3 pax (US$70 for 1; US$55 for 4–6; US$50 for 7+). Market day packages often list around US$60–70.",
      visible: true,
    },
    {
      id: "q5",
      question: "Is yoga experience required?",
      answer:
        "No. Sessions are guided for mixed levels — breathing, stretching, and simple postures in nature.",
      visible: true,
    },
    {
      id: "q6",
      question: "What is included for park entry?",
      answer:
        "Shivapuri Nagarjun National Park entrance fees are included. Carry ID/passport for the checkpoint as required.",
      visible: true,
    },
    {
      id: "q7",
      question: "When is the best time to go?",
      answer:
        "Spring (Mar–May) and autumn (Sep–Nov) usually offer the clearest views. The hike is possible most of the year; monsoon trails can be slippery.",
      visible: true,
    },
    {
      id: "q8",
      question: "Is the hike safe?",
      answer:
        "It is one of the safer, well-managed day hikes near Kathmandu when done with a guide on established trails. Stay with the group and follow local park rules.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Shivapuri yoga hike?",
  ctaBody: `Tell us your preferred date and group size — we will confirm pickup and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Shivapuri Hill Yoga Hike 1 Day | Summit Seek",
  metaDescription:
    "Book 1-day Shivapuri Hill yoga hike from Kathmandu — Budhanilkantha, Nagi Gompa, national park, guided yoga, lunch & group rates from US$50.",
};
