import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_TAMANG_HERITAGE: TrekPageContent = {
  coverImageUrl: img("photo-1544735716-392fe2489ffa", 2000),
  coverTitle: "Tamang Heritage Trail Trek - 11 Days",
  coverSubtitle:
    "A community homestay trek near Kathmandu — Gatlang, Tatopani hot springs, Nagthali views, and authentic Tamang culture beneath Langtang and Ganesh Himal.",
  heroMainImageUrl: img("photo-1544735716-392fe2489ffa", 2000),
  heroSideImage1Url: img("photo-1464822759023-fed622ff2c3b", 900),
  heroSideImage2Url: img("photo-1506905925346-21bda4d32df4", 900),
  breadcrumbLabel: "Langtang Region · Tamang Heritage",
  title: "Tamang Heritage Trail Trek - 11 Days",
  regionLabel: "Langtang Region",
  rating: 5,
  reviewCount: 24,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 600,
  compareAtPrice: 700,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "14% OFF",
  shortTripBadge: "Homestay Trek",
  durationLabel: "11 Days",
  difficultyLabel: "Moderate",
  groupSizeLabel: "1–12",
  bookingNote:
    "Private and small-group departures available. Package includes Kathmandu hotels (BB), sightseeing day, permits, licensed guide, trek meals, and local-bus transfers. Homestay/teahouse lodging on the trail. Porter and private jeep available as add-ons.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 800, visible: true },
    { id: "gd2", paxLabel: "2-5 pax", price: 700, visible: true },
    { id: "gd3", paxLabel: "6-8 pax", price: 600, visible: true },
    { id: "gd4", paxLabel: "9-12 pax", price: 550, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "11 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Moderate", visible: true },
    { id: "f3", label: "Max Altitude", value: "3,165 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Langtang / Rasuwa", visible: true },
    { id: "f6", label: "Group Size", value: "1–12", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Homestay", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The Tamang Heritage Trail is a community-based trek between the Langtang and Ganesh Himal ranges — almost at Kathmandu’s doorstep. Opened in 2004 with local development support, it blends rhododendron forests, gentle trails, and authentic homestays in traditional Tamang villages such as Gatlang, Thuman, and Briddim.\n\nWhat sets this route apart is cultural immersion: stay with local families, share homemade meals, and learn Tamang crafts, festivals, and Buddhist traditions. Highlights include Tatopani natural hot springs, Nagthali viewpoint (~3,165 m), the old salt-trade post at Timure, and Rasuwagadhi fort near the Tibetan border.\n\nWith about 61 km of walking over six trek days, it is family-friendly and less crowded than classic Langtang Valley. Summit Seek includes Kathmandu hotels, a heritage sightseeing day, permits, a licensed guide, trek meals, and clear group pricing. Extend to Langtang Valley or Gosainkunda on request.",
  overviewImageUrl: img("photo-1483728642387-6c3bdd6c93e5"),
  highlightsHeading: "Highlights",
  highlights: [
    "Authentic Tamang community homestays supporting local livelihoods",
    "Views of Langtang Lirung, Ganesh Himal, Langtang Ri & Shishapangma",
    "Villages of Gatlang, Briddim, Thuman & Timure",
    "Natural hot springs at Tatopani",
    "Nagthali hilltop for meditation and mountain panoramas",
    "Ancient stupas, monasteries, and Rasuwagadhi fort history",
    "Rhododendron forests and waterfalls in Langtang National Park",
    "Family-friendly moderate trails close to Kathmandu",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport transfers on arrival and departure",
    "Three nights Kathmandu hotel (BB, twin sharing, 2–3 star)",
    "Guided Kathmandu sightseeing day as per itinerary",
    "Three meals a day on trek days as listed",
    "National park entry permit and TIMS",
    "Local-bus ground transport Kathmandu ↔ Syabrubesi",
    "Guest house / teahouse / homestay lodging on trek (twin sharing)",
    "Licensed local guide with salary, food, lodging, transport & insurance",
  ],
  whyHeading: "Why choose Tamang Heritage?",
  whyPoints: [
    "Culture-first Himalayan trek with real community exchange",
    "Quieter alternative to busy Langtang Valley corridors",
    "Hot springs, viewpoints, and border-history sites in one short circuit",
    "Moderate distances (~7–16 km/day) suited to families and first-timers",
    "Easy to extend toward Langtang Valley or Gosainkunda",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "Yes. Graded moderate with well-maintained trails and about 5–6 hours of walking on trek days. Prior hiking helps but is not required. Max altitude is Nagthali at ~3,165 m — lower than Everest or Gosainkunda pass days.\n\nChildren and older travelers often join successfully at a steady pace. Travel insurance covering helicopter evacuation is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Walk 30–60 minutes several times a week before departure",
    "Break in comfortable waterproof hiking boots",
    "Pack layers for cool evenings in mountain villages",
    "Bring a sleeping bag if you prefer extra warmth in homestays",
    "Buy travel insurance covering high-altitude trekking and evacuation",
    "Consider private jeep if you prefer a smoother road to Syabrubesi",
  ],
  itineraryHeading: "11-day itinerary",
  itineraryIntro:
    "Walking and drive times are estimates and vary with road conditions, weather, and pace. Homestay stops may change with availability. Your Summit Seek guide can adjust the plan for comfort and safety.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,345 m",
      meals: "—",
      accommodation: "Hotel in Kathmandu",
      description:
        "Airport meet-and-greet and private transfer to your hotel. Welcome briefing; free evening in Thamel. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Kathmandu sightseeing & trek briefing",
      maxAltitude: "1,345 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Guided tour of Kathmandu Durbar Square, Pashupatinath, Boudhanath, and Swayambhunath (~6–7 hours). Afternoon trek briefing and gear check with your guide. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Drive Kathmandu – Syabrubesi",
      maxAltitude: "1,500 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Scenic local-bus drive (~117 km / 6–7 hours) past terraces and hills toward Syabrubesi, with first views of Langtang and Ganesh Himal. Overnight in Syabrubesi.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Syabrubesi – Gatlang",
      maxAltitude: "2,240 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house / Homestay",
      description:
        "Begin trekking through forests and hills (~16 km / 5–6 hours) to traditional Gatlang village. Overnight in Gatlang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Gatlang – Tatopani",
      maxAltitude: "2,600 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house / Homestay",
      description:
        "Walk via Chilime, mani walls, chortens, and a suspension bridge toward Gonggang, then to Tatopani (~12 km / 5–6 hours). Soak in natural hot springs. Overnight in Tatopani.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Tatopani – Nagthali – Thuman",
      maxAltitude: "3,165 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house / Homestay",
      description:
        "Climb to Nagthali viewpoint (~3,165 m) for Ganesh Himal panoramas, then steep descent to Thuman village (~9 km / 5–6 hours). Overnight in Thuman.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Thuman – Timure",
      maxAltitude: "1,760 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house / Homestay",
      description:
        "Riverside trail along the Bhote Koshi to Timure (~8 km / 4–5 hours), an old salt-trade post near the Tibetan border. Afternoon visit to Rasuwagadhi fort (1855). Overnight in Timure.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Timure – Briddim",
      maxAltitude: "2,230 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house / Homestay",
      description:
        "Walk via Lingling then climb to Briddim (~8 km / 5–6 hours) — classic Tamang village with warm homestays. Overnight in Briddim.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Briddim – Syabrubesi",
      maxAltitude: "1,700 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guest house",
      description:
        "Final trek day through rhododendron forest back to Syabrubesi (~7 km / 4–5 hours) with farewell views of Ganesh Himal and Langtang Lirung. Overnight in Syabrubesi.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Drive Syabrubesi – Kathmandu",
      maxAltitude: "1,345 m",
      meals: "Breakfast, Lunch",
      accommodation: "Hotel in Kathmandu",
      description:
        "Local-bus return to Kathmandu (~6–7 hours). Free afternoon for shopping or rest. Farewell dinner. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Final departure",
      maxAltitude: "1,345 m",
      meals: "Breakfast",
      accommodation: "— (departure day)",
      description:
        "Private airport transfer for your departure flight. End of the Tamang Heritage Trail journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Tamang Heritage departures run on private and joining bases. Spring and autumn usually bring the clearest Langtang and Ganesh views. Winter is quieter and colder; monsoon means greener hills with more rain.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Groups of 13+ — inquire for special pricing",
    "Private jeep upgrade available (~US$175 each way, up to 6 pax)",
    "Easy to extend toward Langtang Valley or Gosainkunda",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Trekking porter",
      description:
        "Shared porter (typically 2:1, ~20–22 kg) so you hike with a light daypack.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Private jeep Kathmandu ↔ Syabrubesi",
      description: "Upgrade local bus to private jeep (about US$175 one way, up to 6 people).",
      priceLabel: "From US$175",
      visible: true,
    },
    {
      id: "a3",
      title: "Single room / private homestay",
      description: "Private rooms where available in hotels and villages.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport transfers on arrival and departure",
    "Three nights’ accommodation in Kathmandu with breakfast (twin sharing)",
    "Sightseeing tour in Kathmandu as per itinerary",
    "Three meals a day (breakfast, lunch, dinner) as per the trek itinerary",
    "National park entry permits and TIMS",
    "Ground transportation by local bus Kathmandu ↔ Syabrubesi",
    "Guest house / teahouse / homestay accommodation on trek (twin sharing)",
    "Experienced local trekking guide (salary, food, lodging, transport, insurance)",
    "Sleeping bag and down jacket if necessary (returned after the trek)",
    "Trekking map, first-aid kit with oximeter, farewell dinner, taxes as applicable",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Nepal entry visa fee and international flights",
    "Trekking porter (available as add-on)",
    "Travel insurance (mandatory — high-altitude evacuation)",
    "Kathmandu monument entrance fees (approx. NPR 2,600 per person)",
    "Lunch and dinner in Kathmandu (except farewell dinner)",
    "Personal expenses, shopping, and drinks",
    "Hot shower, internet, telephone, and laundry",
    "Tips for guide and staff",
    "Anything not mentioned in the includes section",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Village approaches in the Langtang foothills",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Mountain light toward Ganesh and Langtang",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Alpine ridges near Nagthali",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1483728642387-6c3bdd6c93e5"),
      caption: "Forest trail atmosphere on the heritage route",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "Autumn (September–November) and spring (March–May) usually offer the clearest mountain views and most comfortable temperatures for homestay trekking.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude",
      body: "Highest point is Nagthali at about 3,165 m. Ascend steadily, drink water, and tell your guide early if you feel unwell.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Moderate. About 4–6 hours of walking on most trek days across ~61 km total. Suitable for families and fit beginners with basic hiking experience.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Homestays & meals",
      body: "Expect twin-share rooms in family homes and teahouses. Meals feature dal bhat, noodles, momos, and local dishes — a core part of the cultural experience.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack light for village trails and cool evenings. If you hire a porter, keep water, layers, documents, and camera in a daypack.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece mid-layer",
        "Down / insulated jacket",
        "Waterproof shell",
        "Trekking pants",
        "Warm hat, sun hat, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Camp shoes",
        "Trekking poles (optional)",
        "25–35L daypack",
        "Sleeping bag (optional extra warmth)",
        "2–3 pairs trekking socks",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "SPF sunscreen & lip balm",
        "UV sunglasses",
        "Personal medications & blister care",
        "Water bottle + purification",
        "Headlamp + spare batteries",
        "Trail snacks",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance details",
        "Cash for personal trail expenses & monument fees",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Sleeping bag / down jacket if needed (return after trek)",
    "Trekking map, T-shirt souvenir where available, and farewell dinner",
    "First-aid support with oximeter checks",
    "Advice on Langtang Valley or Gosainkunda extensions",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Tamang Heritage Trail?",
      answer:
        "An 11-day community homestay trek in the Langtang/Rasuwa area near Kathmandu, visiting Gatlang, Tatopani, Thuman, Timure, and Briddim with cultural immersion and moderate walking.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Moderate. Expect 4–6 hour days on well-maintained trails. Max altitude is about 3,165 m at Nagthali — suitable for fit beginners and many families.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This Summit Seek listing starts at US$600 for 6–8 pax (US$800 solo; US$700 for 2–5; US$550 for 9–12). Larger groups — inquire for rates.",
      visible: true,
    },
    {
      id: "q4",
      question: "Are homestays included?",
      answer:
        "Yes. On trail nights you stay in guest houses / teahouses / community homestays on a twin-sharing basis, sharing meals and culture with local families.",
      visible: true,
    },
    {
      id: "q5",
      question: "Is there a hot spring on the trek?",
      answer:
        "Yes. Day 5 reaches Tatopani, known for natural hot springs — a highlight after the forest walk from Gatlang.",
      visible: true,
    },
    {
      id: "q6",
      question: "Is travel insurance necessary?",
      answer:
        "Yes. Cover high-altitude trekking and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q7",
      question: "Can I upgrade the bus to a private jeep?",
      answer:
        "Yes. Private jeep transfers Kathmandu ↔ Syabrubesi are available at about US$175 one way (up to 6 passengers).",
      visible: true,
    },
    {
      id: "q8",
      question: "Can I combine this with Langtang Valley?",
      answer:
        "Yes. Extending to Langtang Valley or Gosainkunda is popular — ask us to customize your itinerary.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Tamang Heritage?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Tamang Heritage Trail Trek 11 Days | Summit Seek",
  metaDescription:
    "Book the 11-day Tamang Heritage Trail with Summit Seek — community homestays, Tatopani hot springs, Nagthali views, permits, guide & group discounts from US$550.",
};
