import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_THREE_PASSES: TrekPageContent = {
  coverImageUrl: img("photo-1486870591958-9b9d0d1dda99", 2000),
  coverTitle: "Everest Three Passes Trek - 18 Days",
  coverSubtitle:
    "Kongma La, Cho La, and Renjo La — plus Everest Base Camp, Kala Patthar, Gokyo Lakes, and Gokyo Ri across the full Khumbu high country.",
  heroMainImageUrl: img("photo-1486870591958-9b9d0d1dda99", 2000),
  heroSideImage1Url: img("photo-1544735716-392fe2489ffa", 900),
  heroSideImage2Url: img("photo-1464822759023-fed622ff2c3b", 900),
  breadcrumbLabel: "Everest Region · Three Passes",
  title: "Everest Three Passes Trek - 18 Days",
  regionLabel: "Everest Region",
  rating: 5,
  reviewCount: 86,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 1255,
  compareAtPrice: 1499,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "16% OFF",
  shortTripBadge: "Challenging Trek",
  durationLabel: "18 Days",
  difficultyLabel: "Strenuous",
  groupSizeLabel: "1+",
  bookingNote:
    "Private and joining departures available. Package includes Kathmandu–Lukla flights (Manthali routing in peak season), permits, guide, teahouse meals, and acclimatization days. Arrive 1–2 days early for flight buffer.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 1399, visible: true },
    { id: "gd2", paxLabel: "2-6 pax", price: 1255, visible: true },
    { id: "gd3", paxLabel: "7-12 pax", price: 1199, visible: true },
    { id: "gd4", paxLabel: "13-20 pax", price: 1150, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "18 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Moderate–Strenuous", visible: true },
    { id: "f3", label: "Max Altitude", value: "5,545 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Everest / Khumbu", visible: true },
    { id: "f6", label: "Group Size", value: "1+", visible: true },
    {
      id: "f7",
      label: "High Passes",
      value: "Kongma La · Cho La · Renjo La",
      visible: true,
    },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "The Everest Three Passes trek is the ultimate Khumbu circuit for trekkers who want more than classic Base Camp — Kongma La (~5,535–5,540 m), Cho La (~5,420 m), and Renjo La (~5,345–5,400 m), plus Everest Base Camp, Kala Patthar (5,545 m), Gokyo Lakes, and Gokyo Ri.\n\nYou fly into Lukla, acclimatize in Namche, follow the classic trail via Tengboche and Dingboche, then divert to Chhukung before crossing Kongma La to Lobuche. After EBC and Kala Patthar you continue via Dzongla over Cho La into the Gokyo valley, then finish with Renjo La and the descent through Thame back to Namche and Lukla.\n\nSummit Seek leads with licensed guides, clear pricing that includes Lukla flights and permits, built-in acclimatization, and flexible private departures. Clockwise or anti-clockwise routing can be discussed when you book.",
  overviewImageUrl: img("photo-1506905925346-21bda4d32df4"),
  highlightsHeading: "Highlights",
  highlights: [
    "Cross Kongma La, Cho La, and Renjo La — the three great Everest high passes",
    "Thrilling Lukla flight and iconic Hillary suspension bridges",
    "Sagarmatha National Park — UNESCO World Heritage Site",
    "Namche Bazaar, Hotel Everest View, and Khumjung culture",
    "Tengboche Monastery beneath Ama Dablam",
    "Everest Base Camp, Gorak Shep, and sunrise from Kala Patthar",
    "Gokyo Lakes, Ngozumpa Glacier, and Gokyo Ri panorama",
    "Views of Everest, Lhotse, Makalu, Cho Oyu, Ama Dablam, and more from multiple angles",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport transfers on arrival and departure by private vehicle",
    "Kathmandu ↔ Lukla flights included (Manthali bus both ways in peak season as required)",
    "Sagarmatha National Park & Khumbu / TIMS permits arranged",
    "Licensed English-speaking guide with salary, food, lodging & insurance",
    "Assistant guide for groups of 6+; porter support available (typically 2:1)",
    "Teahouse lodging and full-board meals on trek days as listed",
    "First-aid kit & oximeter; emergency evacuation coordination via your insurance",
    "Sleeping bag / down jacket / duffel on request; farewell dinner in Kathmandu",
  ],
  whyHeading: "Why choose Three Passes?",
  whyPoints: [
    "One itinerary combining EBC classics with Gokyo and three 5,000 m+ passes",
    "Quieter high sections away from the most crowded Base Camp corridor",
    "Mountain views from multiple valleys and perspectives",
    "Ideal training ground for future peak expeditions without technical climbing",
    "Built-in acclimatization days at Namche and Chhukung for safer high passes",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "Three Passes is challenging — longer than classic EBC, with three crossings above 5,000 m, steep rocky terrain, and cold alpine weather. Strong fitness and prior multi-day trekking experience are strongly recommended.\n\nFit beginners can succeed with heavy preparation (5–6+ weeks of cardio and hill training), a steady pace, and strict attention to acclimatization. Travel insurance covering helicopter evacuation from high altitude is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train 5–6+ weeks with hiking, stairs, jogging, and strength work for legs and core",
    "Break in waterproof boots; practice with a loaded daypack",
    "Pack serious warm layers for windy passes and freezing nights near Gorak Shep / Gokyo",
    "Buy insurance covering trekking to 6,000 m and helicopter evacuation",
    "Arrive in Kathmandu 1–2 days before Day 1 for Lukla flight buffer",
    "Budget ~US$25/day for personal trail extras (Wi-Fi, showers, snacks, drinks)",
  ],
  itineraryHeading: "18-day itinerary",
  itineraryIntro:
    "Times and lodge stops are estimates and may change with weather, flights, and availability. Peak-season Lukla flights often operate via Manthali (Ramechhap). Your Summit Seek guide can adjust the plan for safety. Clockwise routing is available on request.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrival in Kathmandu",
      maxAltitude: "1,350 m",
      meals: "—",
      accommodation: "Hotel in Kathmandu",
      description:
        "Airport meet-and-greet and private transfer to your hotel in Thamel. Trek briefing and gear check with your Summit Seek leader. Free evening to explore. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Fly to Lukla – trek to Phakding",
      maxAltitude: "2,860 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Scenic flight to Lukla (about 35 minutes; peak season may route via Manthali). Meet porters and trek along the Dudh Koshi with suspension bridges to Phakding (about 3–4 hours / ~7 km). Overnight in Phakding.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Phakding – Namche Bazaar",
      maxAltitude: "3,440 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Enter Sagarmatha National Park at Monjo, continue via Jorsalle, then climb steeply into Namche Bazaar — the main Sherpa hub of the Khumbu (about 5–6 hours / ~14 km). First Everest views on a clear day.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Namche acclimatization",
      maxAltitude: "≈ 3,880 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Acclimatization day in Namche. Hike toward Hotel Everest View / Syangboche and optionally Khumjung monastery and Hillary School. Overnight again in Namche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Namche – Tengboche",
      maxAltitude: "3,860 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Forest trails and switchbacks with Everest, Lhotse, and Ama Dablam views to Tengboche. Visit the region’s largest monastery. Overnight in Tengboche (about 5–6 hours / ~12 km).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Tengboche – Dingboche",
      maxAltitude: "4,360 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Via Deboche and Pangboche along the Imja / Dudh Koshi corridor into Dingboche with expanding Himalayan views (about 5–6 hours / ~12 km). Overnight in Dingboche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Dingboche – Chhukung",
      maxAltitude: "4,730 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Shorter walk into the Imja valley to Chhukung beneath Lhotse, Nuptse, and Ama Dablam (about 3 hours / ~5 km). Optional hike toward Chhukung Ri. Overnight in Chhukung.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Chhukung acclimatization",
      maxAltitude: "≈ 5,546 m (optional Ri)",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Second major acclimatization day before the high passes. Optional sunrise hike to Chhukung Ri or shorter active walks. Rest and prepare for Kongma La. Overnight in Chhukung.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Chhukung – Kongma La – Lobuche",
      maxAltitude: "≈ 5,535 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Early start over Kongma La — first of the three high passes — then a careful descent toward the Khumbu Glacier into Lobuche (about 7–8 hours / ~15 km). Overnight in Lobuche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Lobuche – Everest Base Camp – Gorak Shep",
      maxAltitude: "5,364 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Trek the Khumbu moraine to Gorak Shep, continue to Everest Base Camp for photos and celebration, then return to overnight at Gorak Shep (about 7 hours / ~12 km).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Kala Patthar – Dzongla",
      maxAltitude: "5,545 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Pre-dawn climb to Kala Patthar for the best Everest sunrise panorama. Breakfast at Gorak Shep, then trek to Dzongla (about 6–7 hours / ~12 km). Overnight in Dzongla.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Dzongla – Cho La – Gokyo",
      maxAltitude: "≈ 5,420 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Cross Cho La — second high pass — then descend via Thangnak into the Gokyo valley beside turquoise alpine lakes (about 7–8 hours / ~17 km). Overnight in Gokyo.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Gokyo Ri acclimatization",
      maxAltitude: "5,357 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Early hike to Gokyo Ri for sunrise over Cho Oyu, Everest, Lhotse, and the Gokyo Lakes. Free afternoon to rest and explore lakeshores. Overnight in Gokyo.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Gokyo – Renjo La – Marulung",
      maxAltitude: "≈ 5,360 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Final high pass: Renjo La with sweeping views of Ngozumpa Glacier, Gokyo, Everest, and Lhotse. Descend via Lumde to Marulung (about 7–8 hours / ~17 km).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d15",
      dayLabel: "Day 15",
      title: "Marulung – Namche Bazaar",
      maxAltitude: "3,440 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Descend the Bhote Koshi / Thame corridor — historic salt-trade route — via Thame into Namche Bazaar (about 6–7 hours). Overnight in Namche.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d16",
      dayLabel: "Day 16",
      title: "Namche – Lukla",
      maxAltitude: "2,860 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Final mountain walking day down the Dudh Koshi valley with suspension bridges and pine forests back to Lukla (about 6–7 hours / ~16 km). Celebrate with your team. Overnight in Lukla.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d17",
      dayLabel: "Day 17",
      title: "Fly Lukla – Kathmandu",
      maxAltitude: "1,350 m",
      meals: "Breakfast, Farewell dinner",
      accommodation: "Hotel in Kathmandu",
      description:
        "Morning flight Lukla to Kathmandu (or Lukla–Manthali then road transfer in peak season). Hotel transfer, free time, and farewell dinner. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d18",
      dayLabel: "Day 18",
      title: "Final departure",
      maxAltitude: "1,350 m",
      meals: "Breakfast",
      accommodation: "— (departure day)",
      description:
        "Private transfer to Tribhuvan International Airport for your departure flight. End of the Everest Three Passes journey with Summit Seek. Extra Nepal activities available on request.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Three Passes departures run on private and joining bases. Spring (Mar–May) and autumn (Sep–Nov) offer the clearest mountain views. Winter is much colder on the passes; monsoon brings cloud and more Lukla delays.",
  availabilityNotes: [
    "Private and group joining options year-round",
    "Arrive Kathmandu 1–2 days early for Lukla flight buffer",
    "Peak-season Lukla flights often operate via Manthali (Ramechhap)",
    "Clockwise or anti-clockwise routing available on request",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Porter service",
      description: "Shared porter (typically 2:1) or dedicated porter for solo travelers.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Kathmandu ↔ Lukla helicopter",
      description: "Sharing heli options to avoid Manthali transfers or flight delays.",
      priceLabel: "From US$500 / person",
      visible: true,
    },
    {
      id: "a3",
      title: "Private Manthali jeep",
      description: "Upgrade the shared Manthali bus to a private jeep (one way or return).",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport transfers on arrival and departure by private vehicle",
    "Full-board meals (breakfast, lunch, dinner — main course) during the mountain trek",
    "Licensed English-speaking trekking guide (salary, food, lodging, insurance, transport)",
    "Assistant guide for groups of 6 or more",
    "Sagarmatha National Park permit & TIMS / Khumbu fees as applicable",
    "Teahouse / lodge accommodation throughout the trek",
    "Kathmandu ↔ Lukla airfare including airport taxes (Manthali routing in peak season as required)",
    "Supplementary snacks / evening fruit as per package",
    "Farewell dinner in Kathmandu",
    "Sleeping bag / down jacket / duffel on request (return after trek)",
    "Oximeter checks and comprehensive first-aid kit with the guide",
    "Emergency rescue coordination (funded by your travel insurance)",
    "Government and local taxes as per itinerary",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Nepal entry visa fees",
    "Extra hotel nights and city meals outside the trek schedule",
    "Beverages (tea/coffee extras, soft drinks, alcohol, bottled water)",
    "Personal expenses (laundry, Wi-Fi, hot showers, charging, phone)",
    "Travel insurance covering high-altitude helicopter evacuation (mandatory)",
    "Personal trekking equipment",
    "Porter wages if you opt in (available as add-on)",
    "Tips for guide, porter, and staff",
    "Costs from delays, weather, strikes, or events beyond our control",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "High Himalayan passes and prayer flags",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Everest region ridges and glaciers",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Alpine lakes and mountain light",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Khumbu trail atmosphere",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May and September–November usually offer the clearest skies and most reliable pass conditions. Winter is extremely cold on Kongma La, Cho La, and Renjo La; monsoon adds cloud and flight uncertainty.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Difficulty & altitude",
      body: "Moderate to strenuous. Three crossings above 5,000 m, long days, and rugged terrain. Max viewpoint altitude is Kala Patthar at 5,545 m. Respect AMS symptoms and follow your guide’s pacing.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Lukla flights",
      body: "Off-season flights often operate Kathmandu–Lukla direct. In peak spring/autumn, airlines commonly fly via Manthali (Ramechhap) with an early shared bus — included when required.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Lodges & meals",
      body: "Teahouses with twin beds and blankets; bathrooms often shared higher up. Menus feature dal bhat, noodles, soups, momos, porridge, and eggs. Budget extras for Wi-Fi, showers, and charging.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack for cold, windy high passes. Porter loads are shared when you add porter service. Carry a daypack for water, layers, documents, and snacks. Rent bulky items in Kathmandu if needed.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece mid-layer",
        "Heavy down / insulated jacket",
        "Waterproof hard shell",
        "Warm trekking pants + insulated evening layer",
        "Warm hat, sun hat, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Camp shoes",
        "Trekking poles (essential for passes)",
        "25–35L daypack",
        "Duffel for porter (if using)",
        "Microspikes optional in icy seasons",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "Personal medications & blister care",
        "SPF 50+ sunscreen & lip balm",
        "UV sunglasses / glacier glasses",
        "Water bottle / bladder + purification",
        "Headlamp + spare batteries",
        "High-energy snacks",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance (high-altitude evacuation)",
        "Cash for personal trail expenses",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Sleeping bag / down jacket / duffel on request (return after trek)",
    "Route map and pre-trek briefing in Kathmandu",
    "Oximeter monitoring with your guiding team",
    "Help arranging hotel upgrades and helicopter options",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "How hard is the Everest Three Passes trek?",
      answer:
        "It is moderate to strenuous — longer and harder than classic EBC because of three 5,000 m+ passes, steep rocky ground, and cold weather. Strong fitness and prior trekking experience are recommended.",
      visible: true,
    },
    {
      id: "q2",
      question: "What is the maximum altitude?",
      answer:
        "Kala Patthar at approximately 5,545 m is the highest viewpoint. The passes are roughly Kongma La 5,535–5,540 m, Cho La 5,420 m, and Renjo La 5,345–5,400 m.",
      visible: true,
    },
    {
      id: "q3",
      question: "Does this trek include Everest Base Camp?",
      answer:
        "Yes. This 18-day itinerary visits Everest Base Camp and Kala Patthar as well as Gokyo Lakes and Gokyo Ri, in addition to the three high passes.",
      visible: true,
    },
    {
      id: "q4",
      question: "When is the best time to go?",
      answer:
        "March–May and September–November offer the most reliable views and pass conditions. Winter is possible for experienced cold-weather trekkers; monsoon is less ideal.",
      visible: true,
    },
    {
      id: "q5",
      question: "Are Lukla flights included?",
      answer:
        "Yes. Kathmandu–Lukla–Kathmandu flights (or Manthali routing in peak season with included shared bus) are part of the package.",
      visible: true,
    },
    {
      id: "q6",
      question: "Do I need travel insurance?",
      answer:
        "Yes. Cover trekking and helicopter evacuation from high altitude (policy should allow rescue above 5,000 m). Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q7",
      question: "How much does the trek cost?",
      answer:
        "Listed from US$1,255 per person for small groups (2–6), with solo and larger-group rates in the discount table. Exact quotes depend on dates and add-ons such as porter or heli.",
      visible: true,
    },
    {
      id: "q8",
      question: "Can I trek clockwise instead?",
      answer:
        "Yes. Our default is the anti-clockwise route described here, but clockwise is available — tell us your preference when you enquire.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Everest Three Passes?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Everest Three Passes Trek 18 Days | Summit Seek",
  metaDescription:
    "Book the 18-day Everest Three Passes trek with Summit Seek — Kongma La, Cho La, Renjo La, EBC, Kala Patthar, Gokyo, Lukla flights, permits, guide & group discounts.",
};
