import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_TSUM_VALLEY: TrekPageContent = {
  coverImageUrl: img("photo-1464822759023-fed622ff2c3b", 2000),
  coverTitle: "Tsum Valley Trek - 17 Days",
  coverSubtitle:
    "Sacred Beyul of happiness near Tibet — Chumling, Chhokangparo, Mu Gompa, Rachen Gompa, and Tibetan-Buddhist culture in restricted Manaslu country.",
  heroMainImageUrl: img("photo-1464822759023-fed622ff2c3b", 2000),
  heroSideImage1Url: img("photo-1544735716-392fe2489ffa", 900),
  heroSideImage2Url: img("photo-1486870591958-9b9d0d1dda99", 900),
  breadcrumbLabel: "Manaslu Region · Tsum Valley",
  title: "Tsum Valley Trek - 17 Days",
  regionLabel: "Manaslu Region",
  rating: 5,
  reviewCount: 19,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 1425,
  compareAtPrice: 1625,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "12% OFF",
  shortTripBadge: "Restricted Area",
  durationLabel: "17 Days",
  difficultyLabel: "Moderate",
  groupSizeLabel: "1–10",
  bookingNote:
    "Private and small-group departures. Package includes Kathmandu hotels (BB), licensed guide, porter (2:1), trek meals, TIMS, Manaslu/Tsum restricted permits, and road transfers as listed. Licensed guide mandatory in the restricted area.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 1625, visible: true },
    { id: "gd2", paxLabel: "2-3 pax", price: 1425, visible: true },
    { id: "gd3", paxLabel: "4-6 pax", price: 1375, visible: true },
    { id: "gd4", paxLabel: "7-10 pax", price: 1325, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "17 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Moderate", visible: true },
    { id: "f3", label: "Max Altitude", value: "3,910 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Tsum / Manaslu", visible: true },
    { id: "f6", label: "Group Size", value: "1–10", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Culture", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "Tsum Valley — from Tibetan ‘Tsombo’ meaning vivid or clear — is the sacred Beyul Kyimolung, the valley of happiness, believed to have been blessed by Padmasambhava. Opened to trekkers only in 2008, it remains one of Nepal’s most authentic restricted valleys near the Tibetan border in northern Gorkha.\n\nThis 17-day journey drives from Kathmandu toward Arughat / Soti Khola, then follows the Budhi Gandaki into lower and upper Tsum: Chumling, Chhokangparo, Nile/Chhule, Mu Gompa (~3,700–3,910 m), and Rachen Gompa, with a rest day for monastery exploration and Piren Phu (Milarepa’s cave).\n\nExpect Tibetan-style stone houses, Nyingma Buddhism, Ganesh Himal and Shringi views, suspension bridges, and quiet trails away from mass tourism. Summit Seek includes licensed guide, porter (2:1), permits, Kathmandu hotels, trek meals, and clear group pricing. Combine with Manaslu Circuit on request.",
  overviewImageUrl: img("photo-1506905925346-21bda4d32df4"),
  highlightsHeading: "Highlights",
  highlights: [
    "Sacred restricted Tsum Valley — Beyul of happiness near Tibet",
    "Mu Gompa and Rachen Gompa monastic heritage",
    "Piren Phu (Pigeon Cave) linked to Milarepa",
    "Views of Ganesh Himal, Shringi, Hiunchuli, Manaslu & Himalchuli",
    "Budhi Gandaki gorges, waterfalls & suspension bridges",
    "Traditional Tsumba lifestyle and Tibetan-Buddhist culture",
    "Rest day at Mu Gompa for deeper exploration",
    "Quieter alternative to Everest and Annapurna classics",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport transfers and escort",
    "Three nights Kathmandu three-star hotel with breakfast",
    "Food and local-lodge accommodation during the trek as listed",
    "English-speaking licensed local guide",
    "Porters (max ~20 kg; one porter between two persons)",
    "TIMS and Manaslu Conservation / Tsum restricted permits as required",
    "Kathmandu–Soti Khola road transfers as per itinerary",
    "Sleeping bag / first-aid / oximeter support; staff insurance; farewell dinner; certificate",
  ],
  whyHeading: "Why choose Tsum Valley?",
  whyPoints: [
    "One of Nepal’s last truly remote Tibetan-Buddhist valleys",
    "Spiritual depth without crossing Larkya La",
    "Moderate max altitude (~3,910 m) vs full Manaslu Circuit",
    "Opened only in 2008 — still unspoiled by mass tourism",
    "Easy to extend into Manaslu Circuit afterward",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "Graded moderate. Suitable for fit trekkers with some multi-day hiking experience. Days involve riverside trails, suspension bridges, and steady climbs into upper Tsum, with a high point around Mu Gompa (~3,700–3,910 m).\n\nA licensed guide is mandatory in the restricted area. Travel insurance covering helicopter evacuation is required.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train 4–6 weeks with long walks, stairs, and light cardio",
    "Break in waterproof hiking boots",
    "Pack warm layers for cool nights at Mu Gompa",
    "Carry a headlamp, water purification, and blister care",
    "Buy travel insurance covering high-altitude trekking and evacuation",
    "Arrive Kathmandu a day early for briefing and permit processing",
  ],
  itineraryHeading: "17-day itinerary",
  itineraryIntro:
    "Walking and drive times are estimates and vary with weather and road conditions. Lodge stops may change with availability. Your Summit Seek guide can adjust the plan for safety and comfort.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,400 m",
      meals: "—",
      accommodation: "Hotel in Kathmandu",
      description:
        "Airport meet-and-greet and transfer to your hotel. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Kathmandu preparation & sightseeing",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Permit preparation, gear check, and guided Kathmandu sightseeing as arranged. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Drive Kathmandu – Arughat – Soti Khola",
      maxAltitude: "730 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Bus toward Arughat Bazaar then jeep to Soti Khola trailhead. Overnight in Soti Khola.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Soti Khola – Machha Khola",
      maxAltitude: "869 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Trek along the Budhi Gandaki (~5 hours) to Machha Khola. Overnight in Machha Khola.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Machha Khola – Doban",
      maxAltitude: "1,070 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Continue up-valley through forests and villages to Doban. Overnight in Doban.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Doban – Philim",
      maxAltitude: "≈ 1,570 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Trek to Philim, a key Gurung village and gateway toward Tsum. Overnight in Philim.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Philim – Chumling (Lower Tsum)",
      maxAltitude: "2,130 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Enter lower Tsum Valley to Chumling Tower / Chumling (~2,130 m). Overnight in Chumling.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Chumling – Chhokangparo (Upper Tsum)",
      maxAltitude: "3,030 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Climb into upper Tsum to Chhokangparo with expanding Himalayan views. Overnight in Chhokangparo.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Trek to Nile / Chhule",
      maxAltitude: "3,360 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Continue to Nile/Chhule with monastery and village culture. Overnight in Nile/Chhule.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Nile – Mu Gompa",
      maxAltitude: "3,910 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guesthouse / Gompa",
      description:
        "Ascend to Mu Gompa, the largest and highest monastery in Tsum. Overnight at Mu Gompa.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Rest day at Mu Gompa",
      maxAltitude: "3,910 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Guesthouse / Gompa",
      description:
        "Acclimatization and exploration — monastery visits, viewpoints, optional Piren Phu. Overnight at Mu Gompa.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Mu Gompa – Rachen Gompa",
      maxAltitude: "3,240 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Descend via Chhule toward Rachen Gompa with Punchen Himal views. Overnight near Rachen Gompa.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Rachen Gompa – Dumje",
      maxAltitude: "2,440 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Continue descending through forest and villages to Dumje. Overnight in Dumje.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Dumje – Philim",
      maxAltitude: "≈ 1,570 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Rejoin the main Budhi Gandaki corridor back to Philim. Overnight in Philim.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d15",
      dayLabel: "Day 15",
      title: "Philim – Tatopani",
      maxAltitude: "1,830 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Descend toward Tatopani with riverside trails and bridges. Overnight in Tatopani.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d16",
      dayLabel: "Day 16",
      title: "Tatopani – Soti Khola",
      maxAltitude: "730 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Final trek day back to Soti Khola. Overnight in Soti Khola.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d17",
      dayLabel: "Day 17",
      title: "Drive Soti Khola – Kathmandu & departure",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "— (departure day)",
      description:
        "Jeep to Arughat then bus to Kathmandu. Airport transfer for your departure flight (or overnight hotel if your flight is next day — available as add-on). End of the Tsum Valley journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Tsum Valley runs best in March–May and September–November. Private and joining groups of 1–10 are welcome. Winter is colder and quieter; monsoon means rain and slippery trails.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Licensed guide and restricted permits mandatory",
    "Porter included typically 2 clients : 1 porter",
    "Easy to extend into Manaslu Circuit on request",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Extra Kathmandu hotel night",
      description: "Add a buffer night if your flight is the morning after Day 17.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Private jeep upgrades",
      description: "Upgrade local bus sections to private jeep where roads allow.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Manaslu Circuit extension",
      description: "Continue from Philim toward Samagaun and Larkya La.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport transfers and escort",
    "Three nights’ accommodation in Kathmandu (three-star) with breakfast",
    "Food (breakfast, lunch, dinner) and local-lodge lodging during the trek as listed",
    "English-speaking licensed local guide",
    "Porters (max ~20 kg; typically one porter between two persons)",
    "TIMS fees and Manaslu Conservation / Tsum restricted permits as required",
    "Kathmandu–Soti Khola road transfers as per itinerary",
    "Equipment for staff; sleeping bag / first-aid / oximeter support as provided",
    "Insurance for staff and porters; farewell dinner; achievement certificate",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "Nepal visa fees",
    "International flights",
    "Travel insurance (mandatory — helicopter evacuation)",
    "Lunch and dinner during Kathmandu hotel stays",
    "Electronic charging fees and hot showers on trek",
    "Alcoholic drinks, candies, and personal snacks",
    "Extra accommodation and meals outside the itinerary",
    "Personal gear (available on hire) and tips",
    "Emergency evacuation / roadblock expenses beyond our control",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "High Himalayan light toward Ganesh / Manaslu",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Remote valley approaches in Tsum country",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "Alpine ridges near the Tibetan border",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Mountain meadow atmosphere",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May and September–November usually offer the clearest mountain views and most comfortable trail conditions in Tsum Valley.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude",
      body: "Highest point is around Mu Gompa (~3,700–3,910 m). Use the rest day, drink water, and tell your guide early if you feel unwell.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Moderate. Riverside gorges, suspension bridges, and steady climbs into upper Tsum — no Larkya La crossing on this itinerary.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Culture & permits",
      body: "Tsum is a restricted area with deep Tibetan-Buddhist traditions. Dress modestly at gompas. Summit Seek arranges RAP / MCAP / TIMS with your licensed guide.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack for cool monastery nights and dusty jeep roads. Porters carry main bags; keep water, layers, documents, and camera in a daypack.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece mid-layer",
        "Down / insulated jacket",
        "Waterproof shell",
        "Trekking pants",
        "Warm hat, sun hat, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in waterproof hiking boots",
        "Camp shoes",
        "Trekking poles (helpful on descents)",
        "25–35L daypack",
        "Sleeping bag (provided/rental as arranged)",
        "Headlamp + spare batteries",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "SPF sunscreen & lip balm",
        "UV sunglasses",
        "Personal medications & blister care",
        "Water bottle + purification",
        "Hand sanitizer & toilet paper",
        "Trail snacks",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance details",
        "Cash for personal trail extras",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Permit processing and licensed guiding team",
    "Sleeping bag / first-aid / oximeter support as arranged",
    "Farewell dinner and trek completion certificate",
    "Advice on extending into Manaslu Circuit",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Tsum Valley trek?",
      answer:
        "A 17-day restricted-area cultural trek into sacred Tsum Valley near Tibet — Chumling, Chhokangparo, Mu Gompa, and Rachen Gompa — without crossing Larkya La.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Moderate. Expect riverside trails, bridges, and climbs to about 3,910 m at Mu Gompa. Prior multi-day hiking helps.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This Summit Seek listing starts at US$1,425 for 2–3 pax (US$1,625 solo; US$1,375 for 4–6; US$1,325 for 7–10).",
      visible: true,
    },
    {
      id: "q4",
      question: "What is the maximum altitude?",
      answer:
        "Around 3,910 m near Mu Gompa. There is a full rest/exploration day at the monastery.",
      visible: true,
    },
    {
      id: "q5",
      question: "Do I need special permits?",
      answer:
        "Yes. Tsum/Manaslu restricted permits, conservation fees, and TIMS are required. Summit Seek arranges these with a licensed guide.",
      visible: true,
    },
    {
      id: "q6",
      question: "Is travel insurance necessary?",
      answer:
        "Yes. Cover high-altitude trekking and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q7",
      question: "When is the best time to go?",
      answer:
        "March–May and September–November usually offer the best weather and mountain views.",
      visible: true,
    },
    {
      id: "q8",
      question: "Can I combine Tsum with Manaslu Circuit?",
      answer:
        "Yes. Many travelers continue from Philim toward Samagaun and Larkya La — ask us to customize.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Tsum Valley?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Tsum Valley Trek 17 Days | Summit Seek",
  metaDescription:
    "Book the 17-day Tsum Valley trek with Summit Seek — Mu Gompa, Rachen Gompa, restricted permits, guide, porter, meals & group discounts from US$1,325.",
};
