import type { UpcomingTripsContent } from "@/types/upcoming-trips";

export const DEFAULT_UPCOMING_TRIPS: UpcomingTripsContent = {
  eyebrow: "Last-Minute Specials",
  heading: "Join Upcoming Trips",
  noteTitle: "Note to Solo Travelers",
  noteBody:
    "We specialize in accommodating solo trekkers who wish to join a group. We will never cancel your trip due to a limited number of participants.",
  viewAllLabel: "View All Dates",
  viewAllHref: "/packages",
  bookLabel: "Book Now",
  visible: true,
  months: [
    {
      id: "sep-2026",
      label: "Sep 2026",
      trips: [
        {
          id: "sep-1",
          title: "Manaslu Circuit Trek - 14 Days",
          durationDays: 14,
          startsLabel: "Sep 05, 2026",
          endsLabel: "Sep 18, 2026",
          status: "Available",
          badgeLabel: "3 seat",
          price: 950,
          compareAtPrice: 1520,
          bookHref: "/packages/manaslu-circuit-trek",
          visible: true,
        },
        {
          id: "sep-2",
          title: "Annapurna Circuit Trek - 15 Days",
          durationDays: 15,
          startsLabel: "Sep 05, 2026",
          endsLabel: "Sep 19, 2026",
          status: "Available",
          badgeLabel: "6 seat",
          price: 1005,
          compareAtPrice: 1550,
          bookHref: "/packages/annapurna-circuit-trek",
          visible: true,
        },
        {
          id: "sep-3",
          title: "Upper Mustang Trek - 14 Days",
          durationDays: 14,
          startsLabel: "Sep 08, 2026",
          endsLabel: "Sep 21, 2026",
          status: "Available",
          badgeLabel: "4 seat",
          price: 1795,
          compareAtPrice: 2150,
          bookHref: "/treks/upper-mustang",
          visible: true,
        },
        {
          id: "sep-4",
          title: "Ghorepani Poonhill Trekking - 5 Days",
          durationDays: 5,
          startsLabel: "Sep 10, 2026",
          endsLabel: "Sep 14, 2026",
          status: "Available",
          badgeLabel: "8 seat",
          price: 399,
          compareAtPrice: 499,
          bookHref: "/treks/poon-hill",
          visible: true,
        },
        {
          id: "sep-5",
          title: "Everest Base Camp Trek - 15 Days",
          durationDays: 15,
          startsLabel: "Sep 12, 2026",
          endsLabel: "Sep 26, 2026",
          status: "Guaranteed",
          badgeLabel: "5 seat",
          price: 1300,
          compareAtPrice: 1550,
          bookHref: "/packages/everest-base-camp-trek",
          visible: true,
        },
        {
          id: "sep-6",
          title: "Annapurna Base Camp Trek - 15 Days",
          durationDays: 15,
          startsLabel: "Sep 15, 2026",
          endsLabel: "Sep 29, 2026",
          status: "Available",
          badgeLabel: "7 seat",
          price: 955,
          compareAtPrice: 1540,
          bookHref: "/packages/annapurna-base-camp-trek",
          visible: true,
        },
      ],
    },
    {
      id: "oct-2026",
      label: "Oct 2026",
      trips: [
        {
          id: "oct-1",
          title: "Arun Valley Trek - 12 Days",
          durationDays: 12,
          startsLabel: "Oct 08, 2026",
          endsLabel: "Oct 19, 2026",
          status: "Available",
          badgeLabel: "6 seat",
          price: 1190,
          compareAtPrice: 1490,
          bookHref: "/treks/arun-valley",
          visible: true,
        },
        {
          id: "oct-2",
          title: "Annapurna Circuit Trek - 15 Days",
          durationDays: 15,
          startsLabel: "Oct 10, 2026",
          endsLabel: "Oct 24, 2026",
          status: "Available",
          badgeLabel: "6 seat",
          price: 1005,
          compareAtPrice: 1550,
          bookHref: "/packages/annapurna-circuit-trek",
          visible: true,
        },
        {
          id: "oct-3",
          title: "Everest Base Camp Trek - 15 Days",
          durationDays: 15,
          startsLabel: "Oct 12, 2026",
          endsLabel: "Oct 26, 2026",
          status: "Guaranteed",
          badgeLabel: "4 seat",
          price: 1300,
          compareAtPrice: 1550,
          bookHref: "/packages/everest-base-camp-trek",
          visible: true,
        },
        {
          id: "oct-4",
          title: "Manaslu Circuit Trek - 14 Days",
          durationDays: 14,
          startsLabel: "Oct 15, 2026",
          endsLabel: "Oct 28, 2026",
          status: "Available",
          badgeLabel: "5 seat",
          price: 950,
          compareAtPrice: 1520,
          bookHref: "/packages/manaslu-circuit-trek",
          visible: true,
        },
        {
          id: "oct-5",
          title: "Langtang Valley Trek - 9 Days",
          durationDays: 9,
          startsLabel: "Oct 18, 2026",
          endsLabel: "Oct 26, 2026",
          status: "Available",
          badgeLabel: "8 seat",
          price: 790,
          compareAtPrice: 1275,
          bookHref: "/packages/langtang-valley-trek",
          visible: true,
        },
        {
          id: "oct-6",
          title: "Upper Mustang Trek - 14 Days",
          durationDays: 14,
          startsLabel: "Oct 20, 2026",
          endsLabel: "Nov 02, 2026",
          status: "Available",
          badgeLabel: "3 seat",
          price: 1795,
          compareAtPrice: 2150,
          bookHref: "/treks/upper-mustang",
          visible: true,
        },
      ],
    },
    {
      id: "nov-2026",
      label: "Nov 2026",
      trips: [
        {
          id: "nov-1",
          title: "Gokyo Lakes Trek - 12 Days",
          durationDays: 12,
          startsLabel: "Nov 03, 2026",
          endsLabel: "Nov 14, 2026",
          status: "Available",
          badgeLabel: "2 seat",
          price: 1390,
          compareAtPrice: 1590,
          bookHref: "/treks/gokyo-lakes",
          visible: true,
        },
        {
          id: "nov-2",
          title: "Everest Base Camp Trek - 15 Days",
          durationDays: 15,
          startsLabel: "Nov 05, 2026",
          endsLabel: "Nov 19, 2026",
          status: "Guaranteed",
          badgeLabel: "6 seat",
          price: 1300,
          compareAtPrice: 1550,
          bookHref: "/packages/everest-base-camp-trek",
          visible: true,
        },
        {
          id: "nov-3",
          title: "Annapurna Base Camp Trek - 15 Days",
          durationDays: 15,
          startsLabel: "Nov 08, 2026",
          endsLabel: "Nov 22, 2026",
          status: "Available",
          badgeLabel: "5 seat",
          price: 955,
          compareAtPrice: 1540,
          bookHref: "/packages/annapurna-base-camp-trek",
          visible: true,
        },
        {
          id: "nov-4",
          title: "Manaslu Circuit Trek - 14 Days",
          durationDays: 14,
          startsLabel: "Nov 10, 2026",
          endsLabel: "Nov 23, 2026",
          status: "Available",
          badgeLabel: "4 seat",
          price: 950,
          compareAtPrice: 1520,
          bookHref: "/packages/manaslu-circuit-trek",
          visible: true,
        },
        {
          id: "nov-5",
          title: "Ghorepani Poonhill Trekking - 5 Days",
          durationDays: 5,
          startsLabel: "Nov 12, 2026",
          endsLabel: "Nov 16, 2026",
          status: "Available",
          badgeLabel: "9 seat",
          price: 399,
          compareAtPrice: 499,
          bookHref: "/treks/poon-hill",
          visible: true,
        },
        {
          id: "nov-6",
          title: "Langtang Valley Trek - 9 Days",
          durationDays: 9,
          startsLabel: "Nov 15, 2026",
          endsLabel: "Nov 23, 2026",
          status: "Available",
          badgeLabel: "7 seat",
          price: 790,
          compareAtPrice: 1275,
          bookHref: "/packages/langtang-valley-trek",
          visible: true,
        },
      ],
    },
  ],
};
