import type { UpcomingTripsContent } from "@/types/upcoming-trips";

export const DEFAULT_UPCOMING_TRIPS: UpcomingTripsContent = {
  eyebrow: "Last-Minute Specials",
  heading: "Join Upcoming Trips",
  noteTitle: "Note to Solo Travelers",
  noteBody:
    "We specialize in accommodating solo trekkers who wish to join a group. We will never cancel your trip due to a limited number of participants.",
  viewAllLabel: "View All Dates",
  viewAllHref: "/packages",
  bookLabel: "Book Now",
  visible: true,
  months: [
    {
      id: "sep-2026",
      label: "Sep 2026",
      trips: [
        {
          id: "sep-1",
          title: "Manaslu Circuit Trek",
          durationDays: 14,
          startsLabel: "Sep 05, 2026",
          endsLabel: "Sep 18, 2026",
          status: "Available",
          badgeLabel: "3 seat",
          price: 1175,
          compareAtPrice: 1490,
          bookHref: "/packages/manaslu-circuit-trek",
          visible: true,
        },
        {
          id: "sep-2",
          title: "Annapurna Circuit Trek",
          durationDays: 14,
          startsLabel: "Sep 05, 2026",
          endsLabel: "Sep 18, 2026",
          status: "Available",
          badgeLabel: "6 seat",
          price: 1090,
          compareAtPrice: 1350,
          bookHref: "/packages/annapurna-circuit-trek",
          visible: true,
        },
        {
          id: "sep-3",
          title: "Upper Mustang Trek",
          durationDays: 14,
          startsLabel: "Sep 08, 2026",
          endsLabel: "Sep 21, 2026",
          status: "Available",
          badgeLabel: "4 seat",
          price: 1850,
          compareAtPrice: 2150,
          bookHref: "/treks/upper-mustang",
          visible: true,
        },
        {
          id: "sep-4",
          title: "Ghorepani Poon Hill Trek",
          durationDays: 7,
          startsLabel: "Sep 10, 2026",
          endsLabel: "Sep 16, 2026",
          status: "Available",
          badgeLabel: "8 seat",
          price: 615,
          compareAtPrice: 750,
          bookHref: "/treks/poon-hill",
          visible: true,
        },
        {
          id: "sep-5",
          title: "Everest Base Camp Trek",
          durationDays: 14,
          startsLabel: "Sep 12, 2026",
          endsLabel: "Sep 25, 2026",
          status: "Guaranteed",
          badgeLabel: "5 seat",
          price: 1390,
          compareAtPrice: 1650,
          bookHref: "/packages/everest-base-camp-trek",
          visible: true,
        },
        {
          id: "sep-6",
          title: "Annapurna Base Camp Trek",
          durationDays: 11,
          startsLabel: "Sep 15, 2026",
          endsLabel: "Sep 25, 2026",
          status: "Available",
          badgeLabel: "7 seat",
          price: 895,
          compareAtPrice: 1100,
          bookHref: "/packages/annapurna-base-camp-trek",
          visible: true,
        },
      ],
    },
    {
      id: "oct-2026",
      label: "Oct 2026",
      trips: [
        {
          id: "oct-1",
          title: "Guerrilla Trek",
          durationDays: 17,
          startsLabel: "Oct 08, 2026",
          endsLabel: "Oct 24, 2026",
          status: "Available",
          badgeLabel: "6 seat",
          price: 1785,
          compareAtPrice: 2000,
          bookHref: "/treks/arun-valley",
          visible: true,
        },
        {
          id: "oct-2",
          title: "Annapurna Circuit Trek",
          durationDays: 14,
          startsLabel: "Oct 10, 2026",
          endsLabel: "Oct 23, 2026",
          status: "Available",
          badgeLabel: "6 seat",
          price: 1090,
          compareAtPrice: 1350,
          bookHref: "/packages/annapurna-circuit-trek",
          visible: true,
        },
        {
          id: "oct-3",
          title: "Everest Base Camp Trek",
          durationDays: 14,
          startsLabel: "Oct 12, 2026",
          endsLabel: "Oct 25, 2026",
          status: "Guaranteed",
          badgeLabel: "4 seat",
          price: 1390,
          compareAtPrice: 1650,
          bookHref: "/packages/everest-base-camp-trek",
          visible: true,
        },
        {
          id: "oct-4",
          title: "Manaslu Circuit Trek",
          durationDays: 14,
          startsLabel: "Oct 15, 2026",
          endsLabel: "Oct 28, 2026",
          status: "Available",
          badgeLabel: "5 seat",
          price: 1175,
          compareAtPrice: 1490,
          bookHref: "/packages/manaslu-circuit-trek",
          visible: true,
        },
        {
          id: "oct-5",
          title: "Langtang Valley Trek",
          durationDays: 9,
          startsLabel: "Oct 18, 2026",
          endsLabel: "Oct 26, 2026",
          status: "Available",
          badgeLabel: "8 seat",
          price: 790,
          compareAtPrice: 990,
          bookHref: "/packages/langtang-valley-trek",
          visible: true,
        },
        {
          id: "oct-6",
          title: "Upper Mustang Trek",
          durationDays: 14,
          startsLabel: "Oct 20, 2026",
          endsLabel: "Nov 02, 2026",
          status: "Available",
          badgeLabel: "3 seat",
          price: 1850,
          compareAtPrice: 2150,
          bookHref: "/treks/upper-mustang",
          visible: true,
        },
      ],
    },
    {
      id: "nov-2026",
      label: "Nov 2026",
      trips: [
        {
          id: "nov-1",
          title: "Renjo La Pass Gokyo Lake Trek with Helicopter Return",
          durationDays: 11,
          startsLabel: "Nov 03, 2026",
          endsLabel: "Nov 13, 2026",
          status: "Available",
          badgeLabel: "2 seat",
          price: 2530,
          compareAtPrice: 2750,
          bookHref: "/treks/gokyo-lakes",
          visible: true,
        },
        {
          id: "nov-2",
          title: "Everest Base Camp Trek",
          durationDays: 14,
          startsLabel: "Nov 05, 2026",
          endsLabel: "Nov 18, 2026",
          status: "Guaranteed",
          badgeLabel: "6 seat",
          price: 1390,
          compareAtPrice: 1650,
          bookHref: "/packages/everest-base-camp-trek",
          visible: true,
        },
        {
          id: "nov-3",
          title: "Annapurna Base Camp Trek",
          durationDays: 11,
          startsLabel: "Nov 08, 2026",
          endsLabel: "Nov 18, 2026",
          status: "Available",
          badgeLabel: "5 seat",
          price: 895,
          compareAtPrice: 1100,
          bookHref: "/packages/annapurna-base-camp-trek",
          visible: true,
        },
        {
          id: "nov-4",
          title: "Manaslu Circuit Trek",
          durationDays: 14,
          startsLabel: "Nov 10, 2026",
          endsLabel: "Nov 23, 2026",
          status: "Available",
          badgeLabel: "4 seat",
          price: 1175,
          compareAtPrice: 1490,
          bookHref: "/packages/manaslu-circuit-trek",
          visible: true,
        },
        {
          id: "nov-5",
          title: "Ghorepani Poon Hill Trek",
          durationDays: 7,
          startsLabel: "Nov 12, 2026",
          endsLabel: "Nov 18, 2026",
          status: "Available",
          badgeLabel: "9 seat",
          price: 615,
          compareAtPrice: 750,
          bookHref: "/treks/poon-hill",
          visible: true,
        },
        {
          id: "nov-6",
          title: "Langtang Valley Trek",
          durationDays: 9,
          startsLabel: "Nov 15, 2026",
          endsLabel: "Nov 23, 2026",
          status: "Available",
          badgeLabel: "7 seat",
          price: 790,
          compareAtPrice: 990,
          bookHref: "/packages/langtang-valley-trek",
          visible: true,
        },
      ],
    },
  ],
};
