import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_UPPER_MUSTANG: TrekPageContent = {
  coverImageUrl: img("photo-1483728642387-6c3bdd6c93e5", 2000),
  coverTitle: "Upper Mustang Trek - 14 Days",
  coverSubtitle:
    "The Last Forbidden Kingdom — arid rain-shadow trails to walled Lo Manthang, ancient monasteries, sky caves, and Tibetan-Buddhist culture beyond the Annapurnas.",
  heroMainImageUrl: img("photo-1483728642387-6c3bdd6c93e5", 2000),
  heroSideImage1Url: img("photo-1585409677983-0f6c41ca9c3b", 900),
  heroSideImage2Url: img("photo-1464822759023-fed622ff2c3b", 900),
  breadcrumbLabel: "Mustang Region · Upper Mustang",
  title: "Upper Mustang Trek - 14 Days",
  regionLabel: "Mustang Region",
  rating: 5,
  reviewCount: 24,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 1795,
  compareAtPrice: 2150,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "17% OFF",
  shortTripBadge: "Restricted Area",
  durationLabel: "14 Days",
  difficultyLabel: "Moderate",
  groupSizeLabel: "1–12",
  bookingNote:
    "Private and small-group departures. Package includes Kathmandu & Pokhara hotels (BB as listed), Pokhara–Jomsom flights, licensed guide, porter (2:1), trek meals, Upper Mustang RAP and ACAP, and transfers as listed. Licensed agency + guide required in the restricted area.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "1 pax", price: 2150, visible: true },
    { id: "gd2", paxLabel: "2-3 pax", price: 1795, visible: true },
    { id: "gd3", paxLabel: "4-6 pax", price: 1695, visible: true },
    { id: "gd4", paxLabel: "7-12 pax", price: 1595, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "14 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Moderate", visible: true },
    { id: "f3", label: "Max Altitude", value: "4,010 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Upper Mustang", visible: true },
    { id: "f6", label: "Group Size", value: "1–12", visible: true },
    { id: "f7", label: "Activities", value: "Trekking & Culture", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–Nov (monsoon OK)",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "Upper Mustang — the Last Forbidden Kingdom of Lo — sits in the rain shadow of Annapurna (8,091 m) and Dhaulagiri (8,167 m), a high mountain desert of wind-sculpted cliffs, whitewashed villages, and deep Tibetan-Buddhist heritage. Opened carefully to foreigners only after 1990, it still requires a Restricted Area Permit and a licensed guide.\n\nThis 14-day journey flies Kathmandu–Pokhara, then Pokhara–Jomsom, and treks the Kali Gandaki corridor via Kagbeni and Chele through Syangboche, Gheling, Ghami, and Charang to the walled capital Lo Manthang (~3,809 m). A rest day explores monasteries and optional Chhoser caves before returning via Ghami and Chele to Jomsom and Pokhara.\n\nExpect arid plateaus, mani walls, Ghar Gompa, Annapurna–Dhaulagiri panoramas, and a culture closer to Tibet than to the green hills of Nepal. Summit Seek includes flights as listed, RAP/ACAP, guide, porter, teahouse meals, and clear group pricing. Add Tiji Festival timing or a jeep option on request.",
  overviewImageUrl: img("photo-1585409677983-0f6c41ca9c3b"),
  highlightsHeading: "Highlights",
  highlights: [
    "Walled capital of Lo Manthang — the Last Forbidden Kingdom",
    "Arid rain-shadow landscapes like a mountain desert",
    "Ancient monasteries including Ghar Gompa (~1,200 years)",
    "Passes with Annapurna & Dhaulagiri views (Nyi La ~4,010 m)",
    "Tibetan-Buddhist culture, mani walls, chortens & prayer flags",
    "Kagbeni gateway and Kali Gandaki valley approaches",
    "Optional sky caves / Chhoser exploration on rest day",
    "One of Nepal’s best monsoon-season treks (rain shadow)",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport pick-up/drop and transfers as listed",
    "Kathmandu and Pokhara hotel nights with breakfast (as listed)",
    "Teahouse lodging and trek meals (B-L-D on trail days)",
    "Government-licensed English-speaking trekking guide",
    "Porter support (typically one between two persons)",
    "Upper Mustang Restricted Area Permit and ACAP",
    "Kathmandu–Pokhara and Pokhara–Jomsom round-trip flights as listed",
    "First-aid kit, achievement certificate, and government taxes",
  ],
  whyHeading: "Why choose Upper Mustang?",
  whyPoints: [
    "True restricted-area culture rarely seen on classic Nepal trails",
    "Desert scenery unique among Himalayan treks",
    "Moderate max altitude vs Everest or Annapurna Circuit passes",
    "Viable even in monsoon thanks to the rain shadow",
    "Easy to combine with Muktinath, Tiji Festival, or jeep touring",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "Graded moderate. Suitable for fit trekkers with some multi-day hiking experience. Days can run 5–8 hours on dry, windy, rugged trails with steep climbs over passes around 3,600–4,010 m.\n\nA licensed guide and RAP are mandatory. Travel insurance covering helicopter evacuation is required.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train 4–6 weeks with long walks, stairs, and light cardio",
    "Break in boots; pack sun protection for desert glare and wind",
    "Carry a buff/scarf for dust and cold mornings",
    "Pack water purification and blister care",
    "Buy insurance covering trekking to ~4,500 m and helicopter evacuation",
    "Arrive Kathmandu a day early for briefing and permit processing",
  ],
  itineraryHeading: "14-day itinerary",
  itineraryIntro:
    "Flight and walking times are estimates and vary with weather — Jomsom flights are often morning-only and can delay. Lodge stops may change with availability. Your Summit Seek guide can adjust the plan for safety and comfort.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Kathmandu – Pokhara",
      maxAltitude: "822 m",
      meals: "Breakfast",
      accommodation: "Hotel in Pokhara",
      description:
        "Scenic flight (~30 min) or optional ~6–7 hour drive to Pokhara. Overnight in Pokhara.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Pokhara – Jomsom flight – Kagbeni",
      maxAltitude: "2,810 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Early flight to Jomsom (~15–25 min), then trek the Kali Gandaki valley to Kagbeni, gateway to Upper Mustang. Overnight in Kagbeni (~5 hours walking).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Kagbeni – Chele",
      maxAltitude: "3,050 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Enter the restricted area via Tangbe and Chhusang along barren Tibetan-plateau landscapes; cross a suspension bridge to Chele. Overnight in Chele (~5 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Chele – Syangboche",
      maxAltitude: "3,800 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Cross Dorje La (~3,735 m) and Taklam La (~3,624 m) toward Syangboche through arid high country. Overnight in Syangboche (~7 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Syangboche – Gheling",
      maxAltitude: "4,010 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Continue over Yamda La (~3,850 m) and Nyi La (~4,010 m) with Dhaulagiri and Annapurna views to Gheling. Overnight in Gheling (~7 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Gheling – Ghami",
      maxAltitude: "3,520 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Trek past cliffs, valleys, and traditional villages to Ghami. Overnight in Ghami (~6 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Ghami – Charang",
      maxAltitude: "3,870 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Cross Charang La (~3,870 m) to Charang with long mani walls and Tibetan cultural heritage. Overnight in Charang (~7 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Charang – Lo Manthang",
      maxAltitude: "3,809 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Arrive at the walled capital Lo Manthang — whitewashed walls, palace, and ancient monasteries. Overnight in Lo Manthang (~7 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Rest day in Lo Manthang",
      maxAltitude: "3,809 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Acclimatization and exploration — walled city, monasteries, and optional Chhoser / sky-cave side trip. Overnight in Lo Manthang.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Lo Manthang – Ghami (upper route)",
      maxAltitude: "≈ 3,520 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Begin the return via the upper route toward Ghami. Overnight in Ghami (~8 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Ghami – Chele",
      maxAltitude: "3,050 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Continue descending through arid high country to Chele. Overnight in Chele (~8 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Chele – Jomsom",
      maxAltitude: "2,720 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Final trek day along the Kali Gandaki corridor back to Jomsom with Annapurna–Dhaulagiri views. Overnight in Jomsom (~8 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Jomsom – Pokhara flight",
      maxAltitude: "822 m",
      meals: "Breakfast",
      accommodation: "Hotel in Pokhara",
      description:
        "Morning flight to Pokhara (weather permitting). Free afternoon by the lakeside. Overnight in Pokhara.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Pokhara – Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu (as listed) / departure",
      description:
        "Fly or drive back to Kathmandu. Airport transfer or hotel overnight as arranged. End of the Upper Mustang journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Upper Mustang works well from March to November — including monsoon — thanks to the rain shadow. Winter is colder with possible snow on high trails. Private and joining groups of 1–12 are welcome. Time your trip for Tiji Festival (usually May) on request.",
  availabilityNotes: [
    "Private and customizable start dates",
    "Licensed guide and Upper Mustang RAP mandatory",
    "Porter included typically 2 clients : 1 porter",
    "Jomsom flights are weather-dependent — buffer days help",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Extra Kathmandu / Pokhara nights",
      description: "Buffer nights for flight delays or early arrivals.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Tiji Festival timing",
      description: "Extend Lo Manthang stay to coincide with the May festival.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Mustang jeep segments",
      description: "Replace selected walking days with jeep where roads allow.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a4",
      title: "Muktinath side visit",
      description: "Add the sacred Hindu–Buddhist shrine near the Kali Gandaki.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport pick-up/drop and transfers as listed",
    "Kathmandu hotel night(s) with breakfast as listed",
    "Pokhara deluxe hotel nights with breakfast as listed (typically 2)",
    "Teahouse lodging during the trek",
    "Meals as listed (trek days typically B-L-D)",
    "Licensed English-speaking trekking guide",
    "Porter (typically one between two persons)",
    "Upper Mustang Restricted Area Permit and ACAP",
    "Kathmandu–Pokhara and Pokhara–Jomsom round-trip flights as listed",
    "First-aid kit, achievement certificate, government taxes and service charges",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "International airfare and Nepal visa fees",
    "Travel / medical insurance and emergency evacuation costs",
    "Lunch and dinner in Kathmandu and Pokhara (except where listed)",
    "Extra hotel nights outside the itinerary",
    "Personal expenses (phone, laundry, charging, bottled water, hot showers, alcohol)",
    "Personal trekking gear and clothing",
    "Tips for guide and porter",
    "Costs from flight cancellations, roadblocks, or force majeure",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1483728642387-6c3bdd6c93e5"),
      caption: "High arid ridges of the Mustang rain shadow",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1585409677983-0f6c41ca9c3b"),
      caption: "Dramatic Himalayan approaches toward Mustang",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Mountain light over remote high valleys",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Open plateau atmosphere near the Tibetan border",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–November is excellent. Unlike most Nepal treks, Upper Mustang remains viable in monsoon because of the Annapurna–Dhaulagiri rain shadow.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude",
      body: "Most of the trail sits 3,000–4,000 m. Highest points include Nyi La (~4,010 m) and Lo Manthang (~3,809 m). Use the rest day, drink water, and tell your guide early if unwell.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Moderate. Dry, windy trails with long days and several passes — not technical, but fitness and prior multi-day hiking help.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Permits (2026)",
      body: "Upper Mustang RAP is typically USD 50 per person per day inside the restricted zone, plus ACAP. Summit Seek arranges paperwork with your licensed guide. Solo RAP is allowed with a guide.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack for strong sun, wind, dust, and cool nights above 3,000 m. Porters carry main bags; keep water, layers, documents, and camera in a daypack.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece mid-layer",
        "Down / insulated jacket",
        "Windproof / waterproof shell",
        "Trekking pants",
        "Sun hat, warm hat, gloves, buff for dust",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in hiking boots",
        "Camp shoes",
        "Trekking poles (helpful on long descents)",
        "25–35L daypack",
        "Sleeping bag (provided/rental as arranged)",
        "Headlamp + spare batteries",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "High-SPF sunscreen & lip balm",
        "UV sunglasses",
        "Personal medications & blister care",
        "Water bottle + purification",
        "Hand sanitizer & toilet paper",
        "Trail snacks",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance details",
        "Cash for personal trail extras",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "RAP / ACAP processing and licensed guiding team",
    "Flight booking assistance for Pokhara–Jomsom sectors",
    "Achievement certificate and first-aid support",
    "Advice on Tiji Festival, jeep options, and Muktinath add-ons",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Upper Mustang trek?",
      answer:
        "A 14-day restricted-area cultural trek into the arid Last Forbidden Kingdom of Lo Manthang — monasteries, desert landscapes, and Tibetan-Buddhist heritage beyond the Annapurnas.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Moderate. Expect long dry days and passes up to about 4,010 m. Prior multi-day hiking helps; it is not a beginner stroll.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This Summit Seek listing starts at US$1,795 for 2–3 pax (US$2,150 solo; US$1,695 for 4–6; US$1,595 for 7–12).",
      visible: true,
    },
    {
      id: "q4",
      question: "What is the maximum altitude?",
      answer:
        "Around 4,010 m at Nyi La. Lo Manthang sits near 3,809 m with a full rest/exploration day.",
      visible: true,
    },
    {
      id: "q5",
      question: "What permits do I need?",
      answer:
        "Upper Mustang Restricted Area Permit (typically USD 50 per person per day in-zone) plus ACAP. Summit Seek arranges these with a licensed guide.",
      visible: true,
    },
    {
      id: "q6",
      question: "Can I trek in monsoon?",
      answer:
        "Yes — Upper Mustang is one of Nepal’s best rain-shadow treks and often stays dry when other regions are wet.",
      visible: true,
    },
    {
      id: "q7",
      question: "Is travel insurance necessary?",
      answer:
        "Yes. Cover high-altitude trekking (to ~4,500 m) and emergency helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q8",
      question: "Are Jomsom flights reliable?",
      answer:
        "Morning flights are common but weather can cancel them. We recommend buffer time; jeep alternatives may be available at extra cost.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Upper Mustang?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Upper Mustang Trek 14 Days | Summit Seek",
  metaDescription:
    "Book the 14-day Upper Mustang trek with Summit Seek — Lo Manthang, RAP & ACAP, flights, guide, porter, meals & group discounts from US$1,595.",
};
