import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_UPPER_DOLPO: TrekPageContent = {
  coverImageUrl: img("photo-1506905925346-21bda4d32df4", 2000),
  coverTitle: "Upper Dolpo Trek - 24 Days",
  coverSubtitle:
    "Remote restricted circuit — turquoise Phoksundo Lake, sacred Shey Gompa & Crystal Mountain, Kang La and Jeng La, Bon and Tibetan culture in Shey Phoksundo National Park.",
  heroMainImageUrl: img("photo-1506905925346-21bda4d32df4", 2000),
  heroSideImage1Url: img("photo-1486870591958-9b9d0d1dda99", 900),
  heroSideImage2Url: img("photo-1544735716-392fe2489ffa", 900),
  breadcrumbLabel: "Dolpo Region · Upper Dolpo",
  title: "Upper Dolpo Trek - 24 Days",
  regionLabel: "Dolpo Region",
  rating: 5,
  reviewCount: 14,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 2890,
  compareAtPrice: 3290,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "12% OFF",
  shortTripBadge: "Restricted Area",
  durationLabel: "24 Days",
  difficultyLabel: "Strenuous",
  groupSizeLabel: "2–10",
  bookingNote:
    "Private and small-group camping expedition. Package includes Kathmandu–Nepalgunj–Jhupal flights as listed, licensed guide, cook, porters, camping gear, trek meals, Upper Dolpo RAP, and Shey Phoksundo National Park permit. Not for beginners — prior high-altitude camping experience strongly recommended.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "2 pax", price: 3290, visible: true },
    { id: "gd2", paxLabel: "3-5 pax", price: 2890, visible: true },
    { id: "gd3", paxLabel: "6-10 pax", price: 2690, visible: true },
    { id: "gd4", paxLabel: "11-15 pax", price: 2490, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "24 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Strenuous", visible: true },
    { id: "f3", label: "Max Altitude", value: "5,350 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Upper Dolpo", visible: true },
    { id: "f6", label: "Group Size", value: "2–10", visible: true },
    { id: "f7", label: "Activities", value: "Camping Trek", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "May–Oct (rain shadow)",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "Upper Dolpo sits in remote northwest Nepal between the Tibetan Plateau and the Dhaulagiri ranges — opened carefully to visitors only in the late 1980s and still a restricted area requiring a special permit. This 24-day circuit is the land of Peter Matthiessen’s The Snow Leopard and Eric Valli’s film Himalaya: turquoise Phoksundo Lake, Shey Gompa beneath Crystal Mountain, Bon Po and Tibetan-Buddhist culture, and wild Shey Phoksundo National Park.\n\nFrom Kathmandu you fly to Nepalgunj and Jhupal, trek via Dunai to Phoksundo for an acclimatization day, then cross Kang La (~5,350 m) to Shey Gompa. The route continues through Namgung, Saldang, Yangze, and Sibu to Jeng La (~5,150 m), descending into Tarap Valley (Dho Tarap) before returning via Tarakot and Dunai to Jhupal and flights home.\n\nExpect difficult, high, steep trails, long altitude days, and mostly camping with a full cook/porter team. Summit Seek includes RAP and park permits, domestic flights as listed, guide, cook, porters, camping support, and clear group pricing. This is a once-in-a-lifetime expedition for experienced trekkers only.",
  overviewImageUrl: img("photo-1486870591958-9b9d0d1dda99"),
  highlightsHeading: "Highlights",
  highlights: [
    "Turquoise Phoksundo Lake — Nepal’s deepest alpine lake",
    "Sacred Shey Gompa and Crystal Mountain pilgrimage country",
    "Cross Kang La (~5,350 m) and Jeng La (~5,150 m)",
    "Bon Po and Tibetan-Buddhist culture in remote villages",
    "Shey Phoksundo National Park wildlife & landscapes",
    "Dho Tarap valley — setting of the film Himalaya",
    "Ancient trans-Himalayan trade routes and yak caravans",
    "Rain-shadow trekking with dry high-plateau scenery",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Kathmandu–Nepalgunj–Jhupal flights as listed (weather permitting)",
    "Licensed English-speaking guide for the full expedition",
    "Camp cook and required porters (typically 2:1 load sharing)",
    "Camping kit — sleeping, dining, kitchen, and toilet tents as arranged",
    "Upper Dolpo Restricted Area Permit and Shey Phoksundo NP permit",
    "Nepalgunj hotel night as listed; trek meals on trail days",
    "Daily SpO₂ / first-aid support and rescue coordination help",
    "Clear group pricing for private camping teams",
  ],
  whyHeading: "Why choose Upper Dolpo?",
  whyPoints: [
    "One of Nepal’s most remote and least-visited restricted circuits",
    "Phoksundo Lake, Shey Gompa, and Crystal Mountain in one journey",
    "Deep Bon and Tibetan cultural immersion",
    "True expedition camping away from crowded classic trails",
    "Rain-shadow window that can work even in monsoon months",
  ],
  beginnersHeading: "Is this trek good for beginners?",
  beginnersBody:
    "No. Graded strenuous / challenging. You need extensive high-altitude trekking experience, preferably with camping. Average days are 5–7 hours on steep, rocky, sometimes poorly defined trails with multiple passes above 5,000 m.\n\nA licensed agency and guide are mandatory. Travel insurance covering helicopter evacuation to 6,000 m+ is required.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train 3+ months with long hikes, stairs, strength, and backpack weight",
    "Prior multi-week high-altitude trek experience strongly recommended",
    "Pack expedition camping layers for nights well below freezing",
    "Carry microspikes, poles, and comprehensive personal first aid",
    "Buy insurance covering remote high-altitude camping and heli evacuation",
    "Arrive Kathmandu early for briefing, gear check, and permit processing",
  ],
  itineraryHeading: "24-day itinerary",
  itineraryIntro:
    "Flight and walking times are estimates and vary with weather — Jhupal flights are notoriously weather-dependent. Camps may shift for safety. Your Summit Seek guide and cook team adjust the plan for conditions and fitness.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Fly Kathmandu – Nepalgunj",
      maxAltitude: "150 m",
      meals: "—",
      accommodation: "Hotel in Nepalgunj",
      description:
        "Domestic flight to Nepalgunj (~50 min). Briefing and overnight in Nepalgunj.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Fly Jhupal – trek to Dunai",
      maxAltitude: "2,850 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Morning flight to Jhupal; meet camping crew and trek via Kalagaunda to Dunai (~3 hours). Overnight in Dunai.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Dunai – Ankhe",
      maxAltitude: "2,896 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Hike Thulo Bheri / Phoksundo valleys with ups and downs to Ankhe at the park approach (~6 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Ankhe – Sulighat",
      maxAltitude: "3,180 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Enter Shey Phoksundo National Park via the Sulighat checkpoint (~6 hours). First night camping.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Sulighat – Phoksundo Lake",
      maxAltitude: "3,612 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Reach turquoise Phoksundo Lake via Ringmo and Phoksundo waterfall. Camp beside the lake.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Acclimatization at Phoksundo",
      maxAltitude: "3,612 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Rest and short exploration around the lake and Ringmo. Overnight at Phoksundo.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Phoksundo – Phoksundo Khola Camp",
      maxAltitude: "3,507 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Follow the eastern shore and meadows toward Phoksundo Khola Camp under Kanjirowa Himal.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Phoksundo Khola – Phoksundo Bhanjyang",
      maxAltitude: "3,910 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Steep climb through glacier valley toward Phoksundo Bhanjyang with Kang La views ahead.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Cross Kang La – Shey Gompa",
      maxAltitude: "5,350 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Strenuous crossing of Kang La (~5,350 m), then descend to sacred Shey Gompa near Crystal Mountain.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Acclimatization at Shey Gompa",
      maxAltitude: "4,500 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Rest day — monastery visits and optional short walks toward Crystal Mountain approaches.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Shey Gompa – Namgung Gonpa",
      maxAltitude: "4,800 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "High pass views toward the Tibetan Plateau and Mustang, then descend to Namgung Gonpa (~6 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Namgung – Saldang",
      maxAltitude: "3,620 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Descend to Saldang, the largest village in Upper Dolpo (~5 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Saldang – Yangze Gompa",
      maxAltitude: "≈ 3,960 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Continue through high dry country to Yangze Gompa. Overnight camping.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Yangze Gompa – Sibu",
      maxAltitude: "≈ 3,940 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Trek toward Sibu along remote Upper Dolpo trails. Overnight camping.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d15",
      dayLabel: "Day 15",
      title: "Sibu – Jeng La Phedi",
      maxAltitude: "4,900 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Follow Nagon Khola to Jeng La Phedi (pass base) on rocky, windy high ground.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d16",
      dayLabel: "Day 16",
      title: "Cross Jeng La – Tokyu Gaon",
      maxAltitude: "5,150 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Cross Jeng La (~5,150 m) with Dhaulagiri views, then descend into Tarap Valley to Tokyu Gaon.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d17",
      dayLabel: "Day 17",
      title: "Tokyu Gaon – Dho Tarap",
      maxAltitude: "4,040 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Trek to Dho Tarap — fertile high valley of Bon and Buddhist culture featured in Himalaya (~5 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d18",
      dayLabel: "Day 18",
      title: "Acclimatization at Dho Tarap",
      maxAltitude: "4,040 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Rest day exploring Buddhist and Bon gompas around Dho Tarap.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d19",
      dayLabel: "Day 19",
      title: "Dho Tarap – Tarap Khola",
      maxAltitude: "3,800 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping",
      description:
        "Descend along Tarap Chu toward Tarap Khola as vegetation returns.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d20",
      dayLabel: "Day 20",
      title: "Tarap Khola – Khani Gaon",
      maxAltitude: "≈ 2,550 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping / Lodge",
      description:
        "Continue descending through gorges and villages to Khani Gaon.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d21",
      dayLabel: "Day 21",
      title: "Khani Gaon – Tarakot",
      maxAltitude: "2,537 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping / Lodge",
      description:
        "Trek to historic Tarakot with river crossings and steep sections (~5 hours).",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d22",
      dayLabel: "Day 22",
      title: "Tarakot – Dunai",
      maxAltitude: "2,850 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Mostly downhill along the Bheri River back to Dunai. Teahouse overnight.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d23",
      dayLabel: "Day 23",
      title: "Dunai – Jhupal",
      maxAltitude: "2,320 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Camping / Lodge",
      description:
        "Final hike to Jhupal airstrip village (~3 hours). Overnight in Jhupal.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d24",
      dayLabel: "Day 24",
      title: "Fly Jhupal – Nepalgunj – Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "— (Kathmandu)",
      description:
        "Fly Jhupal to Nepalgunj then connect to Kathmandu (weather permitting). End of the Upper Dolpo journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best windows are typically May–October thanks to Dolpo’s rain shadow, with spring and autumn often clearest. Private teams of 2–10 are welcome. Jhupal flights cancel often — build buffer days.",
  availabilityNotes: [
    "Minimum typically 2 trekkers (restricted-area rules)",
    "Licensed guide, cook, and RAP mandatory",
    "Full camping support on the high circuit",
    "Domestic flights are weather-dependent — allow buffers",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Extra Kathmandu hotel nights",
      description: "Buffer nights before/after for flight delays.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Kathmandu sightseeing day",
      description: "Guided UNESCO heritage tour before departure.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Gear rental",
      description: "Sleeping bag, down jacket, poles, microspikes as needed.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Kathmandu–Nepalgunj–Jhupal flights as listed (and return sectors)",
    "1 night hotel in Nepalgunj as listed",
    "Camping accommodation on the circuit (tents as arranged) plus teahouse nights where listed",
    "Licensed English-speaking guide (salary, insurance, meals, lodging)",
    "Camp cook and required porters for the expedition",
    "Upper Dolpo Restricted Area Permit and Shey Phoksundo National Park permit",
    "Breakfast, lunch, and dinner on trek days as listed",
    "Camping equipment support (sleeping/dining/kitchen/toilet tents as arranged)",
    "First-aid / SpO₂ support and emergency rescue coordination help",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "International flights and Nepal visa fees",
    "Kathmandu hotels and meals outside the listed package",
    "Lunch and dinner in Nepalgunj",
    "Travel / medical insurance and helicopter evacuation costs",
    "Personal expenses (drinks, snacks, charging, hot showers where available)",
    "Personal trekking gear and clothing",
    "Tips for guide, cook, and porters",
    "Costs from flight cancellations, weather delays, or force majeure",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "High alpine light toward remote Dolpo country",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "Wild ridgelines and high-plateau atmosphere",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Remote Himalayan approaches",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "Mountain wilderness near the Tibetan border",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "May–October is often ideal in Dolpo’s rain shadow. Spring and autumn usually bring the clearest mountain days; winter is extremely cold.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude",
      body: "Highest points include Kang La (~5,350 m) and Jeng La (~5,150 m). Multiple acclimatization days are built in — still, report symptoms early.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Strenuous remote camping expedition. Steep, rocky, and sometimes faint trails with long high-altitude days — experienced trekkers only.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Permits",
      body: "Upper Dolpo RAP (typically USD 500 for 10 days + USD 50/day after) plus Shey Phoksundo National Park permit. Summit Seek arranges paperwork with your licensed team.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack for a full camping expedition above 5,000 m. Porters/mules carry loads; keep water, layers, documents, and camera in a daypack.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Expedition base layers",
        "Thick fleece / mid-layers",
        "Down jacket rated for deep cold",
        "Hard shell jacket and pants",
        "Insulated pants for camp",
        "Warm hat, sun hat, gloves, buff",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & carry",
      items: [
        "Broken-in stiff hiking boots",
        "Camp shoes",
        "Trekking poles",
        "Microspikes for icy passes",
        "25–35L daypack",
        "Sleeping bag rated to at least -15 °C (or colder)",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Health & sun",
      items: [
        "High-SPF sunscreen & lip balm",
        "UV sunglasses (spare pair helpful)",
        "Personal medications & blister care",
        "Water bottles + purification",
        "Headlamp + spare batteries",
        "High-calorie trail snacks",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies",
        "Travel insurance with heli cover to 6,000 m+",
        "Cash for personal extras",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "RAP / park permit processing and full camping team",
    "Domestic flight booking assistance",
    "Gear rental advice and first-aid support",
    "Buffer-day planning around Jhupal weather",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is the Upper Dolpo trek?",
      answer:
        "A 24-day restricted-area camping circuit through remote northwest Nepal — Phoksundo Lake, Shey Gompa, Crystal Mountain, and high passes including Kang La and Jeng La.",
      visible: true,
    },
    {
      id: "q2",
      question: "How difficult is it?",
      answer:
        "Strenuous. Long high-altitude days, steep/rocky trails, and camping above 4,000–5,000 m. Experienced trekkers only.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This Summit Seek listing starts at US$2,890 for 3–5 pax (US$3,290 for 2; US$2,690 for 6–10; US$2,490 for 11–15).",
      visible: true,
    },
    {
      id: "q4",
      question: "What is the maximum altitude?",
      answer:
        "Around 5,350 m at Kang La. Jeng La is about 5,150 m. Multiple acclimatization days are included.",
      visible: true,
    },
    {
      id: "q5",
      question: "What permits do I need?",
      answer:
        "Upper Dolpo Restricted Area Permit and Shey Phoksundo National Park permit. Summit Seek arranges these with a licensed guide and team.",
      visible: true,
    },
    {
      id: "q6",
      question: "Is travel insurance necessary?",
      answer:
        "Yes — mandatory. Cover remote high-altitude camping and helicopter evacuation to 6,000 m+. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q7",
      question: "When is the best time to go?",
      answer:
        "May–October usually works well due to Dolpo’s rain shadow; spring and autumn often have the clearest views.",
      visible: true,
    },
    {
      id: "q8",
      question: "Are Jhupal flights reliable?",
      answer:
        "No — they frequently delay or cancel for weather. Always build buffer days in Kathmandu / Nepalgunj.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Upper Dolpo?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear expedition quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Upper Dolpo Trek 24 Days | Summit Seek",
  metaDescription:
    "Book the 24-day Upper Dolpo circuit with Summit Seek — Phoksundo Lake, Shey Gompa, Kang La, camping team, RAP & group discounts from US$2,490.",
};
