import type { TrekPageContent } from "@/types/trek-page-cms";
import { SITE } from "@/lib/constants";

const img = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEFAULT_YALA_PEAK: TrekPageContent = {
  coverImageUrl: img("photo-1464822759023-fed622ff2c3b", 2000),
  coverTitle: "Yala Peak Climbing - 14 Days",
  coverSubtitle:
    "Non-technical Langtang trekking-peak summit (~5,520–5,732 m) via Syabrubesi, Kyanjin Gompa, and Yala Base Camp — Tamang culture and views of Langtang Lirung, Dorje Lakpa, and Shishapangma.",
  heroMainImageUrl: img("photo-1464822759023-fed622ff2c3b", 2000),
  heroSideImage1Url: img("photo-1506905925346-21bda4d32df4", 900),
  heroSideImage2Url: img("photo-1544735716-392fe2489ffa", 900),
  breadcrumbLabel: "Langtang Region · Peak Climbing",
  title: "Yala Peak Climbing - 14 Days",
  regionLabel: "Langtang Region",
  rating: 5,
  reviewCount: 8,
  tripAdvisorRating: "5.0",
  googleRating: "5.0",
  trustpilotRating: "5.0",
  price: 1699,
  compareAtPrice: 1799,
  currencyPrefix: "US$",
  perPersonLabel: "Price Per Person",
  discountBadge: "6% OFF",
  shortTripBadge: "Trekking Peak",
  durationLabel: "14 Days",
  difficultyLabel: "Difficult",
  groupSizeLabel: "1–20+",
  bookingNote:
    "Private and small-group departures. Package includes Kathmandu hotels as listed, private/shared ground transfers to Syabrubesi, licensed trekking & climbing guide, porter support, trek meals, teahouse lodging, tented base camp, NMA Yala Peak climbing permit, Langtang National Park fees, TIMS, and group climbing equipment as listed.",
  groupDiscountHeading: "Group Discount Price",
  groupDiscounts: [
    { id: "gd1", paxLabel: "2 pax", price: 1799, visible: true },
    { id: "gd2", paxLabel: "3-5 pax", price: 1699, visible: true },
    { id: "gd3", paxLabel: "6-10 pax", price: 1590, visible: true },
    { id: "gd4", paxLabel: "11-15 pax", price: 1490, visible: true },
  ],
  bookLabel: "Book This Trip",
  bookHref: "/contact",
  customizeLabel: "Customize Trip",
  customizeHref: "/contact",
  enquireLabel: "Inquire Now",
  enquireHref: "/contact",
  whatsappLabel: "WhatsApp Summit Seek",
  whatsappHref: `https://wa.me/${SITE.whatsapp.replace(/\D/g, "")}`,
  facts: [
    { id: "f1", label: "Duration", value: "14 Days", visible: true },
    { id: "f2", label: "Difficulty", value: "Difficult", visible: true },
    { id: "f3", label: "Max Altitude", value: "5,520–5,732 m", visible: true },
    { id: "f4", label: "Starts / Ends", value: "Kathmandu", visible: true },
    { id: "f5", label: "Region", value: "Langtang / Peak Climbing", visible: true },
    { id: "f6", label: "Group Size", value: "1–20+", visible: true },
    { id: "f7", label: "Activities", value: "Trek & Climbing", visible: true },
    {
      id: "f8",
      label: "Best Season",
      value: "Mar–May & Sep–Nov",
      visible: true,
    },
  ],
  overviewHeading: "Trip introduction",
  overviewBody:
    "Yala Peak Climbing is an ideal first Himalayan summit for fit trekkers — a non-technical trekking peak near the Tibetan border in the Langtang region, with panoramic views of Langtang Lirung (7,234 m), Dorje Lakpa (6,966 m), and Shishapangma (8,027 m).\n\nThis 14-day journey drives from Kathmandu to Syabrubesi, treks through Langtang Valley forests and Tamang villages to Kyanjin Gompa, then ascends to Yala Peak Base Camp for acclimatization before a pre-dawn summit attempt. After the climb you descend the same corridor back to Syabrubesi and drive to Kathmandu.\n\nExpect teahouse lodging on the trail, tented camping at base camp, and basic use of crampons and ice axe on the final snow section — advanced rope skills are not required. Summit Seek includes climbing and park permits, licensed climbing guide, meals, transfers, and clear group pricing. Market packages for similar 14-day Yala trips often run about US$1,300–1,800.",
  overviewImageUrl: img("photo-1506905925346-21bda4d32df4"),
  highlightsHeading: "Highlights",
  highlights: [
    "Summit Yala Peak (~5,520–5,732 m) — accessible trekking peak",
    "Scenic drive Kathmandu–Syabrubesi through hill country",
    "Langtang Valley trek via rhododendron and bamboo forest",
    "Kyanjin Gompa monastery village and side hikes (Kyanjin Ri / Tserko Ri)",
    "Views of Langtang Lirung, Dorje Lakpa, and Shishapangma",
    "Tamang culture and hospitality",
    "Langtang National Park wilderness",
    "Ideal first Himalayan peak for experienced trekkers",
  ],
  advantagesHeading: "Why book with Summit Seek",
  advantages: [
    "Airport transfers by private vehicle as listed",
    "Kathmandu hotel accommodation as listed",
    "All ground transfers including Syabrubesi drive",
    "Teahouse / lodge lodging on trek; tented camp at Yala Base Camp",
    "Breakfast, lunch, and dinner during trek and climb",
    "English-speaking trekking guide and NMA climbing guide",
    "Yala Peak climbing royalty, Langtang NP fees, and TIMS",
    "Group camping & climbing equipment; medical kit; farewell dinner as listed",
  ],
  whyHeading: "Why choose Yala Peak?",
  whyPoints: [
    "One of Nepal’s most accessible trekking peaks for first-time climbers",
    "Shorter approach than Everest-region peaks — close to Kathmandu",
    "Strong culture in Langtang Valley with Tamang villages",
    "Non-technical summit with basic mountaineering gear only",
    "Huge Tibetan-border panoramas without Island Peak crowds",
  ],
  beginnersHeading: "Is this climb good for beginners?",
  beginnersBody:
    "Yes for fit trekkers with prior multi-day Himalayan (or similar) trek experience who want a first peak. It is graded difficult physically (often 5–8 hour days; summit day 6–8 hours) but non-technical — no advanced ice climbing required.\n\nBasic instruction with crampons and ice axe is provided. Travel insurance covering high-altitude trekking/climbing and helicopter evacuation is mandatory.",
  prepHeading: "How to prepare",
  prepPoints: [
    "Train 6+ weeks: cardio, hill walks, and daypack hikes",
    "Prior trek experience strongly recommended",
    "Break in boots; practice with poles on steep terrain",
    "Pack for cold nights at base camp (−15°C sleeping bag)",
    "Buy insurance covering peak climbing and heli evacuation",
    "Arrive Kathmandu for briefing, permits, and optional gear rental",
  ],
  itineraryHeading: "14-day itinerary",
  itineraryIntro:
    "Based on the classic Langtang approach to Yala Peak. Driving and walking times vary with road and weather conditions. Summit day depends on conditions — your climbing guide may adjust. Build buffer for Syabrubesi road delays.",
  days: [
    {
      id: "d1",
      dayLabel: "Day 1",
      title: "Arrive Kathmandu",
      maxAltitude: "1,400 m",
      meals: "—",
      accommodation: "Hotel in Kathmandu",
      description:
        "Airport meet-and-greet and hotel transfer. Rest or light evening stroll. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d2",
      dayLabel: "Day 2",
      title: "Kathmandu sightseeing & climb briefing",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Optional heritage tour (Pashupatinath, Swayambhunath, Boudhanath, Durbar Squares). Gear check and permit briefing with your guide. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d3",
      dayLabel: "Day 3",
      title: "Drive Kathmandu – Syabrubesi",
      maxAltitude: "1,462 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Scenic drive north (~7–8 hours) through hills and terraces to Syabrubesi, trailhead for Langtang. Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d4",
      dayLabel: "Day 4",
      title: "Trek Syabrubesi – Lama Hotel",
      maxAltitude: "2,500 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "First walking day along the Langtang River through rhododendron and bamboo forest (~5 hours). Overnight at Lama Hotel.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d5",
      dayLabel: "Day 5",
      title: "Trek Lama Hotel – Langtang Village",
      maxAltitude: "3,430 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Ascend via Gumanechowk with yak pastures and growing mountain views. Overnight in Langtang Village.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d6",
      dayLabel: "Day 6",
      title: "Trek Langtang Village – Kyanjin Gompa",
      maxAltitude: "3,870 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Continue through pastures and rocky trails to Kyanjin Gompa, the monastery village beneath Langtang Lirung. Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d7",
      dayLabel: "Day 7",
      title: "Trek Kyanjin Gompa – Yala Peak Base Camp",
      maxAltitude: "5,000 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Tented camp",
      description:
        "Rocky pastures and alpine approaches to Yala Peak Base Camp. Overnight camping.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d8",
      dayLabel: "Day 8",
      title: "Acclimatization at Yala Peak Base Camp",
      maxAltitude: "5,000 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Tented camp",
      description:
        "Rest, short acclimatization walks, and climbing gear practice with your guide. Overnight at base camp.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d9",
      dayLabel: "Day 9",
      title: "Summit Yala Peak – descend to Kyanjin Gompa",
      maxAltitude: "5,520–5,732 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Early start for the summit (~6–8 hours round trip) with views of Langtang Lirung, Dorje Lakpa, Shishapangma, and more. Descend to Kyanjin Gompa for overnight.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d10",
      dayLabel: "Day 10",
      title: "Trek Kyanjin Gompa – Lama Hotel",
      maxAltitude: "2,500 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse",
      description:
        "Begin the return descent to Lama Hotel. Overnight teahouse.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d11",
      dayLabel: "Day 11",
      title: "Trek Lama Hotel – Syabrubesi",
      maxAltitude: "1,462 m",
      meals: "Breakfast, Lunch, Dinner",
      accommodation: "Teahouse / Lodge",
      description:
        "Final trek day down to Syabrubesi. Overnight lodge.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d12",
      dayLabel: "Day 12",
      title: "Drive Syabrubesi – Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast, Lunch",
      accommodation: "Hotel in Kathmandu",
      description:
        "Drive back to Kathmandu (~7–8 hours). Hotel transfer. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d13",
      dayLabel: "Day 13",
      title: "Leisure day in Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "Hotel in Kathmandu",
      description:
        "Free day for rest, shopping, or optional sightseeing. Farewell dinner as listed. Overnight in Kathmandu.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "d14",
      dayLabel: "Day 14",
      title: "Departure from Kathmandu",
      maxAltitude: "1,400 m",
      meals: "Breakfast",
      accommodation: "—",
      description:
        "Airport transfer for your international flight. End of the Yala Peak journey with Summit Seek.",
      imageUrl: "",
      visible: true,
    },
  ],
  availabilityHeading: "Dates & availability",
  availabilityBody:
    "Best in March–May and September–November for stable weather and clear summit views. Private groups of 1–20+ are welcome. Allow buffer for Syabrubesi road conditions.",
  availabilityNotes: [
    "Private and customizable start dates",
    "NMA climbing permit and Langtang NP entry required",
    "Licensed climbing guide included",
    "Summit day is weather-dependent — guide may adjust",
  ],
  addonsHeading: "Optional add-ons",
  addons: [
    {
      id: "a1",
      title: "Extra Kathmandu nights",
      description: "Buffer nights for road delays or early arrivals.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a2",
      title: "Kyanjin Ri / Tserko Ri side hike day",
      description: "Extra acclimatization viewpoint day before base camp.",
      priceLabel: "On request",
      visible: true,
    },
    {
      id: "a3",
      title: "Personal gear rental",
      description: "Crampons, ice axe, harness, helmet, sleeping bag in Kathmandu.",
      priceLabel: "On request",
      visible: true,
    },
  ],
  includesHeading: "Trip includes",
  includes: [
    "Airport pickup and drop by private vehicle",
    "Kathmandu accommodation as listed",
    "All ground transfers including Kathmandu–Syabrubesi–Kathmandu",
    "Teahouse / lodge lodging on trek; tented accommodation at base camp",
    "Breakfast, lunch, and dinner during trek and climb (tea/coffee as listed)",
    "English-speaking trekking guide and climbing guide",
    "Yala Peak climbing royalty, Langtang National Park fees, TIMS",
    "Tents, camping equipment, fixed ropes / group climbing gear; medical kit; taxes; farewell dinner as listed",
  ],
  excludesHeading: "Trip excludes",
  excludes: [
    "International airfare and airport taxes",
    "Nepal entry visa fees",
    "Personal travel / medical insurance (mandatory — heli evacuation)",
    "Helicopter rescue and evacuation if needed",
    "Personal expenses: bar, laundry, phone, tips",
    "Personal climbing gear (rentable in Kathmandu)",
    "Hot showers, Wi-Fi, and charging on trek",
    "Lunch and dinner in Kathmandu (except farewell dinner as listed)",
  ],
  galleryHeading: "Trip gallery",
  gallery: [
    {
      id: "g1",
      url: img("photo-1464822759023-fed622ff2c3b"),
      caption: "High Langtang ridges toward Yala Peak country",
      visible: true,
    },
    {
      id: "g2",
      url: img("photo-1506905925346-21bda4d32df4"),
      caption: "Alpine valley approaches near Kyanjin",
      visible: true,
    },
    {
      id: "g3",
      url: img("photo-1544735716-392fe2489ffa"),
      caption: "Remote Himalayan light on the climb",
      visible: true,
    },
    {
      id: "g4",
      url: img("photo-1486870591958-9b9d0d1dda99"),
      caption: "Snow peaks along the Tibetan border",
      visible: true,
    },
  ],
  essentialHeading: "Essential information",
  essentialBlocks: [
    {
      id: "e1",
      title: "Best season",
      body: "March–May and September–November offer the most reliable summit windows with clear views and milder temperatures.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e2",
      title: "Altitude & permits",
      body: "Summit ~5,520–5,732 m. You need Langtang National Park entry, TIMS, and an NMA Yala Peak climbing permit. Summit Seek arranges these.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e3",
      title: "Difficulty",
      body: "Difficult physically but non-technical. Summit morning is steep with basic crampon/ice-axe use. Prior trek fitness essential.",
      imageUrl: "",
      visible: true,
    },
    {
      id: "e4",
      title: "Lodging & food",
      body: "Teahouses on the Langtang trail; tents at Yala Base Camp. Dal bhat, noodles, soups, and eggs are common. Hot shower and Wi-Fi cost extra where available.",
      imageUrl: "",
      visible: true,
    },
  ],
  equipmentHeading: "Equipment checklist",
  equipmentIntro:
    "Pack for cold alpine nights and a snowy summit. Group ropes/camping gear are provided; rent personal technical items in Kathmandu if needed.",
  equipmentGroups: [
    {
      id: "eq1",
      title: "Clothing",
      items: [
        "Moisture-wicking base layers",
        "Fleece mid-layer",
        "Down jacket",
        "Waterproof shell jacket and pants",
        "Warm gloves, hat, buff",
        "Sun hat and glacier sunglasses",
      ],
      visible: true,
    },
    {
      id: "eq2",
      title: "Footwear & climbing",
      items: [
        "Sturdy waterproof trekking / climbing boots",
        "Crampons compatible with boots",
        "Ice axe",
        "Harness and helmet (as required)",
        "Trekking poles",
        "Gaiters",
      ],
      visible: true,
    },
    {
      id: "eq3",
      title: "Camp & health",
      items: [
        "Sleeping bag rated to about −15°C",
        "Headlamp + spare batteries",
        "Water bottle + purification",
        "Personal first-aid & blister care",
        "SPF 50+ sunscreen and lip balm",
        "High-energy snacks",
      ],
      visible: true,
    },
    {
      id: "eq4",
      title: "Documents",
      items: [
        "Passport + copies + passport photos",
        "Nepal visa as applicable",
        "Insurance covering peak climbing & heli rescue",
        "Summit Seek trip confirmation",
      ],
      visible: true,
    },
  ],
  companyProvidesHeading: "What Summit Seek can provide",
  companyProvides: [
    "Permit processing (NMA, park, TIMS)",
    "Licensed climbing and trekking guides",
    "Group tents, ropes, and camping equipment",
    "Advice on Kathmandu gear rental",
  ],
  faqsHeading: "Frequently asked questions",
  faqs: [
    {
      id: "q1",
      question: "What is Yala Peak climbing?",
      answer:
        "A 14-day Langtang region trip culminating in a non-technical trekking-peak summit (~5,520–5,732 m) via Syabrubesi and Kyanjin Gompa — ideal for first-time Himalayan climbers with trek experience.",
      visible: true,
    },
    {
      id: "q2",
      question: "Is Yala Peak technical?",
      answer:
        "No. It is a non-technical trekking peak. You use basic mountaineering gear (crampons, ice axe) on the final snow section; advanced rope skills are not required.",
      visible: true,
    },
    {
      id: "q3",
      question: "How much does it cost?",
      answer:
        "This listing starts at US$1,699 for 3–5 pax (US$1,799 for 2; US$1,590 for 6–10; US$1,490 for 11–15). Similar market packages often range about US$1,300–1,800.",
      visible: true,
    },
    {
      id: "q4",
      question: "What is the maximum altitude?",
      answer:
        "The summit of Yala Peak is commonly listed around 5,520–5,732 m depending on the map source used.",
      visible: true,
    },
    {
      id: "q5",
      question: "What permits are required?",
      answer:
        "Langtang National Park entry, TIMS, and an NMA Yala Peak climbing permit. Summit Seek arranges these.",
      visible: true,
    },
    {
      id: "q6",
      question: "Do I need previous climbing experience?",
      answer:
        "No advanced climbing experience is required, but prior multi-day trek experience and good fitness are strongly recommended.",
      visible: true,
    },
    {
      id: "q7",
      question: "Is travel insurance necessary?",
      answer:
        "Yes — covering high-altitude trekking/climbing and helicopter evacuation. Summit Seek does not sell insurance.",
      visible: true,
    },
    {
      id: "q8",
      question: "When is the best time to climb?",
      answer:
        "March–May and September–November usually offer the best summit windows and views.",
      visible: true,
    },
  ],
  ctaHeading: "Ready for Yala Peak?",
  ctaBody: `Tell us your preferred dates and group size — we will confirm availability and a clear quote. WhatsApp ${SITE.whatsappDisplay} or email ${SITE.email}.`,
  ctaPrimaryLabel: "Enquire now",
  ctaPrimaryHref: "/contact",
  ctaSecondaryLabel: "Packing checklist",
  ctaSecondaryHref: "/travel-guide/packing-checklist",
  metaTitle: "Yala Peak Climbing 14 Days | Summit Seek",
  metaDescription:
    "Book 14-day Yala Peak climbing with Summit Seek — Langtang approach, non-technical summit ~5,520 m+, permits, guide, meals & group discounts from US$1,490.",
};
